### ISSUE TITLE
Allow for NodePort to be configurable / switched to LoadBalancer

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#1]
Ref: https://github.com/liyinan926/spark-operator/issues/1.

@sylus, I moved the issue over to this new repository where future development will be done.

**Comment by sylus** [comment]
thanks!

**Comment by liyinan926** [comment]
@sylus sorry I didn't get a chance to work on this issue. For accessing the Spark web UI, there's now an easier way. I recently added a command-line tool named `sparkctl` that supports port forwarding from a local port to the remote port of the web UI. Please check it out at https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/sparkctl. Let me know if you have any questions.

**Comment by sylus** [comment]
I'll take a look in next 2 days and report back :) thanks so much!
