### ISSUE TITLE
IAM Role for Driver and Executor Pods?

### ISSUE THREAD

**Issue by batCoder95** [GoogleCloudPlatform/spark-on-k8s-operator#1002]
Hi all,

I wanted to check if it is possible to define an AWS IAM role that should be attached to driver and worker pods in Spark application YAML file. As per my understanding, currently these pods inherit the role from EKS worker nodes, but I would like to specify my own custom role in the YAML file. Can somebody please suggest on the possibility ?

Thanks in advance :)

**Comment by mrkwtz** [comment]
I think you are looking for IRSA https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html? In your SparkApplication Pod spec you can then define the used ServiceAccounts for the driver und executor.

**Comment by batCoder95** [comment]
Hi @mrkwtz .

I followed the steps in this document and created a service account with name "svc-spark-account". But still getting the same error on using that service account in SparkApplication.

Below is what my YAML file looks like for reference:

`apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: test-pyspark-app
  namespace: dev
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "coqueirotree/spark-py"
  imagePullPolicy: Always
  mainApplicationFile: s3a://my-bucket/TestFile.py
  sparkVersion: "3.0.0"
  sparkConf:
    "spark.kubernetes.driverEnv.serviceAccount": "svc-spark-account"
    "spark.kubernetes.driverEnv.serviceAccountName": "svc-spark-account"
    "spark.kubernetes.authenticate.driver.serviceAccount": "svc-spark-account"
    "spark.kubernetes.authenticate.driver.serviceAccountName": "svc-spark-account"
    "spark.kubernetes.executorEnv.serviceAccount": "svc-spark-account"
    "spark.kubernetes.executorEnv.serviceAccountName": "svc-spark-account"
    "spark.kubernetes.authenticate.executor.serviceAccount": "svc-spark-account"
    "spark.kubernetes.authenticate.executor.serviceAccountName": "svc-spark-account"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: svc-spark-account
    serviceAccountName: svc-spark-account
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: svc-spark-account
    serviceAccountName: svc-spark-account`

Can you please advise if I should do something differently in this case?

Thanks.

**Comment by mrkwtz** [comment]
You can't use IRSA for the S3 authentication with spark itself. That's because spark uses the hadoop-aws[1] library to implement the S3 functionality and this library uses an old version of the aws-sdk[2] which doesn't support Webtoken / OIDC / IRSA. For now you are limited to access / secret key or InstanceProfile/Role authentication.

[1] https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/3.3.0
[2] https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by batCoder95** [comment]
That's surprising. I saw spark documentation saying that it is supported at this link: https://spark.apache.org/docs/latest/running-on-kubernetes.html#rbac

Looks like the GCR image needs some updates to support this ?

**Comment by mrkwtz** [comment]
Thats just that your Spark Application / Job can assume special rights in k8s itself, but is has nothing to do with AWS IAM - unfortunately.

**Comment by bbenzikry** [comment]
You can take a look at https://github.com/bbenzikry/spark-irsa for reference Dockerfiles for spark and pyspark.
Examples are for 2.4.6 but a similar approach should be fine for other spark versions. 
```yaml
hadoopConf:
  "fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
```

If you encounter an error such as 

```
org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by WebIdentityTokenCredentialsProvider : com.amazonaws.SdkClientException: Unable to locate specified web identity token file:
```

Make sure that you have securityContext set as follows ( more on that @ https://github.com/kubernetes/kubernetes/issues/82573 )
```yaml
securityContext:
  fsGroup: 65534
```

Tested on EKS 1.16.8 + 1.17

**Comment by batCoder95** [comment]
@bbenzikry - I tried this approach but am still getting the below error even after specifying the security context parameter:
`org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by WebIdentityTokenCredentialsProvider : com.amazonaws.SdkClientException: Unable to locate specified web identity token file:`

I specified the security context at all below levels:
- under "spec" section i.e. same level as "hadoopConf" and "sparkConf"
- under "spec->driver" i.e. same level as "spec->driver->labels"

Can you please suggest if I should be defining security context at some other level ?

**Comment by bbenzikry** [comment]
Hi @batCoder95 , it should be set like this: 
```yaml
  driver:
    .....
    labels:
        .....
    serviceAccount: spark
    securityContext:
      fsGroup: 65534
```

I saw you replied in #885, if you want to go around this for the meantime, you can do add ( again, probably bad practice ;] ) 

 ```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: SPARK_JOB_NAMESPACE
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/executor-role"
```

**Comment by batCoder95** [comment]
Hi @bbenzikry - Yes I think this approach would be feasible, but I agree that this is not a good practice.

On another note, I observed that this limitation is only from GCP operator. As Spark official [doc](https://spark.apache.org/docs/latest/running-on-kubernetes.html#rbac), we are able to pass custom service account. I haven't tried it yet, but it does seem to be available for use. Or am I misreading into it ?

**Comment by bbenzikry** [comment]
@batCoder95 Sorry for not replying sooner. 
From what I read, the docs don't reference the executor pod default service account constraint that is handled in the spark PR that should be added in 3.1. 
So right now, executors( whether submitted via the operator or not ) will still have that problem. 

From browsing the PR code, it seems that without any configuration the executor pods will default to the driver's service account ( which seems like a good enough solution until #885 has an implementation )
In order to use it you'll have to either wait for 3.1 or build spark from source.

**Comment by batCoder95** [comment]
@bbenzikry - No issues :)
Yeah I guess currently I will have to go with building spark image from scratch only or wait for 3.1 release. Will check it out.

Thank you so much for all your help on this. It has been really really helpful :)

Will close this issue. Stay safe :)

**Comment by batCoder95** [comment]
Hi @bbenzikry ,

It turns out I was finally able make this work using the Spark IRSA Dockerfile that you have provided :)

Just wanted to say thanks a lot for such a bug help :)

Cheers!

**Comment by bbenzikry** [comment]
@batCoder95 Thanks, happy to help - I'm a little busy at work, but I'm going to release a small project soon that shows how we work with both IRSA and the AWS Glue catalog using the operator on Spark 3

**Comment by zhaohc10** [comment]
> Hi @bbenzikry ,
> 
> It turns out I was finally able make this work using the Spark IRSA Dockerfile that you have provided :)
> 
> Just wanted to say thanks a lot for such a big help :)
> 
> Cheers!

Hi just wonder which spark version you were tested, spark2.4.6 or spark3.1?  if spark3.1, you build yourself or download from official ?

**Comment by bbenzikry** [comment]
Hi @zhaohc10, you can see an example for use with spark 3 ( 3.0.1 ) here: https://github.com/bbenzikry/spark-eks

While we don't use 3.1, you can find an example for a 3.0.1 custom build with glue support in the following repo: https://github.com/bbenzikry/spark-glue
Should be very similar for 3.1
