### ISSUE TITLE
ingress-url-format support $appName under path

### ISSUE THREAD

**Issue by jinxingwang** [GoogleCloudPlatform/spark-on-k8s-operator#1007]
Add support for ingress-url-format to allow 
ingress.cluster.com/{{$appName}}

We have a use case that we want to use Nginx ingress to host spark ui under DNS name. 
And put each spark ui under a path
for example: spark.ui.dns.name.com/{{$appNamespace}}/{{$appName}}

We have it working locally with Nginx ingress, and willing to make a contribution.

**Comment by jinxingwang** [comment]
@liyinan926 Hi, Li.

**Comment by arthuersundar** [comment]
i followed the ingressUrlFormat and it got deployed fine. i can see the host and path in kubectl describe ingress. But I'm getting 503 error when i access the UI using http://sample.eastus2.cloudapp.azure.com/spark-apps/spark-pi

Rules:
Host Path Backends

sample.eastus2.cloudapp.azure.com
/spark-apps/spark-pi spark-pi-ui-svc:4040 )

**Comment by andyzheung** [comment]
> i followed the ingressUrlFormat and it got deployed fine. i can see the host and path in kubectl describe ingress. But I'm getting 503 error when i access the UI using http://sample.eastus2.cloudapp.azure.com/spark-apps/spark-pi
> 
> Rules: Host Path Backends
> 
> sample.eastus2.cloudapp.azure.com /spark-apps/spark-pi spark-pi-ui-svc:4040 )

Do you solve this problem? I have met this too.

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1008

@arthuersundar

**Comment by SagarUKU** [comment]
I'm also getting 503 error when i access the UI did you get any solutions ?@arthuersundar @andyzheung
