### ISSUE TITLE
How to terminate pods automatically when completing a spark job

### ISSUE THREAD

**Issue by ocworld** [GoogleCloudPlatform/spark-on-k8s-operator#1015]
How to terminate pods automatically when completing a spark job?

Pods, that are executors and a driver, are always running, even if job is already completed, When spark job is submitted by spark operator on k8s.

I want to release k8s resources on the end of a spark job.

**Comment by liyinan926** [comment]
Can you elaborate a bit more on this? Completed executor pods should be automatically deleted by the driver. We don't automatically delete the driver pod upon completion of a job. The driver pod will still exist even if the job has completed, unless you delete the `SparkApplication` resource or set a TTL for the job (see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#setting-ttl-for-a-sparkapplication).

**Comment by jinxingwang** [comment]
agree with lin, can you elaborate a bit more on the issue. I think you are simplifying missing a
`spark context.stop`
at end of your code.

**Comment by ocworld** [comment]
> agree with lin, can you elaborate a bit more on the issue. I think you are simplifying missing a
> `spark context.stop`
> at end of your code.

Thank you! Adding spark context close in my code is the solution in my problem.
In yarn, standalone, and aws emr, it is not problem without sparkcontext.stop. However, I think it is more restricted checked in k8s spark.

**Comment by sumeetmi2** [comment]
I have a similar issue where in the shutdown hook is called and we see "Kubernetes client has been closed " in the logs. But the application master keeps running even though the sparkcontext has stopped.
