### ISSUE TITLE
Helm Stable and Incubator chart repo deprecation on November 13

### ISSUE THREAD

**Issue by psschwei** [GoogleCloudPlatform/spark-on-k8s-operator#1021]
Per [this](https://lists.cncf.io/g/cncf-helm/topic/stable_and_incubator_chart/76616691?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,76616691) post, the Helm stable and incubator chart repos will be deprecated on November 13. As the Spark Operator chart is in the incubator repo, are there plans to migrate it to another location?

For reference, full text of linked message:
"""
This has been shared previously but we've come to realize that not everyone has noticed.

On November 13th of this year the stable and incubator chart repos will be marked obsolete and will be going away.

There are two elements to this. The first is that they will be obsolete and we will no longer be accepting changes to them. Any charts that want to be around long term will need to migrate to a new location. If you have questions on doing this or running your own repository, we are happy to help. We have documented how to run a repo on GitHub and have released tools, like the chart releaser, to help.

Those charts can be made discoverable through the Helm Hub and Artifact Hub. The Artifact Hub is listed because the Helm Hub is migrating there. You can find the migration issue at https://github.com/helm/hub/issues/439.

The other element is that the chart repositories will be going away. While the git repository will still be available the Helm repository will be garbage collected and no longer available. This can happen on November 13th or any day after that. I would plan on Nov 13th to be on the safe side.

jFrog Chart Center does have a cache of the charts. I have been told this will remain after the stable and incubator repos are gone.

If you have any questions about this please let us know. This was initially announced months ago but I realize the message has been lost with everything else going on. We are putting a renewed focus on it in an attempt to make a clean of a transition as possible.

Regards,
Matt Farina
"""

**Comment by liyinan926** [comment]
I was not aware of this deprecation. Will certainly come up with a plan asap.

**Comment by HagaiBarel** [comment]
Any updates on this? November is fast approaching

**Comment by sharkymcdongles** [comment]
> I was not aware of this deprecation. Will certainly come up with a plan asap.

Any word @liyinan926 ?

**Comment by liyinan926** [comment]
On this now.

**Comment by psschwei** [comment]
New Location For Stable and Incubator Charts: https://helm.sh/blog/new-location-stable-incubator-charts/

**Comment by HagaiBarel** [comment]
@liyinan926 any news? Willing to help out if you'd like

**Comment by liyinan926** [comment]
@HagaiBarel thanks for being willing to help! It's great if you can help with migrating the chart.

**Comment by HagaiBarel** [comment]
@liyinan926 Sure thing, will work on a PR. The idea is to add a `charts` folder (see https://github.com/kubernetes/autoscaler/tree/master), and once we have that going we work on automation on how and where to publish the chart

**Comment by psschwei** [comment]
In terms of automation, this seems like a possibility: https://dev.to/jamiemagee/how-to-host-your-helm-chart-repository-on-github-3kdp

Though to use GitHub Pages, it looks like the charts would either:
(a) have to move to the `docs/` folder, or
(b) be hosted in a separate repository

**Comment by jgardner04** [comment]
I have added the GitHub action for this in PR #1066 and have created issue #1071 to track the creation the the branch. That looks like it is done and the action is succeeding however I don't see the index.yaml file I would expect in the gh-pages branch. I also and not sure of the GitHub Pages for the repo. Is that something someone can let me know so I can test?

**Comment by liyinan926** [comment]
I found this https://github.com/helm/chart-releaser and will give it a try.

**Comment by jgardner04** [comment]
@liyinan926 this is the tool that I use in the GitHub Action I created in PR #1066. More info on the action can be found in the [Chart Releaser Action](https://github.com/helm/chart-releaser-action)

**Comment by jgardner04** [comment]
After merging #1097 the final step is to configure the repo to use [GitHub Pages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites).

**Comment by HagaiBarel** [comment]
@liyinan926 @yuchaoran2011 can someone please configure the github pages?

**Comment by liyinan926** [comment]
What exactly needs to be configured for Github Pages? What are expected in the `index.yaml` file @jgardner04 mentioned above?

**Comment by HagaiBarel** [comment]
You need to go to the repo settings page -> options, and scroll to the bottem to find the github pages section. Than just enable it and select the `gh-pages` branch. Here's a screenshot from my fork - 

![image](https://user-images.githubusercontent.com/3352171/101315961-432f7200-3864-11eb-949c-ee4f00b46351.png)

The `index.yaml` is updated by the `github action` and lists the repository's charts and their location for `helm` to discover. It's the only file `helm` cares about. 

after enabling the `gh-pages`, you can test to see if it works by two ways - 
1. open the browser at https://GoogleCloudPlatform.github.io/spark-on-k8s-operator/index.yaml and you should be prompted to download the `index.yaml` file
2. add a repo with `helm` - `helm repo add spark-operator https://GoogleCloudPlatform.github.io/spark-on-k8s-operator` and helm should be able to add and list charts from this `repo`

**Comment by liyinan926** [comment]
Thanks @HagaiBarel for the info. The `gh-pages` branch has been enabled. I was able to download the `index.yaml` file.

**Comment by HagaiBarel** [comment]
Yup, looks good - 

```shell
$ helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
"spark-operator" has been added to your repositories

$ helm search repo spark-operator
NAME                         	CHART VERSION	APP VERSION        	DESCRIPTION                                  
spark-operator/spark-operator	1.0.2        	v1beta2-1.2.0-3.0.0	A Helm chart for Spark on Kubernetes operator
```

The last part is to update the docs with the new instructions, I'll open a PR for that

**Comment by jgardner04** [comment]
@liyinan926 & @HagaiBarel Awesome! thanks for working on this. I will work on updating the installation documentation.
