### ISSUE TITLE
Spark Streaming offsets keep proceeding without committing

### ISSUE THREAD

**Issue by amitme10** [GoogleCloudPlatform/spark-on-k8s-operator#1024]
Hey ,
I'm not sure if this is the right place (due to the it might not be an Operator related issue at all), but I'll ask :
I'm using Spark streaming (2.4) with the operator and I notice that even without committing to Kafka my already done offsets the offset keep proceeding . however when I close the app , it will start over from the same offset ranges as was before (because there was not any commit to Kafka)
therefore I figured out that there might be a special internal cache method at Spark streaming but I couldn't notice any of this at the documentation ,
maybe you can advice ?

mant thanks.

**Comment by amitme10** [comment]
Hey ,
I'm not sure if this is the right place (due to the it might not be an Operator related issue at all), but I'll ask :
I'm using Spark streaming (2.4) with the operator and I notice that even without committing to Kafka my already done offsets the offset keep proceeding . however when I close the app , it will start over from the same offset ranges as was before (because there was not any commit to Kafka)
therefore I figured out that there might be a special internal cache method at Spark streaming but I couldn't notice any of this at the documentation ,
maybe you can advice ?


mant thanks.

**Comment by jinxingwang** [comment]
Your question seems to be a spark Kafka usage, spark operator doesn't modify how Spark works at all.
Where you are starting your office should be the init configuration of your Kafka producer, things you may want to check, where you are checking the offset spark side or kafka side? you can try to debug your Kafka producer by starting an empty producer, see if the offset still moving.
