### ISSUE TITLE
spark:v3.0.0 image uses too old hadoop jars

### ISSUE THREAD

**Issue by cohadar** [GoogleCloudPlatform/spark-on-k8s-operator#1029]
Specifically it uses hadoop jars 2.7.4 from year 2017.
This is useless because when I try to process files on s3 I can't because hadoop 2.7.4 requires aws-java-sdk 1.7 from year 2014.
This version of aws-java-sdk is not even hosted by maven central any more!

Please update hadoop jars in spark to 3.2.0 or newer.

**Comment by sshah90** [comment]
Hi @cohadar 

Can you please check [this](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/962#issuecomment-651550920) comment if it helps you?

Thanks.

**Comment by liyinan926** [comment]
Thanks @sshah90. @cohadar the image `gcr.io/spark-operator/spark:v3.0.0-hadoop3` has Hadoop 3 support built in.
