### ISSUE TITLE
How to configure SparkApplication on EKS to authenticate with S3 using IAM Roles

### ISSUE THREAD

**Issue by Coqueiro** [GoogleCloudPlatform/spark-on-k8s-operator#1041]
Hi! We’re running the Spark Operator on EKS, and we usually distribute permissions to pods through IAM role annotations (iam.amazonaws.com/role). I have set a role to access S3 buckets, and I’m running a SparkApplication, but I don’t know how to configure the spark confs to correctly access S3. I’m using a custom Spark image (Spark 3.0.0 and Hadoop 3.2.0) with `hadoop-aws` and `aws-sdk-bundle`  and already did a few successful tests with a local minio.

Anyone has any idea on how to configure Spark to authenticate and access S3 using IAM roles?

**Comment by shardulsrivastava** [comment]
@Coqueiro  you can configure your spark driver and executor pods to use a service account like this :

```yaml
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
```

And then you can setup this service account with the IAM role using [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

Let's say your  IAM policy name for S3 is - `my-s3-policy`,  you can create iam service account for your eks cluster using `eksctl` :

```bash
eksctl create iamserviceaccount --cluster=<clusterName> --name=spark --namespace=<spark namespace> --attach-policy-arn=arn:aws:iam::aws:policy/my-s3-policy --override-existing-serviceaccounts
```

Refer to [this](https://eksctl.io/usage/iamserviceaccounts/) for creating IAM service accounts using eksctl

**Comment by Coqueiro** [comment]
Thanks for sharing, @shardulsrivastava !

**Comment by roitvt** [comment]
Also add:
  hadoopConf:
    "fs.s3a.aws.credentials.provider": "com.amazonaws.auth.WebIdentityTokenCredentialsProvider"
So it will use the right credentials
