### ISSUE TITLE
Dynamic Auto Scaling Executors - Kubernetes

### ISSUE THREAD

**Issue by vishnugs** [GoogleCloudPlatform/spark-on-k8s-operator#1044]
Hi Team,

Please let me know when the dynamic scaling out /scale in feature with executors would be available in spark with kubernetes ?

It was suppose to be in 3.0.0

**Comment by liyinan926** [comment]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#dynamic-allocation

**Comment by tommyongib** [comment]
@liyinan926 could you please provide more details on the wording "limited form of dynamic allocation" ? Why is it limited and what would a "full" support be? Thank you.
