### ISSUE TITLE
The port of jmxexporter  8090 is not on  when running the example spark-pi-prometheus.yaml

### ISSUE THREAD

**Issue by joanjiao2016** [GoogleCloudPlatform/spark-on-k8s-operator#1053]
Hi All,
I am running the example with  spark-pi-prometheus.yaml ，the application runs well，but  the port  8090 is not on ，can anyone help ?

```

[root@master examples]# sparkctl list
+----------+-----------+----------------+-----------------+
|   NAME   |   STATE   | SUBMISSION AGE | TERMINATION AGE |
+----------+-----------+----------------+-----------------+
| spark-pi | RUNNING   | 10h            | N.A.            |
| +----------+-----------+----------------+-----------------+

[root@master examples]# kubectl get endpoints
NAME                                   ENDPOINTS                                            AGE
kubernetes                             192.168.96.131:6443                                  86d
spark-pi-557987757045c556-driver-svc   10.244.1.41:4040,10.244.1.41:7078,10.244.1.41:7079   28s
spark-pi-ui-svc                        10.244.1.41:4040                                     28s

[root@master examples]# netstat -an|grep 8090
[root@master examples]# 
```

**Comment by shardulsrivastava** [comment]
@joanjiao2016  as per my understanding, you don't see it in the endpoint because this port is not exposed as part of the service, so this port is accessible on each individual driver and executor pod however service definition didn't contain this port.

you can check your pods whether they have this port exposed or not by running this command.
```bash
kubectl get pods -l version=3.0.0  -o json|jq -r '.items[].spec.containers[].ports'
```

Note: this label `version: 3.0.0` is added in the [spark-pi-prometheus](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-prometheus.yaml) example.

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/bd1b7ec1f20d9a8bd991ddb335b908fab2cc3316/examples/spark-pi-prometheus.yaml#L38


also you can check if your driver and executor pods have annotations with this command:

```bash
kubectl get pods -l version=3.0.0 -o json|jq -r '.items[].metadata.annotations' 
```
it should return something like this
```yaml
{
  "prometheus.io/path": "/metrics",
  "prometheus.io/port": "8090",
  "prometheus.io/scrape": "true"
}

```

**Comment by tinawenqiao** [comment]
@shardulsrivastava   8090 port is not exposed on driver pod. How to expose this port？Can you give us a detailed example.
` wenqiao@bogon  ~/work/bigdata/k8s/spark/spark-on-k8s-operator/manifest   master ●  kubectl get pods -l version=3.0.0  -o json|jq -r '.items[].spec.containers[].ports'
[
  {
    "containerPort": 7078,
    "name": "driver-rpc-port",
    "protocol": "TCP"
  },
  {
    "containerPort": 7079,
    "name": "blockmanager",
    "protocol": "TCP"
  },
  {
    "containerPort": 4040,
    "name": "spark-ui",
    "protocol": "TCP"
  }
]`

**Comment by shardulsrivastava** [comment]
@tinawenqiao you should get this port exposed in your driver and executor pods by following [this](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-prometheus.yaml) example.

If you're not getting it, can you share your yaml manifest and the output of this command ( in a gist, would be easier to read):

```
kubectl get pods -l version=3.0.0  -o json
```

**Comment by tinawenqiao** [comment]
@shardulsrivastava Yes, we try to expose 8090 metric port by following that example. But we didn't get it.
{
    "apiVersion": "v1",
    "items": [
        {
            "apiVersion": "v1",
            "kind": "Pod",
            "metadata": {
                "annotations": {
                    "prometheus.io/path": "/metrics",
                    "prometheus.io/port": "8090",
                    "prometheus.io/scrape": "true"
                },
                "creationTimestamp": "2020-11-04T17:44:32Z",
                "labels": {
                    "spark-app-selector": "spark-ebba8ff4d944431eb9a5406306f12b49",
                    "spark-role": "driver",
                    "sparkoperator.k8s.io/app-name": "spark-pi",
                    "sparkoperator.k8s.io/launched-by-spark-operator": "true",
                    "sparkoperator.k8s.io/submission-id": "691bfffa-3562-48d4-8dc0-68525b9eb072",
                    "version": "3.0.0"
                },
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:metadata": {
                                "f:annotations": {
                                    ".": {},
                                    "f:prometheus.io/path": {},
                                    "f:prometheus.io/port": {},
                                    "f:prometheus.io/scrape": {}
                                },
                                "f:labels": {
                                    ".": {},
                                    "f:spark-app-selector": {},
                                    "f:spark-role": {},
                                    "f:sparkoperator.k8s.io/app-name": {},
                                    "f:sparkoperator.k8s.io/launched-by-spark-operator": {},
                                    "f:sparkoperator.k8s.io/submission-id": {},
                                    "f:version": {}
                                }
                            },
                            "f:spec": {
                                "f:containers": {
                                    "k:{\"name\":\"spark-kubernetes-driver\"}": {
                                        ".": {},
                                        "f:args": {},
                                        "f:env": {
                                            ".": {},
                                            "k:{\"name\":\"SPARK_APPLICATION_ID\"}": {
                                                ".": {},
                                                "f:name": {},
                                                "f:value": {}
                                            },
                                            "k:{\"name\":\"SPARK_CONF_DIR\"}": {
                                                ".": {},
                                                "f:name": {},
                                                "f:value": {}
                                            },
                                            "k:{\"name\":\"SPARK_DRIVER_BIND_ADDRESS\"}": {
                                                ".": {},
                                                "f:name": {},
                                                "f:valueFrom": {
                                                    ".": {},
                                                    "f:fieldRef": {
                                                        ".": {},
                                                        "f:apiVersion": {},
                                                        "f:fieldPath": {}
                                                    }
                                                }
                                            },
                                            "k:{\"name\":\"SPARK_LOCAL_DIRS\"}": {
                                                ".": {},
                                                "f:name": {},
                                                "f:value": {}
                                            },
                                            "k:{\"name\":\"SPARK_USER\"}": {
                                                ".": {},
                                                "f:name": {},
                                                "f:value": {}
                                            }
                                        },
                                        "f:image": {},
                                        "f:imagePullPolicy": {},
                                        "f:name": {},
                                        "f:ports": {
                                            ".": {},
                                            "k:{\"containerPort\":4040,\"protocol\":\"TCP\"}": {
                                                ".": {},
                                                "f:containerPort": {},
                                                "f:name": {},
                                                "f:protocol": {}
                                            },
                                            "k:{\"containerPort\":7078,\"protocol\":\"TCP\"}": {
                                                ".": {},
                                                "f:containerPort": {},
                                                "f:name": {},
                                                "f:protocol": {}
                                            },
                                            "k:{\"containerPort\":7079,\"protocol\":\"TCP\"}": {
                                                ".": {},
                                                "f:containerPort": {},
                                                "f:name": {},
                                                "f:protocol": {}
                                            }
                                        },
                                        "f:resources": {
                                            ".": {},
                                            "f:limits": {
                                                ".": {},
                                                "f:cpu": {},
                                                "f:memory": {}
                                            },
                                            "f:requests": {
                                                ".": {},
                                                "f:cpu": {},
                                                "f:memory": {}
                                            }
                                        },
                                        "f:terminationMessagePath": {},
                                        "f:terminationMessagePolicy": {},
                                        "f:volumeMounts": {
                                            ".": {},
                                            "k:{\"mountPath\":\"/opt/spark/conf\"}": {
                                                ".": {},
                                                "f:mountPath": {},
                                                "f:name": {}
                                            },
                                            "k:{\"mountPath\":\"/var/data/spark-e24c6fc7-3a2f-4cf5-8e0f-033ff82f4346\"}": {
                                                ".": {},
                                                "f:mountPath": {},
                                                "f:name": {}
                                            }
                                        }
                                    }
                                },
                                "f:dnsPolicy": {},
                                "f:enableServiceLinks": {},
                                "f:restartPolicy": {},
                                "f:schedulerName": {},
                                "f:securityContext": {},
                                "f:serviceAccount": {},
                                "f:serviceAccountName": {},
                                "f:terminationGracePeriodSeconds": {},
                                "f:volumes": {
                                    ".": {},
                                    "k:{\"name\":\"spark-conf-volume\"}": {
                                        ".": {},
                                        "f:configMap": {
                                            ".": {},
                                            "f:defaultMode": {},
                                            "f:name": {}
                                        },
                                        "f:name": {}
                                    },
                                    "k:{\"name\":\"spark-local-dir-1\"}": {
                                        ".": {},
                                        "f:emptyDir": {},
                                        "f:name": {}
                                    }
                                }
                            }
                        },
                        "manager": "okhttp",
                        "operation": "Update",
                        "time": "2020-11-04T17:44:32Z"
                    },
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:status": {
                                "f:conditions": {
                                    "k:{\"type\":\"ContainersReady\"}": {
                                        ".": {},
                                        "f:lastProbeTime": {},
                                        "f:lastTransitionTime": {},
                                        "f:reason": {},
                                        "f:status": {},
                                        "f:type": {}
                                    },
                                    "k:{\"type\":\"Initialized\"}": {
                                        ".": {},
                                        "f:lastProbeTime": {},
                                        "f:lastTransitionTime": {},
                                        "f:reason": {},
                                        "f:status": {},
                                        "f:type": {}
                                    },
                                    "k:{\"type\":\"Ready\"}": {
                                        ".": {},
                                        "f:lastProbeTime": {},
                                        "f:lastTransitionTime": {},
                                        "f:reason": {},
                                        "f:status": {},
                                        "f:type": {}
                                    }
                                },
                                "f:containerStatuses": {},
                                "f:hostIP": {},
                                "f:phase": {},
                                "f:podIP": {},
                                "f:podIPs": {
                                    ".": {},
                                    "k:{\"ip\":\"10.244.3.44\"}": {
                                        ".": {},
                                        "f:ip": {}
                                    }
                                },
                                "f:startTime": {}
                            }
                        },
                        "manager": "kubelet",
                        "operation": "Update",
                        "time": "2020-11-04T17:51:01Z"
                    }
                ],
                "name": "spark-pi-driver",
                "namespace": "default",
                "resourceVersion": "2091149",
                "selfLink": "/api/v1/namespaces/default/pods/spark-pi-driver",
                "uid": "1083ad83-cb80-4052-9ba7-6e908a05e116"
            },
            "spec": {
                "containers": [
                    {
                        "args": [
                            "driver",
                            "--properties-file",
                            "/opt/spark/conf/spark.properties",
                            "--class",
                            "org.apache.spark.examples.SparkPi",
                            "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar",
                            "100000"
                        ],
                        "env": [
                            {
                                "name": "SPARK_USER",
                                "value": "root"
                            },
                            {
                                "name": "SPARK_APPLICATION_ID",
                                "value": "spark-ebba8ff4d944431eb9a5406306f12b49"
                            },
                            {
                                "name": "SPARK_DRIVER_BIND_ADDRESS",
                                "valueFrom": {
                                    "fieldRef": {
                                        "apiVersion": "v1",
                                        "fieldPath": "status.podIP"
                                    }
                                }
                            },
                            {
                                "name": "SPARK_LOCAL_DIRS",
                                "value": "/var/data/spark-e24c6fc7-3a2f-4cf5-8e0f-033ff82f4346"
                            },
                            {
                                "name": "SPARK_CONF_DIR",
                                "value": "/opt/spark/conf"
                            }
                        ],
                        "image": "gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus",
                        "imagePullPolicy": "Always",
                        "name": "spark-kubernetes-driver",
                        "ports": [
                            {
                                "containerPort": 7078,
                                "name": "driver-rpc-port",
                                "protocol": "TCP"
                            },
                            {
                                "containerPort": 7079,
                                "name": "blockmanager",
                                "protocol": "TCP"
                            },
                            {
                                "containerPort": 4040,
                                "name": "spark-ui",
                                "protocol": "TCP"
                            }
                        ],
                        "resources": {
                            "limits": {
                                "cpu": "1200m",
                                "memory": "896Mi"
                            },
                            "requests": {
                                "cpu": "1",
                                "memory": "896Mi"
                            }
                        },
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/data/spark-e24c6fc7-3a2f-4cf5-8e0f-033ff82f4346",
                                "name": "spark-local-dir-1"
                            },
                            {
                                "mountPath": "/opt/spark/conf",
                                "name": "spark-conf-volume"
                            },
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "spark-token-4kpfr",
                                "readOnly": true
                            }
                        ]
                    }
                ],
                "dnsPolicy": "ClusterFirst",
                "enableServiceLinks": true,
                "nodeName": "kworker3.example.com",
                "preemptionPolicy": "PreemptLowerPriority",
                "priority": 0,
                "restartPolicy": "Never",
                "schedulerName": "default-scheduler",
                "securityContext": {},
                "serviceAccount": "spark",
                "serviceAccountName": "spark",
                "terminationGracePeriodSeconds": 30,
                "tolerations": [
                    {
                        "effect": "NoExecute",
                        "key": "node.kubernetes.io/not-ready",
                        "operator": "Exists",
                        "tolerationSeconds": 300
                    },
                    {
                        "effect": "NoExecute",
                        "key": "node.kubernetes.io/unreachable",
                        "operator": "Exists",
                        "tolerationSeconds": 300
                    }
                ],
                "volumes": [
                    {
                        "emptyDir": {},
                        "name": "spark-local-dir-1"
                    },
                    {
                        "configMap": {
                            "defaultMode": 420,
                            "name": "spark-pi-52323575945c58fe-driver-conf-map"
                        },
                        "name": "spark-conf-volume"
                    },
                    {
                        "name": "spark-token-4kpfr",
                        "secret": {
                            "defaultMode": 420,
                            "secretName": "spark-token-4kpfr"
                        }
                    }
                ]
            },
            "status": {
                "conditions": [
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2020-11-04T17:44:31Z",
                        "reason": "PodCompleted",
                        "status": "True",
                        "type": "Initialized"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2020-11-04T17:51:00Z",
                        "reason": "PodCompleted",
                        "status": "False",
                        "type": "Ready"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2020-11-04T17:51:00Z",
                        "reason": "PodCompleted",
                        "status": "False",
                        "type": "ContainersReady"
                    },
                    {
                        "lastProbeTime": null,
                        "lastTransitionTime": "2020-11-04T17:44:32Z",
                        "status": "True",
                        "type": "PodScheduled"
                    }
                ],
                "containerStatuses": [
                    {
                        "containerID": "docker://b2465613e4b4614bab17d3f8114f82b89986718dcbba4f504c0bd88f008477a0",
                        "image": "gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus",
                        "imageID": "docker-pullable://gcr.io/spark-operator/spark@sha256:b74421a78bbe577c12827aedab401405d90f02af64a19898a519d771fc7817bd",
                        "lastState": {},
                        "name": "spark-kubernetes-driver",
                        "ready": false,
                        "restartCount": 0,
                        "started": false,
                        "state": {
                            "terminated": {
                                "containerID": "docker://b2465613e4b4614bab17d3f8114f82b89986718dcbba4f504c0bd88f008477a0",
                                "exitCode": 0,
                                "finishedAt": "2020-11-04T17:50:59Z",
                                "reason": "Completed",
                                "startedAt": "2020-11-04T17:44:39Z"
                            }
                        }
                    }
                ],
                "hostIP": "172.42.42.103",
                "phase": "Succeeded",
                "podIP": "10.244.3.44",
                "podIPs": [
                    {
                        "ip": "10.244.3.44"
                    }
                ],
                "qosClass": "Burstable",
                "startTime": "2020-11-04T17:44:31Z"
            }
        }
    ],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}

**Comment by joanjiao2016** [comment]
I found the port on inside the  spark pods，use  the command “kubectl port-forward " can get the metrics .

**Comment by grantatspothero** [comment]
@joanjiao2016 there is a bug with exposing the port if you use a custom prometheus configuration file/spark metrics config file:

 (PR to fix it here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1165)
