### ISSUE TITLE
Spark v1beta2: Incorrect Driver/Executor Resources 

### ISSUE THREAD

**Issue by akhurana001** [GoogleCloudPlatform/spark-on-k8s-operator#1055]
As part of migrating to v1beta2, we ran into an issue where the driver/executor cores/memory values in spark_conf were up getting overridden to defaults set in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/apis/sparkoperator.k8s.io/v1beta2/defaults.go#L50 . 

Looking at https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/submission.go#L152, the spark-submit ends up having duplicate values for these config: firstly  values from spark_conf  are appended to the submit args and then values from the CRD Spec which leads to the CRD values taking precedence.

I believe its fine to have the CRD Spec configs take precedence over spark_conf  if both are set but currently, even if a user sets these values only as part of spark_conf, these get overridden as we default the CRD Spec values if they are not set (https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/apis/sparkoperator.k8s.io/v1beta2/defaults.go#L50)  effectively leading to no-way of specifying these values as part of spark_conf only.

Also any particular reason we need to default these values at the Operator level as Spark will anyways default these if they are not set as part of spark-submit.

**Comment by akhurana001** [comment]
@liyinan926 lemme know what your thoughts are on this. I also created https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1057 to add a check for spark-conf if this looks fine .

**Comment by liyinan926** [comment]
Fixed in #1057.
