### ISSUE TITLE
Unable to create CustomResourceDefinition

### ISSUE THREAD

**Issue by bofaalsarah** [GoogleCloudPlatform/spark-on-k8s-operator#1063]
Hello, 

I am trying to setup the spark operator on minikube with  --kubernetes-version=v1.18.10. When applying the yaml files in the manifest directory, I am not able to apply the ones in the crds directory which are the ones responsible for creating the CustomResourceDefinition. I am getting this below error when trying to do so, 

`The CustomResourceDefinition "sparkapplications.sparkoperator.k8s.io" is invalid: 
*spec.validation.openAPIV3Schema.properties[spec].properties[executor].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
*spec.validation.openAPIV3Schema.properties[spec].properties[executor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
*spec.validation.openAPIV3Schema.properties[spec].properties[driver].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property
*spec.validation.openAPIV3Schema.properties[spec].properties[driver].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property`

To reproduce the issue, you can try executing `kubectl apply -f crds/sparkoperator.k8s.io_sparkapplications.yaml`

Am I missing something here or the manifest files are not complete?

**Comment by scravy** [comment]
Are you using k8s 1.18? I am facing the same problem, I believe it is related to https://github.com/kubernetes/kubernetes/issues/91395

**Comment by liyinan926** [comment]
The CRDs in the Helm Chart has been fixed in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1084.
