### ISSUE TITLE
CRDs fail to deploy on k8s 1.18

### ISSUE THREAD

**Issue by scravy** [GoogleCloudPlatform/spark-on-k8s-operator#1065]
I am getting these:

```
Error: failed to install CRD crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml: CustomResourceDefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
```

This happens with both releases `spark-on-k8s-operator-1beta2-1.2.1-3.0.0` as well as `spark-on-k8s-operator-1beta2-1.2.0-3.0.0`

Using:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:04:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by scravy** [comment]
This seems to be the underlying issue: https://github.com/kubernetes/kubernetes/issues/91395

**Comment by jordanbailes** [comment]
I came across this problem also. Has been fixed in a previous release with https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/5b2fe9218108baa6456eb3472196d5eb55b41efd 

Essentially to get this working with the chart checked into this repo, find anywhere where  
`x-kubernetes-list-map-keys: ` contains `- protocol` and add it into the required 

e.g. 
`                          ports:
                            items:
                              properties:
                                containerPort:
                                  format: int32
                                  type: integer
                                hostIP:
                                  type: string
                                hostPort:
                                  format: int32
                                  type: integer
                                name:
                                  type: string
                                protocol:
                                  type: string
                              required:
                              - containerPort
                              - protocol
                              type: object
                            type: array
                            x-kubernetes-list-map-keys:
                            - containerPort
                            **- protocol**
                            x-kubernetes-list-type: map`

I have done this on a local version of the chart and been able to get through the validation errors. It is clear from the commit message referenced above that this was a manual fix and perhaps there is a better way to address this. If there is no more permanent workaround and would be useful for me to open a PR to do this for, I am happy to do so.

**Comment by akhurana001** [comment]
Ran into this as well and cherry-picking https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/5b2fe9218108baa6456eb3472196d5eb55b41efd does fix the issue thou the latest crd on master is broken.

**Comment by liyinan926** [comment]
This has been fixed in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1084.
