### ISSUE TITLE
How to expose port apply the resident application service?

### ISSUE THREAD

**Issue by marktanzy** [GoogleCloudPlatform/spark-on-k8s-operator#1070]
I write a resident application which accept http request listen on 8000, then apply the application through the command ` kubectl apply -f k8s.yaml`. how can I export the internal container port 8000 to external network. I look up the SparkApplication conf properties, I find no such options in the yaml file to expose the internal server listen tcp port.

help me please!
help me please!
help me please!

**Comment by Rybaak** [comment]
Hi, do you find solution -  I ahve the same problem ?
