### ISSUE TITLE
Helm 3 Chart Release Branch

### ISSUE THREAD

**Issue by jgardner04** [GoogleCloudPlatform/spark-on-k8s-operator#1071]
#1066 creates the GitHub action to publish the index.yaml needed to use the Helm 3 chart. It is configured to publish this to a `gh-pages` branch. The action is failing because this branch does not exist. Without the GitHub Pages configuration using the chart as a Helm Dependency fails. To correct this:

* Create a `gh-pages` branch.
```bash
git checkout master
git checkout --orphan -b gh-pages
git push -u origin gh-pages
```

* [Configure GitHub Pages](https://guides.github.com/features/pages/) for the `gh-pages` branch
This can be found under settings and near the bottom and with the gh-pages branch might already pick up the correct branch settings. 

* Re-run the GitHub action to Release the Charts
Actions -> Release Charts -> [Add GitHub Action to Release Chart (#1066)](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/actions/runs/367442520) -> Re-run jobs

With this done, I can update the Readme with the Helm 3 deployment instructions

**Comment by jkleckner** [comment]
@liyinan926 Can we unblock this?

**Comment by HagaiBarel** [comment]
Pinging @liyinan926 @yuchaoran2011. I'd love to be added as project maintainer to help with this and other `helm` related issues

**Comment by liyinan926** [comment]
Done. Tried rerunning the action and it succeeded.

**Comment by jgardner04** [comment]
@liyinan926 what is the GitHub Pages URL for the site? I will give it a test. I am not seeing the index.yaml I would expect in the `gh-pages` branch so I will need to dig a bit and find out what is going on.

**Comment by jgardner04** [comment]
Update. Tracking problem with #1095
