### ISSUE TITLE
Unable to install the operator with Helm3

### ISSUE THREAD

**Issue by ityuhui** [GoogleCloudPlatform/spark-on-k8s-operator#1087]
Hi there
I want to install this operator in my k8s cluster with Helm3 but cannot succeed. Below is my step:

```shell
root@yuhuium:~# helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

root@yuhuium:~# helm repo add incubator https://charts.helm.sh/incubator --force-update
"incubator" has been added to your repositories

root@yuhuium:~# helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default
Error: must either provide a name or specify --generate-name

root@yuhuium:~# helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default --generate-name
WARNING: This chart is deprecated
W1126 21:05:16.719539    2096 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1126 21:05:16.721503    2096 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: create: failed to create: namespaces "spark-operator" not found
```

Could you please help check this ?  Thanks.

**Comment by jordanbailes** [comment]
You need to add the spark-operator namespace

**Comment by ityuhui** [comment]
Thank you @jordanbailes  !
The solution resolves my problem.

Hi @liyinan926
May I create a PR to update the readme/guide for this problem? I think somebody will have the same question in the future. 

_This will install the Kubernetes Operator for Apache Spark into the namespace spark-operator, **_if the namespce spark-operator does not exist, create it by manul, e.g._** 
 ```kubectl create namespace spark-operator```_

**Comment by ityuhui** [comment]
But from [Quick Start Guide](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md), I can see

```shell
$ helm repo add incubator https://charts.helm.sh/incubator --force-update
$ helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default
```
_Installing the chart will create a namespace spark-operator if it doesn't exist_

**Comment by ityuhui** [comment]
Close this issue because it is resovled.
