### ISSUE TITLE
Apache Spark 2.3 app on which Spark Operator version

### ISSUE THREAD

**Issue by Fixmetal** [GoogleCloudPlatform/spark-on-k8s-operator#1088]
Hello everybody,
I've setup this operator to be working for a bunch of applications. I've been using `v1beta2-1.1.2-2.4.5`.
I'm struggling because I don't understand the compatibility between Spark and the Spark operator really. The [overview](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/v1beta2-1.1.2-2.4.5#overview) states `Supports Spark 2.3 and up.` so I've come to the idea that for running an Apache Spark 2.3 application I've got to define the SparkApplication CR like:
```
spec.sparkVersion: 2.3.0
```
Does this suffice? I use the `gcr.io/spark-operator/spark:v2.4.5` as a Base Image.
Thanks

**Comment by liyinan926** [comment]
You will need a spark operator version based on Spark 2.3.x, like this one https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/releases/tag/v1alpha1-0.4-2.3.x. We stopped maintaining the 2.3 based branch a long time ago so it's lacking features.

**Comment by Fixmetal** [comment]
wouldn't the multi-version-support branch work? isn't it purposed for supporting both 2.3 and 2.4?

**Comment by liyinan926** [comment]
Sure, you can use that branch.

**Comment by Fixmetal** [comment]
> Sure, you can use that branch.

Well in the meantime I started using that. I suppose to make a 2.3 app work it is correct to just override the `spec.sparkVersion` and `spec.driver.labels.version`  `spec.executor.labels.version`, isn't it?

**Comment by liyinan926** [comment]
Yes, and there's some API difference here. You can specify the k8s service account to be used by the pod running `spark-submit` using the following field:

```yaml
spec:
  serviceAccount: <your sa>
```

**Comment by Fixmetal** [comment]
Thanks for confirming that. Seems I did everything correctly. Thank you very much.
Now I'm facing some OOM waddayaknow-whatever errors and can't get any ideas on why is that but that's a whole different story

**Comment by Fixmetal** [comment]
@liyinan926 : just to shed some light on this: which base image version should an application based on 2.3 be using with multi-support-version? Is `gcr.io/spark-operator/spark:v2.4.5-gcs-prometheus` fine or 2.3 specific applications should rely on previous `gcr.io/spark-operator/spark:v2.3.0`

**Comment by liyinan926** [comment]
`gcr.io/spark-operator/spark:v2.3.0` is the one to use. You can also build your own 2.3.x image if you want to have custom jars/deps.

**Comment by Fixmetal** [comment]
> `gcr.io/spark-operator/spark:v2.3.0` is the one to use. You can also build your own 2.3.x image if you want to have custom jars/deps.

Thanks a lot. It happens to be working with 2.4.5 as base image really.
Might I suggest to add all these infos in the multi-support-version branch docs?

**Comment by Fixmetal** [comment]
Hello there,
I just patched my 2.3.x applications to use `gcr.io/spark-operator/spark:v2.3.1-gcs-prometheus` as a base image, fixing the https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/591 by using version `4.6.4` of kubernetes-client and fixing dependencies following [this](https://issues.apache.org/jira/browse/SPARK-28921?focusedCommentId=17022625&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17022625).
I patched the SparkApplications with 2.3.1:
```
$ yq r apps/vqos.yaml  spec.sparkVersion
2.3.1
$ yq r apps/vqos.yaml  spec.driver.labels
version: 2.3.1
$ yq r apps/vqos.yaml  spec.executor.labels
version: 2.3.1
```
Now I'm facing this exact same issue https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/564:
```
+ exec /sbin/tini -s -- /usr/lib/jvm/java-1.8-openjdk/bin/java -cp ':/opt/spark/jars/*' -Xms -Xmx -Dspark.driver.bindAddress=10.233.71.148
Invalid initial heap size: -Xms
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

I'm using the `multi-version-support` branch and the operator is using its original image: `gcr.io/spark-operator/spark-operator:v2.4.5-v1beta2-latest` just as [relative manifest](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/multi-version-support/manifest/spark-operator-with-webhook.yaml)

So now I'm kind of at a loss now because:
- you suggested to use the 2.3 image, but it doesn't work
- using `gcr.io/spark-operator/spark:v2.4.5-gcs-prometheus` as a base image and specificing `sparkVersion: 2.3.1` they work even if the Spark Console shows `2.4.5` at top

Would you mind help sorting this out?

**Comment by Fixmetal** [comment]
Any news on this?

**Comment by Fixmetal** [comment]
bump. no support at all I changed up my solution.
