### ISSUE TITLE
can not create operator by helm

### ISSUE THREAD

**Issue by majorinche** [GoogleCloudPlatform/spark-on-k8s-operator#1093]
[root@d0404 ~]# kubectl create ns spark-operator
namespace/spark-operator created
[root@d0404 ~]# helm install my-spark chartmuseum/sparkoperator --version 0.8.6
WARNING: This chart is deprecated
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: sparkapplications.sparkoperator.k8s.io, existing_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition, new_kind: apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition

what does this error refers to?

**Comment by jgardner04** [comment]
Similar to #1087 

Helm has moved away from the Helm 2 model of a central repo for charts. Work is being done in this repo to migrate to Helm 3 and get this deployment working again.

**Comment by liyinan926** [comment]
The migration has been completed. Please see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1021 for more details.
