### ISSUE TITLE
GitHub Action Fails to Release Chart

### ISSUE THREAD

**Issue by jgardner04** [GoogleCloudPlatform/spark-on-k8s-operator#1095]
When the GitHub action runs to release an update to the Helm Chart, it errors with the following [error](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/runs/1481409848?check_suite_focus=true#step:11:17):

```
Error: error creating GitHub release: POST https://api.github.com/repos/GoogleCloudPlatform/spark-on-k8s-operator/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
![Screen Shot 2020-12-02 at 8 59 03 AM](https://user-images.githubusercontent.com/397953/100905237-b0b25b80-347c-11eb-95cd-4d7ba4b8db68.png)

This is because the action is expecting to create the GitHub release, but this has already been done by TravisCI.

It appears that there is a feature [request/issue](https://github.com/helm/chart-releaser-action/issues/70) in the helm/chart-releaser-action that is used in the GitHub Action to track being able to append the chart release to an existing release in the repo.

The other option to explore is letting the GitHub Action handle the release instead of Travis.

**Comment by HagaiBarel** [comment]
@jgardner04 I recommend taking a look at https://www.github.com/kubernetes/autoscaler/tree/master/, they're doing something similar with travis and a chart as well

**Comment by jgardner04** [comment]
@HagaiBarel & @liyinan926 we should see this release correctly once we rev. the Spark Chart
