### ISSUE TITLE
Support configuring Service type for Spark UI

### ISSUE THREAD

**Issue by jutley** [GoogleCloudPlatform/spark-on-k8s-operator#1096]
The Spark UI services are currently hardcoded to be ClusterIP types. Our Ingress controller requires services to be of type NodePort or LoadBalancer in order for our external load balancer to reach them. In order to support more Ingress implementations, the service type should be configurable.

**Comment by liyinan926** [comment]
It should be straightforward to add an API field under `.spec.sparkUIOptions` for specifying the service type, which defaults to `NodePort` if unspecified.

**Comment by jutley** [comment]
I am attempting to implement this. It seems pretty straightforward, but I think I have a newer version of controller-gen. I figured out how to configure it to use the v1 CRD version instead of v1beta1, but there are a bunch of new generated docs for default Kubernetes types. Is it okay if these get added in?

**Comment by shalseban** [comment]
Has this fix been released. I don't see `ServiceType` in the `api-docs.md`
