### ISSUE TITLE
Examples from multi-support branch version are wrong

### ISSUE THREAD

**Issue by Fixmetal** [GoogleCloudPlatform/spark-on-k8s-operator#1126]
All examples in `multi-version-support` shows to use the `.spec.serviceAccount` to let driver know which SA to use for creating Executors pods, but this is wrong: this way the driver expects `default` SA to have the proper permissions to do so. This is mis-leading in an already challenging branch (is it abandoned?). I'm making a PR to fix this.

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/multi-version-support/examples

**Comment by liyinan926** [comment]
They are not wrong. The field `.spec.serviceAccount` is used by the pod running `spark-submit` to be able to create the driver pod. The service account used by the driver pod is separate,.

**Comment by Fixmetal** [comment]
So how can it be that following multi-version-support [manifests](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/multi-version-support/manifest) it:

- doesn't generate any k8s job
- invalidates `.spec.serviceAccount` field (I get an error)
- I get #1088

**Comment by Fixmetal** [comment]
I'm closing this issue since I've not received any lights therefore I changed the way I deploy Spark on K8S.
