### ISSUE TITLE
Dockerfile source code of gcr.io/ynli-k8s/spark

### ISSUE THREAD

**Issue by elgalu** [GoogleCloudPlatform/spark-on-k8s-operator#113]
Hi, thanks for this project.

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/4f74796bae8dad06fea9d27d3337fda8e69850c4/Dockerfile#L17

Could you point me to the source code of this base docker image?

**Comment by liyinan926** [comment]
Hi @elgalu, the source code of the base image is at https://github.com/apache/spark/tree/master/resource-managers/kubernetes/core. The docker file used to build the base image is at https://github.com/apache/spark/tree/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark.
