### ISSUE TITLE
CPU/Memory Limits for the Operator's pod

### ISSUE THREAD

**Issue by ordukhanian** [GoogleCloudPlatform/spark-on-k8s-operator#1140]
Is it possible to set CPU/Memory limits for the operator's pod?
I was able to find setting only for driver's and executor's pods.

**Comment by fbalicchia** [comment]
Hi, yes if you install operator with helm is possible set the resources limits.
[resources-limits](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/charts/spark-operator-chart/values.yaml#L115)
