### ISSUE TITLE
Spark 2.4.5 with Hadoop 3

### ISSUE THREAD

**Issue by ordukhanian** [GoogleCloudPlatform/spark-on-k8s-operator#1192]
Hello, 
Spark 2.4.5 comes with Hadoop 2, which is old and does not work properly.

Could you please publish docker image for 
- Spark 2.4.5 with Hadoop 3
- Spark Operator based on Spark2.4.5+Hadoop3?

**Comment by sshah90** [comment]
@ordukhanian check [this](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1029) tread
