### ISSUE TITLE
On Spark 3.x, jars listed in spark.jars and spark.jars.packages are not added to sparkContext

### ISSUE THREAD

**Issue by ocworld** [GoogleCloudPlatform/spark-on-k8s-operator#1226]
I'm trying to migrate spark 2 to spark 3.

In my environment, on Spark 3.x, jars listed in spark.jars and spark.jars.packages are not added to sparkContext.
After driver's process is launched, jars are not propagated to Executors. So, NoClassDefException is raised in executors. 

In spark.properties, the only main application jar is contained in spark.jars. It is different from Spark 2.
 
How to solve this situation? Is it any changed spark options in spark 3 from spark 2?

**Comment by LMolr** [comment]
I am facing a similar problem on Spark 3.0.0, but I'm not sure it's exactly the same.

I deploy this `SparkApplication` with Neo4J Connector as package ref.

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
spec:
  type: Python
  pythonVersion: "3"
  # ...
  deps:
      packages:
        - "neo4j-contrib:neo4j-connector-apache-spark_2.12:4.0.1_for_spark_3"
```

The driver Pod fails with `java.lang.ClassNotFoundException: Failed to find data source: org.neo4j.spark.DataSource`.

```
...
File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 184, in load
File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__
File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 131, in deco
File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o59.load.
: java.lang.ClassNotFoundException: Failed to find data source: org.neo4j.spark.DataSource. Please find packages at http://spark.apache.org/third-party-projects.html
```

The `spark-submit` launch arguments show no trace of the third-party package referenced in `SparkApplication`.

```shell
exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.244.14.49 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner local:///my-app.py
```

I also don't see in any log any attempt to resolve and install the package.

**Comment by LMolr** [comment]
Sorry, I think my issue is more related to #1132

**Comment by ocworld** [comment]
@LMolr Thank you for your reply.
I think it is only happened in spark deploy mode "cluster"

**Comment by ocworld** [comment]
I've opened the issue on apache jira also.
https://issues.apache.org/jira/browse/SPARK-35084

**Comment by ocworld** [comment]
I've make pr in apache/spark repo about it.
https://github.com/apache/spark/pull/32397
