### ISSUE TITLE
In spark 3, a driver has running status after finishing a job

### ISSUE THREAD

**Issue by ocworld** [GoogleCloudPlatform/spark-on-k8s-operator#1252]
In spark 3, a driver has running status after finishing a job.

Every executors are deleted as I expected, but driver pod status is not changed to succeed.

Anyone has experienced the same issue?

I've created the same issue in apache jira.
https://issues.apache.org/jira/browse/SPARK-35304

**Comment by arghya18** [comment]
@ocworld I have also experienced the same after I upgraded to Spark 3.1.1 from Spark 3.0. 
I had to use spark.stop() at the end to workaround the issue.
Not sure what changed and is this expected?

**Comment by jdonnelly-apixio** [comment]
We've hit this issue a few times when developers weren't properly closing connections (e.g. cassandra, redis, kafka). If you do a sparkctl forward, open the spark UI, then on the executors tab, do a thread dump for whatever is still running and that should shed some light on the issue. You could also `k exec <driver_and_or_executor_pod> -it /bin/netstat | grep EST` and that should show you whatever connections are open (but I install netstat and a few other things on top of the gcr base image).
