### ISSUE TITLE
CRDs and webhook are registered using v1beta1 of the respective K8s API (both to be desupported in K8s 1.22)

### ISSUE THREAD

**Issue by jgoeres** [GoogleCloudPlatform/spark-on-k8s-operator#1265]
The webhook is still registered admissionregistration.k8s.io/v1beta1 API version of MutatingWebhookConfiguration, which will hbe desupported with K8s 1.22, see https://kubernetes.io/docs/reference/using-api/deprecation-guide/#webhook-resources-v122.

This should be updated soon, or the use of the webhook should be abandoned, as proposed in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1176 (which seems to make a lot of sense, considering that the webhook seems to be the cause of many issues).

A similar issue exists with the CRDs, which use apiextensions.k8s.io/v1beta1, also to be desupported with K8s 1.22:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122

**Comment by abhisrao** [comment]
Hi @liyinan926 
I see that CRD's apiVersion has been changed from v1beta1 to v1. But it is not yet officially released. Do we know by when it will be released?
