### ISSUE TITLE
error running helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator

### ISSUE THREAD

**Issue by michTalebzadeh** [GoogleCloudPlatform/spark-on-k8s-operator#1289]
In reference 

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/volcano-integration.md

Trying to install Volcano I am getting this error

helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
Error: looks like "http://storage.googleapis.com/kubernetes-charts-incubator" is not a valid chart repository or cannot be reached: failed to fetch http://storage.googleapis.com/kubernetes-charts-incubator/index.yaml : 404 Not Found

Please advise.

**Comment by william-wang** [comment]
@michTalebzadeh I will update it today.

**Comment by michTalebzadeh** [comment]
Great many thanks



   view my Linkedin profile
<https://www.linkedin.com/in/mich-talebzadeh-ph-d-5205b2/>



*Disclaimer:* Use it at your own risk. Any and all responsibility for any
loss, damage or destruction of data or any other property which may arise
from relying on this email's technical content is explicitly disclaimed.
The author will in no case be liable for any monetary damages arising from
such loss, damage or destruction.

**Comment by michTalebzadeh** [comment]
Thanks so far looks promising

Install Kubernetes Operator for Apache Spark with Volcano enabled
$ helm repo add spark-operator
https://googlecloudplatform.github.io/spark-on-k8s-operator
$ helm install my-release spark-operator/spark-operator --namespace
spark-operator --set enableBatchScheduler=true --set enableWebhook=true

kubectl get pod -n spark-operator
NAME                                         READY   STATUS    RESTARTS
AGE
my-release-spark-operator-5c64448d84-m2gth   1/1     Running   0
 5m56s



   view my Linkedin profile
<https://www.linkedin.com/in/mich-talebzadeh-ph-d-5205b2/>



*Disclaimer:* Use it at your own risk. Any and all responsibility for any
loss, damage or destruction of data or any other property which may arise
from relying on this email's technical content is explicitly disclaimed.
The author will in no case be liable for any monetary damages arising from
such loss, damage or destruction.

**Comment by michTalebzadeh** [comment]
Hi,

I can see there is a YAML construction in the volcano link as below

Run Spark Application with Volcano scheduler

Now, we can run a updated version of spark application (with
batchScheduler configured),
for instance:

apiVersion: "sparkoperator.k8s.io/v1beta2"kind: SparkApplicationmetadata:
  name: spark-pi
  namespace: defaultspec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.1.1"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile:
"local:///opt/spark/examples/jars/spark-examples_2.12-v3.1.1.jar"
  sparkVersion: "3.1.1"
  batchScheduler: "volcano"   #Note: the batch scheduler name must be
specified with `volcano`
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"

What is not clear to me how you submit such job please, specifically
referencing *batchScheduler* below


spark-submit \
--master k8s://$K8S_SERVER \
--deploy-mode cluster \
--name spark-pi \
--batchScheduler volcano \  ## *is this correct*?
--class org.apache.spark.examples.SparkPi \
--conf spark.executor.instances=3 \
--conf spark.kubernetes.namespace=spark \
--conf spark.kubernetes.driver.pod.name=spark-master \
--conf spark.kubernetes.container.image="gcr.io/spark-operator/spark:v3.1.1"
\
--conf
spark.kubernetes.authenticate.driver.serviceAccountName=spark-serviceaccount
\
local:///opt/spark/examples/jars/jars/spark-examples_2.12-v3.1.1.jar


Can you please update the document with the example of spark-submit with
volcano?


Thanks


   view my Linkedin profile
<https://www.linkedin.com/in/mich-talebzadeh-ph-d-5205b2/>



*Disclaimer:* Use it at your own risk. Any and all responsibility for any
loss, damage or destruction of data or any other property which may arise
from relying on this email's technical content is explicitly disclaimed.
The author will in no case be liable for any monetary damages arising from
such loss, damage or destruction.
