### ISSUE TITLE
Exception in thread "main" org.apache.spark.sql.AnalysisException: LOAD DATA input path does not exist: examples/src/main/resources/kv1.txt

### ISSUE THREAD

**Issue by apurwaj2** [GoogleCloudPlatform/spark-on-k8s-operator#1306]
My spark job yaml file is as follows:

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-hive
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.1.1"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.sql.hive.SparkHiveExample
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar"
  sparkVersion: 3.1.1
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.1.1
  executor:
    cores: 1
    coreLimit: "1000m"
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1

I'm trying to apply this yaml file on my k8s cluster but I keep running into this issue. Am I missing something here?

**Comment by jdonnelly-apixio** [comment]
Does the exception in the title of the issue only have the relative path?

The starting dir is `/opt/spark/work-dir/` but that kv1.txt file lives in `/opt/spark/examples/src/main/resources/kv1.txt`.
```
# docker run -it --entrypoint bash --rm --name spark-app-test0 gcr.io/spark-operator/spark:v3.1.1
Unable to find image 'gcr.io/spark-operator/spark:v3.1.1' locally
v3.1.1: Pulling from spark-operator/spark
6f28985ad184: Already exists
b3555c388585: Already exists
42965fccf401: Already exists
484bb3bd28a7: Already exists
88db0de5c834: Already exists
327ea804e4fb: Already exists
9a55db341cf9: Already exists
1556a52b6ac4: Already exists
7a78bd9be10c: Already exists
d78a463127b4: Already exists
05f6a21d0644: Already exists
a6926b1a05ce: Already exists
ea8c3d739f32: Already exists
26b401b5233a: Already exists
Digest: sha256:1a51dd49c15dac9058abbd7ef7773db62a5c0ae1ac23414bf040ae6efb0b0265
Status: Downloaded newer image for gcr.io/spark-operator/spark:v3.1.1
I have no name!@c460d4a565cd:/opt/spark/work-dir$ cd ..
I have no name!@c460d4a565cd:/opt/spark$ find . -name kv1.txt
./examples/src/main/resources/kv1.txt
```

**Comment by apurwaj2** [comment]
Yes. But then I copied it into another file which was made accessible to all executors as well as driver.
