### ISSUE TITLE
Set the Time zone inside spark applicatioin 

### ISSUE THREAD

**Issue by yangtian9999** [GoogleCloudPlatform/spark-on-k8s-operator#1316]
Hi Google Team,

How can I change the  time zone for spark application job?
My time zone is Hong Kong Time zone. When check with the spark-ui, all the time is UTC which is 8 hours behind.

I am not sure what to add inside the Dockerfile, or other way to modify it.

Thanks.

**Comment by joanjiao2016** [comment]
```
sparkConf:
    "spark.executor.extraJavaOptions": "-Duser.timezone=Asia/Shanghai"
```

**Comment by yangtian9999** [comment]
Thanks a lot!
