### ISSUE TITLE
Install error message when using the latest helm chart for version v2.4.0-v1beta1-0.9.0

### ISSUE THREAD

**Issue by yangtian9999** [GoogleCloudPlatform/spark-on-k8s-operator#1318]
Hi Google team,

I used "helm install dev240 spark-operator/spark-operator --namespace spark-operator --create-namespace --set image.tag=v2.4.0-v1beta1-0.9.0" to install  for spark 2.4.0 version.

My team suggested this was caused by flag parameter did not appear in the previous 2.4.0 version's operator.

Pods logs poped erro message:

flag provided but not defined: -enable-ui-service

full log of spark-operator pod is:
++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/ash
+ set -e
+ echo 0
+ echo 0
+ echo root:x:0:0:root:/root:/bin/ash
+ [[ -z root:x:0:0:root:/root:/bin/ash ]]
+ exec /sbin/tini -s -- /usr/bin/spark-operator -v=2 -logtostderr -namespace= -enable-ui-service=true -ingress-url-format= -controller-threads=10 -res                                 ync-interval=30 -enable-batch-scheduler=false -label-selector-filter= -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpo                                 int=/metrics -metrics-prefix= -enable-resource-quota-enforcement=false
0
0
root:x:0:0:root:/root:/bin/ash
flag provided but not defined: -enable-ui-service
Usage of /usr/bin/spark-operator:
  -alsologtostderr
        log to standard error as well as files
  -controller-threads int
        Number of worker threads used by the SparkApplication controller. (default 10)
  -enable-metrics
        Whether to enable the metrics endpoint.
  -enable-webhook
        Whether to enable the mutating admission webhook for admitting and patching Spark pods.
  -ingress-url-format string
        Ingress URL format.
  -install-crds
        Whether to install CRDs (default true)
  -kubeConfig string
        Path to a kube config. Only required if out-of-cluster.
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -logtostderr
        log to standard error instead of files
  -master string
        The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if out-of-cluster.
  -metrics-endpoint string
        Metrics endpoint. (default "/metrics")
  -metrics-labels value
        Labels for the metrics
  -metrics-port string
        Port for the metrics endpoint. (default "10254")
  -metrics-prefix string
        Prefix for the metrics.
  -namespace string
        The Kubernetes namespace to manage. Will manage custom resource

**Comment by jacobhjkim** [comment]
You should probably update the spark-operator image version to the newer version. It seems like your version of the spark-operator image doesn't have `enable-ui-service` flag.

**Comment by yangtian9999** [comment]
Hello Jacob,

I am not sure which version should I choose to run spark 2.4.0 application? 
From the readme, it wrote 

spark 2.4.0 should use
v1beta1-0.9.0 | v1beta1 | 1.13+ | 2.4.0 | v2.4.0-v1beta1-0.9.0


you suggested me to use the latest operator:v1beta2-1.2.3-3.1.1 to run spark 2.4.0 application?

Thanks.

**Comment by vinodvejandla** [comment]
#helm install my-spark-operator spark-operator/spark-operator --namespace spark-operator --create-namespace --set sparkJobNamespace=default --set operatorVersion=v1beta2-1.1.2-2.4.5 --set image.tag=v1beta2-1.1.2-2.4.5

NAME                                     READY   STATUS             RESTARTS   AGE
pod/my-spark-operator-5c7d7747bf-8txhs   0/1     CrashLoopBackOff   1          17s

Error:
+ exec /usr/bin/tini -s -- /usr/bin/spark-operator -v=2 -logtostderr -namespace=default -enable-ui-service=true -ingress-url-format= -controller-threads=10 -resync-interval=30 -enable-batch-scheduler=false -label-selector-filter= -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpoint=/metrics -metrics-prefix= -enable-resource-quota-enforcement=false
flag provided but not defined: -enable-ui-service

Can you fix "-enable-ui-service" flag for this spark version "v1beta2-1.1.2-2.4.5"?

**Comment by vin4v** [comment]
#helm install my-spark-operator spark-operator/spark-operator --namespace spark-operator --create-namespace --set sparkJobNamespace=default --set operatorVersion=v1beta2-1.1.2-2.4.5 --set image.tag=v1beta2-1.1.2-2.4.5

NAME                                     READY   STATUS             RESTARTS   AGE
pod/my-spark-operator-5c7d7747bf-8txhs   0/1     CrashLoopBackOff   1          17s

Error:
+ exec /usr/bin/tini -s -- /usr/bin/spark-operator -v=2 -logtostderr -namespace=default -enable-ui-service=true -ingress-url-format= -controller-threads=10 -resync-interval=30 -enable-batch-scheduler=false -label-selector-filter= -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpoint=/metrics -metrics-prefix= -enable-resource-quota-enforcement=false
flag provided but not defined: -enable-ui-service

Can you fix "-enable-ui-service" flag for this spark version "v1beta2-1.1.2-2.4.5"?

**Comment by jiangjian0920** [comment]
@yangtian9999 Have you tried running 2.4.0 Spark application  with latest operator image？

**Comment by WilliamQLiu** [comment]
I tried the operator with a few different `v2.4.X` versions (with `image.tag` = `"v2.4.0-v1beta1-0.7.1"`, `v1beta2-1.0.1-2.4.4`, `v1beta2-1.1.2-2.4.5`) and they all got the same error of `flag provided but not defined: -enable-ui-service`.

**Comment by jesuinovieira** [comment]
@WilliamQLiu, I'm running into a similar problem: `flag provided but not defined: -webhook-timeout`.
Do you have any updates on this?
