### ISSUE TITLE
Ingress and Service objects are not deleted when spark application completes

### ISSUE THREAD

**Issue by tekumara** [GoogleCloudPlatform/spark-on-k8s-operator#1336]
Ingress and Service objects are not deleted when spark application completes

**Comment by tekumara** [comment]
On [deletion of a SparkApplication object](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/d38c904a4dd84e849408153cdf4d7a30a7be5a07/pkg/controller/sparkapplication/controller.go#L238), the operator will delete the application's Ingress and Service objects.

**Comment by ViktorGlushak** [comment]
What I should mention in my SparkApplication manifest that after pod is completed the ingress will delete?
