### ISSUE TITLE
Why my sidecar is not working ?

### ISSUE THREAD

**Issue by everydots** [GoogleCloudPlatform/spark-on-k8s-operator#1430]
I tried to setup sidecar for my spark driver. but seems the sidecar didn't even started. Can anyone have any comments ?

![image](https://user-images.githubusercontent.com/16937202/146114949-34592b81-d16b-4c5b-bfc8-6fb2090729c5.png)

**Comment by charlesa101** [comment]
did you get this working?

**Comment by Ryan817** [comment]
I have the same problem, is there any solution?
