### ISSUE TITLE
build image success, but fail to run the image.

### ISSUE THREAD

**Issue by indianmifan** [GoogleCloudPlatform/spark-on-k8s-operator#1436]
I build the image without changing any source code and try to """docker run """ the image on Debian. I ran into this error

standard_init_linux.go:228: exec user process caused: no such file or director

**Comment by TomHellier** [comment]
I've just seen [my pr was merged](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1422), so the image should exist at [ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.2-3.1.1](https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator)
