### ISSUE TITLE
Question: Is creation of ClusterRole and ClusterRoleBinding mandatory?

### ISSUE THREAD

**Issue by mladen-djordjevic** [GoogleCloudPlatform/spark-on-k8s-operator#1437]
I am trying to install spark-operator and run spark-pi example in Kubernetes in which I have only permissions for 1 namespace, not for the whole cluster.

Currently, I am receiving this error, which (I think) is because of some permissions:
`Error: UPGRADE FAILED: unable to recognize "": no matches for kind "SparkApplication" in version "sparkoperator.k8s.io/v1beta2"`

Since in the background spark-operator creates ClusterRole and ClusterRoleBinding which is by definition for the whole cluster, not for the namespace, is the creation of ClusterRole and ClusterRoleBinding are mandatory for the spark-operator? If yes, is there an option to handle this properly on the namespace level?

**Comment by aneagoe** [comment]
Even without that, you'll still face an issue with the creation of the CRDs. You will need admin rights or request an admin to deploy the spark operator for you (see https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/ and https://docs.openshift.com/container-platform/4.9/operators/understanding/crds/crd-extending-api-with-crds.html).

**Comment by mladen-djordjevic** [comment]
Thank you for the confirmation. After discussion with our DevOps team, we are already moving in that direction.

**Comment by mladen-djordjevic** [comment]
Question answered
