### ISSUE TITLE
Allow uploading dependencies to s3

### ISSUE THREAD

**Issue by mrow4a** [GoogleCloudPlatform/spark-on-k8s-operator#144]
Currently, there is no implementation for s3 - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/sparkctl/cmd/create.go#L273

One solution, reusing existing flags and envs (`--project` and `GOOGLE_APPLICATION_CREDENTIALS`) could be to have `--project` as s3 profile and some other ENV to point to configuration file, structured as:

```
[<project>]
s3_access_key_id=<key>
s3_secret_access_key=<secret>
region=<region>
output=json
```

Could that be a correct approach?

**Comment by mrow4a** [comment]
Env variable is required to point to config file (which has specific structure), so something like S3_APPLICATION_CREDENTIALS, with `--profile` pointing to proper profile inside the config file.

**Comment by mrow4a** [comment]
If you have any thoughts on how best it could work with aws, gcp interoperability and s3 in general, this was the initial idea I got.

**Comment by liyinan926** [comment]
Thanks, @mrow4a. I'm not super familiar with S3 configuration. The link is super helpful. I'm gonna take a look and get back to this later.
