### ISSUE TITLE
ingressUrlFormat No value was passed in using $appName

### ISSUE THREAD

**Issue by Bill-Tao-Yang** [GoogleCloudPlatform/spark-on-k8s-operator#1441]
I added `--set ingressUrlFormat="spark.example.com/{{$appNamespace}}/{{$appName}}"` when using helm deployment.

but when i `kubectl describe ingress test-ingress`, as shown below:

```
Rules:
  Host                        Path                Backends
  ----                        ----                   --------
  spark.example.com           /{{}}/{{}}              test-5-ui-svc:4040 (<none>)
```
It seems that $appName and $appNamespace values have not been successfully passed in.

It is worth mentioning that the spark operator and spark driver are not in the same namespace.

**Comment by Bill-Tao-Yang** [comment]
use `--set ingressUrlFormat="spark.example.com/\{\{\$appNamespace\}\}/\{\{\$appName\}\}"` can work

**Comment by arthuersundar** [comment]
i followed this ingressUrlFormat deployed fine. i can see the path as well. But I'm getting 503 error when i access the UI using http://sample.eastus2.cloudapp.azure.com/spark-apps/spark-pi

Rules:
  Host                                         Path  Backends
  ----                                         ----  --------
  sample.eastus2.cloudapp.azure.com
                                               /spark-apps/spark-pi   spark-pi-ui-svc:4040   <none>)
