### ISSUE TITLE
spark-operator compatible with K8S 1.22

### ISSUE THREAD

**Issue by abhisrao** [GoogleCloudPlatform/spark-on-k8s-operator#1450]
The last official version of spark-operator (v1beta2-1.2.2-3.0.0) is not compatible with K8S 1.22 as there are many API's used in spark-operator which are now deprecated. What is the plan to release a new version of spark-operator which is compatible to K8S 1.22.

Thanks,
Abhishek

**Comment by abhisrao** [comment]
@liyinan926 , please share your views on this.

**Comment by aneagoe** [comment]
@abhisrao with https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1426 now closed, this should be resolved. The image that contains the fix is `v1beta2-1.3.3-3.1.1`.

**Comment by aneagoe** [comment]
@jgoeres recently, `spark-operator` has moved on to using github container registry. You can check the tagged versions here: https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator/versions. If I get a chance, I'll create a PR to update the default registry in the chart's `values.yaml`.

**Comment by jgoeres** [comment]
@aneagoe Thanks for clarifying this (at some point, I was actually wondering if GCR was still the right registry and checked the Helm chart's defaults, and found GCR there so, I assumed wrongly that it was).

**Comment by abhisrao** [comment]
@aneagoe , Thanks for sharing the update. We'll pick v1beta2-1.3.3-3.1.1 and use it for K8S 1.22.
Thanks!!!

**Comment by aneagoe** [comment]
@abhisrao glad it helps. Please close this issue if this resolves your problem.

**Comment by abhisrao** [comment]
Sure. Is it ok if I close this after our validation?

**Comment by abhisrao** [comment]
We've now validated with k8s 1.22 and hence am closing this ticket.
