### ISSUE TITLE
spark.kubernetes.file.upload.path issue

### ISSUE THREAD

**Issue by yevsh** [GoogleCloudPlatform/spark-on-k8s-operator#1474]
After upgrading from  2.4.5 to 3.1.1

getting error:

INFO KerberosConfDriverFeatureStep: You have not specified a krb5.conf file locally or via a ConfigMap. Make sure that you have the krb5.conf locally on the driver image.                                                                                                                            
Exception in thread "main" org.apache.spark.SparkException: Please specify spark.kubernetes.file.upload.path property.    

If i a add property:

```
sparkConf:    
    "spark.kubernetes.file.upload.path": "/opt/spark/work-dir"
```

getting:
INFO KubernetesUtils: Uploading file: /opt/app/jars to dest: /opt/spark/work-dir/spark-upload-602369fb-c5ac-42bf-a870-b66cbd15b363/jars..
.                                                                                                                                                           
Exception in thread "main" org.apache.spark.SparkException: Uploading file /opt/app/jars failed..
.
 Caused by: java.io.FileNotFoundException: File /opt/app/jars does not exist

i also have in my yaml:

```
 deps:
    jars:
      - /opt/app/jars
      - /opt/app
```

Why it uploading anything? I have everything locally why it's required now? with 2.4.5 it worked fine.

**Comment by khaledosman74** [comment]
Hi was it solved?

**Comment by mgarnaudFTOS** [comment]
Hi @yevsh,

I'm running Spark 3.5.0 and I have a very similar issue, was yours ever solved ? If so how ?

Thanks
