### ISSUE TITLE
Compatibility with Kubernetes 1.23

### ISSUE THREAD

**Issue by indranilr** [GoogleCloudPlatform/spark-on-k8s-operator#1476]
Compatibility with 1.22 is covered in issue https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1450 . Which image tag should be used for compatibility with K8s 1.23 ?

**Comment by aneagoe** [comment]
@indranilr you can use `v1beta2-1.3.3-3.1.1` onward... there are no deprecations from 1.22->1.23 (until 1.25 actually). See https://kubernetes.io/docs/reference/using-api/deprecation-guide/.
Please close the issue if the above helped.
