### ISSUE TITLE
spark-on-k8s-operator- 1.1.17 - v1beta2-1.2.3-3.1.1 

### ISSUE THREAD

**Issue by mshilamk8s** [GoogleCloudPlatform/spark-on-k8s-operator#1477]
GCP/Spark-on-k8s-operator
Reg: Critical and High Vulnerabilities

There are around 266 vulnerabilities found out of which 9 are critical and 95 are high vulnerabilities using Xray report. is there any remediation offered to address the critical and high CVE's in next releases or any active development going on to fix these.

**Comment by aneagoe** [comment]
Duplicate of #1487, @mshilamk8s can you please close one of them?

**Comment by mshilamk8s** [comment]
closing duplicate
