### ISSUE TITLE
Can't create pod in namespace 

### ISSUE THREAD

**Issue by robscc** [GoogleCloudPlatform/spark-on-k8s-operator#1478]
Hi, when i submit spark-pi , it comes out with error

> Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Operation: [create]  for kind: [Pod]  with name: [null]  in namespace: [spark-operator]  failed.
> 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
> 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:72)
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:349)
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:84)
> 	at org.apache.spark.deploy.k8s.submit.Client.run(KubernetesClientApplication.scala:139)
> 	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$3(KubernetesClientApplication.scala:213)
> 	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.$anonfun$run$3$adapted(KubernetesClientApplication.scala:207)
> 	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2611)
> 	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.run(KubernetesClientApplication.scala:207)
> 	at org.apache.spark.deploy.k8s.submit.KubernetesClientApplication.start(KubernetesClientApplication.scala:179)
> 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
> 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
> 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
> 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
> 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> Caused by: javax.net.ssl.SSLHandshakeException: KeyUsage does not allow digital signatures
> 	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)
> 	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)
> 	at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
> 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
> 	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
> 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
> 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
> 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
> 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
> 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
> 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at io.fabric8.kubernetes.client.utils.BackwardsCompatibilityInterceptor.intercept(BackwardsCompatibilityInterceptor.java:135)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at io.fabric8.kubernetes.client.utils.OIDCTokenRefreshInterceptor.intercept(OIDCTokenRefreshInterceptor.java:41)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at io.fabric8.kubernetes.client.utils.ImpersonatorInterceptor.intercept(ImpersonatorInterceptor.java:68)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at io.fabric8.kubernetes.client.utils.HttpClientUtils.lambda$createHttpClient$3(HttpClientUtils.java:151)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
> 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
> 	at okhttp3.RealCall.execute(RealCall.java:93)
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:490)
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:451)
> 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:252)
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:879)
> 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:341)
> 	... 14 more
> Caused by: sun.security.validator.ValidatorException: KeyUsage does not allow digital signatures
> 	at java.base/sun.security.validator.EndEntityChecker.checkTLSServer(Unknown Source)
> 	at java.base/sun.security.validator.EndEntityChecker.check(Unknown Source)
> 	at java.base/sun.security.validator.Validator.validate(Unknown Source)
> 	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
> 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
> 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
> 	... 62 more

I am working with 
k8s version: 1.19
operator version : v1beta2-1.3.3-3.1.1

**Comment by guptap11** [comment]
Can you check that if webhook is enabled and is configured correctly ?
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#mutating-admission-webhooks-on-a-private-gke-cluster

**Comment by robscc** [comment]
> Can you check that if webhook is enabled and is configured correctly ? https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#mutating-admission-webhooks-on-a-private-gke-cluster

i fixed it by update the cert of apiserver.  thx anyway,

**Comment by lihuawei321** [comment]
> 

hi,How did you solve this problem? How to renew the certificate of apiserver.

**Comment by lihuawei321** [comment]
> > Can you check that if webhook is enabled and is configured correctly ? https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#mutating-admission-webhooks-on-a-private-gke-cluster
> 
> i fixed it by update the cert of apiserver. thx anyway,

hi,How did you solve this problem? How to renew the certificate of apiserver.

**Comment by sreejesh-radhakrishnan-db** [comment]
How was this issue solved?   any help would be much appreciated.  @robscc
