### ISSUE TITLE
ubuntu based spark-py docker creation requirement

### ISSUE THREAD

**Issue by rwathena** [GoogleCloudPlatform/spark-on-k8s-operator#1488]
Hello there,
          I want to import [spark-on-k8s-operator] to rosbag analysis system. The Ros can only be installed in ubuntu.
          Is there anyone can make a ubuntu(16 is the best version fo ROS1) based spark image? The image gcr.io/spark-operator/spark-py:v3.1.1 is based on centos.
          And I can not pull the image from gcr, so can anyone push the images to docker hub?
         Thanks very much.

**Comment by or0or1** [comment]
gcr.io/spark-operator/spark-py:v3.1.1  is debian, not centos.

**Comment by rwathena** [comment]
@or0or1 So I can analyize rosbag in docker gcr.io/spark-operator/spark-py:v3.1.1 by ros python libraries, can I?

**Comment by rwathena** [comment]
The repo does provide unbuntu/debian os.
