### ISSUE TITLE
spark operator ignores hive metastore settings

### ISSUE THREAD

**Issue by scaladevspark** [GoogleCloudPlatform/spark-on-k8s-operator#1515]
I have a hive metastore running in kubernetes as a service on "thrift://hms-service.default.svc.cluster.local:9083". However, spark operator seems to completely ignore the settings in the metastore-site.xml

for example metastore-site xml has the property:
     ```   <property>```
       ```     <name>metastore.warehouse.dir</name>```
       ```     <value>s3a://spark/warehouse/</value>```
        ```</property> ```

however, this is not shown in the log from the spark operator driver - the metastore.warehouse.dir is null (so it is not read from the metastore) and it has to be set manually in the spark session via spark.sql.warehouse.dir
```22/04/18 12:32:33 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('s3a://spark/warehouse/').```

This causes other issues, e.g. trino is unable to see any tables via the metastore - I guess spark operator is creating its own local metastore then?

relevant settings in the metastore-site.xml:
     ``` <property>```
      ```    <name>metastore.thrift.uris</name>```
      ```    <value>thrift://hms-service.default.svc.cluster.local:9083</value>```
      ```    <description>Thrift URI for the remote metastore. Used by metastore client to connect to remote metastore.</description>```
    ```  </property>```

relevant settings in my spark app:
  ```  "spark.sql.catalog.spark_catalog.uri": "thrift://hms-service.default.svc.cluster.local:9083"```
   ``` "spark.hadoop.hive.metastore.uris": "thrift://hms-service.default.svc.cluster.local:9083"```

the settings from spark app seem to be propagated properly, in spark gui on :4040, I can see e.g.
![image](https://user-images.githubusercontent.com/101802776/163811627-a679226b-eab4-401c-847f-fd73b7a5b9ef.png)

As far as I can tell, the hive metastore is up and running - is there anything in the spark operator that would make it incompatible? Any ideas how to debug this?

Thanks for any help.

**Comment by scaladevspark** [comment]
got it, since there is no single place for hive-site.xml (no more shared hdfs), the spark application needs it own hive-site.xml. This can be achieved in the SparkApplication yaml via   sparkConfigMap: spark-config-map
spark-config-map should contain the definition of hive-site.xm

**Comment by Andromelus** [comment]
Could you please provide an example ?
