### ISSUE TITLE
Support for imagePullSecrets

### ISSUE THREAD

**Issue by andreyxebialabs** [GoogleCloudPlatform/spark-on-k8s-operator#152]
Hello, 

We are using our private Docker repository for our images, and as a result when specifying a image for container for pod we have to specify imagePullSecrets. 

Right now as I can see it is not supported. I can see that normal Secrets are supported, but not imagePullSecrets which are used to authenticate with Docker repository. Please correct me if I'm wrong. 

Do you plan to add this support? I can and create a PR for that if that helps. 

Thank you. 

AG

**Comment by liyinan926** [comment]
Yes, we do plan to support this (see #129 for the plan to sync with apache/spark/master). Support for it was added in https://github.com/apache/spark/pull/20811.  So to support this, it's just a matter of adding an optional field to `SparkApplicationSpec` of type `[]string`, and set the new config key added in https://github.com/apache/spark/pull/20811 if the field is not empty. It's great if you are willing to work on this!

**Comment by liyinan926** [comment]
@andreyxebialabs I added support for this in #158. It has one dependency that should be merged soon. You will need to use a Spark image based on the latest spark master.
