### ISSUE TITLE
Scheduled a spark application just once

### ISSUE THREAD

**Issue by manjiler** [GoogleCloudPlatform/spark-on-k8s-operator#1528]
Hello

I have a use-case where the a spark job needs to triggered just once. 

Currently, I am relying on setting the schedule
`
schedule: "@every 20s"
concurrencyPolicy:` Forbid
`

With concurrency policy set to `Forbid` and the just takes around 5 minutes to finish the next scheduled run does not trigger. 

Is there is a better way to do this?

**Comment by oscar-dela** [comment]
How about just using `SparkApplication`? It will only be triggered once when you just deployed.

**Comment by manjiler** [comment]
This will work. Some reason, I was always associated a `SparkApplication` to a streaming spark application. 
For a `SparkApplication` is the source not a streaming source then it just become a batch job (one time spark job)...

Thanks @oscar-dela
