### ISSUE TITLE
code references k8s.io/spark-on-k8s-operator which does not resolve to an accessible repo

### ISSUE THREAD

**Issue by scotthew1** [GoogleCloudPlatform/spark-on-k8s-operator#153]
i'm trying to make use of the generated client code, but can't even fetch the dependency because the client refers to a repo that doesn't exist...
```golang
import (
	sparkClientset "github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/clientset/versioned"
	sparkV1aplpha1 "github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/apis/sparkoperator.k8s.io/v1alpha1"
)
```
```sh
$ go get
# cd .; git clone https://github.com/kubernetes/spark-on-k8s-operator /Users/scott/go/src/k8s.io/spark-on-k8s-operator
Cloning into '/Users/scott/go/src/k8s.io/spark-on-k8s-operator'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
package k8s.io/spark-on-k8s-operator/pkg/apis/sparkoperator.k8s.io: exit status 128
package k8s.io/spark-on-k8s-operator/pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1: cannot find package "k8s.io/spark-on-k8s-operator/pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1" in any of:
	/usr/local/Cellar/go/1.10/libexec/src/k8s.io/spark-on-k8s-operator/pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1 (from $GOROOT)
	/Users/scott/go/src/k8s.io/spark-on-k8s-operator/pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1 (from $GOPATH)
```

**Comment by liyinan926** [comment]
In your import block, can you try using `k8s.io/spark-on-k8s-operator/pkg/client/clientset/versioned` and `k8s.io/spark-on-k8s-operator/pkg/apis/sparkoperator.k8s.io/v1alpha1`?

**Comment by liyinan926** [comment]
Yes, currently `k8s.io/spark-on-k8s-operator` will not resolve. I think what you need to do is:
1. `git clone github.com/GoogleCloudPlatform/spark-on-k8s-operator $GOPATH/k8s.io/spark-on-k8s-operator`.
2. Use `k8s.io/spark-on-k8s-operator/pkg/client/clientset/versioned` and `k8s.io/spark-on-k8s-operator/pkg/apis/sparkoperator.k8s.io/v1alpha1` in imports.

**Comment by scotthew1** [comment]
```sh
git clone github.com/GoogleCloudPlatform/spark-on-k8s-operator $GOPATH/src/k8s.io/spark-on-k8s-operator
```
gets the job done (notably for anyone else reading this you left out `src` above)

tho it would be nice if this weren't necessary.. either by having `k8s.io/spark-on-k8s-operator` resolve properly or regen the code to reference `github.com/GoogleCloudPlatform/spark-on-k8s-operator`

**Comment by liyinan926** [comment]
I will update the code to reference `github.com/GoogleCloudPlatform/spark-on-k8s-operator` since this is not under the kubernetes project anyway.

**Comment by liyinan926** [comment]
Opened #154. Closing this.
