### ISSUE TITLE
SparkApplication Enqueued and Deleted without processing

### ISSUE THREAD

**Issue by gangahiremath** [GoogleCloudPlatform/spark-on-k8s-operator#1571]
Hello!
 
 Spark Application enqueued and deleted, as can be seen in following log; in what context this could occur:

![image](https://user-images.githubusercontent.com/104861640/177831475-f3428363-0b7c-401d-855e-b4f1ea49f822.png)

**Comment by gangahiremath** [comment]
Above mentioned issue, we observe once Spark Operator stops processing submitted SparkApplications, except enqueueing them. We dont see see any other errors other than the one mentioned in above screenshot.

**Comment by gangahiremath** [comment]
I have identified the root cause of the issue, thank you.

**Comment by pjoshisolo** [comment]
hello @gangahiremath I am getting the similar error. Curious to know what was the root cause?

**Comment by gangahiremath** [comment]
I had interpreted the logs in wrong way @pjoshisolo ;  but Spark Operator spark-submit threads were stuck for longer time due to library version compatibility issue. Once I addressed the same, Spark Operator started processing SparkApplications
