### ISSUE TITLE
sparkapplication uses volcano as batchScheduler FAILED

### ISSUE THREAD

**Issue by huangyufeng0507** [GoogleCloudPlatform/spark-on-k8s-operator#1585]
I run the official demo spark-pi.yaml, and assign the parameter that batchScheduler: "Volcano". However, when i exec `kubectl describe pod` of driver pod or executor pod, it displays that these pods are scheduler by "default-scheduler". I am confused about it, is it supposed to be volcano rather than "default-scheduler"?

**Comment by huangyufeng0507** [comment]
![image](https://user-images.githubusercontent.com/91405051/182516684-a0b6744b-776f-4fe3-80b6-5b362113b34d.png)

**Comment by chanecho** [comment]
How to resolve the problem? Can you help me?
Thank you!
