### ISSUE TITLE
Add restartPolicy field

### ISSUE THREAD

**Issue by ozzieba** [GoogleCloudPlatform/spark-on-k8s-operator#16]
We have a lot of Streaming applications that need to be restarted if they ever die. 
Currently, the controller considers an application finished if the driver pod dies for any reason. 
We would like to be able to specify `restartPolicy: Always` or `restartPolicy: OnFailure` to get behavior similar to Kubernetes Deployments and Jobs, respectively, ie have the controller re-submit a completed or failed application.

**Comment by liyinan926** [comment]
Note that when an application is restarted, e.g., due to a driver failure, the old driver won't be deleted. However, each driver pod has a `OwnerReference` that points to the `SparkApplication` object. So when the `SparkApplication` gets deleted, every driver pods it owns will be deleted.
