### ISSUE TITLE
java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda when using spark-operator

### ISSUE THREAD

**Issue by richiesgr** [GoogleCloudPlatform/spark-on-k8s-operator#1607]
Hi
I need to use spark 3.2.2 as it's our production version so I've followed the guide to customize spark-operator to make one running spark 3.2.2

The operator is deployed and seems to work 
The application is deployed and start running as expected but 
Then I get this error :

`org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (10.1.0.189 executor 1): java.lang.ClassCastException: cannot assign instance of java.lang.invoke.SerializedLambda to field org.apache.spark.sql.catalyst.expressions.ScalaUDF.f of type scala.Function1 in instance of org.apache.spark.sql.catalyst.expressions.ScalaUDF
	at java.base/java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(Unknown Source)
	at java.base/java.io.ObjectStreamClass$FieldReflector.checkObjectFieldValueTypes(Unknown Source)
	at java.base/java.io.ObjectStreamClass.checkObjFieldValueTypes(Unknown Source)
	at java.base/java.io.ObjectInputStream.defaultCheckFieldValues(Unknown Source)
	at java.base/java.io.ObjectInputStream.readSerialData(Unknown Source)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.base/java.io.ObjectInputStream.readObject0(Unknown Source)
....`
Same error appears in the workers

Not much information on internet just an issue using different version of scala 2.12.

When I used the application on databricks no problem 
When deploy on spark stand alone cluster no problem 

Please help Thanks

**Comment by nanthana** [comment]
@richiesgr - I am facing a similar problem as you. Do you mind giving some advices on how you resolved this? Many thanks.

**Comment by sanjanakspratha** [comment]
I am facing the same issue. What was the solution

**Comment by theroadbacktonature** [comment]
same issue, anyone managed to resolve this?

**Comment by FandonGeek** [comment]
Facing the same issue right now, do you have any suggestions for fixing this?

**Comment by allen-zhang-akunacapital** [comment]
I had the same issue until I went through the `spark-sql-kafka` dependency tree in maven and manually included the jars with correct dependencies in our custom baked Spark docker image:

```
ENV SPARK_VERSION=3.3.0 \
    SCALA_BINARY_VERSION=2.12 \
    KAFKA_VERSION=2.8.0 \
    COMMONS_POOL2_VERSION=2.12.0 \
    JSR305_VERSION=3.0.0 \
    DELTA_CORE_VERSION=2.1.1 \
    DELTA_STORAGE_VERSION=2.1.1

RUN curl -o /opt/spark/jars/spark-sql-kafka-0-10_${SCALA_BINARY_VERSION}-${SPARK_VERSION}.jar https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_${SCALA_BINARY_VERSION}/${SPARK_VERSION}/spark-sql-kafka-0-10_${SCALA_BINARY_VERSION}-${SPARK_VERSION}.jar && \
    curl -o /opt/spark/jars/spark-token-provider-kafka-0-10_${SCALA_BINARY_VERSION}-${SPARK_VERSION}.jar https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_${SCALA_BINARY_VERSION}/${SPARK_VERSION}/spark-token-provider-kafka-0-10_${SCALA_BINARY_VERSION}-${SPARK_VERSION}.jar && \
    curl -o /opt/spark/jars/spark-tags_${SCALA_BINARY_VERSION}-${SPARK_VERSION}.jar https://repo1.maven.org/maven2/org/apache/spark/spark-tags_${SCALA_BINARY_VERSION}/${SPARK_VERSION}/spark-tags_${SCALA_BINARY_VERSION}-${SPARK_VERSION}.jar && \
    curl -o /opt/spark/jars/kafka-clients-${KAFKA_VERSION}.jar https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/${KAFKA_VERSION}/kafka-clients-${KAFKA_VERSION}.jar && \
    curl -o /opt/spark/jars/commons-pool2-${COMMONS_POOL2_VERSION}.jar https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/${COMMONS_POOL2_VERSION}/commons-pool2-${COMMONS_POOL2_VERSION}.jar && \
    curl -o /opt/spark/jars/jsr305-${JSR305_VERSION}.jar https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/${JSR305_VERSION}/jsr305-${JSR305_VERSION}.jar && \
    curl -o /opt/spark/jars/delta-core_${SCALA_BINARY_VERSION}-${DELTA_CORE_VERSION}.jar https://repo1.maven.org/maven2/io/delta/delta-core_${SCALA_BINARY_VERSION}/${DELTA_CORE_VERSION}/delta-core_${SCALA_BINARY_VERSION}-${DELTA_CORE_VERSION}.jar && \
    curl -o /opt/spark/jars/delta-storage-${DELTA_STORAGE_VERSION}.jar https://repo1.maven.org/maven2/io/delta/delta-storage/${DELTA_STORAGE_VERSION}/delta-storage-${DELTA_STORAGE_VERSION}.jar
```
