### ISSUE TITLE
Spark application scheduling with volcano doesn't work

### ISSUE THREAD

**Issue by hodaya-shabtay** [GoogleCloudPlatform/spark-on-k8s-operator#1646]
Hi,

I'm using spark operator version 1.1.19 with `enable-batch-scheduler` configured to `True` and the latest volcano version.
I'm trying to submit a new spark application by adding the `batchScheduler: "volcano"` to the yaml file, but the application isn't started and no pods or podgroup are created.
When looking on the application events I can see a single event from the spark operator with this message: `SparkApplication volcano-test was added, enqueuing it for submission`

What am I missing? Does the operator need specific permissions for creating the PodGroup that will be associated with the default queue?

**Comment by hodaya-shabtay** [comment]
Well, I add the `scheduling.volcano.sh` to apiGroup of the spark-operator and now it works!

**Comment by zhaoshenghao111** [comment]
hello, did u resolve the issue? I have the same problem.
