### ISSUE TITLE
helm install operator failed

### ISSUE THREAD

**Issue by VioletCoding** [GoogleCloudPlatform/spark-on-k8s-operator#1649]
### helm version
v3.10.2

### kubernetes version
v1.25.4

### command
```shell
  helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
  helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=spark --generate-name
```

### result
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "sparkapplications.sparkoperator.k8s.io" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "scheduledsparkapplications.sparkoperator.k8s.io" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first]

What did I miss?

**Comment by debugger24** [comment]
Use `helm install spark-operator/spark-operator`. 

Not sure `incubator/sparkoperator` is in this spark repo, in the old one it was deprecated (https://github.com/helm/charts/tree/master/incubator/sparkoperator)

**Comment by VioletCoding** [comment]
@debugger24 It works, thanks!
