### ISSUE TITLE
resources are not cleaned up when a sparkapp is deleted

### ISSUE THREAD

**Issue by scotthew1** [GoogleCloudPlatform/spark-on-k8s-operator#167]
right now the onDelete handler in the sparkapp controller doesn't really do anything. this is the last opportunity for it to clean up the pods / services created. seems like `deleteDriverAndUIService()` should be called in `onDelete()`

**Comment by liyinan926** [comment]
There's a bit of story here. The Initializer if enabled adds an `OwnerReference` referencing a `SparkApplication` to the driver pod and service of the application. So deletion of a `SparkApplication` object should cause the driver pod and service to be garbage collected. The initializer used to be enabled by default. It was later changed to be disabled by default instead so garbage collection won't help. I agree that it should call `deleteDriverAndUIService` explicitly.

**Comment by scotthew1** [comment]
@liyinan926 semi related question.. this doesn't appear to be spark-operator's fault since i can't find it creating this service anywhere, but maybe you have some experience with it... when the driver pod is created, somethings also creating a driver service. but since they're not being managed by spark-operator, these services never get cleaned up. do you know if this is something that spark-submit is doing or if there's some way to make sure these services don't pile up over time?

```
aggregation-029325f937f8374a9015c291832e3872-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP               37m
aggregation-0489083e999c335b8db951ae079cd336-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP               39m
aggregation-064c62dce3c73c24a3fb3ed1020e5675-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP               30m
aggregation-0f99ee2ea16a32af944d806786206624-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP               33m
aggregation-10ad4cd3619539b3992d4ef45dd34e75-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP               1h
aggregation-11932b97ab153f52b141eb75db8fdd25-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP               40m
aggregation-1320b189b0063cb4a90a0a00d25b73ee-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP               29m
aggregation-133d0f57f5f93faaab90da0df82a85cd-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP               32m
aggregation-20244fa05db339afbaa9a24ab45c1214-driver-svc   ClusterIP   None             <none>        7078/TCP,7079/TCP
```

**Comment by liyinan926** [comment]
Yes, such services are what the k8s-specific submission client creates. However, the submission client adds an `OwnerReference` pointing to the driver pod to such a service. So deleting the driver pod should cause the service to be garbage collected.

**Comment by scotthew1** [comment]
hmmm nothing seems to be cleaning em up, even after 24 hours. i see the annotation on the driver pod, but the value seems a bit strange..
```
Annotations:  spark-app-name=aggregation
              sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGgthZ2dyZWdhdGlvbiIkNGE1ZGVjM2ItNjAyZi0xMWU4LTk1NzgtMDA1MDU2YmUxZWNmKh1zcGFya29wZXJhdG9yLms4cy5pby92MWFscGhhMQ==
```
that reference decodes to
```

SparkApplication
                aggregation"$650b25a9-5faa-11e8-9578-005056be1ecf*sparkoperator.k8s.io/v1alpha1
```
meanwhile the service looks like this
```
Name:              aggregation-bb8b050e70963729b5c67eeb20936f52-driver-svc
Namespace:         sreisor
Labels:            <none>
Annotations:       <none>
Selector:          spark-app-selector=spark-caa04b4c8a9a41e493ae08954ec83318,spark-role=driver,sparkoperator.k8s.io/app-id=aggregation-2060457416,sparkoperator.k8s.io/app-name=aggregation,sparkoperator.k8s.io/launched-by-spark-operator=true
Type:              ClusterIP
IP:                None
Port:              driver-rpc-port  7078/TCP
TargetPort:        7078/TCP
Endpoints:         10.40.128.74:7078
Port:              blockmanager  7079/TCP
TargetPort:        7079/TCP
Endpoints:         10.40.128.74:7079
Session Affinity:  None
Events:            <none>
```

**Comment by liyinan926** [comment]
So do you have the initializer enabled? Looks like so because of the `OwnerReference` added to the driver pod. There are two kinds of services: one created by the operator for accessing the driver UI, and the other created by the spark-submit for the executors to connect to the driver. The former is what `deleteDriverAndUIService` tries to delete. The latter is supposed to be garbage collected once the driver pod gets deleted due to the presence of an `OwnerReference` on the service.

**Comment by scotthew1** [comment]
i'm currently running spark-operator with a modified version of the `spark-operator.yaml` that works with our helm charts. so we have `-enable-initializer=false` set in the args.

**Comment by liyinan926** [comment]
OK, sorry didn't realize you were talking about the annotation, not the actual `OwnerReferences`. Without the initializer, the `OwnerReference` won't be added but the annotation is set regardlessly.

**Comment by scotthew1** [comment]
ah sorry, i've just been inspecting the annotations on the pods as they spin up. so we need the initializer enabled if we want these services cleaned up?

**Comment by liyinan926** [comment]
No, both the driver pod and the UI service created by the operator should be deleted when you delete the `SparkApplication` object with the fix for this issue. The service created by spark-submit should be garbage collected once the driver pod is gone. So deleting the `SparkApplication` should cause the driver pod and both services to be deleted.

**Comment by scotthew1** [comment]
oooh you're right. i just started again fresh with everything and with the fix from this issue it looks like deleting the CRD does cause the driver/exec pods to delete along with both services. i must've had some services lying around from before the fix that were confusing me. thanks again for your help!
