### ISSUE TITLE
duplicated drivers when used restful api and RestartPolicy=Never

### ISSUE THREAD

**Issue by xiaoliushen** [GoogleCloudPlatform/spark-on-k8s-operator#171]
When i used restful api to create a SparkApplication for the spark pi.I got duplicate drivers and service.
I saw the issue [#155](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/155) , and i pull the new master and rebuild it,but it was always happening.

my k8s cluster has one master and two workers.

my restful request:

> curl --basic -u username:passwd -k -l -H "Content-type: application/json" -X POST -d '{"apiVersion":"sparkoperator.k8s.io/v1alpha1","kind":"SparkApplication","metadata":{"name":"spark-pi001","namespace":"default"},"spec":{"driver":{"memory":"512m","coreLimit":"200m","cores":0.1,"labels":{"version":"2.3.0"},"serviceAccount":"spark","volumeMounts":[{"mountPath":"/SkyDiscovery/cephfs/user/username","name":"test-volume"}]},"executor":{"cores":1,"instances":2,"labels":{"version":"2.3.0"},"memory":"512m","volumeMounts":[{"mountPath":"/SkyDiscovery/cephfs/user/username","name":"test-volume"}]},"image":"spark:v2.3.0_skydata","mainApplicationFile":"local:///SkyDiscovery/cephfs/user/username/spark-examples_2.11-2.3.0.jar","arguments":[],"mainClass":"org.apache.spark.examples.SparkPi","mode":"cluster","restartPolicy":"Never","type":"Scala","volumes":[{"name":"test-volume","hostPath":{"path":"/SkyDiscovery/cephfs/user/username"}}]}}' https://*****:6443/apis/sparkoperator.k8s.io/v1alpha1/namespaces/default/sparkapplications

duplicate drivers：

> spark-pi001-090fd4fdefb131e08b4142efea55eca9-driver             0/1       ContainerCreating   0          20s
spark-pi001-af2e021c6dcc37f3b404093f37da3fe8-driver             0/1       ContainerCreating   0          19s

duplicate service：

> spark-pi001-2249495700-ui-svc
spark-pi001-2284845769-ui-svc
spark-pi001-090fd4fdefb131e08b4142efea55eca9-driver-svc
spark-pi001-af2e021c6dcc37f3b404093f37da3fe8-driver-svc

when i check the operator log, spark-pi001 was updated after it was added,then spark-submit was executed twice.

> I0528 06:20:17.754806       1 controller.go:169] SparkApplication spark-pi001 was added, enqueueing it for submission
I0528 06:20:17.760060       1 sparkui.go:75] Creating a service spark-pi001-2284845769-ui-svc for the Spark UI for application spark-pi001
I0528 06:20:17.838537       1 submission_runner.go:81] spark-submit arguments: [/opt/spark/bin/spark-submit --class org.apache.spark.examples.SparkPi --master k8s://https://10.96.0.1:443 --deploy-mode cluster --conf spark.kubernetes.namespace=default --conf spark.app.name=spark-pi001 --conf spark.kubernetes.container.image=192.168.61.32:9980/skydiscovery/spark:v2.3.0_skydata --conf spark.kubernetes.submission.waitAppCompletion=false --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=spark-pi001 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-id=spark-pi001-2284845769 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.driver.cores=0.100000 --conf spark.kubernetes.driver.limit.cores=200m --conf spark.driver.memory=512m --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark --conf spark.kubernetes.driver.label.version=2.3.0 --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/volumemounts.test-volume=Cgt0ZXN0LXZvbHVtZRAAGiEvU2t5RGlzY292ZXJ5L2NlcGhmcy91c2VyL3NqbHRlc3QiAA== --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/volumes.test-volume=Cgt0ZXN0LXZvbHVtZRIlCiMKIS9Ta3lEaXNjb3ZlcnkvY2VwaGZzL3VzZXIvc2psdGVzdA== --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=spark-pi001 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-id=spark-pi001-2284845769 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.executor.instances=2 --conf spark.executor.cores=1 --conf spark.executor.memory=512m --conf spark.kubernetes.executor.label.version=2.3.0 --conf spark.kubernetes.executor.annotation.sparkoperator.k8s.io/volumemounts.test-volume=Cgt0ZXN0LXZvbHVtZRAAGiEvU2t5RGlzY292ZXJ5L2NlcGhmcy91c2VyL3NqbHRlc3QiAA== --conf spark.kubernetes.executor.annotation.sparkoperator.k8s.io/volumes.test-volume=Cgt0ZXN0LXZvbHVtZRIlCiMKIS9Ta3lEaXNjb3ZlcnkvY2VwaGZzL3VzZXIvc2psdGVzdA== --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGgtzcGFyay1waTAwMSIkMzBlM2ViMzctNjIzZi0xMWU4LWE2NzItZmExNjNlNWE4ZDg3Kh1zcGFya29wZXJhdG9yLms4cy5pby92MWFscGhhMQ== local:///SkyDiscovery/cephfs/user/username/spark-examples_2.11-2.3.0.jar]
I0528 06:20:18.338777       1 controller.go:218] SparkApplication spark-pi001 was updated, enqueueing it for submission
I0528 06:20:18.344042       1 sparkui.go:75] Creating a service spark-pi001-2249495700-ui-svc for the Spark UI for application spark-pi001
I0528 06:20:18.433535       1 submission_runner.go:81] spark-submit arguments: [/opt/spark/bin/spark-submit --class org.apache.spark.examples.SparkPi --master k8s://https://10.96.0.1:443 --deploy-mode cluster --conf spark.kubernetes.namespace=default --conf spark.app.name=spark-pi001 --conf spark.kubernetes.container.image=192.168.61.32:9980/skydiscovery/spark:v2.3.0_skydata --conf spark.kubernetes.submission.waitAppCompletion=false --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=spark-pi001 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-id=spark-pi001-2249495700 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.driver.cores=0.100000 --conf spark.kubernetes.driver.limit.cores=200m --conf spark.driver.memory=512m --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark --conf spark.kubernetes.driver.label.version=2.3.0 --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/volumemounts.test-volume=Cgt0ZXN0LXZvbHVtZRAAGiEvU2t5RGlzY292ZXJ5L2NlcGhmcy91c2VyL3NqbHRlc3QiAA== --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/volumes.test-volume=Cgt0ZXN0LXZvbHVtZRIlCiMKIS9Ta3lEaXNjb3ZlcnkvY2VwaGZzL3VzZXIvc2psdGVzdA== --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=spark-pi001 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-id=spark-pi001-2249495700 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.executor.instances=2 --conf spark.executor.cores=1 --conf spark.executor.memory=512m --conf spark.kubernetes.executor.label.version=2.3.0 --conf spark.kubernetes.executor.annotation.sparkoperator.k8s.io/volumemounts.test-volume=Cgt0ZXN0LXZvbHVtZRAAGiEvU2t5RGlzY292ZXJ5L2NlcGhmcy91c2VyL3NqbHRlc3QiAA== --conf spark.kubernetes.executor.annotation.sparkoperator.k8s.io/volumes.test-volume=Cgt0ZXN0LXZvbHVtZRIlCiMKIS9Ta3lEaXNjb3ZlcnkvY2VwaGZzL3VzZXIvc2psdGVzdA== --conf spark.kubernetes.driver.annotation.sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGgtzcGFyay1waTAwMSIkMzBlM2ViMzctNjIzZi0xMWU4LWE2NzItZmExNjNlNWE4ZDg3Kh1zcGFya29wZXJhdG9yLms4cy5pby92MWFscGhhMQ== local:///SkyDiscovery/cephfs/user/username/spark-examples_2.11-2.3.0.jar]
I0528 06:20:20.672806       1 initializer.go:292] Processing Spark driver pod spark-pi001-090fd4fdefb131e08b4142efea55eca9-driver
I0528 06:20:20.672905       1 initializer.go:439] Removed initializer on pod spark-pi001-090fd4fdefb131e08b4142efea55eca9-driver
I0528 06:20:21.194235       1 initializer.go:292] Processing Spark driver pod spark-pi001-af2e021c6dcc37f3b404093f37da3fe8-driver
I0528 06:20:21.194350       1 initializer.go:439] Removed initializer on pod spark-pi001-af2e021c6dcc37f3b404093f37da3fe8-driver
I0528 06:20:21.238599       1 submission_runner.go:99] spark-submit completed for SparkApplication spark-pi001 in namespace default
I0528 06:20:21.749293       1 submission_runner.go:99] spark-submit completed for SparkApplication spark-pi001 in namespace default
I0528 06:21:53.275856       1 initializer.go:292] Processing Spark executor pod spark-pi001-090fd4fdefb131e08b4142efea55eca9-exec-2
I0528 06:21:53.275968       1 initializer.go:439] Removed initializer on pod spark-pi001-090fd4fdefb131e08b4142efea55eca9-exec-2
I0528 06:21:53.576619       1 initializer.go:292] Processing Spark executor pod spark-pi001-090fd4fdefb131e08b4142efea55eca9-exec-1
I0528 06:21:53.576683       1 initializer.go:439] Removed initializer on pod spark-pi001-090fd4fdefb131e08b4142efea55eca9-exec-1
I0528 06:21:58.583400       1 initializer.go:292] Processing Spark executor pod spark-pi001-af2e021c6dcc37f3b404093f37da3fe8-exec-2
I0528 06:21:58.583499       1 initializer.go:439] Removed initializer on pod spark-pi001-af2e021c6dcc37f3b404093f37da3fe8-exec-2
I0528 06:21:58.779218       1 initializer.go:292] Processing Spark executor pod spark-pi001-af2e021c6dcc37f3b404093f37da3fe8-exec-1
I0528 06:21:58.779334       1 initializer.go:439] Removed initializer on pod spark-pi001-af2e021c6dcc37f3b404093f37da3fe8-exec-1

**However, when i use "kubectl apply -f *.yaml" to create sparkApplication, i got the only driver.**

I am new to k8s. Is there anyway to get the only driver and service.

**Comment by liyinan926** [comment]
Somehow the spec of the SparkApplication object you created using the rest api was updated (see the log below). 

```
I0528 06:20:18.338777 1 controller.go:218] SparkApplication spark-pi001 was updated, enqueueing it for submission
```

This caused the operator to submit the application again.

**Comment by xiaoliushen** [comment]
@liyinan926 thanks for the replay.

yes, i noticed the log, but i didn't do any update in fact. and it only happened in the first time go through onUpdate().

and i added log print when the "deepEqual" in the func onUpdate()  return false, but the spec's fields look the same.

it reappeared in my another environment with the image “gcr.io/spark-operator/spark-operator:v2.3.0-v1alpha1-latest” and the “restartPolicy” set to “never”.

in my project, "update" operation is not needed, so i passed the problem by used my own func compared the specs instead of "deepEqual".

ps: 
why i used rest api:
i created my SparkApplication CustomResource, and used the io.fabric8.kubernetes.client （in fact rest api） to create and delete the SparkApplication.

is there anyone met the same problem.

**Comment by liyinan926** [comment]
Interesting. So you only ran into this issue when using the fabric8 client to create a `SparkApplication`?

**Comment by xiaoliushen** [comment]
> So you only ran into this issue when using the fabric8 client to create a SparkApplication?

Use "curl" directly also ran into this issue. So it's not because of fabric8 client, i think.


> Can you share more details on how you create using the fabric8 client? 

I use `customResources`  in `io.fabric8.kubernetes.client.KubernetesClient` to build my custom resource, then call the `create `method.

`<T extends HasMetadata, L extends KubernetesResourceList, D extends Doneable<T>> MixedOperation<T, L, D, Resource<T, D>> customResources(CustomResourceDefinition var1, Class<T> var2, Class<L> var3, Class<D> var4);`

like this:
`client.customResources(definition, SparkApplication.class, SparkApplicationList.class, DoneableSparkApplication.class).create(sa);`


> It would also be helpful if you can share the logs that show the case when DeepEqual returns false but the oldApp.Spec and newApp.Spec are the same (with the specs fully printed).

oldApp.Spec:
```
spec.Type: Scala
spec.Mode: cluster
spec.Image: 192.168.61.32:9980/mycomp/spark:v2.3.0_skydata
spec.InitContainerImage:  <nil>
spec.ImagePullPolicy:  <nil>
spec.MainClass: org.apache.spark.examples.SparkPi
spec.MainApplicationFile: local:///MyComp/cephfs/user/username/spark-examples_2.11-2.3.0.jar
spec.Arguments:  []
spec.SparkConf:  map[]
spec.HadoopConf:  map[]
spec.SparkConfigMap:  <nil>
spec.HadoopConfigMap:  <nil>
spec.RestartPolicy: Never
spec.NodeSelector:  map[]
spec.MaxSubmissionRetries:  <nil>
spec.SubmissionRetryInterval:  <nil>
============================spec.Deps begin============================
spec.Deps.Jars:  []
spec.Deps.Files:  []
spec.Deps.PyFiles:  []
spec.Deps.JarsDownloadDir:  <nil>
spec.Deps.FilesDownloadDir:  <nil>
spec.Deps.DownloadTimeout:  <nil>
spec.Deps.MaxSimultaneousDownloads:  <nil>
============================spec.Driver begin============================
spec.Driver.ServiceAccount: spark
spec.Driver.PodName:  <nil>
spec.Driver.Cores: 0.100000
spec.Driver.CoreLimit: 200m
spec.Driver.Memory: 512m
spec.Driver.Labels:  map[version:2.3.0]
spec.Driver.Memory: [{Name:test-volume ReadOnly:false MountPath:/MyComp/cephfs/user/username SubPath: MountPropagation:<nil>}]
============================spec.executor begin============================
spec.Executor.Instances: 2
spec.Executor.Cores: 1.000000
spec.Executor.Memory: 512m
spec.Executor.Labels:  map[version:2.3.0]
spec.Executor.Memory: [{Name:test-volume ReadOnly:false MountPath:/MyComp/cephfs/user/username SubPath: MountPropagation:<nil>}]
============================spec.volumes begin============================
spec.Volumes.name: test-volume
spec.Volumes.VolumeSource: {HostPath:&HostPathVolumeSource{Path:/MyComp/cephfs/user/username,Type:nil,} EmptyDir:nil GCEPersistentDisk:nil AWSElasticBlockStore:nil GitRepo:nil Secret:nil NFS:nil ISCSI:nil Glusterfs:nil PersistentVolumeClaim:nil RBD:nil FlexVolume:nil Cinder:nil CephFS:nil Flocker:nil DownwardAPI:nil FC:nil AzureFile:nil ConfigMap:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil Projected:nil PortworxVolume:nil ScaleIO:nil StorageOS:nil}
```

newApp.Spec:
```
spec.Type: Scala
spec.Mode: cluster
spec.Image: 192.168.61.32:9980/mycomp/spark:v2.3.0_skydata
spec.InitContainerImage:  <nil>
spec.ImagePullPolicy:  <nil>
spec.MainClass: org.apache.spark.examples.SparkPi
spec.MainApplicationFile: local:///MyComp/cephfs/user/username/spark-examples_2.11-2.3.0.jar
spec.Arguments:  []
spec.SparkConf:  map[]
spec.HadoopConf:  map[]
spec.SparkConfigMap:  <nil>
spec.HadoopConfigMap:  <nil>
spec.RestartPolicy: Never
spec.NodeSelector:  map[]
spec.MaxSubmissionRetries:  <nil>
spec.SubmissionRetryInterval:  <nil>
============================spec.Deps begin============================
spec.Deps.Jars:  []
spec.Deps.Files:  []
spec.Deps.PyFiles:  []
spec.Deps.JarsDownloadDir:  <nil>
spec.Deps.FilesDownloadDir:  <nil>
spec.Deps.DownloadTimeout:  <nil>
spec.Deps.MaxSimultaneousDownloads:  <nil>
============================spec.Driver begin============================
spec.Driver.ServiceAccount: spark
spec.Driver.PodName:  <nil>
spec.Driver.Cores: 0.100000
spec.Driver.CoreLimit: 200m
spec.Driver.Memory: 512m
spec.Driver.Labels:  map[version:2.3.0]
spec.Driver.Memory: [{Name:test-volume ReadOnly:false MountPath:/MyComp/cephfs/user/username SubPath: MountPropagation:<nil>}]
============================spec.executor begin============================
spec.Executor.Instances: 2
spec.Executor.Cores: 1.000000
spec.Executor.Memory: 512m
spec.Executor.Labels:  map[version:2.3.0]
spec.Executor.Memory: [{Name:test-volume ReadOnly:false MountPath:/MyComp/cephfs/user/username SubPath: MountPropagation:<nil>}]
============================spec.volumes begin============================
spec.Volumes.name: test-volume
spec.Volumes.VolumeSource: {HostPath:&HostPathVolumeSource{Path:/MyComp/cephfs/user/username,Type:nil,} EmptyDir:nil GCEPersistentDisk:nil AWSElasticBlockStore:nil GitRepo:nil Secret:nil NFS:nil ISCSI:nil Glusterfs:nil PersistentVolumeClaim:nil RBD:nil FlexVolume:nil Cinder:nil CephFS:nil Flocker:nil DownwardAPI:nil FC:nil AzureFile:nil ConfigMap:nil VsphereVolume:nil Quobyte:nil AzureDisk:nil PhotonPersistentDisk:nil Projected:nil PortworxVolume:nil ScaleIO:nil StorageOS:nil}
```
They look the same.

Thanks.

**Comment by liyinan926** [comment]
That's interesting. The printed specs are exactly the same even by doing a diff. I don't know what's going on but `DeepEqual` returned `false` must for some reason. I think it's worth trying a different golang deep compare method that can tell the differences.

**Comment by liyinan926** [comment]
Closing this. Feel free to reopen if this issue still persists.
