### ISSUE TITLE
support for operating on a specific namespace

### ISSUE THREAD

**Issue by scotthew1** [GoogleCloudPlatform/spark-on-k8s-operator#172]
the current spark operator setup assumes that it runs in its own namespace and manages the sparkapp crds for the whole cluster. we were hoping that we could deploy this alongside our application which currently has the requirement that it has namespace isolation. with our current setup, if we have multiple applications on our cluster, each spark-operator sees all the crds on the cluster regardless of namespace. i was hoping i could restrict this with different role bindings but alas...
```
E0529 21:44:38.579020       1 reflector.go:205] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.SparkApplication: sparkapplications.sparkoperator.k8s.io is forbidden: User "system:serviceaccount:sreisor:ideal-tuatara-sparkoperator" cannot list sparkapplications.sparkoperator.k8s.io at the cluster scope
E0529 21:44:38.579370       1 reflector.go:205] k8s.io/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.ScheduledSparkApplication: scheduledsparkapplications.sparkoperator.k8s.io is forbidden: User "system:serviceaccount:sreisor:ideal-tuatara-sparkoperator" cannot list scheduledsparkapplications.sparkoperator.k8s.io at the cluster scope
```
is there anything we can do to restrict spark operator listing only within its namespace or a specific namespace? it's our first dependency that would break our ability to `helm install` our application into an isolated namespace.

**Comment by liyinan926** [comment]
Thanks for creating this. We also have a use case that requires limiting the operator to a single namespace. It should be straightforward to add an option to do that. Note that if the operator manipulates SparkApplications in a namespace that is different than the one of the operator, it still needs a ClusterRoleBinding.

**Comment by scotthew1** [comment]
cool! glad to hear we're not the only ones looking for this functionality. if you point me in the right direction i'd be happy to help add the option.

**Comment by liyinan926** [comment]
Sounds great. I think we need a new flag, e.g., `namespace` in `main.go` that specifies the namespace the operator is limited to. It defaults to all namespaces if not set (the flag variable will be `nil` in this case). The value of the flag if set is used as a filter for list and watch. The tricky part is creating the informer factory. If the flag is set, we can no longer use the shared informer factory as it by default lists and watches against all namespaces. In `main.go`, instead of calling `crdinformers.NewSharedInformerFactory`, we need to do the following:

```
factory := NewSharedInformerFactoryWithOptions(crdClient, time.Duration(*resyncInterval)*time.Second, crdinformers.WithNamespace(*namespace))
```

**Comment by liyinan926** [comment]
@scotthew1 just want to check are you going to add the option?

**Comment by scotthew1** [comment]
@liyinan926 yes indeed

**Comment by liyinan926** [comment]
Cool. Thanks! Will review the PR soon.

**Comment by scotthew1** [comment]
@liyinan926 did you happen to push a new docker image with this change?

**Comment by liyinan926** [comment]
@scotthew1 will push now.

**Comment by liyinan926** [comment]
Done.

**Comment by scotthew1** [comment]
thanks!
