### ISSUE TITLE
set spark k8s pod request, limit memory with different values

### ISSUE THREAD

**Issue by dfercode** [GoogleCloudPlatform/spark-on-k8s-operator#1726]
Currently spark driver and exec pod request and limit memory can only be same, not able to set separately when cluster get diff memory limit and request quota. then not able to fully use cluster memory resource.

E.g. cluster get total 50G memory request, 200G memory limit, but every spark pod limit memory are same as request memory, then in this cluster total memory spark can use is depends on the smaller one: 50G

**Comment by dfercode** [comment]
can any one give me a JIRA ticket for this? I have a PR to resolve this.

**Comment by dhia-gharsallaoui** [comment]
Hello @dfercode I am interested by this feature can you share the PR code ? Thank you

**Comment by pycgo** [comment]
any update?
