### ISSUE TITLE
Launch multiple SparkApplications

### ISSUE THREAD

**Issue by tamis-laan** [GoogleCloudPlatform/spark-on-k8s-operator#1728]
We are using flux ci/cd to launch spark pipelines. The only problem is that the spark operator can't launch multiple jobs at the same time. 

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1466

This forces us to suspend and resume spark jobs one by one to get things running. Is there some way to deal with this? For example create dependencies between spark applications so they start one after the other?

**Comment by phyyou** [comment]
Hey, just increase resource for spark operator.
It can multiple application if resource enough for processing the submitted applications.
