### ISSUE TITLE
Multiple spark versions for breaking changes in spark submit

### ISSUE THREAD

**Issue by mccheah** [GoogleCloudPlatform/spark-on-k8s-operator#182]
Suppose a user's cluster has a Spark operator bundled with version 2.3 of Spark Submit. Suppose then we introduce a breaking change in the contract between Spark Submit and the Spark application docker containers. Therefore any Spark application using Spark 2.4 needs to use Spark 2.4's spark submit, and conversely, all applications using Spark 2.3 need to use Spark 2.3's spark submit.

Unfortunately it's not easy right now to support having a single Spark operator deploying both Spark 2.3 and Spark 2.4 applications. If you upgrade the Spark operator's bundled Spark submit version to 2.4, suddenly all applications running Spark 2.3 will break.

There are multiple ways to tackle this problem. First of all, we should be ensuring that the contract between spark submit and the Spark driver it launches is stable. This has been the case for a long time with Spark on YARN.

However, we can be clever and allow for the above use case even if the above contract breaks, as follows:

- Add a `sparkVersion` field to the spec of `SpatkApplication`
- The Spark operator comes bundled with a certain Spark submit version that is compatible with some subset of spark versions of Spark applications
- A given operator will only deploy a `SparkApplication` if the `sparkVersion` declared by that application is compatible with its bundled spark-submit version.

This allows one to implement something like a rolling upgrade strategy for Spark applications run on their cluster. As an example, a cluster administrator can install a Spark 2.4 compatible Spark operator and leave the Spark 2.3 operator running on the cluster. Once the organization has upgraded all Spark applications to Spark 2.4 and higher, the Spark 2.3 operator can be decommissioned.

Tasks:
* [x] Add a new field for specifying the Spark version.
* [x] Use a Kubernetes `Job` to run `spark-submit`.

**Comment by liyinan926** [comment]
Tasks:
* [ ] Add a new field for specifying the Spark version.
* [ ] Add an optional command-line flag for specifying the list of Spark versions supported.
* [ ] Add logic for checking version match.

**Comment by akhurana001** [comment]
@liyinan926 , @mccheah  

This is something of interest to us(/Lyft) as well as we are starting to use the Operator for production use-cases. We were also looking at a few potential solutions to achieve this and I can share more details. What's the current status of this: Is the story/design closed out, is this being actively worked on ? 

( cc @kumare3)

**Comment by liyinan926** [comment]
No, this is not being worked on. It's great to know that you have some thoughts, and looking forward to the details.

**Comment by liyinan926** [comment]
@akhurana001 thanks for proposing the solutions!

> CRD Label based Routing/Multiple Operators: This is very similar to the approach mentioned above but instead of adding spark-version as part of the CRD Spec, users/clients add a relevant spark-version label to SparkApplication CRD and we run multiple Operators one for each spark version we want to support. Each Operator will listen to SparkApplications only for the particular spark-version it supports. Additionally, the Operator is also responsible for propagating this label to any driver/executor pods it creates and listening for status update for only those pods.

This requires separating out the code for registering/updating the CRDs and carefully coordinating the creation/updating of CRDs for all instances of the operator running in a cluster. There is also an issue with applications not properly labeled. For example, `SparkApplication`s not labeled or labeled with a version with no corresponding operator instance won't be handled.

> Multiple Spark-Version within SparkOperator: In this approach, we install multiple spark-distributions within the Operator image. Each SparkApplication CRD will have a spark-version field and the Operator will consume this spark-version to create the correct spark-submit arguments and trigger the spark-submit on the correct distribution via correctly set environment variables like SPARK_HOME etc.

You summarized pretty well the issues with this solution.

> Spark Submission via Kubernetes Job: In this approach, the spark-distribution the operator image will not contain the spark-distribution and spark-submit will be triggered on separate Spark-Distribution images via Kubernetes Jobs. Same as above, each SparkApplication CRD will have a spark-version field and the Operator will consume this spark-version to create the correct spark-submit arguments for the spark-version but instead of directly executing spark-submit, the Operator will create a new Kubernetes Job with the relevant spark-distribution image as the container image, spark-submit as the container entrypoint and the spark-submit arguments as the container arguments. This Job will just trigger the spark-submit on the correct distribution and exit.

One benefit of this approach is we can delegate the handling of submission retries to the Job controller. The Kubernetes Job can use the user-specified image in the `SparkApplication` resource. However, it has the same problem with the proposal of using a Job to run the driver pod in https://github.com/apache/spark/pull/21067. See https://github.com/kubernetes/kubernetes/issues/66620. This might not be a real issue given that the submission command should complete or fail fairly fast.

**Comment by kumare3** [comment]
@liyinan926 as @akhurana001 explained above, Solution (3) seems promising and Solution (2) is also workable. 
As explained in Solution (3), in the previous PR we made it such that Spark-Driver pod creation is `idempotent`. As long as the name is deterministic, we guarantee only one pod creation per SparkApplication, even if the spark-submit is invoked multiple times.
Solution (2) seems ok for a migration strategy, but seems unwieldy where the matrix of versions increases.

I think we should narrow down on the solution, as we ramp up our production traffic on the operator, we want it to be easy for the users to migrate versions, without breaking their usecases. An important thing to note is @akhurana001 is going to be out for rest of the month and I am really slammed, but can definitely help you in CodeReviews. Do you feel you can take this up? OR lets come up with a gameplan, before Anmol leaves for vacation next week, do you want to have a quick hangout?

**Comment by liyinan926** [comment]
@kumare3 @akhurana001 I like solution 3 better. Let's meet and come up with a plan before @akhurana001 leaves for vacation. Also FYI: I will be at kubecon in the week of 12/10. So maybe let's meet next week?

**Comment by kumare3** [comment]
@liyinan926 Kubecon is in Seattle this year, I have my name in the waitlist :) (was late in registering). But, you should definitely come visit us at the Lyft Seattle office. Also, lets setup sometime next week for Tuesday 12/04 or 12/06, you can send us an invite.

**Comment by liyinan926** [comment]
@kumare3 sounds good. I will send an invite.

**Comment by liyinan926** [comment]
Multi-version support has been implemented in the branch `multi-version-support`.

**Comment by stijndehaes** [comment]
@liyinan926 I see this has been implemented in the branch, but not sure what the status of that branch is the last commit was from July? Is this still being worked on? Has it been abandoned? If possible I am willing to help with making this land.

**Comment by kumare3** [comment]
@stijndehaes we actually use this branch in production at Lyft and has been the way to migrate from spark 2 - spark 3. It does add the additional dependence on jobs api (which is a little brittle) but we are still happy with this change as this allows us to transparently migrate our users.
We run spark in GitHub.com/lyft/Flyte project
