### ISSUE TITLE
gcr.io image releases that contain current fixes?

### ISSUE THREAD

**Issue by juvlarN** [GoogleCloudPlatform/spark-on-k8s-operator#184]
I guess the maintainers of this project are pushing new images to the gcr.io repository when errors are fixed or code additions are made.
Is there a list of available images in the gcr.io repository? 

To be specific: I am looking for an image that contains the commit https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/971de3b542f2419cd60c0b11a970a02a11e6a52f -- is there one published to the repository already?

**Comment by juvlarN** [comment]
Someone on Slack pointed me into the right direction: https://console.cloud.google.com/gcr/images/spark-operator/GLOBAL/spark-operator?gcrImageListsize=50

**Comment by juvlarN** [comment]
Looks like there is no current version pushed to the repo though. Any plans when the current changes are pushed to the repo? @liyinan926

**Comment by liyinan926** [comment]
Just pushed the latest image.

**Comment by juvlarN** [comment]
@liyinan926 I can't see your pushed image? 
The last push was 9 days ago, according to the website linked above:
![image](https://user-images.githubusercontent.com/8269353/41348587-5ceb0fb0-6f0d-11e8-8389-c46277e881ea.png)

**Comment by liyinan926** [comment]
Oops, pushed to the wrong project. Can you check again?
