### ISSUE TITLE
GKE warning *Update webhook to no longer intercept system requests*

### ISSUE THREAD

**Issue by BalaMahesh** [GoogleCloudPlatform/spark-on-k8s-operator#1846]
Hello all,

I have installed spark on k8's operator and enabled the web hook on our GKE cluster.  We started seeing the warning in GCP console which says 

This cluster has an admission webhook installed that is intercepting system critical requests in the last 24 hours. Intercepting these requests can impact availability of the GKE Control Plane.

spark-on-k8s-operator-spark-operator-webhook-config | Intercepting resources in the kube-system namespace. 

I have updated the namespaceSelector,

  namespaceSelector: kubernetes.io/metadata.name=ns

but still we are seeing the scope as "*" 

```      service:
        name: spark-on-k8s-operator-spark-operator-webhook
        namespace: ns
        path: /webhook
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: webhook.sparkoperator.k8s.io
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: glance-grap
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: NoneOnDryRun 
```

https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks?&_ga=2.240100609.-362041899.1669613969#unsafe-webhooks - this documentation says that scope should be namespaces and  not "*"

Kindly suggest on fixing this issue.

**Comment by Markieta** [comment]
> [the recommendation is resolved within 24 hours and no longer appears in the console.](https://cloud.google.com/kubernetes-engine/docs/how-to/optimize-webhooks?authuser=1#troubleshoot-webhooks)

You need to wait 1 day for the recommendations to update in the Console.

> spark-on-k8s-operator-spark-operator-webhook-config | Intercepting resources in the kube-system namespace.

But in your code it's named `spark-on-k8s-operator-spark-operator-webhook` (missing `-config` suffix), perhaps you modified an incorrect/duplicate webhook?

**Comment by BalaMahesh** [comment]
@Markieta - yes the warning disappeared after waiting for 24 hours. Thanks for your time and attention.
