### ISSUE TITLE
[sparkctl] Instead of public upload, use pre-signed url with long expiration date

### ISSUE THREAD

**Issue by mrow4a** [GoogleCloudPlatform/spark-on-k8s-operator#186]
I am wondering, if we could use pre-signed URLs (with expiration date like a week or so) in case of GCS and S3, instead-of/along-with `--public` ?  

What do you think @liyinan926 ?

CC @prasanthkothuri

**Comment by liyinan926** [comment]
@mrow4a I think we can add that as an option while keeping the `--public` option.

**Comment by mrow4a** [comment]
I had another look into this, and I think it might be better if dependency is available all the time (secure or public), except for manual delete or storage clean-up. 

If someone finds value in pre-signed, please reopen. @liyinan926 can we close?

**Comment by liyinan926** [comment]
Yes, closing.
