### ISSUE TITLE
gcr.io/spark-operator/spark:v3.1.1 not found

### ISSUE THREAD

**Issue by gringParis** [GoogleCloudPlatform/spark-on-k8s-operator#1860]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/Dockerfile#L17C17-L17C51
The spark image found here is not reachable. 
Any solution for this?

**Comment by HarshkumarEO** [comment]
@gringParis Same issue here. till morning of today it was working

**Comment by liyinan926** [comment]
The images were removed due to vulnerability concerns. I suggest you build and push your own image for now.

**Comment by msdolbey** [comment]
> The images were removed due to vulnerability concerns. I suggest you build and push your own image for now. Alternatively, we can also host the images here on Github's repository.

Thanks for the update.

**Comment by 18ksquare24** [comment]
how to build our own image

**Comment by gringParis** [comment]
Are you going to publish an updated version?

**Comment by jinnerbichler** [comment]
Where can the Dockerfile for gcr.io/spark-operator/spark:v3.1.1 be found?

**Comment by VA-PLE** [comment]
Maybe someone has this image saved locally?

**Comment by gringParis** [comment]
@jinnerbichler here is the image : https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/Dockerfile

**Comment by gringParis** [comment]
Does anyone knows where to find the dockerfile for this image: [gcr.io/spark-operator/spark-py:v3.1.1](http://gcr.io/spark-operator/spark-py:v3.1.1)

**Comment by jinnerbichler** [comment]
@gringParis the Dockerfile is using gcr.io/spark-operator/spark:v3.1.1 (see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/Dockerfile#L37).

**Comment by jinnerbichler** [comment]
Our solution was to use the following image instead apache/spark:v3.1.3.

**Comment by gringParis** [comment]
@jinnerbichler That worked for us too. Thank you :)
