### ISSUE TITLE
Why images not found

### ISSUE THREAD

**Issue by szainalie** [GoogleCloudPlatform/spark-on-k8s-operator#1862]
When I used "gcr.io/spark-operator/spark-py:v3.1.1" as the base image in my customized docker image I faced an error "not found". Is the image address changed?

**Comment by robwithhair** [comment]
Found same issue.  Can you confirm if `apache/spark:v3.1.3` is in fact the same as `gcr.io/spark-operator/spark-py:v3.1.1` for backwards compatibility purposes?  If not, is there a way to build the old `gcr.io/spark-operator/spark-py:v3.1.1`  locally to ensure existing systems are not impacted?

**Comment by szainalie** [comment]
@liyinan926, Thanks for your response, but when I used your mentioned image I faced an error about the Python problem(this image must used for Java), and when used this image "apache/spark-py:v3.1.3", this is not backward compatible. 
@robwithhair
