### ISSUE TITLE
Not able to submit same application again when first one is completed

### ISSUE THREAD

**Issue by deveshk0** [GoogleCloudPlatform/spark-on-k8s-operator#187]
I submitted the sparkpi example application, when it got completed i have deleted the driver pod.
Now when i am resubmitting the same application again, nothing is happening. Any idea??

**Comment by deveshk0** [comment]
when I am changing the application name then it is working. any way i can make that work in same application name.
Something like helm replace feature.. ?

**Comment by juvlarN** [comment]
@deveshk0 have you watched into the logs of the spark-operator pod already?

**Comment by liyinan926** [comment]
@deveshk0 This is by design. The operator won't re-submit an application of the same name if the application spec remains the same. But if you update the spec, e.g., changing or adding a label or annotation, the operator will re-submit the application to run.

**Comment by deveshk0** [comment]
Thanks, I will try that way.
