### ISSUE TITLE
Getting error standard_init_linux.go:190: exec user process caused "no such file or directory" when building the latest master

### ISSUE THREAD

**Issue by yuchaoran2011** [GoogleCloudPlatform/spark-on-k8s-operator#191]
Not sure when this issue started happening, I was trying to build the latest master of the operator, but unable to install it to the cluster because the operator pod threw an error:
```
standard_init_linux.go:178: exec user process caused "no such file or directory"
```

**Comment by yuchaoran2011** [comment]
After searching around, I found this [link](https://github.com/docker/labs/issues/215) that helped me fix the error for me. 
Some guy/lady suggested:
```
OK, I see the problem. You're probably building your go binary on the Mac and trying to run it in Linux container. Try this when building your go binary:

env GOOS=linux GOARCH=386 go build hello-world.go
```
This described my situation and the proposed solution worked for me. I simply changed this [line](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/Dockerfile#L27).

**Comment by liyinan926** [comment]
Yes, if you want to build it locally on a Mac, you will need to add `GOOS=linux`.

**Comment by yuchaoran2011** [comment]
I was hoping for a one-liner comment in the README.
