### ISSUE TITLE
How to Expose Custom Port for my spark application

### ISSUE THREAD

**Issue by deveshk0** [GoogleCloudPlatform/spark-on-k8s-operator#192]
Hi i have jetty server running in spark app. I want to expose this to a port. Any idea how I can achieve it.

**Comment by liyinan926** [comment]
Spark itself doesn't support this kind of customization yet. This will be supported by https://issues.apache.org/jira/browse/SPARK-24434. Alternatively, this can also be supported by the pod initializer the operator uses. The initializer is an alpha feature and requires an alpha cluster. We plan to switch the initializer to a mutating webhook.

**Comment by liyinan926** [comment]
Are your Jetty server running in a separate container than the main Spark driver/executor container?

**Comment by deveshk0** [comment]
No I am running jetty in driver container.
It is working but service for that port I had to create manually for every deployment.

**Comment by liyinan926** [comment]
I think this can be supported by the mutating admission webhook recently added into the operator. Essentially you need a way to specify that the driver exposes a certain port backed by a service that can be automatically created by the operator.
