### ISSUE TITLE
Support affinity/anti-affinity/tolerations

### ISSUE THREAD

**Issue by adamresson** [GoogleCloudPlatform/spark-on-k8s-operator#195]
Is there any planned support for setting affinity/anti-affinity/tolerations on both the driver and executor pods (albeit separately)?

I want to try to run my jobs on pre-emptable nodes, but I know this can cause problems with the driver pod (since by default it doesn't get rescheduled). Ideally, I could run driver nodes on non-premetible nodes and workers on an autoscaling pre-emptable node pool, and have my processing power be relatively inexpensive.

Having support for being able to specify affinity/anti-affinity/tolerations should weird enough power to make this possible. I know right now Spark submit (2.3.0) supports node selectors, but it's for both driver and executor, and doesn't allow for tolerations to allow scheduling on nodes with taints.

**Comment by liyinan926** [comment]
Support for setting affinity/anti-affinity can be solved by https://issues.apache.org/jira/browse/SPARK-24434. The operator will use that solution depending on when it becomes ready.

**Comment by liyinan926** [comment]
An alternative is to use a mutating admission webhook to support this. This is particularly useful for Spark 2.3 since https://issues.apache.org/jira/browse/SPARK-24434 probably won't even get into 2.4. The operator currently uses an initializer for pod customization, but work is in progress to replace the initializer with a mutating admission webhook.

**Comment by liyinan926** [comment]
@adamresson I will add support for this as part of the work on replacing the initializer with a mutating webhook.

**Comment by liyinan926** [comment]
Support for pod affinity/anti-affinity has been added through a new mutating admission webhook. It is currently available in branch https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/webhook. Refer to the [Quick Start Guide](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/webhook/docs/quick-start-guide.md) on how to use the mutating admission webhook and [Using Pod Affinity](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/webhook/docs/user-guide.md#using-pod-affinity).

**Comment by liyinan926** [comment]
Closing this as it is available now. The feature will be merged back to master soon.

**Comment by samsonov90** [comment]
> Were tolerations ever added? Or just affinity/anti-affinity?

In order to support for tolerations I have just created PR - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/312
