### ISSUE TITLE
ScheduledSparkApplication failing with no logs to debug

### ISSUE THREAD

**Issue by dharmeshkakadia** [GoogleCloudPlatform/spark-on-k8s-operator#196]
Spark operator log is full with

```
E0620 13:52:27.962182       1 controller.go:138] failed to sync ScheduledSparkApplication "default/braze-blob-delete": pods "braze-blob-delete-1529197207414975848-1529197209364-driver" not found
W0620 14:08:40.257852       1 reflector.go:341] k8s.io/spark-on-k8s-operator/pkg/controller/sparkapplication/spark_pod_monitor.go:114: watch of *v1.Pod ended with: too old resource version: 1649124 (1649155)
E0620 14:09:07.975880       1 controller.go:138] failed to sync ScheduledSparkApplication "default/braze-blob-delete": pods "braze-blob-delete-1529197207414975848-1529197209364-driver" not found
E
```
Also, the failed driver pods are not available so I can't get the logs as well. Here is the describe output for the run:

```
kubectl describe sparkapplications/braze-blob-delete-1529197207414975848
Name:         braze-blob-delete-1529197207414975848
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  sparkoperator.k8s.io/v1alpha1
Kind:         SparkApplication
Metadata:
  Cluster Name:
  Creation Timestamp:  2018-06-17T01:00:07Z
  Generation:          0
  Owner References:
    API Version:     sparkoperator.k8s.io/v1alpha1
    Kind:            ScheduledSparkApplication
    Name:            braze-blob-delete
    UID:             00f7668b-6ffc-11e8-bfb0-000d3a1d5635
  Resource Version:  1583436
  Self Link:         /apis/sparkoperator.k8s.io/v1alpha1/namespaces/default/sparkapplications/braze-blob-delete-1529197207414975848
  UID:               c6e6a7e4-71c9-11e8-b63e-000d3a1d5437
Spec:
  Deps:
  Driver:
    Cores:  2
    Labels:
      Version:  2.4.0
    Memory:     2048m
    Secrets:
      Name:           mdldatasecrets-gdpr-blob
      Path:           /mnt/secrets/
      Secret Type:    Generic
    Service Account:  spark
  Executor:
    Cores:      2
    Instances:  20
    Labels:
      Version:            2.4.0
    Memory:               4096m
  Image:                  mdldata.azurecr.io/data/gdpr-blob:latest
  Main Application File:  local:///code/delete_controller_braze.py
  Mode:                   cluster
  Restart Policy:         Never
  Spark Conf:
    Spark . Event Log . Enabled:                                                               true
  Type:                                                                                        Python
Status:
  App Id:  braze-blob-delete-1529197207414975848-248004312
  Application State:
    Error Message:
    State:          SUBMITTED
  Completion Time:  2018-06-17T06:38:12Z
  Driver Info:
    Pod Name:             braze-blob-delete-1529197207414975848-1529197209364-driver
    Web UI Port:          31318
    Web UI Service Name:  braze-blob-delete-1529197207414975848-248004312-ui-svc
  Executor State:
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 1:   FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 10:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 11:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 12:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 13:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 14:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 15:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 16:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 17:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 18:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 19:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 2:   FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 20:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 21:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 22:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 23:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 24:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 25:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 26:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 27:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 28:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 29:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 3:   FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 30:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 31:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 32:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 33:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 34:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 35:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 36:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 37:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 38:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 39:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 4:   FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 40:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 41:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 42:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 43:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 44:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 45:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 46:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 47:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 48:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 49:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 5:   FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 50:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 51:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 52:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 53:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 54:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 55:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 56:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 57:  PENDING
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 58:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 59:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 6:   FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 60:  FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 7:   FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 8:   FAILED
    Braze - Blob - Delete - 1529197207414975848 - 1529197209364 - Exec - 9:   FAILED
  Submission Time:                                                            2018-06-17T01:00:07Z
Events:                                                                       <none>
```
How can I get the driver logs?

**Comment by liyinan926** [comment]
Are you using a concurrency policy of `Replace`?

**Comment by dharmeshkakadia** [comment]
Yes.

**Comment by dharmeshkakadia** [comment]
Any update?

**Comment by liyinan926** [comment]
With a `Replace` concurrency policy, the operator should delete **both** the driver pod and `SparkApplication` instance of old runs that fall out of the maintenance window. It's weird that you could still see the `SparkApplication` instance while the driver pod of the run was gone. Regarding log access, if the driver pod was deleted, you wouldn't have access to its logs anymore.

**Comment by dharmeshkakadia** [comment]
How do you debug such scenarios?

**Comment by liyinan926** [comment]
Is `braze-blob-delete-1529197207414975848` a run that falls outside the maintenance window? What are the values of `SuccessfulRunHistoryLimit` and `FailedRunHistoryLimit`?

**Comment by dharmeshkakadia** [comment]
I set `runHistoryLimit: 3`. I don't think it was outside of the maintenance window.

**Comment by liyinan926** [comment]
OK, looks like you are running an older version of the operator. Can you try the latest master with https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/202?

**Comment by dharmeshkakadia** [comment]
Oh that looks like it should solve this. I will try it on another cluster where I am running latest. Closing this in the mean time.

**Comment by dineshabbi** [comment]
Doesn't this issue exist with SparkApplication kind ? I see that all my pods are cleaned up after failure:
`
apiVersion: sparkoperator.k8s.io/v1beta1
kind: SparkApplication
metadata:
  name: spark-stream
  namespace: default
spec:
  type: Java
  mode: cluster
  image: "spark:stream-N"
  imagePullPolicy: Always
  mainClass: myClass
  mainApplicationFile: "local:///my.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 5
    onFailureRetryInterval: 5
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 10
  driver:
    cores: 1
    coreLimit: "2000m"
    memory: "2g"
    serviceAccount: spark
    labels:
      version: 2.4.0
  executor:
    cores: 1
    instances: 1
    memory: "4g"
    labels:
      version: 2.4.0
  imagePullSecrets:
    - my-secret
`
sparkapplication log:
`:~/repos-ct/ct-spark-analytics$ kubectl describe sparkapplication spark-stream
Name:         spark-stream
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  sparkoperator.k8s.io/v1beta1
Kind:         SparkApplication
Metadata:
  Creation Timestamp:  2019-03-13T11:10:56Z
  Generation:          1
  Resource Version:    6738903
  Self Link:           /apis/sparkoperator.k8s.io/v1beta1/namespaces/default/sparkapplications/spark-stream
  UID:                 ac6c1717-4580-11e9-bce9-02f8ab1c69a4
Spec:
  Arguments:
    /opt/colortokens/ct-analytics/jsc/config/FlinkProperties.properties
    5
  Deps:
  Driver:
    Core Limit:  2000m
    Cores:       2
    Labels:
      Version:        2.4.0
    Memory:           4g
    Service Account:  spark
  Executor:
    Cores:      2
    Instances:  1
    Labels:
      Version:        2.4.0
    Memory:           8g
  Image:              colortokens/spark:stream-1077
  Image Pull Policy:  Always
  Image Pull Secrets:
    colortokens-docker-hub-secret
  Main Application File:  local:///opt/spark/jars/ct_analytics_Spark.jar
  Main Class:             com.colortokens.analytics.main.Driver
  Mode:                   cluster
  Restart Policy:
    On Failure Retries:                    5
    On Failure Retry Interval:             5
    On Submission Failure Retries:         3
    On Submission Failure Retry Interval:  10
    Type:                                  OnFailure
  Spark Version:                           2.4.0
  Type:                                    Java
Status:
  Application State:
    Error Message:  
    State:          FAILED
  Driver Info:
    Pod Name:             spark-stream-driver
    Web UI Port:          30512
    Web UI Service Name:  spark-stream-ui-svc
  Execution Attempts:     6
  Executor State:
    Spark - Stream - 1552499312139 - Exec - 1:  FAILED
  Last Submission Attempt Time:                 2019-03-13T17:48:33Z
  Spark Application Id:                         spark-206186df3bfe4401b989396058fd608f
  Submission Attempts:                          1
  Termination Time:                             2019-03-13T17:50:28Z
Events:                               `

**Comment by dharmeshkakadia** [comment]
@dineshabbi It might be easier for you to debug with `restartPolicy: Never`. With that driver pod should be there after failure.

**Comment by dineshabbi** [comment]
@dharmeshkakadia, are you saying this is an expected behavior for 'restartPolicy : OnFailure' ? I wanted the restartPolicy to be OnFailure, but at the same time expected operator to keep me at least the last failed pod once the restart attempt limit exceeded. This behavior is important especially if I am hitting some upstream spark corner case bug because of which my spark application is crashing. @liyinan926 I was hoping you could clarify my confusion so that I can contribute some code if this requirement makes any sense.

**Comment by dharmeshkakadia** [comment]
@dineshabbi I am not saying its expected behavior. You should have had the pod for debugging. I was just suggesting it as way for you to debug the job failure.
