### ISSUE TITLE
UI service has a random hash in its name

### ISSUE THREAD

**Issue by kumare3** [GoogleCloudPlatform/spark-on-k8s-operator#201]
The Operator appends a 32 bit hash to the appName specified in the spec (https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/controller.go#L729 ) . Is there a particular reason to append the 32 bit hash ? I understand this is used to create the UI service but won't the appName/resourceName already be unique in kubernetes and can be used directly for the same ? 
 
Also kubernetes enforces a 63 character limit on the name and the hash (with the "ui-svc" string) ends up consuming a good part of it.  We ended up breaching this threshold.

**Comment by kumare3** [comment]
@liyinan926 after the discussion, it seems the reason for the has is to make retries possible. If we delete the service between retries, we could just use the regular name.

**Comment by liyinan926** [comment]
@kumare3 yes, we can get rid of the hash.
