### ISSUE TITLE
Provide a way for sparkctl to authenticate when run inside a pod

### ISSUE THREAD

**Issue by crobby** [GoogleCloudPlatform/spark-on-k8s-operator#203]
I have a use case where I need to have sparkctl run from inside a pod at runtime.  Ideally, it could grab a token from a serviceaccount's secret that is mounted in the pod and use that to authenticate and be able to create/delete SparkApplication objects.

I would be happy to do the work, if necessary, and submit a PR, but before I do that, I figured that I'd create an issue and get feedback in case anyone may have objections or insight on this.

**Comment by liyinan926** [comment]
Are you able to use the `kubeconfig` flag of `sparkctl` for this?

**Comment by crobby** [comment]
I don't think the kubeconfig flag is an option for us since I don't think (definitely correct me if I'm wrong) that there is a .kube/config available from within the pod.  If the required credentials are indeed already available from within the running pod, then the --kubeconfig flag would probably work for us.

**Comment by liyinan926** [comment]
There's a service account under `/var/run/secrets/kubernetes.io/serviceaccount/` within the pod, which can be used to build an in-cluster config using `clientcmd.InClusterConfig`. The code for building the kube client in sparkctl needs to be fixed to make it work. Definitely a PR is appreciated.

**Comment by crobby** [comment]
Thanks for the tip.  I was indeed looking at making a tweak to use InClusterConfig.  Glad to know I was on the right path.  Hopefully, I'll have a PR soon.

**Comment by crobby** [comment]
Ah, perhaps we won't need a PR for this.
I hadn't tried passing --kubeconfig="" before.  It seems that when we do this, it may trigger the InClusterConfig on our behalf.  That might be sufficient for our use.  I'll verify this and close the issue if no change is required.

// BuildConfigFromFlags is a helper function that builds configs from a master
// url or a kubeconfig filepath. These are passed in as command line flags for cluster
// components. Warnings should reflect this usage. If neither masterUrl or kubeconfigPath
// are passed in we fallback to inClusterConfig. If inClusterConfig fails, we fallback
// to the default config.

**Comment by crobby** [comment]
Closing this issue since it looks like we can already get InClusterConfig() called from sparkctl.  Thanks for the help.
