### ISSUE TITLE
Relaunch executor pods on failure

### ISSUE THREAD

**Issue by dharmeshkakadia** [GoogleCloudPlatform/spark-on-k8s-operator#204]
Currently, we don't create new executor pods to replace the failed once. This is very useful resiliency.

**Comment by liyinan926** [comment]
This is not something the operator is positioned to do, but rather something Spark itself should handle. More specifically, the driver should be responsible for replacing failed executors with new ones.

**Comment by dharmeshkakadia** [comment]
I will close this. Do you think I should open a JIRA on spark for this ?

**Comment by liyinan926** [comment]
Yes, a JIRA against Spark is useful.

**Comment by dharmeshkakadia** [comment]
opened https://issues.apache.org/jira/browse/SPARK-24751
