### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by thbeh** [GoogleCloudPlatform/spark-on-k8s-operator#225]
Not a issue per say...

Would operator be a long term work incorporated into Kubernetes as I am seeing Apache Spark (Databrick) have a different way of working Spark on K8s.

**Comment by thbeh** [comment]
Sorry excuse me for the brevity. I tested Apache Spark on K8s earlier using this 

_bin/spark-submit --master k8s://https://192.168.205.150:8443 --deploy-mode cluster --name spark-pi --class org.apache.spark.examples.SparkPi --conf spark.executor.instances=5 --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark --conf spark.kubernetes.container.image=gcr.io/thbeh-kube/spark:k8s-spark-2.3 --conf spark.kubernetes.driver.pod.name=spark-pi-driver local:///opt/spark/examples/jars/spark-examples_2.11-2.3.0.jar 1000_

but it looks like using SparkOperator is way much easier. So my question is there will eventually be 2 ways of running Spark on k8s and whether the SparkOperator way will be the preferred way?

**Comment by liyinan926** [comment]
Got it. The Spark Operator is the more Kubernetes idiomatic and cloud-native way of running Spark applications on Kubernetes than `spark-submit`. So I would say if you don't have heavy investment into tooling around `spark-submit` or are new to Spark on Kubernetes and would like to make Spark integrate better with the rest of your stack on Kubernetes, the operator is definitely the more idiomatic way and it offers much more than just submitting your applications to run. With that being said, however, `spark-submit` is definitely not going away and is still the Spark native way of submitting applications. In the long term, the operator will not semantically nor functionally diverge from `spark-submit` and will use it under the hood. So I wouldn't say there will be two ways. Instead, it's a matter of if you prefer a more Kubernetes idiomatic way or a Spark native way. Hope this answers your question.

**Comment by liyinan926** [comment]
Closing this and feel free to reopen if you have further questions.
