### ISSUE TITLE
Feature roadmap for sparkctl

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#235]
* [x] Supports printing Kubernetes events on `SparkApplication` resources.
* [ ] Supports `ScheduledSparkApplication`.

**Comment by liyinan926** [comment]
@dharmeshkakadia @mrow4a for thoughts and comments on what new features should `sparkctl` has.

**Comment by dharmeshkakadia** [comment]
We should consider adding first class support for `ScheduledSparkApplication` that includes 
- listing 
- creating
- deleting
- logs (from last run, etc)
- describing
- alter schedule
- trigger (to create one job from the schedule) mentioned in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/233
