### ISSUE TITLE
gcr.io/ynli-k8s/spark:v2.3.0

### ISSUE THREAD

**Issue by thbeh** [GoogleCloudPlatform/spark-on-k8s-operator#238]
Hi, could you help on the process of generating the above image. I downloaded both v2.3.0, with and without Hadoop support and running build from the kubernetes and can't pass thought the FSDataInputStream error. No code change just did a Docker build. What did I missed? Thanks

**Comment by thbeh** [comment]
This is what i am getting -

_+ exec /sbin/tini -s -- /usr/lib/jvm/java-1.8-openjdk/bin/java -Dspark.driver.blockManager.port=7079 -Dspark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=spark-tpcds -Dspark.kubernetes.namespace=default -Dspark.kubernetes.executor.label.sparkoperator.k8s.io/app-id=spark-tpcds-1284983346 -Dspark.hadoop.fs.s3a.access.key=minio -Dspark.kubernetes.driver.limit.cores=1000m -Dspark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true -Dspark.kubernetes.driver.annotation.sparkoperator.k8s.io/volumes.test-volume=Cgt0ZXN0LXZvbHVtZRITChEKBC90bXASCURpcmVjdG9yeQ== -Dspark.kubernetes.driver.label.version=2.3.0 -Dspark.kubernetes.driver.pod.name=spark-tpcds-4f583b5582a33cfa9e44ff1c856ed820-driver -Dspark.app.id=spark-5a4e39a81e7b4969a547972fa2258ca0 -Dspark.executor.memory=2048m -Dspark.kubernetes.container.image.pullPolicy=IfNotPresent -Dspark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=spark-tpcds -Dspark.submit.deployMode=cluster -Dspark.kubernetes.driver.annotation.sparkoperator.k8s.io/ownerreference=ChBTcGFya0FwcGxpY2F0aW9uGgtzcGFyay10cGNkcyIkODAwY2QyZjgtOTQ3YS0xMWU4LTlmZWQtMDgwMDI3YTAwMzllKh1zcGFya29wZXJhdG9yLms4cy5pby92MWFscGhhMQ== -Dspark.kubernetes.container.image=thbeh/spark-tpcds-hadoop:latest -Dspark.kubernetes.authenticate.driver.serviceAccountName=spark -Dspark.app.name=spark-tpcds -Dspark.master=k8s://https://10.96.0.1:443 -Dspark.driver.port=7078 -Dspark.driver.memory=1024m -Dspark.kubernetes.driver.label.sparkoperator.k8s.io/app-id=spark-tpcds-1284983346 -Dspark.hadoop.fs.s3a.endpoint=http://192.168.205.201:9000 -Dspark.kubernetes.executor.label.version=2.3.0 -Dspark.kubernetes.executor.annotation.sparkoperator.k8s.io/volumemounts.test-volume=Cgt0ZXN0LXZvbHVtZRAAGgQvdG1wIgA= -Dspark.kubernetes.executor.annotation.sparkoperator.k8s.io/volumes.test-volume=Cgt0ZXN0LXZvbHVtZRITChEKBC90bXASCURpcmVjdG9yeQ== -Dspark.driver.cores=1.000000 -Dspark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true -Dspark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem -Dspark.executor.instances=1 -Dspark.driver.host=spark-tpcds-4f583b5582a33cfa9e44ff1c856ed820-driver-svc.default.svc -Dspark.kubernetes.executor.podNamePrefix=spark-tpcds-4f583b5582a33cfa9e44ff1c856ed820 -Dspark.jars=/opt/spark/examples/jars/spark-examples_2.11-2.3.0.jar,/opt/spark/examples/jars/spark-examples_2.11-2.3.0.jar -Dspark.kubernetes.driver.annotation.sparkoperator.k8s.io/volumemounts.test-volume=Cgt0ZXN0LXZvbHVtZRAAGgQvdG1wIgA= -Dspark.executor.cores=1 -Dspark.hadoop.fs.s3a.secret.key=minio123 -cp ':/opt/spark/jars/*:/opt/spark/examples/jars/spark-examples_2.11-2.3.0.jar:/opt/spark/examples/jars/spark-examples_2.11-2.3.0.jar' -Xms1024m -Xmx1024m -Dspark.driver.bindAddress=10.244.2.38 org.apache.spark.examples.SparkPi
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/fs/FSDataInputStream
        at org.apache.spark.SparkConf.loadFromSystemProperties(SparkConf.scala:75)
        at org.apache.spark.SparkConf.<init>(SparkConf.scala:70)
        at org.apache.spark.SparkConf.<init>(SparkConf.scala:57)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:922)
        at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:921)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:921)
        at org.apache.spark.examples.SparkPi$.main(SparkPi.scala:31)
        at org.apache.spark.examples.SparkPi.main(SparkPi.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.fs.FSDataInputStream
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 9 more
[root@k8s-master ~]#_

**Comment by thbeh** [comment]
I built from release distribution image.

**Comment by liyinan926** [comment]
Do you have any custom jars added into your image? Can you give the commands you used to build your image? I'm assuming you downloaded a distribution from http://spark.apache.org/downloads.html?

**Comment by thbeh** [comment]
Yes I downloaded the distribution from http://spark.apache.org. this is my Dockerfile, the only changes I made was adding core-site.xml and aws related jars to support S3. 

FROM openjdk:8-alpine

ARG spark_jars=jars
ARG img_path=kubernetes/dockerfiles
ENV HADOOP_VERSION "hadoop-2.8.4"
ENV TPCDS_VERSION "master"
ENV EXAMPLES_VERSION "0.2.0"
ENV AWS_HADOOP_VERSION "3.1.0"

RUN set -ex && \
    apk upgrade --no-cache && \
    apk add --no-cache bash tini libc6-compat git curl && \
    mkdir -p /opt/spark && \
    mkdir -p /opt/spark/work-dir \
    mkdir -p /opt/hadoop && \
    mkdir -p /opt/tpcds-kit && \
    touch /opt/spark/RELEASE && \
    rm /bin/sh && \
    ln -sv /bin/bash /bin/sh && \
    chgrp root /etc/passwd && chmod ug+rw /etc/passwd

# Install hadoop
RUN curl -s http://www-eu.apache.org/dist/hadoop/common/$HADOOP_VERSION/$HADOOP_VERSION.tar.gz | tar -xzvf - -C /tmp/ && \
    mv /tmp/$HADOOP_VERSION/* /opt/hadoop/

#RUN curl http://central.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.8.4/hadoop-aws-2.8.4.jar -o /opt/spark/aws-java-sdk-1.7.4.jar && \
#    curl http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar -o /opt/spark/httpclient-4.5.3.jar && \
#    curl http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.11.234/aws-java-sdk-core-1.11.234.jar -o /opt/spark/aws-java-sdk-core-1.11.234.jar && \
#    curl http://central.maven.org/maven2/com/amazonaws/aws-java-sdk/1.11.234/aws-java-sdk-1.11.234.jar -o /opt/spark/aws-java-sdk-1.11.234.jar && \
#    curl http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-kms/1.11.234/aws-java-sdk-kms-1.11.234.jar -o /opt/spark/aws-java-sdk-kms-1.11.234.jar && \
#    curl http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.11.234/aws-java-sdk-s3-1.11.234.jar -o /opt/spark/aws-java-sdk-s3-1.11.234.jar


COPY ${spark_jars} /opt/spark/jars
COPY bin /opt/spark/bin
COPY sbin /opt/spark/sbin
COPY conf /opt/spark/conf
COPY ${img_path}/spark/entrypoint.sh /opt/
COPY examples /opt/spark/examples
COPY data /opt/spark/data
COPY ${img_path}/spark/core-site.xml /opt/hadoop/etc/hadoop/
COPY ${img_path}/spark/tools /opt/tpcds/

ENV SPARK_HOME /opt/spark
ENV PATH $PATH:${SPARK_HOME}/bin
ENV HADOOP_HOME /opt/hadoop
ENV PATH $PATH:${HADOOP_HOME}/bin

RUN curl http://central.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.8.4/hadoop-aws-2.8.4.jar -o /opt/spark/jars/hadoop-aws-2.8.4.jar && \
    curl http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar -o /opt/spark/jars/httpclient-4.5.3.jar && \
    curl http://central.maven.org/maven2/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar -o /opt/spark/jars/joda-time-2.9.9.jar && \
    curl http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.11.234/aws-java-sdk-core-1.11.234.jar -o /opt/spark/jars/aws-java-sdk-core-1.11.234.jar && \
    curl http://central.maven.org/maven2/com/amazonaws/aws-java-sdk/1.11.234/aws-java-sdk-1.11.234.jar -o /opt/spark/jars/aws-java-sdk-1.11.234.jar && \
    curl http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-kms/1.11.234/aws-java-sdk-kms-1.11.234.jar -o /opt/spark/jars/aws-java-sdk-kms-1.11.234.jar && \
    curl http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.11.234/aws-java-sdk-s3-1.11.234.jar -o /opt/spark/jars/aws-java-sdk-s3-1.11.234.jar

WORKDIR /opt/spark/work-dir

ENTRYPOINT [ "/opt/entrypoint.sh" ]

**Comment by thbeh** [comment]
Will try your suggestions but I did this in spark-env.sh - export SPARK_DIST_CLASSPATH=$(hadoop classpath) with same error...

**Comment by thbeh** [comment]
It still spilling out that error.

**Comment by thbeh** [comment]
I have also seen the entrypoint.sh have changed in v.2.3.0 and https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/entrypoint.sh which I believe is v2.4.0
So I reset and change to use v2.4.0 instead?

**Comment by liyinan926** [comment]
You might need to add your `$HADOOP_HOME/jars/*` to `SPARK_PATH`.

**Comment by mrow4a** [comment]
@thbeh Please note that `hadoop-aws` https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/2.7.6 is with compiled dependencies `com.amazonaws » aws-java-sdk | 1.7.4` and `org.apache.hadoop » hadoop-common | 17.6`, while https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws/3.1.0 uses much newer versions.

**Comment by thbeh** [comment]
I am currently on k8s v1.9.2, that should still be good to use spark-operator?

**Comment by mrow4a** [comment]
@thbeh Yes, it should be fine - this might allow you to use webhooks (if enabled in the cluster). Did you happen to solve the issue, so we can close the ticket? For other topic you can reach more people at [#spark-operator channel](https://kubernetes.slack.com/messages/CALBDHMTL) and [#sig-big-data channel](https://kubernetes.slack.com/messages/C0ELB338T)

**Comment by thbeh** [comment]
I have not tested the last couple of comments but I will close this ticket and if any further issues will open another. Thanks all.
