### ISSUE TITLE
How to customize spark ui Service - (From Node Port to Cluster IP/ Node Port to LoadBalancer)

### ISSUE THREAD

**Issue by deveshk0** [GoogleCloudPlatform/spark-on-k8s-operator#240]
`},
			Selector: map[string]string{
				config.SparkAppNameLabel: app.Name,
				config.SparkAppIDLabel:   appID,
				sparkRoleLabel:           sparkDriverRole,
			},
			Type: apiv1.ServiceTypeNodePort,`

This particular code hard binds the service to node port.
Can we add any customization for this.

**Comment by liyinan926** [comment]
Yes, we can make it configurable.

**Comment by shensonj** [comment]
@liyinan926 I have got following service available after deploying "windower-app" spark application in kubernetes using spark operator. What is the URL I should use to access spark UI?

[root@rtanalytics opt]# kubectl describe svc windower-app-ui-svc
Name:              windower-app-ui-svc
Namespace:         nsp
Labels:            sparkoperator.k8s.io/app-name=windower-app
                   sparkoperator.k8s.io/submission-id=8c5afbcc-eb13-46ea-a112-f06e55f39d11
Annotations:       <none>
Selector:          spark-role=driver,sparkoperator.k8s.io/app-name=windower-app
Type:              ClusterIP
IP:                10.100.125.48
Port:              spark-driver-ui-port  4045/TCP
TargetPort:        4045/TCP
Endpoints:         192.169.80.143:4045
Session Affinity:  None
Events:            <none>
