### ISSUE TITLE
controller did not follow classic `controller` mode

### ISSUE THREAD

**Issue by u2takey** [GoogleCloudPlatform/spark-on-k8s-operator#246]
refer:
https://github.com/kubernetes/sample-controller

key point:
should follow logic: event -> queue -> controller get `actual state` to `desired state`
`Do not` simply depend on event (add/update/delete), event is `unreliable`, for example: if controller restart, update/add/delete event loss ->  actual state may never become desired state.

**Comment by u2takey** [comment]
maybe related: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/199

**Comment by liyinan926** [comment]
> maybe related: #199

Yes.
