### ISSUE TITLE
Better integration with Stackdriver Monitoring

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#252]
* [x] Automatic configuration for exposing internal Spark metrics to Prometheus: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/255.

**Comment by andrewgdavis** [comment]
Is there a diagram that explains how this works?  Is this just exposing the metrics via a port that can be scraped by prometheus ... 

or do the metrics get aggregated and pushed back to the operator (which is scraped by prometheus)... 

or does it make more sense to make use of the prometheus gateway (pods in a completed state that can no longer be scraped)
