### ISSUE TITLE
 Failed to list *v1alpha1.SparkApplication

### ISSUE THREAD

**Issue by dailong** [GoogleCloudPlatform/spark-on-k8s-operator#258]
![image](https://user-images.githubusercontent.com/5086821/44080556-f93fb274-9fde-11e8-8abb-91a8bf8d8d50.png)
K8s version:
![image](https://user-images.githubusercontent.com/5086821/44080595-18a561e0-9fdf-11e8-9893-575a825cf790.png)

How to solve this problem? thank you.

**Comment by mrow4a** [comment]
Can you paste error you got? ```Cores: Read string: expects ' or n, parsing 1500...," at...``` ?

Your SparkApplication definition is somehow wrong.

**Comment by liyinan926** [comment]
As @mrow4a said, there's something wrong with your `SparkApplication` specification that failed validation on the API server. Can you paste your `SparkApplication` spec here?

**Comment by dailong** [comment]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml

**Comment by dailong** [comment]
apiVersion: "sparkoperator.k8s.io/v1alpha1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "mesosphere/spark:2.3.1-2.2.1-2-hadoop-2.7"
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/dist/examples/jars/spark-examples_2.11-2.2.1.jar"
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.3.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.3.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  restartPolicy: Never

Thank you for responding so quickly @mrow4a @liyinan926

**Comment by liyinan926** [comment]
Can you paste the error text here?

**Comment by liyinan926** [comment]
Is the image you used built following the instruction at http://spark.apache.org/docs/latest/running-on-kubernetes.html#docker-images?

**Comment by dailong** [comment]
After I rebuild my image at http://spark.apache.org/docs/latest/running-on-kubernetes.html#docker-images, there's a  problem:
spark-operator logs:
 
![tim 20180816101506](https://user-images.githubusercontent.com/5086821/44183379-62f37700-a13d-11e8-9ace-cf59d341b81e.jpg)

spark-pi logs:
![tim 20180816095835](https://user-images.githubusercontent.com/5086821/44183405-70106600-a13d-11e8-9b5d-d201a9e5b00b.jpg)

@liyinan926

**Comment by liyinan926** [comment]
Which version of the operator are you running? It certainly looks outdated from the operator logs. We no longer use an initializer. Can you following the quick start guide to install the latest version of the operator and try running `examples/spark-pi.yaml`?

**Comment by mrow4a** [comment]
@dailong you try to use Spark 2.4.0-SNAPSHOT and examples at location `jars/spark-examples_2.11`, are you sure they exists there? Your job cannot find application jar

**Comment by dailong** [comment]
I use https://hub.docker.com/r/liyinan926/spark-operator:v2.3.0 @liyinan926

**Comment by mrow4a** [comment]
@dailong you cannot use Spark Operator in version 2.3.0 with drivers/executors being 2.4.0-SNAPSHOT I think

**Comment by dailong** [comment]
Thand you @mrow4a ,I  will  try to build spark 2.3

**Comment by dailong** [comment]
After I builded  spark 2.3  docker image,there's new problem:
![tim 20180816190734](https://user-images.githubusercontent.com/5086821/44205161-ff426b80-a187-11e8-8957-893fded4f33a.jpg)

**Comment by liyinan926** [comment]
How did you build Spark and the image? It looks like you didn't enable the Kubernetes mode when building Spark.

**Comment by dailong** [comment]
Do as you say.I solved this problem,Thank you very much  @mrow4a  @liyinan926
