### ISSUE TITLE
Image Pull Secret Not Wroking

### ISSUE THREAD

**Issue by deveshk0** [GoogleCloudPlatform/spark-on-k8s-operator#260]
If I use private registry for the image and use Kubernetes secret to access the image. It is giving no basic auth error while getting image manifest.

**Comment by liyinan926** [comment]
Which image of Spark are you using? The config property for specifying image pull secret is only available in the master branch of Spark.

**Comment by liyinan926** [comment]
Closing this. If you find a different cause please reopen it.
