### ISSUE TITLE
Support for injecting sidecar containers

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#269]
Sidecar containers are useful for things like exporting custom metrics to Stackdriver and running custom logging agents that allows adding application-specific labels to log records.

**Comment by skonto** [comment]
I am current using the pod template PR to do so for prometheus metrics. It is far better than running the exporter within the same jvm.

**Comment by skonto** [comment]
Just open a port and some annotations:

apiVersion: v1
Kind: Pod
metadata:
  labels:
    template-label-key: driver-template-label-value
spec:
  containers:
  - name: test-driver-container
    image: skonto/spark:k8s-template
    ports:
    - containerPort: 9100
```
./bin/spark-submit \
--master k8s://http://127.0.0.1:8001 \
--deploy-mode cluster \
--name spark-pi \
--class org.apache.spark.examples.SparkPi \
--conf spark.kubernetes.driver.annotation.prometheus.io/port=9100 \
--conf spark.kubernetes.driver.annotation.prometheus.io/scrape=true \
--conf spark.executor.instances=2 \
--conf spark.sql.streaming.metricsEnabled=true \
--conf spark.kubernetes.container.image=skonto/spark:k8s-metrics \
--conf "spark.executor.extraJavaOptions=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8090 -Dcom.sun.management.jmxremote.rmi.port=8091 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -javaagent:/jmx_prometheus_javaagent-0.10.jar=9100:/spark-prom-exporter.yml" \
--conf spark.kubernetes.driver.podTemplateFile=/path/to/pod.yaml \
--conf "spark.driver.extraJavaOptions=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8090 -Dcom.sun.management.jmxremote.rmi.port=8091 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -javaagent:/jmx_prometheus_javaagent-0.10.jar=9100:/spark-prom-exporter.yml" \
--conf spark.metrics.conf.*.sink.jmx.class=org.apache.spark.metrics.sink.JmxSink \
local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0-SNAPSHOT.jar 1000000
```

**Comment by liyinan926** [comment]
OK, this still requires the JMX exporter, which is what #266 does. A sidecar container running a custom exporter is indeed needed if users want to export the metrics as custom metrics to Stackdriver.

**Comment by skonto** [comment]
Yes maybe I was misunderstood I dont remove the jmx exporter depndency just saying Im using that PR to expose the ports required.

**Comment by liyinan926** [comment]
Got it. Makes sense. This should definitely leverage that PR for adding sidecars when it's merged and released. In the meanwhile, I probably will use the mutating webhook for Spark 2.4 and below.

**Comment by skonto** [comment]
You mean via the operator?

**Comment by liyinan926** [comment]
Yes, the mutating webhook run by the operator is needed to add sidecar containers for Spark 2.3 and 2.4. But in the future, that PR will be used instead for future Spark releases.

**Comment by liyinan926** [comment]
This is now supported through #478.
