### ISSUE TITLE
How to generate java client code?

### ISSUE THREAD

**Issue by dailong** [GoogleCloudPlatform/spark-on-k8s-operator#270]
I want to  generate java client code and models,What shall I do? Thank you~

**Comment by liyinan926** [comment]
It seems an open api spec is needed to generate Java client, and this open api spec needs to be generated first. I'm not familiar with it.

**Comment by deveshk0** [comment]
I have written some code on top kubernetes java client to submit spark job i will commit that and share the link here.

**Comment by liyinan926** [comment]
Cool. Thanks, @deveshk0 !

**Comment by deveshk0** [comment]
@liyinan926  I didn't use any tool for this. I have manually created these class by looking into **type.go** of spark operator  keeping Kubernetes java client as base reference.

**Comment by deveshk0** [comment]
Since **types.go** is now updated with ** MonitoringSpec and PrometheusSpec** so i have to add those things into java client also.

**Comment by ligao101** [comment]
From Java side I am using this as example to talk to CRD:
https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java

The contracts are basically dynamically encoded nested maps.

**Comment by talgos1** [comment]
I'm trying to auto-generate the java client code using the official auto generator but it seems not to work properly (for instance: 1. io.k8s group prefix is filtered out, 2. SparkApplication model is generated as an object)
Does anyone manage to solve this?
https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md
