### ISSUE TITLE
OOMKilled

### ISSUE THREAD

**Issue by dailong** [GoogleCloudPlatform/spark-on-k8s-operator#274]
![image](https://user-images.githubusercontent.com/5086821/44772896-b506b480-aba1-11e8-8539-f41ab2a396b8.png)
![image](https://user-images.githubusercontent.com/5086821/44772957-e3848f80-aba1-11e8-8243-938f76101bef.png)

There is enough memory already. Why did this error happen?
@liyinan926  @mrow4a  Thank you~

**Comment by mrow4a** [comment]
Long story short: 

Kubelet on each Kubernetes Node monitors memory and disk available to the Node. Kubelet prevents node unstability by detecting MemoryPressure or System Out Of Memory  and reclaiming resources from running containers (OOMKilled errors)

With Spark 2.4 there is spark.kubernetes.memoryOverheadFactor which allocates memory for off-heap memory, non-JVM processes (e.g. in case of Python higher limit) and processes required for operation of container. Apart from Memory Overhead, OOMKills are coming from spark.memory.fraction and spark.memory.storageFraction.

![image](https://user-images.githubusercontent.com/13368647/44791393-d10a5600-aba1-11e8-9c86-448da8130bca.png)

**Comment by dailong** [comment]
![image](https://user-images.githubusercontent.com/5086821/44825856-10d34b00-ac3f-11e8-903c-f8a1a7204cce.png)
Another problem is that Volumn is not mounted
![5va wpfp da0b3oyk t4849](https://user-images.githubusercontent.com/5086821/44826015-b7b7e700-ac3f-11e8-8cb7-2b8d08713f21.png)

**Comment by liyinan926** [comment]
> Another problem is that Volumn is not mounted

Volume mounting requires the use of the mutating admission webhook. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#using-the-mutating-admission-webhook.

**Comment by dailong** [comment]
![image](https://user-images.githubusercontent.com/5086821/44834259-32462e00-ac63-11e8-9305-a4255cd4be91.png)
What is the cause of this error? @liyinan926 Thanks

**Comment by mrow4a** [comment]
@dailong try setting `spark.kubernetes.memoryOverheadFactor` to different value. Do you have any other workload running in that node?

**Comment by liyinan926** [comment]
> What is the cause of this error? @liyinan926 Thanks

It seems you have more than volume that are requested to be mounted under `/tmp`. Looks like you have `local:///tmp/main.py` and additionally an `emptyDir` volume mounted to `/tmp`.

**Comment by dailong** [comment]
@mrow4a  I try setting spark.kubernetes.memoryOverheadFactor  to 0.4, 0.5, 0.6,0.8,But it was the same problem. I only have one Node ,Not many Pod runs,The others can run correctly.

**Comment by dailong** [comment]
![image](https://user-images.githubusercontent.com/5086821/44920686-2fd2f980-ad73-11e8-80e7-fbbd2c8ac8e3.png)

![image](https://user-images.githubusercontent.com/5086821/44920669-247fce00-ad73-11e8-924a-e28627172348.png)

I don't understand the "Duplicate value: "test-volume", spec.containers[0].volumeMounts[4].mountPath: Invalid value: "/tmp": must be unique ",
I want to mount the main python file into the container for execution. What should I do? Looking forward to your reply~ @mrow4a @liyinan926

**Comment by liyinan926** [comment]
So the main py file and `gmm.py` are both supposed to be mounted into the pods? Can you paste your complete `SparkApplication` spec here instead of using screenshots?
