### ISSUE TITLE
Implement sparkctl: a cmd tool for working with the operator

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#29]

**Comment by liyinan926** [comment]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/sparkctl

**Comment by foxish** [comment]
Question - we went from using an imperative cmdline, spark-submit to a declarative specification through the operator. What's additional value are we gaining from another utility? Would be good to have a list of that and understand what problem this solves.

**Comment by liyinan926** [comment]
`sparkctl` is basically a `kubectl` for Spark. Additionally to making it easier to create, delete, list, check status of, and fetch logs of Spark applications, it has the following features:
* Staging local dependencies (currently only staging to GCS is supported) automatically as part of `sparkctl create`.
* Creating a ConfigMap from local `HADOOP_CONF_DIR` and adding it to the driver and executor pods.
* Forwarding from a local port to a remote port for easy access of the Spark web UI. This can be done using `kubectl`, but `sparkctl` is much easier to use in this regard.
