### ISSUE TITLE
Spark 2.4 RC support

### ISSUE THREAD

**Issue by ligao101** [GoogleCloudPlatform/spark-on-k8s-operator#306]
Hi,
I am having trouble to make the build work using Spark 2.4 RC2/3 tag from the upstream. Does anyone has a working image of Spark 2.4 RC2/3 with Spark Operator?

Thanks!

**Comment by liyinan926** [comment]
I can help build an image based upon 2.4 rc3 and update here.

**Comment by mrow4a** [comment]
@ligao101 yes, I managed to run on RC2. What is the problem?

**Comment by liyinan926** [comment]
@ligao101 Are you running into issue with `go generate`? If so, the issue has been resolved, and please rebase to the latest master to give it another try.

**Comment by liyinan926** [comment]
BTW: I just built and pushed the following images:
`gcr.io/spark-operator/spark-operator:v2.4.0-rc3-v1alpha1`
`gcr.io/spark-operator/spark-operator:v2.4.0-rc3-v1alpha1-py` with PySpark support

**Comment by ligao101** [comment]
thanks. It is working fine for me now. Thanks!
