### ISSUE TITLE
Add Operator Integration Tests 

### ISSUE THREAD

**Issue by skonto** [GoogleCloudPlatform/spark-on-k8s-operator#307]
AFAIK there are no integration tests for testing Operator's functionality.
We could test against minikube.

**Comment by liyinan926** [comment]
#123 was supposed to add the basic setup for integration/e2e tests, but was never really brought to completion.

**Comment by skonto** [comment]
@liyinan926 good to know, is it ok to work on this? @foxish?

**Comment by skonto** [comment]
Thanx :)

**Comment by yuchaoran2011** [comment]
@liyinan926 This issue can be closed. We'll open new issues for specific integration tests we want to add.
