### ISSUE TITLE
Does SparkOperator support rebooting stateful spark jobs?

### ISSUE THREAD

**Issue by ancientsea** [GoogleCloudPlatform/spark-on-k8s-operator#345]
Does SparkOperator support rebooting stateful spark jobs? And is it possible to just use `spark-submit` and k8s [Deployments](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/) to submit and refresh those spark jobs?

**Comment by liyinan926** [comment]
What you meant by `rebooting`? Did you mean `restarting` an application on failures for example for streaming applications? If so, yes, the operator allows you to configure a `RestartPolicy`.

**Comment by ancientsea** [comment]
> What you meant by `rebooting`? Did you mean `restarting` an application on failures for example for streaming applications? If so, yes, the operator allows you to configure a `RestartPolicy`.

Nope, not on failures. I mean can we proactively update the spark job image and reboot the spark job while still keeping the checkpoint data from the previous spark job? Thanks @liyinan926

**Comment by liyinan926** [comment]
By `proactively update the spark job image` did you mean updating the container image of your job?

**Comment by ancientsea** [comment]
> By `proactively update the spark job image` did you mean updating the container image of your job?

Yes

**Comment by liyinan926** [comment]
We do support restart on spec updates. So if you update the image of your `SparkApplication` spec, the operator will try to kill the current run and re-start it. Checkpointing is up to your application.

**Comment by ancientsea** [comment]
> We do support restart on spec updates. So if you update the image of your `SparkApplication` spec, the operator will try to kill the current run and re-start it. Checkpointing is up to your application.

Thanks @liyinan926 ! Just to confirm, I can also use the the command below to restart the spark jobs (deleting the spark executors not the driver):

`kubectl -n <namespace> delete pods -l spark-job-app=<app-name>`

However, this won't keep the checkpointing data, right?

While using the `SparkApplication` in the Operator, it will use the previous checkpointing data, right?

**Comment by liyinan926** [comment]
How you restart a job with a different image without deleting and restarting your driver pod? Checkpointing is totally up to the applications in Spark on k8s. The k8s scheduler backend is not involved in checkpointing at all.

**Comment by liyinan926** [comment]
> Can I know more about Checkpointing is totally up to the applications in Spark on k8s.? When we delete the spark job pods, are these checkpointing data will be deleted as well? Is there a way to preserve these data while updating their images and restart them?

It all depends on where your checkpoint data is stored. If it's stored on HDFS, yes, the data is preserved even if the driver pod is restarted. If the checkpoint data is stored on some persistent volume, again, the data is preserved in case of driver restart. I assume you were talking about Spark streaming checkpoint data, right?

**Comment by ancientsea** [comment]
> > Can I know more about Checkpointing is totally up to the applications in Spark on k8s.? When we delete the spark job pods, are these checkpointing data will be deleted as well? Is there a way to preserve these data while updating their images and restart them?
> 
> It all depends on where your checkpoint data is stored. If it's stored on HDFS, yes, the data is preserved even if the driver pod is restarted. If the checkpoint data is stored on some persistent volume, again, the data is preserved in case of driver restart. I assume you were talking about Spark streaming checkpoint data, right?

Yes. Ah, I see your point. I guess we need to figure out a way to handle the data persistence by ourselves (will try HDFS). BTW, last question, I read the document on https://spark.apache.org/docs/latest/running-on-kubernetes.html and it seems like the official spark-k8s only supports `spark-submit` command to submit spark jobs. And there's no easy way to expand/shrink capacity or even stop the existing pods. (We'll have to kill the driver pod by using `kubectl` command and resubmit spark jobs). While using the Operators, we can easily achieve these, right? And are the Operators also stop the driver pod each time it tries to expand/shrink the capacity of the spark job pods? Thanks!

**Comment by liyinan926** [comment]
> Yes. Ah, I see your point. I guess we need to figure out a way to handle the data persistence by ourselves (will try HDFS). BTW, last question, I read the document on https://spark.apache.org/docs/latest/running-on-kubernetes.html and it seems like the official spark-k8s only supports spark-submit command to submit spark jobs. And there's no easy way to expand/shrink capacity or even stop the existing pods. (We'll have to kill the driver pod by using kubectl command and resubmit spark jobs). While using the Operators, we can easily achieve these, right? And are the Operators also stop the driver pod each time it tries to expand/shrink the capacity of the spark job pods? Thanks!

Yes, the operator gives you a way to declaratively specify your job and is able to handle lifecycle management for your job. When you use the operator, the life time of your job is tied to your `SparkApplication` resource. When you scale your job up/down to use more/less executors, the operator will handles job restart for you.

**Comment by ancientsea** [comment]
> > Yes. Ah, I see your point. I guess we need to figure out a way to handle the data persistence by ourselves (will try HDFS). BTW, last question, I read the document on https://spark.apache.org/docs/latest/running-on-kubernetes.html and it seems like the official spark-k8s only supports spark-submit command to submit spark jobs. And there's no easy way to expand/shrink capacity or even stop the existing pods. (We'll have to kill the driver pod by using kubectl command and resubmit spark jobs). While using the Operators, we can easily achieve these, right? And are the Operators also stop the driver pod each time it tries to expand/shrink the capacity of the spark job pods? Thanks!
> 
> Yes, the operator gives you a way to declaratively specify your job and is able to handle lifecycle management for your job. When you use the operator, the life time of your job is tied to your `SparkApplication` resource. When you scale your job up/down to use more/less executors, the operator will handles job restart for you.

Great, thanks so much!!!

**Comment by liyinan926** [comment]
Closing this. Let us know if you have any questions through the Slack channel at https://kubernetes.slack.com/messages/CALBDHMTL.
