### ISSUE TITLE
How to specify number of cores and memory for worker containers 

### ISSUE THREAD

**Issue by alokgogate** [GoogleCloudPlatform/spark-on-k8s-operator#354]
How do i specify the number of cores to use and the memory for the worker containers through connection from jupyter notebook in client mode?

thanks in advance!

**Comment by liyinan926** [comment]
The spark operator doesn't support notebook like applications in client mode yet. You might want to check out the Jupyter notebook documentation.

**Comment by liyinan926** [comment]
Closing. Feel free to reopen if you have more questions.
