### ISSUE TITLE
Failed to run spark-pi example following the guide.

### ISSUE THREAD

**Issue by ringtail** [GoogleCloudPlatform/spark-on-k8s-operator#355]
version: kubernetes 1.11.2 
branch: master 

describe SparkApplication 
```
Status:
  Application State:
    Error Message:  failed to run spark-submit for SparkApplication default/spark-pi: exit status 1
    State:          FAILED
  Driver Info:
  Last Submission Attempt Time:  2018-12-23T17:42:21Z
  Submission Attempts:           1
  Termination Time:              <nil>
Events:
  Type     Reason                            Age   From            Message
  ----     ------                            ----  ----            -------
  Normal   SparkApplicationAdded             8m5s  spark-operator  SparkApplication spark-pi was added, Enqueuing it for submission
  Warning  SparkApplicationSubmissionFailed  8m4s  spark-operator  failed to submit SparkApplication spark-pi: failed to run spark-submit for SparkApplication default/spark-pi: exit status 1
  Warning  SparkApplicationFailed            8m4s  spark-operator  SparkApplication spark-pi terminated with state: FAILED
```
operator logs
```
I1223 17:42:21.993391       1 controller.go:254] Ending processing key: "default/spark-pi"
I1223 17:42:21.993582       1 controller.go:207] SparkApplication default/spark-pi was updated, enqueueing it
I1223 17:42:21.993618       1 controller.go:247] Starting processing key: "default/spark-pi"
I1223 17:42:21.993633       1 controller.go:509] Trying to update SparkApplication default/spark-pi, from: [{ 2018-12-23 17:42:21 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {FAILED failed to run spark-submit for SparkApplication default/spark-pi: exit status 1} map[] 0 1}] to [{ 2018-12-23 17:42:21 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {FAILED failed to run spark-submit for SparkApplication default/spark-pi: exit status 1} map[] 0 1}]
```

**Comment by liyinan926** [comment]
Which image of the operator are you using?

**Comment by ringtail** [comment]
I use the master branch and no more useful logs. The logs are repeated again and again like this.
```
I1223 17:42:21.993391       1 controller.go:254] Ending processing key: "default/spark-pi"
I1223 17:42:21.993582       1 controller.go:207] SparkApplication default/spark-pi was updated, enqueueing it
I1223 17:42:21.993618       1 controller.go:247] Starting processing key: "default/spark-pi"
I1223 17:42:21.993633       1 controller.go:509] Trying to update SparkApplication default/spark-pi, from: [{ 2018-12-23 17:42:21 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {FAILED failed to run spark-submit for SparkApplication default/spark-pi: exit status 1} map[] 0 1}] to [{ 2018-12-23 17:42:21 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } {FAILED failed to run spark-submit for SparkApplication default/spark-pi: exit status 1} map[] 0 1}]
```
and the yaml is the `spark-pi` in examples folder

**Comment by liyinan926** [comment]
Looks like you enabled `V2` logs. The line starting with `Trying to update` just indicates the operator was trying to perform a status update of your `SparkApplication` object. Your application failed with `failed to run spark-submit...`. Have you setup RBAC for the operator?

**Comment by kz33** [comment]
I also have the same problem. @ringtail 
I checke the official documents of spark on k8s for RBAC:  http://spark.apache.org/docs/latest/running-on-kubernetes.html
I execute the following commands to solve this problem and you can try i:

1) `kubectl create serviceaccount spark`
2) `kubectl create clusterrolebinding spark-role --clusterrole=edit --serviceaccount=default:spark --namespace=default`

**Comment by liyinan926** [comment]
Yes, the Spark driver pod needs a custom service account with permission to create/get/list/delete pods and configmaps, in most clusters. You can also do `kubectl apply -f manifest/spark-rbac.yaml`, which will create a service account named `spark` in the default namespace with the appropriate permissions.

**Comment by ringtail** [comment]
@liyinan926 I think that's the not root cause. The api server use a self-sign ca and fabric8 can not pass the TLS verify. So I use the annotations below.
```
  sparkConf:
    spark.kubernetes.authenticate.driver.caCertFile: "/etc/kubernetes/pki/ca.crt"
    spark.kubernetes.authenticate.submission.caCertFile: "/etc/kubernetes/pki/ca.crt"
``` 
It works. But I don't think it's the best practice.if i set `caCertFile` then the `ServiceAccount` can not be specified.(https://spark.apache.org/docs/2.3.1/running-on-kubernetes.html)  
```
Service account that is used when running the driver pod. The driver pod uses this service account when requesting executor pods from the API server. Note that this cannot be specified alongside a CA cert file, client key file, client cert file, and/or OAuth token.
--



```

**Comment by ringtail** [comment]
@liyinan926 I found the root cause. The ca file in my cluster contains two more white space lines. And the serviceaccount can not be handled by fabric8 kubernetes client.

**Comment by mrow4a** [comment]
@ringtail I had the same issue some time ago (Openstack). Certificates need to be trimmed.

**Comment by nsaboo** [comment]
So, how to overcome this issue @ringtail ?

We are unable to spawn executors, can you help us with this issue.

**Comment by ringtail** [comment]
> So, how to overcome this issue @ringtail ?
> 
> We are unable to spawn executors, can you help us with this issue.

Could you check the serviceaccount ca.crt content. The correct ca.crt can't contains blank lines.
