### ISSUE TITLE
Unable to load in-cluster configuration with custom Spark Operator

### ISSUE THREAD

**Issue by roksolana-d** [GoogleCloudPlatform/spark-on-k8s-operator#357]
I have built a custom Spark operator using Developer-guide. I have successfully built a binary executable called spark-operator but when I tried to run it with `./spark-operator` I've got an error (stack trace is below). I suspect that this error happens because I am using minikube for Kubernetes. How can I set up these environment values for the operator to work properly?

Error stack trace:

```
F1227 15:53:06.681520    4240 main.go:79] unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
goroutine 1 [running]:
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.stacks(0xc000349400, 0xc0003a6000, 0x97, 0xec)
	$GOPATH/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:769 +0xd4
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.(*loggingT).output(0x1ff30a0, 0xc000000003, 0xc00014af20, 0x1f6f744, 0x7, 0x4f, 0x0)
	$GOPATH/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:720 +0x329
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.(*loggingT).printDepth(0x1ff30a0, 0xc000000003, 0x1, 0xc00010fed0, 0x1, 0x1)
	$GOPATH/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:646 +0x129
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.(*loggingT).print(0x1ff30a0, 0x3, 0xc00010fed0, 0x1, 0x1)
	$GOPATH/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:637 +0x5a
github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog.Fatal(0xc00010fed0, 0x1, 0x1)
	$GOPATH/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/vendor/github.com/golang/glog/glog.go:1128 +0x53
main.main()
	$GOPATH/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator/main.go:79 +0x144
```

**Comment by liyinan926** [comment]
It seems to me that there's something wrong with your minikube instance. See this https://medium.com/@pczarkowski/the-kubernetes-api-call-is-coming-from-inside-the-cluster-f1a115bd2066. The author of this post also used minikube and did see the environment variables.

**Comment by roksolana-d** [comment]
I reinstalled Minikube and configured everything again. For some reason, Spark-operator is created from the Dockerfile but this error I get when I run go binary which I've built locally.

**Comment by liyinan926** [comment]
I don't quite get what you mean by `created from the Dockerfile but this error I get when I run go binary which I've built locally`. Were you trying to run it locally on your machine or in minikube?

**Comment by roksolana-d** [comment]
I run `eval $(minikube docker-env)` to get Minikube context and then build my Docker image and execute it. But when I get Minikube context and try to build a binary execution from Go sources I get this config error.

**Comment by liyinan926** [comment]
Has the issue been resolved?

**Comment by roksolana-d** [comment]
I am not sure, as this error only appears when I build the operator from binary Go executable. With Dockerfile it works just fine
