### ISSUE TITLE
Spark 2.4 worker containers stuck in terminating state and jobs dont complete when in running state

### ISSUE THREAD

**Issue by alokgogate** [GoogleCloudPlatform/spark-on-k8s-operator#360]
Hello,

The spark worker containers spawned remain in terminating state for a long time. Also which i create a container the task such as  reading a small parquet file doesnt complete. This happens abruptly, it works one day and the other it doesnt. Any clue as to what may cause it to not work.

Thanks!

**Comment by liyinan926** [comment]
Do you mean the Spark executor pods or the workers in Spark standalone?

**Comment by alokgogate** [comment]
The spark Executor pods

**Comment by alokgogate** [comment]
Also when i run some long running spark job, the jobs doesn't get completed and the executor pods also get destroyed and new ones spawn back up again
