### ISSUE TITLE
error: unable to recognize "examples/spark-pi.yaml": no matches for kind "SparkApplication" in version "sparkoperator.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by ancientsea** [GoogleCloudPlatform/spark-on-k8s-operator#368]
Downloaded the latest operator source code and run: `kubectl apply -f examples/spark-pi.yaml` then got errors as below:

`error: unable to recognize "examples/spark-pi.yaml": no matches for kind "SparkApplication" in version "sparkoperator.k8s.io/v1beta1"`

Did I miss anything here?

PS: I installed the spark-operator today and the list of my crd is:

```
$kubectl get crd
NAME                                              AGE
scheduledsparkapplications.sparkoperator.k8s.io   4h51m
sparkapplications.sparkoperator.k8s.io            4h51m
```

And both of them are using the v1beta1 version:

```
$ kubectl describe crd scheduledsparkapplications.sparkoperator.k8s.io | grep "API Version"
API Version:  apiextensions.k8s.io/v1beta1

$ kubectl describe crd sparkapplications.sparkoperator.k8s.io  | grep "API Version"
API Version:  apiextensions.k8s.io/v1beta1
```

**Comment by liyinan926** [comment]
The API version you showed is the version of the `CustomResourceDefinition` API. The version of the `SparkApplication` API has been updated to `v1beta1`. Please delete the CRDs named `sparkapplications.sparkoperator.k8s.io` and `scheduledsparkapplications.sparkoperator.k8s.io`, and then re-install the operator, which will install the `v1beta1` version of the CRDs.

**Comment by ancientsea** [comment]
Right, thanks. BTW, when I run `$ kubectl describe sparkapplication spark-pi`, I didn't see the events as expected. It's empty:

```
$ k describe sparkapplication spark-pi
Name:         spark-pi
Namespace:    ***
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"sparkoperator.k8s.io/v1beta1","kind":"SparkApplication","metadata":{"annotations":{},"name":"spark-pi","namespace":"***"},"...
API Version:  sparkoperator.k8s.io/v1beta1
Kind:         SparkApplication
Metadata:
  ***
Spec:
  ***
Events:      <none>
```

Everything else looks normal. Did I miss anything here?

**Comment by liyinan926** [comment]
Is the driver pod created and running?

**Comment by ancientsea** [comment]
What's the name of the driver pod? I cannot find anything related to the spark operator or spark-pi. However, I can see the sparkApplication was been created:

```
$ kubectl get sparkapplications
NAME       AGE
spark-pi   78m
```

**Comment by liyinan926** [comment]
I meant the Spark driver pod that should have been created for your `SparkApplication`. The name of the driver pod is after your `SparkApplication` name with the `driver` suffix. If you don't see the driver pod, you need to check the logs of the operator to see what's going on.

**Comment by ancientsea** [comment]
I think I followed every step in the [Quick Start Guide](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#running-the-examples) and still I cound't see the driver pod running. (as for the service account, I've tried all the service accounts end with `-spark` and still don't work)

And also, I cannot see the `status` section while running the `kubectl get sparkapplications spark-pi -o=yaml` command ( i can see all of other sections including `metadata`, `spec` and so on)

How can I check the logs of the operator?

**Comment by liyinan926** [comment]
Check the name of the pod running the operator, and do `kubectl logs <pod name>`.

**Comment by ancientsea** [comment]
Hmm, somehow the operator pods was missing in my own namespace. Now they are up:
```
$ kubectl -n $NS get pods

NAME                                             READY   STATUS      RESTARTS   AGE
amber-ocelot-sparkoperator-77ffb667f-5xzxc       1/1     Running     0          3m53s
quaffing-bronco-sparkoperator-7c96fc5c59-pst9j   1/1     Running     0          3m8s
```

Are these two the operator pods you were referring to? 

Besides, after they're up and running, I then run the `$ kubectl -n $NS apply -f examples/spark-pi.yaml` but got errors:

```
error: unable to recognize "examples/spark-pi.yaml": no matches for kind "SparkApplication" in version "sparkoperator.k8s.io/v1beta1"`
```

So what does this error mean?

**Comment by ancientsea** [comment]
OK, BTW, what's the difference between the `spark-operator` and `test-ns` namespaces? 
 
```
helm install incubator/sparkoperator --namespace spark-operator --set createSparkJobNamespace=true --set sparkJobNamespace=test-ns
```

Is the `spark-operator` used to run the operator pods and `test-ns` used to run spark applications? And should we separate the two namespaces? Thanks.

**Comment by liyinan926** [comment]
I believe the Helm chart has been updated to use a single namespace parameter `sparkJobNamespace `. That namespace is both the namespace where the operator is deployed into and the one where Spark applications are watched and run in.

**Comment by liyinan926** [comment]
Actually I was wrong. The namespace you specified using `--namespace` is the namespace where the operator gets installed into. The `sparkJobNamespace` is the namespace in which `SparkApplication`s are watched and run.

**Comment by ancientsea** [comment]
Hi @liyinan926 After I reinstall everything, it works now. Thanks.

**Comment by samarthkansal** [comment]
> The API version you showed is the version of the `CustomResourceDefinition` API. The version of the `SparkApplication` API has been updated to `v1beta1`. Please delete the CRDs named `sparkapplications.sparkoperator.k8s.io` and `scheduledsparkapplications.sparkoperator.k8s.io`, and then re-install the operator, which will install the `v1beta1` version of the CRDs.

should a reinstallation of the spark operator work ? it did not work for me. Did i miss anything

**Comment by janarthanandev** [comment]
you can try new version `apiVersion: "sparkoperator.k8s.io/v1beta2"`
