### ISSUE TITLE
Support PodPriority for driver and executors

### ISSUE THREAD

**Issue by ligao101** [GoogleCloudPlatform/spark-on-k8s-operator#375]
At the first step to bring a priority and preemption capable queuing mechanism to the operator, I'd like to propose to have the spark operator to support specifying the PodPriority for both driver and executor pods.

https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

Since the upstream Spark does not support `PodPriority` yet, thought this is a good chance to add it here first. Thoughts and ideas?

**Comment by liyinan926** [comment]
Yes, we can definitely add support for PodPriority as a first step, and particularly for drivers, which effectively adds some sort of priority support at the job level. This is straightforward to add through the mutating webhook.

**Comment by ligao101** [comment]
hi @liyinan926 I think we need to support priority for both driver and executor to make priority work well under a shared cluster environment.

when dynamic scaling is enabled on k8s, the preferred/expected behavior for different jobs would be the higher priority job should get the executor pods allocated first before lower priority jobs.

**Comment by liyinan926** [comment]
Sure, we can support both.

**Comment by ligao101** [comment]
could adding the support for `PodTemplate` be one of the approaches to implement this?

https://github.com/apache/spark/pull/22146/files

**Comment by liyinan926** [comment]
Yes, that could be one option if you are OK using a build of Spark from the master. The operator doesn't yet have a way to support specifying a template though.

**Comment by ligao101** [comment]
We will go with updating the mutating webhook since the spark master is not stable. Thanks!
