### ISSUE TITLE
Add support for configuring PodSecurityContext for driver/executors

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#382]

**Comment by baxor** [comment]
Will this be on the 2019 Roadmap?

**Comment by liyinan926** [comment]
Yes, we will work on this in the near future.

**Comment by liyinan926** [comment]
This is now supported, see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#using-pod-security-context.
