### ISSUE TITLE
Improve error reporting of failed applications

### ISSUE THREAD

**Issue by maasg** [GoogleCloudPlatform/spark-on-k8s-operator#383]
When a spark application fails at the `spark-submit` stage, the Spark Operator reports the application as failed, but provides no clues into what went wrong. 
This is an example output from a failed submission:
```json
applicationState": {
            "errorMessage": "failed to run spark-submit for SparkApplication app-connected-stuff/connected-stuff-aggregation: exit status 1",
            "state": "SUBMISSION_FAILED"
...}
```
Currently, the only way to debug these issues is to follow the following steps (*):

1.  access the SparkOperator logs
1. find the `spark-submit` launch command
1. start a shell to the SparkOperator pod
1. manually launch the complete `spark-submit` command obtained at step 1 
1. figure out what was wrong, fix, rinse, repeat

A possible approach would be to capture the output of `spark-submit` and report it through the `status` stanza in the `get sparkApplication` command.

(*) hopefully these steps help as a workaround for other people with the same issue

**Comment by liyinan926** [comment]
Will fix this with a PR that surfaces the actual error.
