### ISSUE TITLE
unable to create ingress

### ISSUE THREAD

**Issue by jyipks** [GoogleCloudPlatform/spark-on-k8s-operator#392]
I am following the quick start guide and would like to setup the ingress. I am attempting to run the following command : 

`helm install incubator/sparkoperator --namespace spark-operator --set ingress-url-format={{$appName}}.ingress.cluster.com
`

and i get the Error: failed parsing --set data: key map "}" has no value

Instructions says it can be added via cli flag. Can anyone help. 

Thanks

**Comment by liyinan926** [comment]
Looks like the Helm chart does not yet support that flag. Flag `ingress-url-format` is used by the operator. But the Helm chart needs a way of populating value for that flag with a Chart level parameter. See https://github.com/helm/charts/blob/master/incubator/sparkoperator/values.yaml.

**Comment by jyipks** [comment]
Got it, are you able to point me to instructions to install the spark operator manually so I can utilize the ingress, or hopefully helm chart will be updated soon?

**Comment by liyinan926** [comment]
We will update the Helm Chart. @yuchaoran2011.

**Comment by liyinan926** [comment]
The Helm chart has been updated to support the flag. Please check it out.

**Comment by aftlabs** [comment]
This issue seems resurfacing in my. Is there any workaround?
value.yaml:
     operatorImageName: gcr.io/spark-operator/spark-operator
     operatorVersion: v1beta2-1.0.1-2.4.4
Helm:  
   "v2.14.3", GitCommit:"0e7f3b663
K8S:
   "v1.16.1", GitCommit:"d647ddbd
