### ISSUE TITLE
Can the application running inside the k8s pod talk to the operator?

### ISSUE THREAD

**Issue by JoeyLuffa** [GoogleCloudPlatform/spark-on-k8s-operator#396]
I am trying to implement a spark app manager and whenever it receives a message or signal for app creation, it will try to talk to the spark on k8s operator to launch the app. My question is, what's the correct way of doing this? Does the operator have an internal endpoint address across the whole cluster? (maybe it's similar as how the operator talk to the k8s API server) And why kind of authentication it should use? (k8s service account?) Thanks.

**Comment by liyinan926** [comment]
Can't the app manager just create a new `SparkApplication` resource from the message it receives?

**Comment by JoeyLuffa** [comment]
@liyinan926  it can. And the manager uses the default service account associated with the pod. Can I know why the default service account has permission to connect to the spark operator? Thanks.

**Comment by liyinan926** [comment]
Sorry I don't quite understand what you meant by `why the default service account has permission to connect to the spark operator`. Which default service account, the one used by the operator or Spark driver pods?

**Comment by JoeyLuffa** [comment]
The one used by spark app manager (it runs within a pod in k8s and every pod in k8s would be assigned to a default service account). I am wondering why this default service account has permission to talk to spark-on-k8s-operator.

**Comment by liyinan926** [comment]
You mean the app manager you are trying to build? The default service account doesn't allow you to create custom resources most likely, but you can give it a custom service account with RBAC that allows it to create custom resources.

**Comment by JoeyLuffa** [comment]
The thing is: the default service account allows me to talk to the `sparkapplication` crd and create an instance of it.

**Comment by liyinan926** [comment]
That has something to do with your cluster setup.

**Comment by liyinan926** [comment]
Closing this. Feel free to reopen if you have more questions.
