### ISSUE TITLE
Driver startup needs a timeout

### ISSUE THREAD

**Issue by jpiper** [GoogleCloudPlatform/spark-on-k8s-operator#410]
There should be a timeout on how long it takes the driver to start before deleting the driver pod and retrying. I had a case where the driver pod couldn't start and was stuck in `ContainerCreating` due to a node HW issue, and the job just hung indefinitely.

**Comment by abhisrao** [comment]
I think we're waiting for the spark-submit command to complete before deciding if the job is success or failure. 

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/4439d47e47c9e282149b8c52591eff72d2bdd2bc/pkg/controller/sparkapplication/submission.go#L64

Instead we could return immediately after command submission and then implement some retry and timeout to check if driver pod is running.
