### ISSUE TITLE
Provide detailed logging for Operator pod

### ISSUE THREAD

**Issue by amukhopad** [GoogleCloudPlatform/spark-on-k8s-operator#412]
As developer I find It hard to debug my job and getting not informative outputs for 
`kubectl logs -n namespace sparkopertator-someid` like this:

```
E0218 21:44:09.735581      11 controller.go:569] failed to run spark-submit for SparkApplication my-tenant/spark-pi: failed to run spark-submit for SparkApplication my-tenant/spark-pi: exit status 1
```

I also miss log of generated `spark-submit` command which I personally found useful.

**Comment by skonto** [comment]
if you launch the operator with -v v=2 you should get the desired output.

**Comment by amukhopad** [comment]
Thanks for reply @skonto. I tried with launching operator with `--v=4` and it shows a bit more information. However it still doesn't show neither submission error nor `spark-submit`.

**Comment by ligao101** [comment]
`- -v=4` only shows the `spark-submit` command parameters. To get the actual `stdout` or `stderr` of the `spark-submit` command you can manually rerun it to check. Ideally the operator should be able to output the `stdout` and `stderr` of the `spark-submit` command

**Comment by liyinan926** [comment]
@amukhopad The problem with not being able to see detailed error message when the submission fails has been resolved in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/384. If you use the latest image, it should work for you.
