### ISSUE TITLE
Spark-Operator and Jupyter Notebooks

### ISSUE THREAD

**Issue by metrofun** [GoogleCloudPlatform/spark-on-k8s-operator#422]
Greetings,

I'm new to spark-operator and would like to know whether it can be used together with Jupyter Notebooks?

Spark-Operator latest beta seems to use Apache Spark 2.4, which comes with client mode support that allows for notebook-likes. Does it mean spark-operator can be leveraged by Jupyter? Any further pointers/examples to start piping it together?

**Comment by liyinan926** [comment]
The Spark operator is designed to work well with cluster mode. It currently doesn't support client mode.

**Comment by metrofun** [comment]
@liyinan926 Thank you for the prompt response

**Comment by cujoy** [comment]
Any update on client mode support?

**Comment by alfccc** [comment]
is there an ticket for this work in the future?

**Comment by mattdornfeld** [comment]
Is this still true? I see that client mode is an option in the SparkApplication manifest?

**Comment by kyprifog** [comment]
@liyinan926  How is this intended to be used interactively in a  notebook, I am running a spark script in a local jupyter notebook, but it stalls out with 

```
TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
```

because the operator doesn't spin up any workers when running specifying the master to be the k8s master.

**Comment by kyprifog** [comment]
Answering my own question.  I think that the openshift spark operator is much more suited for what I'm trying to do here as it allows you to run standalone clusters:

https://github.com/radanalyticsio/spark-operator

**Comment by kyprifog** [comment]
@liyinan926 do you have an answer for @mattdornfeld?  I was going to take a shot at adding support for client mode but I dont want to duplicate any existing in progress work.

**Comment by cwei-bgl** [comment]
It would be good to add Jupyter Notebooks support. I am waiting for it also.

**Comment by NKcqx** [comment]
me too

> It would be good to add Jupyter Notebooks support. I am waiting for it also.

**Comment by kyprifog** [comment]
Just wanted to make those in this thread aware, in the mean time i've been using this helm chart https://github.com/JahstreetOrg/spark-on-kubernetes-helm developed by @jahstreet  Its based around Livy which is a better fit architecturally for interactive sessions.  spark-on-k8s-operator is still a good fit I think for non-interactive workflows.  Happy to have your help working out any rough edges.

**Comment by tahesse** [comment]
@kyprifog Can you shed some light on the details of your deployment? Do you have a separate Spark cluster running (for interactive apps) next to the Spark operator (for non-interactive apps)?

**Comment by cometta** [comment]
can elaborate more how you do the interactive mode with jupyterlab notebook

**Comment by tahesse** [comment]
@cometta You can also use jupyter-gateway with spark-on-k8s-operator.
