### ISSUE TITLE
spark conf for executors

### ISSUE THREAD

**Issue by ksp17788** [GoogleCloudPlatform/spark-on-k8s-operator#423]
Hey. I wanted the driver and executor pods to start logging in DEBUG level. I created a config map for with log4j properties setting the level to debug. I, then, set the value for spec.sparkConfigMap to point to my newly created configmap. I noticed that the driver pod started to log at debug level, but the executor pods were still logging at INFO level. Is this the expected behavior ? If so, is it intended that executor spark configs be passed as configmaps ?

**Comment by liyinan926** [comment]
Interesting. Have you checked if the ConfigMap indeed got mounted into the executor pods?

**Comment by liyinan926** [comment]
You might also want to take a look at https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/395.

**Comment by ksp17788** [comment]
Verified that the log4j properties file is in `SPARK_CONF_DIR`.

**Comment by ksp17788** [comment]
so from #395 and my observation is that,
My `sparkConf` setting is as follows:
```sparkConf:
        "spark.executor.extraJavaOptions": "-Dlog4j.configuration=/etc/spark/conf/log4j.properties"
```

if you specify the following lines
```monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.3.1.jar"
      port: 8090```
then, the `SPARK_JAVA_OPT_0` within the executor pod is set to 

`SPARK_JAVA_OPT_0=-javaagent:/opt/spark/jars/jmx_prometheus_javaagent-0.3.1.jar=8090:/etc/metrics/conf/prometheus.yaml`

but when i remove the monitoring part, 

`SPARK_JAVA_OPT_0=-Dlog4j.configuration=/etc/spark/conf/log4j.properties`

So, i guess these opts are not getting appended and sent to the executor jvm.

My next observation is that when monitoring block is removed from the manifest and there are no `.spec.sparkConf`(s) specified, but the `.spec.sparkConfigMap` is specified (which in my case is the log4j properties file), the executor pod `env` variables have no extra options set.

**Comment by liyinan926** [comment]
The options should definitely be appended instead of replaced. Will fix that. If you don't have extra java options set, yes, that env will not be there.

**Comment by liyinan926** [comment]
@ksp17788 just realized that you were setting `spark.executor.extraJavaOptions` under `sparkConf`. We actually have dedicated fields `javaOptions` under both `driver` and `executor` for specifying extra Java options. Options specified this way will not be overwritten by the monitoring config.

**Comment by ksp17788** [comment]
okay sounds good. Closing this ticket as we have a solution.

**Comment by EladDolev** [comment]
I think it would be wise adding it to the documentation :-)
