### ISSUE TITLE
Executor cores  always need to be + positive integer 

### ISSUE THREAD

**Issue by varuns-zetaris** [GoogleCloudPlatform/spark-on-k8s-operator#424]
executor:
                 cores 0.5 
                 coresrequest: 0.5

this would give error. Is this expected. Does that mean we cannot run multiple executor in a core like we do for many other applications where we give cpu slices. instead of entire vcpu.

**Comment by liyinan926** [comment]
Yes, this is expected. `cores` is translated to `spark.executor.cores`, which only takes integer values. `coreRequest` can take fractional value and is translated to the cpu request for executors. If you want to share cpus among executors running on the same node, you can set `coreRequest` to a fractional value smaller than 1.

**Comment by liyinan926** [comment]
Closing this and feel free to reopen if you have additional questions.
