### ISSUE TITLE
Labels and annotation support for CRD objects

### ISSUE THREAD

**Issue by ligao101** [GoogleCloudPlatform/spark-on-k8s-operator#425]
Hi,

We are looking for ways to specify `Labels` and `Annotations` to CRD objects so we can do custom attributions and label selectors on spark CRDs easier.

The current Spark Operator (beta1) appears only support attaching `labels` and `annotations` to spark pods not the crd itself.

Is this a fairly straightforward fix to add both? 

Thanks!

**Comment by liyinan926** [comment]
You can add labels and annotations in the `metadata` section of your custom resource yamls.

**Comment by ligao101** [comment]
ah, I see. Cool thanks!
