### ISSUE TITLE
sparkoperator queues new requests after driver pod launch failure

### ISSUE THREAD

**Issue by rohit-menon** [GoogleCloudPlatform/spark-on-k8s-operator#428]
We have observed this issue a couple of times. 

If a driver pod creation fails due to configmap not being mounted, the spark operator restarts and then does not process any further requests.

<img width="1433" alt="screen shot 2019-02-26 at 10 26 57 pm" src="https://user-images.githubusercontent.com/765741/53511383-2ce06980-3a75-11e9-85de-38b778e15a47.png">

CRD Events:
```
Events:
  Type    Reason                 Age   From            Message
  ----    ------                 ----  ----            -------
  Normal  SparkApplicationAdded  38m   spark-operator  SparkApplication aa7f155124703318269 was added, Enqueuing it for submission
  Normal  SparkApplicationAdded  38m   spark-operator  SparkApplication aa7f155124703318269 was added, Enqueuing it for submission
  Normal  SparkApplicationAdded  24m   spark-operator  SparkApplication aa7f155124703318269 was added, Enqueuing it for submission
```

We were able to resolve this by deleting all the CRDs and then restarting the spark operator. Any ideas on how we could debug this situation further or avoid this from happening again?

Thanks

**Comment by liyinan926** [comment]
Do you have a `RestartPolicy` set on the application? What's the status of the application when it happened?

**Comment by liyinan926** [comment]
Any update on this? Have you run into this again?

**Comment by liyinan926** [comment]
Closing this.
