### ISSUE TITLE
spark-submit failures

### ISSUE THREAD

**Issue by ligao101** [GoogleCloudPlatform/spark-on-k8s-operator#433]
Hi,

We are seeing issues with the operator with some of the CRDs we are creating:

failed to run spark-submit for SparkApplication xxxxxxx: failed to run spark-submit for SparkApplication xxxxxxx: fork/exec /opt/spark/bin/spark-submit: argument list too long

Context:
The spark-submit command arg size is ~ 150KBytes
And we have ARG_MAX set to 2MBytes on the operator container

Not sure how to fix this issue.

Thanks!

**Comment by liyinan926** [comment]
Have you figured out what's going on?

**Comment by liyinan926** [comment]
Closing this. Feel free to ping me if you have any update.
