### ISSUE TITLE
Add network option to driver pod and executors

### ISSUE THREAD

**Issue by ringtail** [GoogleCloudPlatform/spark-on-k8s-operator#451]
Sometimes,We want to use host network in driver pod and executors. So I want to add a option called network to v1beta1. What's your opinion about this.

**Comment by ringtail** [comment]
@liyinan926

**Comment by liyinan926** [comment]
What does this `network` field contain?

**Comment by ringtail** [comment]
@liyinan926 Just like the field in pod spec. You can specific `hostNetwork: true or false`.

**Comment by liyinan926** [comment]
Got it. Yes, this is pretty straightforward to support. We just need to add this as an optional field into `SparkPodSpec` and in the webhook set the field in the pod spec based on the value in the `SparkApplication` spec.

**Comment by ringtail** [comment]
@liyinan926 ok! I’ll submit this pr later

**Comment by ringtail** [comment]
@liyinan926 I found there is no option about hostNetwork in [spark-submit command](https://spark.apache.org/docs/latest/running-on-kubernetes.html#docker-images). So should we support something like `spark.kubernetes.driver.podTemplateFile`

**Comment by liyinan926** [comment]
No, that's not what I meant. This kind of customization is not supported in Spark itself, i.e., there's no Spark config option for this. What we use to solve this is the mutating webhook. Please take a look at `pkg/webhook/webhook.go` to see how it supports other kinds of pod configurations.

**Comment by ringtail** [comment]
@liyinan926 Got it,That's really cool!

**Comment by liyinan926** [comment]
@ringtail are you interested in creating a PR for this?

**Comment by ringtail** [comment]
Yes, But we are doing something else now. If you are willing to do it right away just take it.

**Comment by liyinan926** [comment]
Thanks @tkanng for the PR!
