### ISSUE TITLE
Not able to use s3:// from with-in spark job

### ISSUE THREAD

**Issue by omnipresent07** [GoogleCloudPlatform/spark-on-k8s-operator#460]
I'm getting a `java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found` while trying to use `s3a` from inside my spark job while reading a simple s3 file like this: `spark.read.csv("s3a://....)`. The docker image I prepare has the `hadoop-aws` and `aws-java-sdk` jars. Below is my Dockerfile that prepares the docker image:

```
  new Dockerfile {
    from("lightbend/spark:2.1.0-OpenShift-2.4.0-rh-2.12") //Uses 2.12 Scala
    
    addRaw("http://central.maven.org/maven2/org/apache/hadoop/hadoop-aws/2.7.3/hadoop-aws-2.7.3.jar", "$SPARK_HOME/jars")
    addRaw("http://central.maven.org/maven2/com/amazonaws/aws-java-sdk/1.7.4/aws-java-sdk-1.7.4.jar", "$SPARK_HOME/jars")
    add(artifact, artifactTargetPath)
  }
```

Is there a way to resolve this? I get the `ClassNotFoundException` in the driver logs (edited) 

For completeness, here is the relevant part of my YAML file:

```
  image: "omnipresent/mydockerimage"
  imagePullPolicy: Always
  mainClass: com.hmda.reports.MyReports
  mainApplicationFile: "local:///opt/spark/examples/jars/my-reports.jar"
  sparkVersion: "2.4.0"
```

Any pointers on what else I need to do in order to use `spark.read.csv("s3a://...)` from within my mainClass `MyReports` ?

**Comment by amukhopad** [comment]
Can you make sure that:
 - jars you added are present in image
 - jars you added are actually in classpath?

**Comment by yuchaoran2011** [comment]
Hi @omnipresent07, if you have resolved this issue, could you please close it? Thanks!
