### ISSUE TITLE
Job is not submited if app-name label exceeds 63 characters

### ISSUE THREAD

**Issue by amukhopad** [GoogleCloudPlatform/spark-on-k8s-operator#465]
@liyinan926 After #459 fix Issue still exists. I guess, now these labels are the problem 
```
--conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name
--conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name
```
when I remove them, job starts with long name.

**Comment by liyinan926** [comment]
The values of these two labels are the name of the `SparkApplication`. I believe object names and label values shared the same length limit, so if the name is within the limit, these two labels should be fine.

**Comment by amukhopad** [comment]
@liyinan926 Does it mean that we have this 63 char limit for CR names?

**Comment by liyinan926** [comment]
Yes.

**Comment by amukhopad** [comment]
@liyinan926 So I guess now it makes sense to limit application name length in CRD?

**Comment by liyinan926** [comment]
> @liyinan926 So I guess now it makes sense to limit application name length in CRD?

Yes, we have to limit names to <= 63 characters.

**Comment by liyinan926** [comment]
Actually I just realized that we don't necessarily need the name label. To select the right pods of a particular submission of a `SparkApplication`, we can use a combination of the UID of the `SparkApplication` and the submission ID previously added. The name label can be converted to an annotation for use cases where the app name is needed.

**Comment by sarjeet2013** [comment]
@liyinan926 Will it be straight forward to restrict the name length from CRD itself? Otherwise, this may have adverse effect at other place, such as mentioned above.

**Comment by sarjeet2013** [comment]
@amukhopad Can you submit your PR for upstream for json schema validation for > 63 chars?
