### ISSUE TITLE
Unable to run example with webhook enabled

### ISSUE THREAD

**Issue by Bfoster-melrok** [GoogleCloudPlatform/spark-on-k8s-operator#470]
Using the master branch I run:
kubectl apply -f manifest/spark-operator-crds.yaml 
kubectl apply -f manifest/spark-operator-rbac.yaml 
kubectl apply -f manifest/spark-rbac.yaml 
kubectl apply -f manifest/spark-operator-with-webhook.yaml 
kubectl apply -f examples/spark-pi.yaml 

The Driver pod gets created but fails to start.
describe shows this error:
[spark-pi-1.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/3045342/spark-pi-1.log)

if I remove the volume from the spark-pi example I get only this:
[spark-pi-2.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/3045343/spark-pi-2.log)

If I run without the webhook it works fine.
kubernetes version: v1.13.4
bare metal.

I've tested it on kubernetes 1.10.3 in aws and it works fine. 

here is the whole log from the operator.
[spark-operator.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/3045324/spark-operator.log)

**Comment by liyinan926** [comment]
It seems the for some reason your driver pod got updated after it was created. The webhook is invoked for both pod creation and pod update. So in this case the same set of patches were applied twice: both when the driver pod was created and when it was updated. I'm not sure how the driver pod got updated though.

**Comment by Bfoster-melrok** [comment]
I doubled checked that I don't have 2 operators running, don't think that is the problem.

**Comment by Bfoster-melrok** [comment]
I'm fairly certain its something along those lines though. I tried creating everything in a brand new namespace and got the same results. I've installed the operator and tore it down via helm and the manifests several times.

I was unable to replicate it on a minikube cluster with version 1.13.4. So I'm pretty sure there's something wrong with my environment.

**Comment by liyinan926** [comment]
Makes sense. On the other hand, https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/471 changed the webhook to only be invoked for pod creation, as it doesn't make much sense to invoke the webhook for pod update anyway. You might want to give the latest master a try.

**Comment by Bfoster-melrok** [comment]
thanks, yea I tried building from master and it still doesn't work. I scrubbed through the kube-api audit logs and don't see any strange patch or update calls happening. So I'm kind of at a loss.

**Comment by Bfoster-melrok** [comment]
I added some debugging code and it is running addOwnerReference twice in my dev environment and only once in my minikube environment. same manifests, same images built from master + my debugging code. 
But I'm limited in my programming skill and am not able to determine why it would do that, or why it would happen in one environment and not another.

**Comment by Bfoster-melrok** [comment]
Sorry for the spam today. But I think I figured it out. I was running an old version of calico as my network plugin, apparently, that was also hitting the webhook. 
I updated to the latest version and it seems to be working

**Comment by liyinan926** [comment]
Thanks for updating here! Good to know that it works.
