### ISSUE TITLE
Where i can find Docker file for "gcr.io/spark-operator/spark:v2.4.0" image?

### ISSUE THREAD

**Issue by GrigorievNick** [GoogleCloudPlatform/spark-on-k8s-operator#487]
Hello guys, please help me.
I want modify spark distribution and hadoop dependecny in my project,
So i need build my own spark image, can some one share to me Docker file of "gcr.io/spark-operator/spark:v2.4.0" image ?
If  this image is build using https://spark.apache.org/docs/2.4.0/running-on-kubernetes.html#docker-images? please share build options that you use.

**Comment by liyinan926** [comment]
Yes, the Dockerfiles are at https://github.com/apache/spark/tree/branch-2.4/resource-managers/kubernetes/docker/src/main/dockerfiles/spark.

**Comment by GrigorievNick** [comment]
Thanks.
