### ISSUE TITLE
spark driver UI not accessible when SSL is enabled

### ISSUE THREAD

**Issue by breetasinha1109** [GoogleCloudPlatform/spark-on-k8s-operator#490]
On setting "spark.ssl.ui.enabled" to true, ssl enabled driver UI is not accessible. As, Spark web UI port value is read from configuration parameter spark.ui.port, the SSL port is being derived from the non-SSL port (that is, "spark.ui.port" = 4040) for the same service, even if spark.ssl.ui.enabled is true.

The default port value where the SSL service will listen on is 4440, which should also be set by configuring "spark.ssl.ui.port" parameter if "spark.ssl.ui.enabled" is set to true.

**Comment by breetasinha1109** [comment]
In spark-on-k8s-operator-1beta1-0.8.2-2.4.0/pkg/controller/sparkapplication/sparkui.go :-
two constants are declared,
const (
      sparkUIPortConfigurationKey = "spark.ui.port"
      defaultSparkWebUIPort       = "4040"
)
which are further used in func getUITargetPort(app *v1beta1.SparkApplication) where, getWebUITargetPort attempts to get the Spark web UI port from configuration property "spark.ui.port".

Making Spark web UI port to read value of configuration property "spark.ssl.ui.port" (defaults to 4440) when "spark.ssl.ui.enabled" is true, will make SSL enabled driver UI accessible.

We tried fixing the same, and it worked. Below is code we modified for the fix:-
Instead of constants, three variables are declared :- 
sparkUIPortConfigurationKey = "spark.ui.port"
defaultSparkWebUIPort = "4040"
sparkSSLUIEnabled = "spark.ssl.ui.enabled"

Then, in func getUITargetPort(app *v1beta1.SparkApplication) string {}, we should reset the value of "sparkUIPortConfigurationKey" and  "defaultSparkWebUIPort" based on if condition as below:-

if app.Spec.SparkConf[sparkSSLUIEnabled] == "true" {
        sparkUIPortConfigurationKey = "spark.ssl.ui.port"
        defaultSparkWebUIPort       = "4440"
        }

The above fix worked fine and once proper testing is done, we can create a PR for the same.

Thanks!!
Breeta

**Comment by liyinan926** [comment]
Thanks for reporting and fixing this! Can you create a PR for your fix? Thanks!

**Comment by breetasinha1109** [comment]
Hi,

Sorry, was occupied in other activities so couldn't reply. 
I am on vacation for next two weeks, will create a PR for the same once I am back.
Thanks!!

**Comment by breetasinha1109** [comment]
Hi @liyinan926 

I have created a [PR](https://github.com/nokia/spark-on-k8s-operator/pull/3)  in nokia/spark-on-k8s-operator fork and the fix is available at https://github.com/nokia/spark-on-k8s-operator/tree/master.

Thanks.
