### ISSUE TITLE
Spark Custom Object status returns null

### ISSUE THREAD

**Issue by nishantsh77** [GoogleCloudPlatform/spark-on-k8s-operator#501]
I am trying to get execution status of Spark Application From Java application code using "Watch", but its constantly coming as NULL.

I followed https://github.com/kubernetes-client/java/issues/475 and https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/363 but still I am getting status as NULL.

Watch<V1Namespace> watch =  Watch.createWatch(
									            client,
									            customApiInstance.listNamespacedCustomObjectCall(
								            		group, 
								    				version, 
								    				namespace, 
								    				plural,
								    				pretty, 
								    				null, //labelSelector
								    				null, //resourceVersion
								    				Boolean.TRUE, //watch
								    				null, 
								    				null),
									            	new TypeToken<Watch.Response<V1Namespace>>() {}.getType()
									            );

				while(watch.hasNext()) {
        			Watch.Response<V1Namespace> item = watch.next() ;
        			System.out.println("Name :" + item.object.getMetadata().getName());
        			System.out.println("Type :" + item.type);
        			System.out.println("Status :" + item.status);  
        			System.out.println("Status :" + item.object.getStatus());  
        			        			

Observations:
1. When I add " subresources: status: {}" in spark-operator-crds.yaml then something strange happens that only 2 events are shown in "kubectl describe sparkapplications.sparkoperator.k8s.io" command otherwise all events displayed till "COMPLETED"

Events:
  Type    Reason                     Age                 From            Message
  ----    ------                     ----                ----            -------
  Normal  SparkApplicationSubmitted  10m                 spark-operator  SparkApplication java-spark-pi-1 was submitted successfully
  Normal  SparkApplicationAdded      19s (x22 over 10m)  spark-operator  SparkApplication java-spark-pi-1 was added, enqueuing it for submission

2. Output of  curl 127.0.0.1:8001/apis/sparkoperator.k8s.io/v1beta1/namespaces/default/sparkapplications/java-spark-pi-1 and  curl 127.0.0.1:8001/apis/sparkoperator.k8s.io/v1beta1/namespaces/default/sparkapplications/java-spark-pi-1/status are same:
{"apiVersion":"sparkoperator.k8s.io/v1beta1","kind":"SparkApplication","metadata":{"creationTimestamp":"2019-05-24T12:06:16Z","generation":2,"name":"java-spark-pi-1","namespace":"default","resourceVersion":"4381375","selfLink":"/apis/sparkoperator.k8s.io/v1beta1/namespaces/default/sparkapplications/java-spark-pi-1/status","uid":"554b59bc-7e1c-11e9-8e83-00155d17051e"},"spec":{"deps":{},"driver":{"coreLimit":"200m","cores":0.1,"labels":{"version":"2.4.1"},"memory":"512m","serviceAccount":"spark","volumeMounts":[{"mountPath":"/tmp","name":"test-volume"}]},"executor":{"cores":1,"instances":1,"labels":{"version":"2.4.1"},"memory":"512m","volumeMounts":[{"mountPath":"/tmp","name":"test-volume"}]},"image":"registry.renovite.com/spark-example:v1","imagePullPolicy":"Always","imagePullSecrets":["dev-registry-key"],"mainApplicationFile":"local:///opt/spark/examples/jars/spark-examples_2.11-2.4.1.jar","mainClass":"org.apache.spark.examples.JavaSparkPi","mode":"cluster","restartPolicy":{"type":"Never"},"sparkVersion":"2.4.1","type":"Java","volumes":[{"hostPath":{"path":"/tmp","type":"Directory"},"name":"test-volume"}]}}

Please help in identifying the problem.

**Comment by liyinan926** [comment]
Which version of Kubernetes are you running?

**Comment by nishantsh77** [comment]
I am using 1.14, please let me know if I need to test anything. I will be happy to assist you...
Otherwise, on which version shall I test ?

**Comment by nishantsh77** [comment]
@liyinan926 today I ran spark-pi.yaml (from examples using command prompt after enabling status in crd) and downgrading Kubernetes version to v1.12.8 and "observations" are exactly same as mentioned earlier.
