### ISSUE TITLE
Error while running spark-pi-prometheus example - cannot find jar file

### ISSUE THREAD

**Issue by IshaniSanturkar** [GoogleCloudPlatform/spark-on-k8s-operator#503]
I ran the example `examples/spark-pi-prometheus.yaml` and the driver fails with the following error:

```
Error opening zip file or JAR manifest missing : prometheus/jmx_prometheus_javaagent-0.11.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

I ran a container with the image `gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus` which is used in `spark-pi-prometheus.yaml` to look at its contents and found that the jar file was named `jmx_prometheus_javaagent-0.3.1.jar`. In the example, the jar file was named `jmx_prometheus_javaagent-0.11.0.jar`. 

Could you please look into this? Thanks.

**Comment by yuchaoran2011** [comment]
@liyinan926 I updated the Prometheus exporter jar version from 0.3.1 to 0.11.0 in this [commit](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/0fa38e4fc9f008c4fd1fccb4152d9db3acdeab32), could you update the image `gcr.io/spark-operator/spark:v2.4.0-gcs-prometheus` with the new jar?

**Comment by liyinan926** [comment]
Done.

**Comment by IshaniSanturkar** [comment]
It works for me now. Thanks!
