### ISSUE TITLE
SparkApplication properties - .spec.sparkConfigMap, .spec.driver.securityContext, .spec.executor.securityContext, spec.driver.nodeAffinity not working as expected.

### ISSUE THREAD

**Issue by breetasinha1109** [GoogleCloudPlatform/spark-on-k8s-operator#505]
Hi,

We are facing following issues on using the above mentioned properties :- 

1. **.spec.sparkConfigMap**
When  Spark configuration is added by ConfigMap storing Spark configuration files (spark-defaults.conf, spark-env.sh, log4j.properties) using the optional field .spec.sparkConfigMap ,SPARK_CONF_DIR is being set to point to the mount path of the ConfigMap , i.e, /etc/spark/conf/ but properties mentioned in spark-defaults.conf are not being considered and environment variables set in spark-env.sh are not getting reflected in driver. 
We observed that properties mentioned in spark-defaults.conf are not getting appended in /opt/spark/conf/spark.properties so it is not being taken into affect.
log4j.properties is taking effect as expected.
Configuration Used :- 
sparkConfigMap: "spark-config"

2. **.spec.driver.securityContext/ .spec.executor.securityContext**:
When PodSecurityContext is specified for the driver and executor pod by setting .spec.driver.securityContext.runAsUser to '1000’, the pods are still coming up with default root user.
Configuration Used :-
spec:
  driver:
    securityContext:
      runAsUser: 1000    
  executor:
    securityContext:
      runAsUser: 1000

3. **spec.driver.affinity:**
When nodeAffinity for driver is set to run on a node with label ‘<key=value>’,the driver is coming up on different node ignoring the affinity set.
Configuration Used :- 
driver
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: spark-affinity-test
            operator: In
            values:
            - true
executor
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: spark-affinity-test
            operator: In
            values:
            - true
We, also tried specifying podAntiAffinity for executor, but that also didn't work.

Also, please be informed that webhook is enabled for all of the above scenarios.
Can you please verify if we are missing any configuration or is it a known issue?

Thanks!!
Breeta

**Comment by SachinRavadi** [comment]
hi @liyinan926  

Writing on behalf of @breetasinha1109  
We do see that OwnerReference is added to the driver pod that references the owning SparkApplication in metadata.
[root@vm-10-15-173-143 programs]# kubectl get pod spark-security-context-driver -ncspk -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: restricted
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  creationTimestamp: "2019-06-03T06:52:49Z"
  labels:
    spark-app-selector: spark-7f97fd6ae3e042faaa6b659b87c107f2
    spark-role: driver
    sparkoperator.k8s.io/app-name: spark-security-context
    sparkoperator.k8s.io/launched-by-spark-operator: "true"
    sparkoperator.k8s.io/submission-id: bb961944-a799-4113-9706-e3cc08cd518e
    version: 2.4.0
  name: spark-security-context-driver
  namespace: cspk
  **ownerReferences:
  - apiVersion: sparkoperator.k8s.io/v1beta1
    controller: true
    kind: SparkApplication
    name: spark-security-context**
    uid: 30d7af7d-85cc-11e9-9094-fa163e610ac2
  resourceVersion: "15064848"
  selfLink: /api/v1/namespaces/cspk/pods/spark-security-context-driver
  uid: 3389150d-85cc-11e9-9094-fa163e610ac2

**Comment by skonto** [comment]
I am hitting the same on Openshift,I cannot override the default security context. 
I think its the check here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/webhook/patch.go#L76-L81 where it assumes the pod context to be nil. Why is that?

**Comment by liyinan926** [comment]
@SachinRavadi and @breetasinha1109 which version of Spark operator are you running?

**Comment by skonto** [comment]
@liyinan926 on Openshift you get a default policy if you dont specify anything:

```
 oc describe scc restricted
Name:	restricted
Priority:	<none>
Access:	
  Users:	<none>
  Groups:	system:authenticated
Settings:	
  Allow Privileged:	false
  Allow Privilege Escalation:	true
  Default Add Capabilities:	<none>
  Required Drop Capabilities:	KILL,MKNOD,SETUID,SETGID
  Allowed Capabilities:	<none>
  Allowed Seccomp Profiles:	<none>
  Allowed Volume Types:	configMap,downwardAPI,emptyDir,persistentVolumeClaim,projected,secret
  Allowed Flexvolumes:	<all>
  Allowed Unsafe Sysctls:	<none>
  Forbidden Sysctls:	<none>
  Allow Host Network:	false
  Allow Host Ports:	false
  Allow Host PID:	false
  Allow Host IPC:	false
  Read Only Root Filesystem:	false
  Run As User Strategy: MustRunAsRange	
    UID:	<none>
    UID Range Min:	<none>
    UID Range Max:	<none>
  SELinux Context Strategy: MustRunAs	
    User:	<none>
    Role:	<none>
    Type:	<none>
    Level:	<none>
  FSGroup Strategy: MustRunAs	
    Ranges:	<none>
  Supplemental Groups Strategy: RunAsAny 
```
https://docs.okd.io/3.6/install_config/persistent_storage/pod_security_context.html
I am planning to make overriding options configurable is that ok?

**Comment by breetasinha1109** [comment]
@liyinan926  We are using v2.4.0-v1beta1-0.8.2 version of spark-operator.

**Comment by oliv3340** [comment]
Hi,

Facing the same issue here about **.spec.driver.securityContext** **and .spec.executor.securityContext** which not change the user context inside the container.

Our use case is to run Spark jobs which send requests to Hive througth LLAP. LLAP does not support impersonation so we have to be able to run our job as the Hive UID if we want to be authorized by the Hive metastore, pretty anoying and no workaround found on the job itself for now.

Are we agree about the fact that this specs allow jobs to be run on a different context inside the container ? For example, running with user test or something ? Or maybe I missunderstand something.

**Driver logs :** 
`
++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/ash
+ set -e
+ '[' -z root:x:0:0:root:/root:/bin/ash ']'
+ SPARK_K8S_CMD=driver
+ case "$SPARK_K8S_CMD" in
+ shift 1
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
+ readarray -t SPARK_EXECUTOR_JAVA_OPTS
+ '[' -n '' ']'
+ '[' -n '' ']'
+ PYSPARK_ARGS=
+ '[' -n '' ']'
+ R_ARGS=
+ '[' -n '' ']'
+ '[' '' == 2 ']'
+ '[' '' == 3 ']'
+ case "$SPARK_K8S_CMD" in
+ CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
`
And next, we've got a permission denied exception from hive saying specificly USER=root.
As you can see the user context remain root.

I have deploy spark-operator with the latest helm charts (v0.5.0) deploying the latest img (v1beta2-1.0.1-2.4.4). I have just enabled metrics and webhook and set sparkJobNamespace as "spark".

I run my spark's jobs with a YAML static file realy closed to this one : [https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-prometheus.yaml](url) with .spec.*.securityContext of course

Thanks !!
