### ISSUE TITLE
Driver pod failed to start   

### ISSUE THREAD

**Issue by tkanng** [GoogleCloudPlatform/spark-on-k8s-operator#508]
According to the pod's events, I found that the driver pod failed to start because configMap doesn't exist, but actually the configmap object **does exist** in the cluster.

### Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.0-alpha.1.222+0b8566f3887a2d", GitCommit:"0b8566f3887a2d13baba623d88aeb64f6e637f46", GitTreeState:"clean", BuildDate:"2019-05-04T08:58:31Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

```

### Operator version:
```
root@iZhp3gki207s34o84d5nlvZ:~/k/spark-on-k8s-operator/examples# helm ls
NAME             	REVISION	UPDATED                 	STATUS  	CHART              	APP VERSION         	NAMESPACE     
coiling-dachshund	1       	Mon Jun  3 17:15:46 2019	DEPLOYED	sparkoperator-0.2.3	v2.4.0-v1beta1-0.8.2	spark-operator
```
### SparkApplication Status
Execute `kubectl apply -f spark-pi.yaml` after setting up operator properly.

`spark-pi.yaml`:
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.azk8s.cn/spark-operator/spark:v2.4.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar"
  sparkVersion: "2.4.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 0.1
    coreLimit: "200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: default
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"

```
`kubect get pod  spark-pi-driver -oyaml`:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.42.1.141/32
  creationTimestamp: "2019-06-03T09:40:29Z"
  labels:
    spark-app-selector: spark-515e3c4dabb94d3694e4dc46637b7b03
    spark-role: driver
    sparkoperator.k8s.io/app-name: spark-pi
    sparkoperator.k8s.io/launched-by-spark-operator: "true"
    sparkoperator.k8s.io/submission-id: 3d8e211a-c063-4ec7-8039-80b00b9bb4b5
    version: 2.4.0
  name: spark-pi-driver
  namespace: default
  resourceVersion: "4024968"
  selfLink: /api/v1/namespaces/default/pods/spark-pi-driver
  uid: 9fad4727-85e3-11e9-b823-00163e00808b
spec:
  containers:
  - args:
    - driver
    - --properties-file
    - /opt/spark/conf/spark.properties
    - --class
    - org.apache.spark.examples.SparkPi
    - spark-internal
    env:
    - name: SPARK_DRIVER_BIND_ADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SPARK_LOCAL_DIRS
      value: /var/data/spark-4a8b8077-a742-4540-82a0-5be5e3025400
    - name: SPARK_CONF_DIR
      value: /opt/spark/conf
    image: gcr.azk8s.cn/spark-operator/spark:v2.4.0
    imagePullPolicy: Always
    name: spark-kubernetes-driver
    ports:
    - containerPort: 7078
      name: driver-rpc-port
      protocol: TCP
    - containerPort: 7079
      name: blockmanager
      protocol: TCP
    - containerPort: 4040
      name: spark-ui
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 896Mi
      requests:
        cpu: 100m
        memory: 896Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/data/spark-4a8b8077-a742-4540-82a0-5be5e3025400
      name: spark-local-dir-1
    - mountPath: /opt/spark/conf
      name: spark-conf-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-n6zsv
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: izhp3gki207s34o84d5nluz
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: spark-local-dir-1
  - configMap:
      defaultMode: 420
      name: spark-pi-1559554828312-driver-conf-map
    name: spark-conf-volume
  - name: default-token-n6zsv
    secret:
      defaultMode: 420
      secretName: default-token-n6zsv
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-06-03T09:40:29Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-06-03T09:41:12Z"
    message: 'containers with unready status: [spark-kubernetes-driver]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-06-03T09:41:12Z"
    message: 'containers with unready status: [spark-kubernetes-driver]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-06-03T09:40:29Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b784902e710fbfb656eca086ed7929a0ac158ee30b25b4d77c9b9e24a9417c86
    image: gcr.azk8s.cn/spark-operator/spark:v2.4.0
    imageID: docker-pullable://gcr.azk8s.cn/spark-operator/spark@sha256:375cd079d14179687b37625ce850c905c452010325d62c35618b8e0c8ddc749b
    lastState: {}
    name: spark-kubernetes-driver
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: docker://b784902e710fbfb656eca086ed7929a0ac158ee30b25b4d77c9b9e24a9417c86
        exitCode: 1
        finishedAt: "2019-06-03T09:41:11Z"
        reason: Error
        startedAt: "2019-06-03T09:40:33Z"
  hostIP: 10.10.251.242
  phase: Failed
  podIP: 10.42.1.141
  qosClass: Burstable
  startTime: "2019-06-03T09:40:29Z"
```
### Pod Events
`spark-pi-driver` has these events below:
```
Events:
  Type     Reason       Age   From                              Message
  ----     ------       ----  ----                              -------
  Normal   Scheduled    10m   default-scheduler                 Successfully assigned default/spark-pi-driver to izhp3gki207s34o84d5nluz
  Warning  FailedMount  10m   kubelet, izhp3gki207s34o84d5nluz  MountVolume.SetUp failed for volume "spark-conf-volume" : configmaps "spark-pi-1559554828312-driver-conf-map" not found
  Normal   Pulling      10m   kubelet, izhp3gki207s34o84d5nluz  pulling image "gcr.azk8s.cn/spark-operator/spark:v2.4.0"
  Normal   Pulled       10m   kubelet, izhp3gki207s34o84d5nluz  Successfully pulled image "gcr.azk8s.cn/spark-operator/spark:v2.4.0"
  Normal   Created      10m   kubelet, izhp3gki207s34o84d5nluz  Created container
  Normal   Started      10m   kubelet, izhp3gki207s34o84d5nluz  Started container
```
But actually configMap `spark-pi-1559554828312-driver-conf-map` does exist in the cluster. `kubect get cm`:
```
root@iZhp3gki207s34o84d5nlvZ:~/k/spark-on-k8s-operator/examples# kubectl get cm
NAME                                     DATA   AGE
dummy-cm                                 0      14m
ingress-controller-leader-nginx          0      8d
spark-pi-1559554828312-driver-conf-map   1      11m
```

**Comment by liyinan926** [comment]
Your driver pod didn't fail because of the `ConfigMap`. The event you referred to was a earning and is not uncommon because the driver pod was created before other k8s resources got created by the Kubernetes-specific Spark submission client. The pod failed for other reasons that you need to find out by checking the driver logs.

**Comment by tkanng** [comment]
Thanks you very much! I found that driver's service account has no permission for create Pod.  Thanks!  :)

**Comment by SKYDawson** [comment]
so  can i ask how did you solved it

**Comment by SKYDawson** [comment]
![image](https://user-images.githubusercontent.com/51279121/62260746-ac6bcd80-b445-11e9-9676-4ef40fef3e06.png)
![image](https://user-images.githubusercontent.com/51279121/62260760-b4c40880-b445-11e9-8027-1b224e3cd93a.png)
kubectl logs spark-pi-driber
![image](https://user-images.githubusercontent.com/51279121/62260806-dc1ad580-b445-11e9-8c2a-0ed0ed8641ea.png)

**Comment by SKYDawson** [comment]
how to give the right to the driver's serviceaccount to create pod

**Comment by drametoid** [comment]
@SKYDawson - You can do that using rolebinding or clusterrolebinding (refer official RBAC Authorizations [doc](https://kubernetes.io/docs/reference/access-authn-authz/rbac/)) to the particular serviceAccount you are working with in Spark. You can find the usage doc [here](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-clusterrolebinding-em-). 
Example: kubectl create clusterrolebinding spark-role  --clusterrole=edit --serviceaccount=default:spark --namespace=default

where,
**spark-role** is the name of your role binding
**edit** is basically a pre-defined **clusterrole** that we are giving for this binding and as the name suggests you are giving it permissions/privileges to create, list, delete, edit etc the various resources in the cluster
**default:spark** is the name of our namespace resolved serviceAccount. If your serviceAccount is in the default namespace just use default:yourServiceAccountName

**Comment by drametoid** [comment]
However, @tkanng : I have given appropriate permissions to my service account and I still encounter this same error where it's unable to find the **configMap** even though it exists for the spark driver.

I found a stackoverflow [answer](https://stackoverflow.com/a/58508313/8135861) to this error and it seems this bug exists in spark for kubernetes and based on the answer was still there till Spark version **2.4.4**, I am using **2.4.5** but it seems there is even no listed issue for this in Apache Spark's Jira as well.

Please contribute here if somebody facing this issue has a solution.

P.S - Also, I'm running this cluster inside a nested VM. Let me know if you think this might be an issue.

**Comment by softol90** [comment]
Hi all,
Is there any solution for this problem?
Is there a way to generate our custom **configMap** assigning it to driver-pod before initialization of it?

**@drametoid** - did you find any solution for the problem so far?

Thanks!

**Comment by drametoid** [comment]
Hi @softol90 , yes I did. So if you've landed here, mostly `configMap` is not your issue, because it's just a WARNING. 

Most likely it's a **version mismatch** between your Kubernetes version and Spark version (Spark's Kubernetes Client version to be more precise). It fixed the issue for me.

So Spark v2.4.5 uses Kubernetes client v4.6.1 which only supports Kubernetes version till v1.15.3 only. You can refer the **compatibility matrix** [here](https://github.com/fabric8io/kubernetes-client/blob/master/README.md#compatibility-matrix).

For a detailed answer, you can refer [this](https://stackoverflow.com/a/61595653/8135861) response to a question I posted on SO.

**Comment by manushnandan** [comment]
@softol90 , I also face this same issue("MountVolume.SetUp failed for volume") and If i check the kube-apiserver's event audit logs(/var/log/bcmt/apiserver/audit.log) it looks like driver is trying to mount the configmap even before it was created. It was just a difference of few milliseconds between the events(get and create). I also use spark 2.4 in kubernetes. Is there any solution for this already?

**Comment by softol90** [comment]
Hi @manushnandan,

My problem was solved using the below steps:

- Upgrading the versioning of spark-operator to the latest one(spark-operator v1beta2).

- Upgrading the cluster(GKE) to 1.15.9.gke24

- The image which I used in my spark_submit.yaml was  gcr.io/spark-operator/spark-py:v2.4.5

I think this problem emerges when there is compatibility problem!

P.S @drametoid Thank you a lot!

**Comment by swill** [comment]
@drametoid how did you confirm which Kubernete client version was being used?  Is there a command I can run to verify in my setup?  Thanks...

**Comment by sanazba** [comment]
Hi all,
Is there any solution to this problem?
Is there any way to generate our custom configMap assigning it to driver-pod before initialization of it?
MountVolume.SetUp failed for volume "spark-conf-volume" : configmap "spark-45545489ca1f20-driver-conf-map" not found

**Comment by sanazba** [comment]
@tkanng Hi,  would you please tell me how do you create permission for a driver? I would appreciate it if you could send me RBAC YAML file sample?
