### ISSUE TITLE
Fix unit tests in branch multi-version-support

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#526]
@akhurana001 are you able to help with this? Thanks! I want to merge the change back to the master branch and the only blocker is the unit tests.

**Comment by akhurana001** [comment]
@liyinan926 Definitely, getting this merged into master will be great. I can spend some time early next week and probably send out a PR by mid-week if that works for you ?

**Comment by liyinan926** [comment]
Thanks! No hurry, I will be on vacation in the first two weeks of July. Please take your time working on this.

**Comment by akhurana001** [comment]
Just to update you, I have started working on this. Should have a PR out by the time you get back from vacation.
