### ISSUE TITLE
external shuffle service in kubernetes

### ISSUE THREAD

**Issue by ringtail** [GoogleCloudPlatform/spark-on-k8s-operator#531]
Is this feature still in progress？
(https://docs.google.com/document/d/1uCkzGGVG17oGC6BJ75TpzLAZNorvrAU3FRd2X-rVHSM/edit#heading=h.btqugnmt2h40 )

**Comment by liyinan926** [comment]
Yes. The proposal just passed the SPIP process, and we should see PRs soon.

**Comment by liyinan926** [comment]
Also there's a separate JIRA on enabling dynamic resource allocation without an external shuffle service at https://issues.apache.org/jira/browse/SPARK-24432 with a WIP PR at https://github.com/apache/spark/pull/24817.

**Comment by ringtail** [comment]
@liyinan926 That's really cool! We are highly interested in this feature and we are going to test it as soon as possible.

**Comment by liyinan926** [comment]
@ringtail https://github.com/apache/spark/pull/24817 has been merged and the feature (dynamic resource allocation without an external shuffle service) is now available in the master branch. If you want to try it out in the Kubernetes mode, you can build a custom Spark image from the master branch.

**Comment by ringtail** [comment]
@liyinan926 Thanks. But I think this is not what i want.  In this doc.(https://docs.google.com/document/d/1uCkzGGVG17oGC6BJ75TpzLAZNorvrAU3FRd2X-rVHSM/edit#heading=h.btqugnmt2h40 ) The external shuffle proxy for kubernetes  is the key point. shuffle to local disk or pv is not that elegant. I think shuffle proxy maybe the answer.

**Comment by jamesthegiantpeach** [comment]
Will try this as soon as available.
