### ISSUE TITLE
How Enable Dynamic Resource Allocation and External Shuffle Service

### ISSUE THREAD

**Issue by Dimss** [GoogleCloudPlatform/spark-on-k8s-operator#538]
Where and how I can enable the Enable Dynamic Resource feature? 
Where I can configuring the following options
```
spark.dynamicAllocation.enabled=true
spark.shuffle.service.enabled=true
spark.dynamicAllocation.initialExecutors=1
```
And who/how deploy the External Shuffle Service?

**Comment by GrigorievNick** [comment]
This feature do not supported yet.
And most of all will be implemented only in 3.x spark.
https://spark.apache.org/docs/latest/running-on-kubernetes.html#future-work
There are huge discussion inside spark team, about refactoring that needed for this feature.

**Comment by liyinan926** [comment]
Related to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/531.
