### ISSUE TITLE
GroupName for sparkoperator.k8s.io conflicts with sparkoperator

### ISSUE THREAD

**Issue by staugust** [GoogleCloudPlatform/spark-on-k8s-operator#539]
**pkg/apis/sparkoperator.k8s.io/register.go**  defines variable **GroupName**  which is used in both **pkg/apis/sparkoperator.k8s.io/v1alpha1/register.go** and **pkg/apis/sparkoperator.k8s.io/v1beta1/register.go** . 
```
package sparkoperator

const (
	GroupName = "sparkoperator.k8s.io"
)
```
At the mean time, **pkg/apis/sparkoperator.k8s.io/v1alpha1/doc.go** and **pkg/apis/sparkoperator.k8s.io/v1beta1/doc.go**  define **groupname** to **sparkoperator**, hence,  source code like   **pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1/fake/fake_sparkapplication.go** use group **sparkoperator**. 
Here is a code snippet of **pkg/client/clientset/versioned/typed/sparkoperator.k8s.io/v1alpha1/fake/fake_sparkapplication.go**:

```
var sparkapplicationsResource = schema.GroupVersionResource{Group: "sparkoperator", Version: "v1alpha1", Resource: "sparkapplications"}

var sparkapplicationsKind = schema.GroupVersionKind{Group: "sparkoperator", Version: "v1alpha1", Kind: "SparkApplication"}
```

Finally, all these thing leads to that we cannot  create a valid informer for spark in our unit tests with **fake.NewSimpleClientset**. Here's a code snippet that we used to construct a sparkapplication informer:

```
import (
   "	sparkclient "github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/clientset/versioned/fake"

)
fsparkClient := sparkclient.NewSimpleClientset()
sparkInformerFac := sparkinformers.NewSharedInformerFactoryWithOptions(fsparkClient , 3*time.Minute, sparkinformers.WithNamespace(TestNamespace))
SparkInformer := SparkInformerFac.Sparkoperator().V1beta1().SparkApplications()
sparkInformerFac.Start(stopChan)
go SparkInformer.Informer().Run(stopChan)
```
Below is the error output:
```
E0703 18:00:02.938875   14608 reflector.go:134] my_test.go:113: Failed to list *v1beta1.SparkApplication: no kind "SparkApplicationList" is registered for version "sparkoperator/v1beta1" in scheme "github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/clientset/versioned/fake/register.go:33"
```
I'm wondering whether groupname defined in **doc.go**  have other purpose. If not, should we change it to sparkoperator.k8s.io to keep the same with that in register.go ?

**Comment by liyinan926** [comment]
I don't remember why `doc.go` ended up using the wrong group name. But I agree we should change it to `sparkoperator.k8s.io`.
