### ISSUE TITLE
Finalize SparkApplication API for alpha release

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#54]

**Comment by foxish** [comment]
Can we turn this (just the API) into a doc for today's gathering?

**Comment by liyinan926** [comment]
https://github.com/liyinan926/spark-on-k8s-operator/blob/master/docs/api.md

**Comment by foxish** [comment]
Great, Thanks! We can use that for driving discussion.

**Comment by liyinan926** [comment]
Version v1alpha of the API definition is documented at https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api.md.
