### ISSUE TITLE
Configuring spark streaming job to run continuous for incoming event messages

### ISSUE THREAD

**Issue by gemanilkashyap** [GoogleCloudPlatform/spark-on-k8s-operator#540]
I have operator configured and working for batch job but wanted to know if that can be extended to streaming capabilities running continuous and listening for events?

**Comment by liyinan926** [comment]
Can you elaborate on this? You can run Spark streaming jobs with the operator. Not sure what you meant by "can be extended to streaming capabilities running continuous and listening for events".
