### ISSUE TITLE
Spark Operator cannot apply security policies on Openshift

### ISSUE THREAD

**Issue by skonto** [GoogleCloudPlatform/spark-on-k8s-operator#546]
Issue described here: https://github.com/openshift/origin/issues/20543#issuecomment-508733000
and verified on Openshift 3.11. I think we need to move to the pod template faster.

**Comment by liyinan926** [comment]
As I commented in the other issue, we cannot get rid of the webhook as it's still needed for Spark 2.3.x and 2.4.x applications. Also the particular issue you referred to seems unique to Openshift, not vanilla Kubernetes.

**Comment by liyinan926** [comment]
Can this be closed now?
