### ISSUE TITLE
Add completed time stamp to spark application 

### ISSUE THREAD

**Issue by ringtail** [GoogleCloudPlatform/spark-on-k8s-operator#549]
When a spark application is completed we need a timestamp to indicate the resource are all free now.

**Comment by akhurana001** [comment]
@ringtail   `TerminationTime` is probably what you are looking for: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/apis/sparkoperator.k8s.io/v1beta1/types.go#L291 ?

**Comment by liyinan926** [comment]
@ringtail Does `TerminationTime` fits your need? If so, I will close this issue.

**Comment by ringtail** [comment]
Thanks and close issue
