### ISSUE TITLE
Integration spark-operator with Volcano

### ISSUE THREAD

**Issue by k82cn** [GoogleCloudPlatform/spark-on-k8s-operator#550]
We're evaluating spark-operator and would like to integrate with [Volcano](http://github.com/volcano-sh/volcano) for following features:

1. Resource sharing between spark job by DRF
1. Preemption based on resource sharing, e.g. drf
1. Delay pod creation to reduce resource consumption from driver
1. Queue (on-going)

What we're going to do is to create PodGroup for each SparkApplication; the PodGroup can not be created outside operator as 1. it's better to make SparkApplcation as its owner reference for GC 2. PodGroup's `minResource` will help to avoid one driver with one executor, and the `minResources` comes from SparkApplication.

**Comment by k82cn** [comment]
If that's ok, I'm going to open PR for that :)

**Comment by liyinan926** [comment]
@k82cn will get back to you when I get back to work next week.

**Comment by k82cn** [comment]
sure, "see" you next week :)

**Comment by liyinan926** [comment]
@k82cn I have a couple of questions/comments:
* Is a `PodGroup` only for the executors or both the driver and executors? How does it work if it's the latter where the executor pods come after the driver pod starts running?
* Creating a `PodGroup` should be optional and can be enabled/disabled through a flag.
* If we do this, there'll be a dependency on the Volcano controller and CRDs. We need a way to check the presence of the Volcano controller and CRDs and install them when necessary, if the feature is enabled.

**Comment by k82cn** [comment]
> Is a PodGroup only for the executors or both the driver and executors? 

For spark-operator, prefer to use the same PodGroup for both driver and executors.

> How does it work if it's the latter where the executor pods come after the driver pod starts running?

We will provide `minResource` in PodGroup to support DelayPodCreation, and scheduler support minAvaialbe is 1, total pod is more than 1. As PodGroups in scheduler will share resource by DRF, so SparkApplication (driver + executor). And some other features that supported by volcano :)

> Creating a PodGroup should be optional and can be enabled/disabled through a flag.

Yes, it's controlled by flag.

> If we do this, there'll be a dependency on the Volcano controller and CRDs.
> We need a way to check the presence of the Volcano controller and CRDs and install them when necessary, if the feature is enabled.

I think it's not required: if no volcano there, we just give a log/event when creating PodGroup;
the behaviour is similar to feature disabled.

**Comment by liyinan926** [comment]
@k82cn thanks. I would like to see the PR for this, and in the meantime, I will look a bit deeper into Volcano and the `PodGroup` CRD.

**Comment by liyinan926** [comment]
Closing this one and please use #583 for all future things related to Volcano integration. Thanks!
