### ISSUE TITLE
Spark operator will not delete the pods after an app update 

### ISSUE THREAD

**Issue by skonto** [GoogleCloudPlatform/spark-on-k8s-operator#557]
Spark operator will not delete the pods after an app update  and that leads updating to fail since the same pods exists. See attached log [scale-spark.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/3451981/scale-spark.log). For some reason code [here ](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/controller.go#L745) never worked. That implies that app.Status.DriverInfo.PodName is empty. That name should have been filled due to the successful submission before the scaling. Not sure what is happening in the meantime.
This was fixed before here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/0fa38e4fc9f008c4fd1fccb4152d9db3acdeab32 but now the logic (code has been refactored since that PR) sets the driverInfo at the time of a submission which should be preserved until the update time (when invalidating state is being processed).

**Comment by liyinan926** [comment]
We recently changed the way the driver pod is tracked. It used to be that the operator listed pods belonging to an application and went through the list of pods to find out the driver pod. Since the operator always sets the driver pod name if the user does not specify one, it makes more sense to keep track of the driver pod by name. The updated logic is that the driver pod name is stored in the status section while the job gets successfully submitted.

**Comment by xbaran** [comment]
Same problem here. 

Running on `master@62ac9668` and the sparkapplication is not getting its status updated thus `deleteSparkResources` obtain empty `PodName` from status and driver is not removed with sparkapplication.

It seems the problem starts with `55a1eebc`.

Also if there is a problem with status the driver stay alive after sparkapplication has been deleted.

It would be nice to add something like this: (sorry for non-idiomatic code I've no practice with golang)

```
	possibleNames := []string{app.Status.DriverInfo.PodName,string(*app.Spec.Driver.PodName),app.Name}
	var driverPodName = ""
	for i := range possibleNames {
		if len(possibleNames[i]) > 0 {
			driverPodName = possibleNames[i]
			break
		}
	}
```

**Comment by liyinan926** [comment]
We set the driver pod name in the status section when submitting the application. The driver pod name is set to either the one in `app.Spec.Driver.PodName` or an auto-generated one. So the name is set in a way similar to what you suggested above.

**Comment by liyinan926** [comment]
See #624.
