### ISSUE TITLE
Volume mounts on sidecars doesn't work unless mounted to driver first

### ISSUE THREAD

**Issue by bendrio** [GoogleCloudPlatform/spark-on-k8s-operator#561]
I'm very happy to see that sidecar support was added. I had actually hacked an other version of  the operator to have this functionality. My implementation was minimally invasive, but this approach is much better.

One thing I noticed, I cannot mount a volume unless it is also mounted on the driver container. I thought maybe the functionality was completely broken, but after also adding the mount to the driver first, I can also mount on the sidecar.

**Comment by liyinan926** [comment]
That's the current behavior. The driver pod spec gets mutated to add a volume only if the volume is requested to be mounted to the driver pod/container.

**Comment by bendrio** [comment]
Good to know!

**Comment by rucshah** [comment]
Hi,

We have use case where we need to mount secret to sidecar which should not be visible to driver container. Is there anyway to achieve it?
