### ISSUE TITLE
Could not create JVM error

### ISSUE THREAD

**Issue by sakthig** [GoogleCloudPlatform/spark-on-k8s-operator#564]
I have a custom spark image with 2.3.1 as base and my code inside the jar folder., built using docker-image-tool provided by spark.

I have been so far able to run this image using spark-submit and directly submitting it to a kubernetes cluster. 

Recently wanted to move on to spark-operator, so installed it using helm and created spark user. After this i was able to run spark-pi example.

Now when i try to submit my custom job it fails with this error.

```
++ id -u
+ myuid=0
++ id -g
+ mygid=0
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/ash
+ '[' -z root:x:0:0:root:/root:/bin/ash ']'
+ SPARK_K8S_CMD=driver
+ '[' -z driver ']'
+ shift 1
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
+ grep SPARK_JAVA_OPT_
+ readarray -t SPARK_JAVA_OPTS
+ '[' -n '' ']'
+ '[' -n '' ']'
+ case "$SPARK_K8S_CMD" in
+ CMD=(${JAVA_HOME}/bin/java "${SPARK_JAVA_OPTS[@]}" -cp "$SPARK_CLASSPATH" -Xms$SPARK_DRIVER_MEMORY -Xmx$SPARK_DRIVER_MEMORY -Dspark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS $SPARK_DRIVER_CLASS $SPARK_DRIVER_ARGS)
+ exec /sbin/tini -s -- /usr/lib/jvm/java-1.8-openjdk/bin/java -cp ':/opt/spark/jars/*' -Xms -Xmx -Dspark.driver.bindAddress=10.48.2.34
Invalid initial heap size: -Xms
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Am i missing anything with the setup ?

**Comment by liyinan926** [comment]
The `v1beta1-2.4.0` version of the operator only supports Spark 2.4.x. There were some significant changes in how Spark on Kubernetes works between Spark 2.3.x and Spark 2.4.x. If you install the operator through the Helm chart, it only works with Spark 2.4.x images.

**Comment by liyinan926** [comment]
Closing this unless you have other questions.
