### ISSUE TITLE
How to cleanup completed jobs

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#579]
Is there an expected workflow for cleaning up old jobs?

**Comment by liyinan926** [comment]
You mean cleaning up drivers of finished jobs or `SparkApplication` objects?

**Comment by AceHack** [comment]
both and if you deploy with a helm chart the helm chart

**Comment by liyinan926** [comment]
We recently added TTL support for `SparkApplication`s. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#setting-ttl-for-a-sparkapplication.

**Comment by liyinan926** [comment]
Closing this and please reopen if necessary.
