### ISSUE TITLE
Cannot set deploy-mode cluster

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#580]
It always uses client no matter what I put in SparkApplication for mode

**Comment by liyinan926** [comment]
The driver pod launched in the cluster mode runs `spark-submit` in client mode internally to run the driver program. That's why you will always see the `client` mode being used if you check the command run in the driver container. The client mode is not supported by the operator.

**Comment by AceHack** [comment]
Thank you
