### ISSUE TITLE
How do I set a memory limit

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#582]
I see
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/b0a4d1c923951161a753c1bee0837cac4b6bccea/pkg/apis/sparkoperator.k8s.io/v1beta1/types.go#L349

But that looks like memory request, I would like to set a memory limit

**Comment by liyinan926** [comment]
The memory limit is set to the same value as the memory request, see https://github.com/apache/spark/blob/master/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/BasicDriverFeatureStep.scala#L134.

**Comment by AceHack** [comment]
Thank you
