### ISSUE TITLE
Follow up for batch scheduler support changes.

### ISSUE THREAD

**Issue by TommyLike** [GoogleCloudPlatform/spark-on-k8s-operator#583]
There are some leftovers from patch #567, including.

- [x] 1. configure update for supporting different schedulers. see [comment](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/567#issuecomment-524406290)
- [x] 2. add document for how to use and configure
- [x] 3. add helm support for scheduler.
- [ ] 4. More testing.

**Comment by liyinan926** [comment]
@TommyLike do you have more PRs coming for this? If so, I will wait for those before cutting a new release for `v1beta2`.

**Comment by TommyLike** [comment]
@liyinan926 oh, please do the release, I will add them later.

**Comment by liyinan926** [comment]
@TommyLike are we pretty much done on Volcano integration?

**Comment by TommyLike** [comment]
@liyinan926  it looks good to me now, will add more pr if there is any issues/feature requests in the future. But those would not bound to this issue, so will close this.
