### ISSUE TITLE
problems with the image v2.4.0-v1beta1-latest

### ISSUE THREAD

**Issue by marcoverl** [GoogleCloudPlatform/spark-on-k8s-operator#593]
Hi there, when deploying the spark-operator with the last image of 2 days ago, it seems the ScheduledSparkApplication controller doesn't start:

`$ kubectl logs -n spark-operator sparkoperator-6d6f7cb466-bdp6b`
`[...]`
`+ exec /sbin/tini -s -- /usr/bin/spark-operator -logtostderr -enable-metrics=true -metrics-labels=app_type
I0830 09:25:07.378385      11 main.go:137] Starting the Spark Operator
I0830 09:25:07.405256      11 crd.go:73] Creating CustomResourceDefinition sparkapplications.sparkoperator.k8s.io
I0830 09:25:08.027041      11 crd.go:73] Creating CustomResourceDefinition scheduledsparkapplications.sparkoperator.k8s.io
I0830 09:25:08.658270      11 main.go:212] Enabling metrics collecting and exporting to Prometheus
I0830 09:25:08.658360      11 metrics.go:141] Started Metrics server at localhost:10254/metrics
I0830 09:25:08.660693      11 main.go:221] Starting application controller threads
I0830 09:25:08.660716      11 controller.go:154] Starting the workers of the SparkApplication controller
`

while with the v2.4.0-v1beta1-0.9.0 i get:

`$ kubectl logs -n spark-operator sparkoperator-6d6f7cb466-cfjjh`
`[...]`
`+ exec /sbin/tini -s -- /usr/bin/spark-operator -logtostderr -enable-metrics=true -metrics-labels=app_type
I0830 10:08:30.713604      11 main.go:96] Enabling metrics collecting and exporting to Prometheus
I0830 10:08:30.713862      11 metrics.go:141] Started Metrics server at localhost:10254/metrics
I0830 10:08:30.713875      11 main.go:100] Starting the Spark Operator
I0830 10:08:30.739025      11 crd.go:55] Creating CustomResourceDefinition sparkapplications.sparkoperator.k8s.io
I0830 10:08:31.348560      11 crd.go:55] Creating CustomResourceDefinition scheduledsparkapplications.sparkoperator.k8s.io
I0830 10:08:31.945928      11 controller.go:149] Starting the workers of the SparkApplication controller
I0830 10:08:32.046239      11 controller.go:96] Starting the ScheduledSparkApplication controller
I0830 10:08:32.146494      11 controller.go:102] Starting the workers of the ScheduledSparkApplication controller
`

**Comment by liyinan926** [comment]
This was fixed in #592 . The image has been updated with the fix. Please give it another try.

**Comment by marcoverl** [comment]
ok, it works now, thanks
