### ISSUE TITLE
Spark Drivers and Executors should have access to the CRD definitions

### ISSUE THREAD

**Issue by doctapp** [GoogleCloudPlatform/spark-on-k8s-operator#595]
Currently, the [spark-rbac.yaml](https://github.com/helm/charts/blob/master/incubator/sparkoperator/templates/spark-rbac.yaml) only allows access to pods and services. Our use case requires at least read access to the Spark Operator CRDs ("sparkapplications" and "scheduledsparkapplications").

Would adding "get" access on the CRDs make sense as the new default? Or at least configurable from within the Helm chart?

Thanks

**Comment by liyinan926** [comment]
It doesn't make sense to make it the default. Making the RBAC configurable through Helm makes more sense.

**Comment by doctapp** [comment]
Ok, thanks. I'll try to do a PR for this. Should this go here or to the helm repo (or both)?

**Comment by liyinan926** [comment]
Another option is to disable creation of the RBAC when you install through the chart. This way, you can create and use your own RBAC settings.

**Comment by doctapp** [comment]
Ok, will try this instead. Thanks

**Comment by liyinan926** [comment]
Closing this and feel free to reopen.
