### ISSUE TITLE
.spec.monitoring.prometheus.port behaves as a mandatory field 

### ISSUE THREAD

**Issue by breetasinha1109** [GoogleCloudPlatform/spark-on-k8s-operator#614]
Hi,

Although .spec.monitoring.prometheus.port is an optional field and defaults to 8090 if not specified, I am getting below error message in operator pod, when I don't specify .spec.monitoring.prometheus.port field in spark-job.yaml :- 

validation failure list:
spec.monitoring.prometheus.port in body must be of type integer: "null"

I can see default port 8090 being used in the spark-submit arguments output, however the spark-submit fails with above mentioned error.

Thanks,
Breeta

**Comment by liyinan926** [comment]
Thanks for raising this issue. Looks like the field is missing the tag `,omitempty`.

**Comment by abhisrao** [comment]
Thats right @liyinan926. With this change, we are not seeing the issue. Thanks.

**Comment by liyinan926** [comment]
Fixed in #622.
