### ISSUE TITLE
How to use downwardAPI to set envVars with spark operator.

### ISSUE THREAD

**Issue by varuns-zetaris** [GoogleCloudPlatform/spark-on-k8s-operator#620]
NAMESPACE:
         valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

gives error - "E0916 12:07:31.045873       1 reflector.go:205] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: Failed to list *v1beta1.SparkApplication: v1beta1.SparkApplicationList.Items: []v1beta1.SparkApplication: v1beta1.SparkApplication.Spec: v1beta1.SparkApplicationSpec.Driver: v1beta1.DriverSpec.SparkPodSpec: EnvVars: ReadString: expects " or n, but found {, error found in #10 byte of ...|ACCOUNT":{"valueFrom|..., bigger context ...|name":"workspace-secrets"}},"envVars":{"ACCOUNT":{"valueFrom":{"fieldRef":{"fieldPath":"metadata.nam|..."

**Comment by liyinan926** [comment]
We don't support using `fieldRef` with environment variables yet. The type of `envVars` is a `map[string]string`, which only accepts string environment variable values.
