### ISSUE TITLE
ResourceQuota enforcement Questions

### ISSUE THREAD

**Issue by akhurana001** [GoogleCloudPlatform/spark-on-k8s-operator#633]
Hi @liyinan926 @khogeland 

It is  really great to see that we now have ResourceQuota enforcement support.  A couple of quick questions: 

- I understand we currently only enforce quotas on requests and not limits.  At Lyft, we currently use limits quotas for cpu/memory as well and I was wondering we there is a plan to add quotas enforcement for limits as well or be able to configure this somehow.
- Also it looks like we  don't look at `spark-conf` currently . Since users can set driver/executor resources via `spark-conf` directly, I believe its worth to fallback to the conf if they aren't set in `PodSpec` .
- Also this is minor but any particular reason we use  `cpu` or `memory` resourceNames (https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/webhook/resourceusage/enforcer.go#L59) to enforce request quotas  and not `request.cpu` or `request.memory`  as per https://kubernetes.io/docs/concepts/policy/resource-quotas/#compute-resource-quota .

Let me know what you guys think about these and if these minor changes make sense.

**Comment by khogeland** [comment]
- This didn't seem necessary, as Kubernetes does not use limits for scheduling. The point of limits is to allow Pods to push over their allocated resources while there is no resource contention, so contraining limits may limit (heh) their usefulness. Is there a case I'm missing where this is required?
- I think the enforcer should assume the user is doing the correct thing (i.e. going through the SparkApplication API). If they bypass the RQ enforcer by using Spark conf, they'll still be subject to the RQ at pod creation time.
- Good catch, I think we're using deprecated resource names, let me try to find a relevant PR/discussion. Looks like we should be using `requests.*` in case the old names get removed.

**Comment by akhurana001** [comment]
> This didn't seem necessary, as Kubernetes does not use limits for scheduling. [edit: I think this is an objective improvement in terms of feature support and I'll look into it :)]

Thanks @khogeland  for the reply. I do believe there there is a use to having resource-quotas on limits in some scenarios. There can be a case when the existing pods (for one namespace) on a kubelet which are now using resources more than what they requested for and the kubelet will now reject a new pod because it can no longer support the requested resources for the new pod. This can cause one user/namespace to take over larger set of resources than what was expected despite having resource-quotas enforced.

> I think the enforcer should assume the user is doing the correct thing (i.e. going through the SparkApplication API). The rest of the operator works the same way, there's nothing preventing a user from shooting themselves in the foot by setting conflicting Spark configuration. If they bypass the RQ webhook, they'll still be subject to the RQ at pod creation time.

I think it's fine to say that the resources specified in the CRD spec will have a precedence over the spark_conf in-case of conflict etc. but I believe the operator still supports (?) specifying resources only via spark_conf and in that case, we should also provide that support in the RQ webhook in my opinion. 

I don't think these are  major changes to the webhook but in my opinion would be good additions to help help us cover all the cases.
