### ISSUE TITLE
The use of Volcano batch scheduler 

### ISSUE THREAD

**Issue by yuanchen8911** [GoogleCloudPlatform/spark-on-k8s-operator#637]
I used "_kubectl apply -f spark-operator.yaml"_ to create the spark operator instead of using helm. Everything worked fine with the default scheduler.  Now I wanted to try the Volcano batch scheduler. How should I set the _**enableBatchScheduler**_ flag in the yaml file? I added the following under sparkoperator in spark-operator.yaml , but it didn't work.  

_args:
\- -enableBatchScheduler=true_

Any suggestions? Thanks!

**Comment by liyinan926** [comment]
Have you enabled the mutating admission webhook by setting `-enable-webhook=true`? This feature needs the webhook to apply pod scheduler config to the driver and executor pods.

**Comment by yuanchen8911** [comment]
@liyinan926 Yes, I used spark-operator-with-webhook.yaml. The problem was that the operator failed to start after adding "**_enableBatchScheduler=true_**".  enableBatchScheduler is the parameter for helm install. I suspect we have a different name used in the yaml file just like **_enable-webhook_** for  **_enableWebhook**_. But what's the correct name?

Here is some additional information. 

NAME                             READY   STATUS             RESTARTS   AGE
**sparkoperator-5f9dc87556-j67tg   0/1     CrashLoopBackOff**   1          13s
sparkoperator-init-756hs         0/1     Completed          0          13s

The spark-operator pod description looks like

 Normal   Scheduled  3m21s                  default-scheduler  Successfully assigned spark-operator/sparkoperator-5f9dc87556-j67tg to minikube
  Normal   Pulled     2m37s (x4 over 3m19s)  kubelet, minikube  Successfully pulled image "gcr.io/spark-operator/spark-operator:v2.4.4-v1beta2-latest"
  Normal   Created    2m37s (x4 over 3m19s)  kubelet, minikube  Created container sparkoperator
  Normal   Started    2m37s (x4 over 3m19s)  kubelet, minikube  Started container sparkoperator
  **Warning  BackOff    2m (x8 over 3m16s)     kubelet, minikube  Back-off restarting failed container**
  Normal   Pulling    107s (x5 over 3m20s)   kubelet, minikube  Pulling image "gcr.io/spark-operator/spark-operator:v2.4.4-v1beta2-latest"

**Comment by liyinan926** [comment]
The cmd flag is `enable-batch-scheduler`.

**Comment by yuanchen8911** [comment]
Great, the spark operator is now running. Thanks!

A new problem arose. Spark-pi didn't start and the pod was waiting for enqueue forever.  

Type    Reason                 Age    From            Message
\----    ------                 ----   ----            -------
 Normal  SparkApplicationAdded  2m53s  spark-operator  **SparkApplication spark-pi was added, enqueuing it for submission**

I guess it may be related to Volcano's job queue. I tried default-queue, but it didn't work. How to specify the queue name in the spari-pi.yaml file?  Can anyone give an example? **batchSchedulerOptions: queue: "queue1"**

**Comment by liyinan926** [comment]
Yes

```
spec:
    batchSchedulerOptions:
        queue: <queue name>
```

**Comment by TommyLike** [comment]
hey @yuanchen8911 there is a demo regarding how to use queue: https://github.com/TommyLike/spark-operator-volcano-demo/tree/master/demos/queue

**Comment by TommyLike** [comment]
@yuanchen8911 recently I am working on integration testing on spark operator and volcano too. And found some issue regrading the cooperation:
1. Fix on spark operator: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/632  which was merged yesterday. and the image and the chart that I used which can work if you want a short way:
```
helm install incubator/sparkoperator --namespace spark-operator --set enableBatchScheduler=true --version 0.3.1 --set operatorImageName=tommylike/spark-operator --set operatorVersion=0.0.5 --set enableWebhook=true
```
2. Fix on volcano which makes gang-scheduling works: https://github.com/volcano-sh/volcano/pull/465.

**Comment by yuanchen8911** [comment]
Thanks, will try it. @TommyLike

**Comment by yuanchen8911** [comment]
Thanks a lot for your help. @TommyLike @liyinan926! It's working now.

**Comment by liyinan926** [comment]
Cool!

**Comment by leo7490** [comment]
I have set the batchschedular to "volcano",but id do not work,why ,
