### ISSUE TITLE
New CRD v1beta2 doesn't work on okd 3.11 (kubernetes 1.11)

### ISSUE THREAD

**Issue by Reamer** [GoogleCloudPlatform/spark-on-k8s-operator#640]
Hi,
I am using Openshift Origin 3.11 and had some problems with the new crd definitions.
Output, when creating the resources with `kubectl create -f sparkoperator.k8s.io_scheduledsparkapplications.yaml`
https://gist.github.com/Reamer/e5b1e591dc0db9c9cfa87250ff98ab77

I had to remove this line in both definitions to get it working:
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/5d9e8e924ff23a30fe3c64363f84865b0148a807/manifest/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml#L2566

Is this a bug of the validator or the custom resource definition?

Best Regards
Reamer

**Comment by liyinan926** [comment]
I have no issue creating the CRDs on GKE. I checked the CRD yamls generated by `controller-gen` in some other projects, and they all have the same type `object` for `metadata` and `spec`. I'm not sure if this is an issue of Openshift.

**Comment by liyinan926** [comment]
@Reamer I'm not aware of any other CRD yamls other than the ones under `manifest/crds`.

**Comment by liyinan926** [comment]
Actually found https://github.com/kubernetes/apiextensions-apiserver/issues/25. Not sure if it's related.

**Comment by skonto** [comment]
I hit the same issue.
