### ISSUE TITLE
Spark Application Metrics are NOT exported

### ISSUE THREAD

**Issue by VladimirKravtsov** [GoogleCloudPlatform/spark-on-k8s-operator#644]
Hi all!
Trying get the operator metrics scraping works, I figured out that the metrics are exported partially - [work-queue-metrics](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/v1beta2-1.0.0-2.4.4/docs/quick-start-guide.md#work-queue-metrics) are there, but [spark-application-metrics](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/v1beta2-1.0.0-2.4.4/docs/quick-start-guide.md#spark-application-metrics) are never been appeared in my Prometheus instance.

Looking into the operator logs, I see the message every time when i'm submitting new Spark application or re-creating previously submitted:
```
I1001 19:40:00.235304       9 sparkapp_metrics.go:144] Exporting metrics for spark-pi; old status: {  0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } { } map[] 0 0} new status: {  0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } { } map[] 0 0}
```
And due to old status and new status are equals, [the condition](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/v1beta2-1.0.0-2.4.4/pkg/controller/sparkapplication/sparkapp_metrics.go#L149) always is false and exporting is skipped.

**Comment by liyinan926** [comment]
@akhurana001.

**Comment by akhurana001** [comment]
I ran a quick sample job using the latest `v1beta2` operator and I don't see the status field at all in the CRD. 

I see that we started marking the `status` field as a `subresource` and  K8s ignores status sub-resource while doing a PUT so looks like `status` is never updated which will also explain no-metrics.
Ref: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#status-subresource .

**Comment by akhurana001** [comment]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/645 to fix this.

**Comment by liyinan926** [comment]
Thanks @akhurana001 for catching this!

**Comment by liyinan926** [comment]
This has been fixed.
