### ISSUE TITLE
Is there a way to deploy sparkoperator with clusterrole

### ISSUE THREAD

**Issue by kodelint** [GoogleCloudPlatform/spark-on-k8s-operator#652]
I am working on `RBAC` enabled K8S Cluster. My permissions are

```
kubectl auth can-i create roles --as=system:serviceaccount:some-name-space:tiller -n some-name-space

yes
```
```
kubectl auth can-i create clusterroles --as=system:serviceaccount:some-name-space:tiller -n some-name-space

no
```

Is there way to deploy `sparkoperator` with `clusterrole` or just use `role` restricted to `namespace`

**Comment by liyinan926** [comment]
The Spark Operator by default uses a `ClusterRole` because by default it watches `SparkApplication`s in all namespaces. You can limit the operator to watch `SparkApplication`s in a single namespace by setting the command flag `-namespace`. In this case, a `Role` in that namespace is sufficient.

**Comment by kodelint** [comment]
thanks for the response @liyinan926
