### ISSUE TITLE
Base spark images

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#653]
Please release the code/process for creating your spark base images

**Comment by liyinan926** [comment]
http://spark.apache.org/docs/latest/running-on-kubernetes.html#docker-images

**Comment by AceHack** [comment]
Are you just doing that manually, not part of any build pipeline?

**Comment by liyinan926** [comment]
We are not currently doing that as part of any build pipeline. Help on enabling that would be highly appreciated!
