### ISSUE TITLE
Multitasking issue

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#655]
When deploying two SparkApplications at the same time with configmaps, one of them ends up not mounting the configmap.

**Comment by AceHack** [comment]
One works fine, the other fails.

**Comment by AceHack** [comment]
I believe this issue was caused by something different, I have not been able to reproduce it.  Feel free to close if you don't see any value.  Thanks.

**Comment by liyinan926** [comment]
OK, feel free to reopen this if you find something suspicious within the operator.
