### ISSUE TITLE
Replacing the initializer with a mutating webhook

### ISSUE THREAD

**Issue by liyinan926** [GoogleCloudPlatform/spark-on-k8s-operator#66]

**Comment by liyinan926** [comment]
Ref: https://github.com/openshift/generic-admission-server.

**Comment by foxish** [comment]
I think this might be an alpha release blocker. WDYT? Alpha features like initializers aren't available on GKE by default for example.

**Comment by liyinan926** [comment]
Actually the initializer can be disabled by a flag if it's not really needed by the users. Yes, it won't work on non-alpha clusters. I plan to switch to use a mutation webhook in Q2.

**Comment by foxish** [comment]
I see - turn off customization and it should just work even without the initializer then. That makes sense; okay, maybe then we should document that as an experimental feature or something. The docs currently say "Spark Operator relies on Initializers and garbage collection support for custom resources which are in Kubernetes 1.8+." which probably needs some rewording.

**Comment by liyinan926** [comment]
Yes, agreed. We should make it clear that pod customization through initailizers is experimental.
