### ISSUE TITLE
Spark driver crashes with sigbus 0x7 

### ISSUE THREAD

**Issue by vishnugs** [GoogleCloudPlatform/spark-on-k8s-operator#670]
Hi

My spark driver crashes every few days with sigbus 0x7 error code. I took intermittent directory usage of /tmp it is hardly 10 mb. 

Spark operator it 0.8.0
And spark version is 2.4.0

fatal error has been detected by the Java Runtime Environment:#

 SIGBUS (0x7) at pc=0x00007fe179e1df4e, pid=15, tid=0x00007fe15ee19ae8#

JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)

Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)

Derivative: IcedTea 3.9.0

Distribution: Custom build (Tue Oct 23 11:27:22 UTC 2018)

Problematic frame:

V  [libjvm.so+0x5a0f4e]  JVM_handle_linux_signal+0x318cb#

Core dump written. Default location: /opt/abc/analytics/core or core.15#

An error report file with more information is saved as:

/opt/abc/analytics/hs_err_pid15.log#

If you would like to submit a bug report, please include

instructions on how to reproduce the bug and visit:

  http://icedtea.classpath.org/bugzilla

**Comment by liyinan926** [comment]
I suggest you post the question to the Spark user mailing list instead of here, where you will more likely get help or answers you are seeking.
