### ISSUE TITLE
Update the latest docker image.

### ISSUE THREAD

**Issue by MQasimSarfraz** [GoogleCloudPlatform/spark-on-k8s-operator#673]
I deployed the operator using the [manifests](manifests) in the tagged version (`v1beta2-1.0.1-2.4.4   `) but since the manifest were using `v2.4.4-v1beta2-latest`  I ran into some issues like scheduled jobs not running because of missing status field and it turns out that `v2.4.4-v1beta2-latest ` is outdated.  
```
gcr.io/spark-operator/spark-operator                                        v1beta2-1.0.1-2.4.4                           81813b1bc4b8        3 weeks ago         418MB
gcr.io/spark-operator/spark-operator                                        v2.4.4-v1beta2-latest                         146eeb215030        5 weeks ago         418MB

```
So we should update the image or if possible the tagged manifests have fixed docker image version rather than latest.

**Comment by liyinan926** [comment]
Ideally we should have a pipeline setup to automatically build, tag, and push the image whenever a PR gets merged. But we don't currently have one. I will manually update the image now.

**Comment by liyinan926** [comment]
Done.

**Comment by MQasimSarfraz** [comment]
Thansks @liyinan926 . Do you have any preference on how to setup it? I will be happy to contribute!
