### ISSUE TITLE
failed or deleted driver pod should delete sparkapplication?

### ISSUE THREAD

**Issue by dennischin** [GoogleCloudPlatform/spark-on-k8s-operator#674]
If a driver pod goes into failed state or I manually delete the driver pod (not the sparkapp), will the sparkapp get deleted as well?  Will the new ttl feature v1beta2 address my scenario?

**Comment by liyinan926** [comment]
As I said in the Slack channel, the `SparkApplication` object will not be deleted if you delete the driver pod. This is not the way the operator is designed to work. Garbage collection works in the reverse direction though, i.e., if you delete a `SparkApplication` object, the driver pod will be deleted. If you don't want `SparkApplication` objects of completed/failed driver pods to stay around, you can set a TTL for them, and the operator will delete them when the TTL expires.
