### ISSUE TITLE
Issue with enableResourceQuotaEnforcement

### ISSUE THREAD

**Issue by bkosuru** [GoogleCloudPlatform/spark-on-k8s-operator#675]
Hi,
I tried setting--set enableResourceQuotaEnforcement=true
to install operator using helm chart.

I am using GKE cluster. I could not run sparkapplication with this setting.
When I checked the spark-operator logs I noticed the following errors.

  reflector.go:125] k8s.io/client-go/informers/factory.go:132: Failed to list *v1.ResourceQuota: resourcequotas is forbidden: User "system:serviceaccount:spark-operator:spark-operator-sparkoperator" cannot list resource "resourcequotas" in API group "" in the namespace "spark-operator"

Is there anything else I need to do to use this setting? Thanks!

**Comment by liyinan926** [comment]
Thanks for reporting this. Looks like we are missing the necessary permissions for `ResourceQuota` in the cluster role used by the operator. Will add it.

**Comment by liyinan926** [comment]
This has been resolved in the Helm chart through https://github.com/helm/charts/pull/18501.

**Comment by bkosuru** [comment]
Now I am getting a different error. From spark-operator-sparkoperator pod logs:

validatingwebhookconfigurations.admissionregistration.k8s.io "spark-operator-sparkoperator-webhook-config" is forbidden: User "system:serviceaccount:spark-operator:spark-operator-sparkoperator" cannot get resource "validatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope
