### ISSUE TITLE
volcano with spark-operator

### ISSUE THREAD

**Issue by bkosuru** [GoogleCloudPlatform/spark-on-k8s-operator#676]
Anyone successfully installed volcano on gke cluster? I am having issues -

volcano-system   volcano-admission-fd4b955cf-pgxmv                                 0/1     ContainerCreating   0          14m
volcano-system   volcano-admission-init-7j92b                                      0/1     ImagePullBackOff    0          14m
volcano-system   volcano-controllers-57864457d4-gzzls                              0/1     ImagePullBackOff    0          14m
volcano-system   volcano-scheduler-7b68f9c55-d84q4                                 0/1     ImagePullBackOff    0          14m

**Comment by liyinan926** [comment]
Can you check which images are being used?

**Comment by bkosuru** [comment]
I am using  https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml to install volcano.

Here is the info I got from the pods:
volcano-scheduler:
 Failed to pull image "volcanosh/vc-scheduler:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

volcano-controllers:
 Failed to pull image "volcanosh/vc-controllers:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

volcano-admission-init:
Failed to pull image "volcanosh/vc-admission:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

volcano-admission:
MountVolume.SetUp failed for volume "admission-certs" : secrets "volcano-admission-secret" not found
Unable to mount volumes for pod "volcano-admission-fd4b955cf-652x2_volcano-system(bb051efe-ff18-11e9-9a06-42010a03d9e3)": timeout expired waiting for volumes to attach or mount for pod "volcano-system"/"volcano-admission-fd4b955cf-652x2". list of unmounted volumes=[admission-certs]. list of unattached volumes=[admission-certs volcano-admission-token-tgf6q]

**Comment by abelbarrera15** [comment]
@bkosuru , were you able to resolve this?
