### ISSUE TITLE
kubernetes 1.16 does not work now

### ISSUE THREAD

**Issue by veezhang** [GoogleCloudPlatform/spark-on-k8s-operator#677]
The alpha metadata.initializers field, deprecated in 1.13, has been removed.

https://github.com/kubernetes/kubernetes/pull/79504

**Comment by veezhang** [comment]
```
error: error validating "./spark-operator.yaml": error validating data: ValidationError(Deployment.spec.template.metadata): unknown field "initializers" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by liyinan926** [comment]
The field has been removed from all the manifests in this repo in #678. I also created a PR in the Helm chart repo to remove the field: https://github.com/helm/charts/pull/18520.
