### ISSUE TITLE
Resource Quota Enforcement does not seem to work

### ISSUE THREAD

**Issue by bkosuru** [GoogleCloudPlatform/spark-on-k8s-operator#690]
Hello,
I used the following options
--set enableResourceQuotaEnforcement=true --set enableWebhook=true --set webhookFailOnError=true
to install operator using helm chart.

I started 10 scheduledSparkApplications scheduled to run at the same time. All the drivers are running but executors remained in pending state forever as there are no cpu/memory resources to run executors.

See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/594. This feature is supposed to help mitigate the issue.

**Comment by liyinan926** [comment]
@khogeland.

**Comment by khogeland** [comment]
I'll take a look at this tomorrow, we haven't been using scheduled apps so there's likely some minor disparity in the ScheduledSparkApplication logic.
