### ISSUE TITLE
Dockerfile for gcr.io/spark-operator/spark-py:2.4.4 image

### ISSUE THREAD

**Issue by abinet** [GoogleCloudPlatform/spark-on-k8s-operator#705]
Where can I find the Dockerfile for gcr.io/spark-operator/spark-py:2.4.4 image ?

**Comment by echang0929** [comment]
docker pull gcr.io/spark-operator/spark-py:v2.4.4

**Comment by Jeffwan** [comment]
This should be default one from spark python binding Dockerfile (https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/bindings/python/Dockerfile)

**Comment by liyinan926** [comment]
Yes, the Dockerfile @Jeffwan referred to is the right one.

**Comment by liyinan926** [comment]
Closing this and feel free to reopen it if you have more questions.
