### ISSUE TITLE
Config port of kubernetes.default.svc from default 443 to 6443

### ISSUE THREAD

**Issue by MingzhouZhou** [GoogleCloudPlatform/spark-on-k8s-operator#706]
Hi folks,

I'm running the spark-pi example and the driver fails with error 
```
Caused by: java.net.ConnectException: Failed to connect to kubernetes.default.svc/xx.xxx.xxx.xxx:443
```
The api-server IP is correct but we use port 6443 not the default 443, I tried to set env variable KUBERNETES_SERVICE_PORT="6443", and spark.master is set correctly, but still get the same error. Is there any configuration that allows us to change the port to 6443? 

Many thanks!

**Comment by liyinan926** [comment]
Unfortunately, the master URL used by the driver pod is hard-coded. See https://github.com/apache/spark/blob/c4bbfd177b4e7cb46f47b39df9fd71d2d9a12c6d/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/Constants.scala#L82.

**Comment by junshi15** [comment]
can you add a port number instead of hard coded to default 443? We don't always use the default port. for example 
https://spark.apache.org/docs/latest/running-on-kubernetes.html#cluster-mode

$ bin/spark-submit \
    --master k8s://https://<k8s-apiserver-host>:<k8s-apiserver-port> \
    --deploy-mode cluster \
    --name spark-pi \
    --class org.apache.spark.examples.SparkPi \
    --conf spark.executor.instances=5 \
    --conf spark.kubernetes.container.image=<spark-image> \
    local:///path/to/examples.jar

**Comment by liyinan926** [comment]
@junshi15 the config option `--master` you referred to is for the Kubernetes submission client to create the driver pod. The Kubernetes scheduler backend running in the driver pod uses a hard-coded URL as defined at https://github.com/apache/spark/blob/c4bbfd177b4e7cb46f47b39df9fd71d2d9a12c6d/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/Constants.scala#L82.

**Comment by junshi15** [comment]
@liyinan926 can we make the scheduler use a different port than 443? I know it is hard coded to 443 right now. How much effort does it take to make it configurable? It would provide a lot of flexibility to be able to configure the port freely. Thanks.

**Comment by liyinan926** [comment]
It would be as simple as introducing a new config option for the master port.

**Comment by wackxu** [comment]
@liyinan926 I have made a pr to make KUBERNETES_MASTER_INTERNAL_URL configurable https://github.com/apache/spark/pull/27029, could you take a look at this?
