### ISSUE TITLE
Not possible to set "leader-election-lock-namespace" from helm chart

### ISSUE THREAD

**Issue by Toerq** [GoogleCloudPlatform/spark-on-k8s-operator#710]
As can be seen in, https://github.com/helm/charts/blob/master/incubator/sparkoperator/templates/spark-operator-deployment.yaml, the parameter "-leader-election-lock-namespace" cannot be set when installing via a helm chart.

**Comment by liyinan926** [comment]
We will fix the Helm chart. Thanks for reporting this issue.

**Comment by liyinan926** [comment]
This has been fixed in https://github.com/helm/charts/pull/20702.
