### ISSUE TITLE
sparkctl is simple. Does  it support blocking mode?

### ISSUE THREAD

**Issue by WorldSayHello** [GoogleCloudPlatform/spark-on-k8s-operator#711]
I want create a spark application and wait logging, but sparkctl didn't support it

**Comment by liyinan926** [comment]
If all you want is to stream the driver logs after your app gets submitted, you can use `sparkctl log <app name> --f`.

**Comment by jkleckner** [comment]
I suspect the OP is interested in something like https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/732
