### ISSUE TITLE
how does it integrate with jupyter hub ?

### ISSUE THREAD

**Issue by vivekjain123** [GoogleCloudPlatform/spark-on-k8s-operator#717]
how does it integrate with jupyter hub ? Can find any supporting document.

**Comment by liyinan926** [comment]
It currently doesn't work with Jupyter notebooks. The operator in its current form only supports running non-interactive applications in cluster mode.

**Comment by arghya18** [comment]
Is it still the case or changed?

**Comment by aniruddhdandotiya** [comment]
Hi, any updates on this?

**Comment by JWDobken** [comment]
https://github.com/kubeflow/spark-operator/issues/1652#issuecomment-2045185719
