### ISSUE TITLE
UnknownHostException when use hadoop ha url

### ISSUE THREAD

**Issue by erictanghu** [GoogleCloudPlatform/spark-on-k8s-operator#722]
I create hadoop config map contains my "hdfs-site.xml"
and i configured in my spark application yaml file.
spec.hadoopConfigMap
My jar file in hdfs and in my spark application i access a hdfs url
hdfs://ha-short-name/path
My jar file can download and run
but in my application i cannot access my hdfs url, why?
val textCount = spark.sparkContext.textFile(hdfs_path).filter(line => line.contains("hello")).count()

**Comment by liyinan926** [comment]
Did you add the ConfigMap to both the driver and executors?

**Comment by erictanghu** [comment]
> Did you add the ConfigMap to both the driver and executors?

I add "hadoopConfigMap" in "spec" of "app.yaml"
not "spec.driver" / "spec.executor"

**Comment by liyinan926** [comment]
Did you see the ConfigMap being mounted to the driver pods?

**Comment by erictanghu** [comment]
> Did you see the ConfigMap being mounted to the driver pods?

thx

i solve this proplem by setting "deps.files"
I rebuild the docker image and put my hdfs-site.xml inside
