### ISSUE TITLE
spark-submit pod resources should be configurable (in multi-version-support)

### ISSUE THREAD

**Issue by urihoenig** [GoogleCloudPlatform/spark-on-k8s-operator#730]
I'd like to be able to configure the spark-submit pod resources.
I'm wondering whether to use the driver's resources or define new parameters.
What do you think?

**Comment by liyinan926** [comment]
Why would you need to configure the resources of that pod, given that the only thing it does is to fire `spark-submit` and exit?

**Comment by urihoenig** [comment]
I've had my spark-submit pod OOMKilled. I guess that it depends on the image you're using.

**Comment by urihoenig** [comment]
#754 is a temporary solution until this is resolved
