### ISSUE TITLE
automate create serviceaccout if there is no serviceAccount specified in sparkapp yaml

### ISSUE THREAD

**Issue by xrmzju** [GoogleCloudPlatform/spark-on-k8s-operator#733]
roles need by spark lancher is  is fixed(https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/manifest/spark-rbac.yaml),  we need  create the sa manually now, which is not so convenient.

**Comment by xrmzju** [comment]
@liyinan926 ,what do you think about this idea?

**Comment by liyinan926** [comment]
This could be a feature for operator deployments that limits the operation of the operator to a single namespace. The feature could be enabled/disabled through a command-line flag. If enabled, the operator automatically creates the RBAC role and service account for that namespace, and automatically patches `SparkApplication` instances submitted to the namespace to use the service account. This helps save quite a lot of work from users.

**Comment by liyinan926** [comment]
@KoopaKing is this relevant?
