### ISSUE TITLE
How to specify external spark checkpoint directory in spark operator

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#734]
How to specify external spark checkpoint in spark operator?
Can we use persistence volume claim as checkpoint directory in spark operator submit command.

**Comment by shensonj** [comment]
@liyinan926

**Comment by liyinan926** [comment]
Yes, you can use a PersistentVolumeClaim for checkpointing. Simply add the PVC you want to use following the instruction in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#mounting-volumes, and then set your checkpoint (under the mount path of your persistent volume) using the right Spark config option under `spec.sparkConf`.

**Comment by shensonj** [comment]
@liyinan926 Is it possible to use host machines files system as checkpointLocation for **"spark.sql.streaming.checkpointLocation"** configuration

**Comment by liyinan926** [comment]
You can use a `hostPath` volume for that.

**Comment by shensonj** [comment]
Thanks @liyinan926 
Is it a good practice to use hostPath volume instead of HDFS?
Can you please provide an example on how to use hostPath volume?

**Comment by liyinan926** [comment]
I'm not familiar with how people usually setup the checkpointing location so unfortunately not sure it it's a good practice or not.

**Comment by liyinan926** [comment]
You might want to check out this article on checkpointing: https://banzaicloud.com/blog/spark-checkpointing/.
