### ISSUE TITLE
comparison with Databricks Spark on K8s?

### ISSUE THREAD

**Issue by ashish8work** [GoogleCloudPlatform/spark-on-k8s-operator#735]
Wondering if anyone has compared this with databricks spark on K8s impl. Or evaluated both?
What is the strength and weakness of each implementation?

**Comment by liyinan926** [comment]
Does Databricks has an implementation of Spark on K8S? I'm not aware of one.

**Comment by ashish8work** [comment]
Yes, that is the one I meant.

**Comment by liyinan926** [comment]
OK, that's in the OSS, so not an implementation from Databricks. Actually it's a community effort. Regarding your original question: the Spark Operator in this repo is built upon the K8S deployment mode and submits, runs, and monitors applications on Kubernetes using the Kubernetes deployment mode.

**Comment by ashish8work** [comment]
So how is it different than the other implementation? ie. when will I chose one over another?

**Comment by liyinan926** [comment]
The operator is not a different implementation. It's a way to run Spark apps on K8S in a K8S-native way, using Kubernetes custom resources and the operator pattern. It's runs apps using the Kubernetes deployment mode in Spark.
