### ISSUE TITLE
Sidecar not showing up

### ISSUE THREAD

**Issue by alexakr** [GoogleCloudPlatform/spark-on-k8s-operator#737]
Hi,
I am trying to use a sidecar container using Helm chart sparkoperator-0.6.0 v1beta2-1.0.1-2.4.4 but I don't see it working. According to [https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/558](url) it works with the previous v1beta1 version of spark operator.

**Comment by liyinan926** [comment]
Have you had the webhook enabled?

**Comment by alexakr** [comment]
No, it's disabled. Also it is not mentioned in "Using Sidecar Containers" section in the User Guide.

**Comment by liyinan926** [comment]
We will fix the documentation. But using sidecars requires the webhook to be enabled.

**Comment by alexakr** [comment]
Great, thanks. I will check.

**Comment by alexakr** [comment]
Works as expected.

**Comment by apiwoni** [comment]
@liyinan926 Documentation still mentions that webhooks are needed only for init-containers but but not sidecar containers.
Can you clarify it webhooks are still required for sidecars as well?
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#using-sidecar-containers

Thank you
