### ISSUE TITLE
adapt to spark 2.4 remote dependencies support

### ISSUE THREAD

**Issue by dynofu** [GoogleCloudPlatform/spark-on-k8s-operator#738]
start from this issue https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/404 
and trying to get s3a:// dependencies work,
i think the problem is because the change of how dependency are retrieved in spark 2.4

> The Spark driver running in a pod in a Kubernetes cluster no longer uses an init-container for downloading remote application dependencies, e.g., jars and files on remote HTTP servers, HDFS, AWS S3, or Google Cloud Storage. Instead, the driver uses spark-submit in client mode, which automatically fetches such remote dependencies in a Spark idiomatic way. 
- https://databricks.com/blog/2018/09/26/whats-new-for-apache-spark-on-kubernetes-in-the-upcoming-apache-spark-2-4-release.html
 
and this is confirmed by the removal of `spark.kubernetes.mountDependencies.filesDownloadDir` etc
https://spark.apache.org/docs/2.4.4/running-on-kubernetes.html#spark-properties
https://spark.apache.org/docs/2.3.4/running-on-kubernetes.html#spark-properties

this part might needs to change or have a compatible layer?
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L362

**Comment by liyinan926** [comment]
Yes, some legacy fields like the ones you referred to should be deprecated and removed.

**Comment by liyinan926** [comment]
Legacy init-container related fields will be removed in #750.
