### ISSUE TITLE
need resource file example of thrift server 

### ISSUE THREAD

**Issue by kansz** [GoogleCloudPlatform/spark-on-k8s-operator#743]
Hi guys,
I want to use JDBC to connect with spark thrift server.
But I can't find crd for this thrift server. 
I think a related example(like spark-pi.yaml) is necessary.
about thrift server in k8s, https://medium.com/@vrshu112/running-spark-thrift-server-in-kubernetes-4cc2bdc4b134 seems like useful

**Comment by liyinan926** [comment]
Have you tried the command in that Medium post?

**Comment by liyinan926** [comment]
I took a look at that post and the command wouldn't work without the patch in https://github.com/apache/spark/pull/22433, which didn't get in. So if you want to run the Thrift server on Kubernetes, you will need to run the server inside a pod in client mode, with a master URL  like `k8s://https://<$KUBERNETES_SERVICE_HOST>:<$KUBERNETES_SERVICE_PORT>`. Note that environment variables `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` are expected to be available in the pod where `start-thriftserver.sh` is run.

**Comment by kansz** [comment]
Thanks very much! The answer is very clear!

**Comment by liyinan926** [comment]
Thanks. Also we have a plan to support Spark SQL through the Thrift server as tracked in #744.
