### ISSUE TITLE
spark-kubernetes-driver fails to start with recent update spark:v2.4.4-gcs-prometheus

### ISSUE THREAD

**Issue by emiliauskas-fuzzy** [GoogleCloudPlatform/spark-on-k8s-operator#752]
Recent update to docker image gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus cause issue below when spark driver is starting:

Warning FailedMount 15s kubelet, gke-main-default-default-pool-3-b664dbbf-2b4f MountVolume.SetUp failed for volume "spark-conf-volume" : configmap "reports-1576912466574-driver-conf-map" not found
Normal SuccessfulAttachVolume 10s attachdetach-controller AttachVolume.Attach succeeded for volume "reports-state"
Normal Pulling 5s kubelet, gke-main-default-default-pool-3-b664dbbf-2b4f Pulling image "gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus"
Normal Pulled 5s kubelet, gke-main-default-default-pool-3-b664dbbf-2b4f Successfully pulled image "gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus"
Normal Created 5s kubelet, gke-main-default-default-pool-3-b664dbbf-2b4f Created container spark-kubernetes-driver
Warning Failed 5s kubelet, gke-main-default-default-pool-3-b664dbbf-2b4f Error: failed to start container "spark-kubernetes-driver": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/868741e6-23c1-11ea-842b-42010a840fd1/volumes/kubernetes.io~configmap/hadoop-configmap-volume\\\" to rootfs \\\"/var/lib/docker/overlay2/ddbb16b5118ff7f0fed577b2a4070e3026961bd0b6c3e292e942de588a8e2d22/merged\\\" at \\\"/var/lib/docker/overlay2/ddbb16b5118ff7f0fed577b2a4070e3026961bd0b6c3e292e942de588a8e2d22/merged/etc/hadoop/conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

it looks like the file was removed from the image? As a workaround - using gcr.io/spark-operator/spark:v2.4.5-SNAPSHOT-gcs-prometheus doesn't have this issue

**Comment by liyinan926** [comment]
Can you share your `SparkApplication` spec with the image `gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus`? The issue you ran into seems to have something with the `hadoopConfigMap` volume. I rebuilt and pushed the image again. Let me know if you still run into the same issue.

**Comment by emiliauskas-fuzzy** [comment]
Hey! Thanks for quick fix, it seems to be working now. For reference here is the spec and hadoopConfigMap below:

> kind: SparkApplication
metadata:
  name: reports
  namespace: default
spec:
  sparkVersion: 2.4.4
  type: Scala
  hadoopConfigMap: reports-hadoop-config
  sparkConf:
    "spark.scheduler.mode": FAIR
    "spark.scheduler.allocation.file": /tmp/spark-conf/fairscheduler.xml
  image: gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus
  imagePullPolicy: Always
  mainApplicationFile: gs://{{ .bucket-name }}/spark/reports/production/new-pipeline-reports-v391.jar
  mainClass: Reports
  mode: cluster
  restartPolicy:
    type: OnFailure
    onFailureRetries: 9999
    onFailureRetryInterval: 5
  arguments: []
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
      port: 8090
  deps:
    jars:
    - http://central.maven.org/maven2/com/google/guava/guava/27.1-jre/guava-27.1-jre.jar
  driver:
    coreLimit: 2000m
    cores: 1
    labels:
      version: 2.4.4
      app: reports-driver
    memory: 12g
    serviceAccount: spark-operator-sparkoperator
    volumeMounts:
      - mountPath: /tmp/keyfile
        name: gcs-keyfile
      - mountPath: /tmp/log4j
        name: log4j-properties
      - mountPath: /tmp/reports
        name: reports-state
      - mountPath: /tmp/spark-conf
        name: spark-conf
    javaOptions: -Dlog4j.debug=false -Dlog4j.configuration=file:///tmp/log4j/log4j.properties
  executor:
    cores: 3
    instances: 3
    labels:
      version: 2.4.4
      app: reports-executor
    tolerations:
      - key: executors
        operator: Equal
        value: "true"
        effect: NoSchedule
    memory: 20g
    volumeMounts:
      - mountPath: /tmp/keyfile
        name: gcs-keyfile
      - mountPath: /tmp/log4j
        name: log4j-properties
      - mountPath: /tmp/spark-conf
        name: spark-conf
    javaOptions: -Dlog4j.debug=false -Dlog4j.configuration=file:///tmp/log4j/log4j.properties
  volumes:
    - name: gcs-keyfile
      secret:
        secretName: gcs-keyfile
    - name: log4j-properties
      configMap:
        name: reports-log4j-config
    - name: spark-conf
      configMap:
        name: reports-spark-config
    - name: reports-state
      gcePersistentDisk:
        pdName: {{ .Values.volume }}
        fsType: ext4
`

hadoopConfigMap:

> apiVersion: v1
kind: ConfigMap
metadata:
  name: reports-hadoop-config
data:
  core-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    

    

    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://new-hdfs-namenode.default.svc.cluster.local:9000</value>
      </property>

      <property>
        <name>google.cloud.auth.service.account.enable</name>
        <value>true</value>
      </property>
      <property>
        <name>google.cloud.auth.service.account.json.keyfile</name>
        <value>/tmp/keyfile/key.json</value>
      </property>
      <property>
        <name>fs.gs.impl</name>
        <value>com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem</value>
      </property>
      <property>
        <name>fs.AbstractFileSystem.gs.impl</name>
        <value>com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem</value>
      </property>
      <property>
        <name>fs.gs.project.id</name>
        <value>stacktome-prod</value>
      </property>

      <property>
        <name>hadoop.http.staticuser.user</name>
        <value>root</value>
      </property>
    </configuration>
  dfs.exclude: ""
  hdfs-site.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    

    

    <configuration>
      <property>
        <name>dfs.replication</name>
        <value>3</value>
      </property>
      <property>
        <name>dfs.namenode.datanode.registration.ip-hostname-check</name>
        <value>false</value>
      </property>
      <property>
        <name>dfs.datanode.data.dir</name>
        <value>file:///mnt/dfs</value>
      </property>

      
      <property>
        <name>dfs.namenode.rpc-bind-host</name>
        <value>0.0.0.0</value>
      </property>
      <property>
        <name>dfs.namenode.servicerpc-bind-host</name>
        <value>0.0.0.0</value>
      </property>
      <property>
        <name>dfs.namenode.http-bind-host</name>
        <value>0.0.0.0</value>
      </property>
      <property>
        <name>dfs.namenode.https-bind-host</name>
        <value>0.0.0.0</value>
      </property>

      <property>
        <name>dfs.client.use.datanode.hostname</name>
        <value>true</value>
      </property>
      <property>
        <name>dfs.datanode.use.datanode.hostname</name>
        <value>true</value>
      </property>

      <property>
        <name>dfs.hosts.exclude</name>
        <value>/opt/hadoop/etc/hadoop/exclude/dfs.exclude</value>
      </property>

    </configuration>
  mapred.exclude: ""

**Comment by liyinan926** [comment]
Thanks for confirming and sharing the spec!
