### ISSUE TITLE
Must stop session in pyspark code

### ISSUE THREAD

**Issue by urihoenig** [GoogleCloudPlatform/spark-on-k8s-operator#756]
Lately, I've run into an issue that if I don't stop the spark session at the end of my mainApplicationFile, the driver (& executor, if I remember well) pod hangs instead of completing its execution.

I'm not sure if it began after I moved to using multi-version-support branch or after it was rebased on the master branch couple of weeks ago. Before that, the job completed as soon as it reached the end of the file (without closing the session).

**Comment by liyinan926** [comment]
Have you tried running the same app using a version based on the master branch?

**Comment by andrewgdavis** [comment]
I noticed this also, and now explicitly call sc.stop().  I don't know why the context is hanging around, but i do have "spark.streaming.stopGracefullyOnShutdown": "true" set to ensure checkpointing completes.
https://stackoverflow.com/questions/33217511/spark-streaming-context-hangs-on-stop

**Comment by liyinan926** [comment]
Looks like both of you ran into this issue: https://issues.apache.org/jira/browse/SPARK-27812.

**Comment by pudong7163** [comment]
@liyinan926 Thank you for providing such important info Yinan. Appreciate it! Is there a way we can get to know the eta for 2.4.5 from spark? I have done some search but no luck. Thank you!

**Comment by liyinan926** [comment]
@pudong7163 we are waiting for the official release of Spark 2.4.5 before putting up an official operator image based on that version. Stay tuned. Thanks!

**Comment by liyinan926** [comment]
A new release based on Spark 2.4.5 has been published: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/releases/tag/v1beta2-1.1.0-2.4.5. The Helm chart has also been updated to use the new release. Spark 2.4.5 images have also been published at gcr.io/spark-operator.
