### ISSUE TITLE
Can’t find API spec 

### ISSUE THREAD

**Issue by jamesthegiantpeach** [GoogleCloudPlatform/spark-on-k8s-operator#757]
It looks like the API spec link is giving a 404.

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api.md

I’m trying to figure out how to add an argument to the main class that I would like to run.

**Comment by liyinan926** [comment]
The API spec doc has been moved to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md.

**Comment by liyinan926** [comment]
Which link directed you to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api.md? Looks like some existing links need to be fixed.

**Comment by jamesthegiantpeach** [comment]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md

The first mention of api spec is a broken link. Thanks!

**Comment by liyinan926** [comment]
The broken link has been fixed.
