### ISSUE TITLE
readme could make it clear that you need to specify sparkJobNamespace if this isn't the same as the spark operator namespace

### ISSUE THREAD

**Issue by ChloeConnor** [GoogleCloudPlatform/spark-on-k8s-operator#760]
would be good for the readme to mention the flag s`parkJobNamespace=default` as below:
```
helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default
```
just incase someone doesn't go straight to the quick start guide.

This is also required to run any of the examples which all specify the default namespace.

**Comment by liyinan926** [comment]
Sure, will fix it.

**Comment by liyinan926** [comment]
Updated the README. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/README.md#installation.
