### ISSUE TITLE
Monitoring spark applications using spark operator

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#763]
@liyinan926  Is there any way to monitor spark applications using spark operator

**Comment by liyinan926** [comment]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#monitoring

**Comment by liyinan926** [comment]
Closing this and please posting further questions to our Slack channel.
