### ISSUE TITLE
How to specify config file in SparkApplication yaml file

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#764]
@liyinan926 We have a configuration file /opt/nsp/os/spark/spark-app/conf/windower/application.conf which is currently part of docker image. Some of the configuration in this file will change dynamically. What would be the best way to specify this file in 
SparkApplication yaml file? Please see below example file

apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: windower-app
  namespace: nsp
spec:
  type: Scala
  mode: cluster
  sparkVersion: 2.4.4
  image: orbw-artifactory.ca.alcatel-lucent.com:8081/nokia-nsp-docker-virtual/nspos-spark:19.11.0-rel.107
  mainClass: com.nokia.nsp.rtanalytics.baseline.spark.windower.WindowerApp
  mainApplicationFile: local:///opt/nsp/os/spark/spark-app/analytics-rtanalytics-baseline-spark-all.jar
  sparkConf:
    "spark.ui.port": "4045"
    "spark.sql.streaming.checkpointLocation": "/opt/window-data"
    "spark.shuffle.memoryFraction": "0"
    "spark.kubernetes.memoryOverheadFactor": "0.4"
  deps:
    files:
      - local:///opt/nsp/os/spark/spark-app/conf/windower/application.conf 
      - local:///opt/nsp/os/spark/spark-app/log4j.properties

**Comment by liyinan926** [comment]
You can put the file `application.conf` in a ConfigMap and mount it onto the driver pod. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#mounting-configmaps for details.

**Comment by liyinan926** [comment]
In the future, please consider posting questions to the Slack channel instead.

**Comment by shensonj** [comment]
@liyinan926 Thanks for the reply
How do I post questions to the Slack channel?Is there any link for that

**Comment by liyinan926** [comment]
https://kubernetes.slack.com/messages/CALBDHMTL
