### ISSUE TITLE
Accessing spark UI

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#765]
@liyinan926 I have got following service available after deploying "windower-app" spark application in kubernetes using spark operator. What is the URL I should use to access spark UI?

[root@rtanalytics opt]# kubectl describe svc windower-app-ui-svc
Name: windower-app-ui-svc
Namespace: nsp
Labels: sparkoperator.k8s.io/app-name=windower-app
sparkoperator.k8s.io/submission-id=8c5afbcc-eb13-46ea-a112-f06e55f39d11
Annotations:
Selector: spark-role=driver,sparkoperator.k8s.io/app-name=windower-app
Type: ClusterIP
IP: 10.100.125.48
Port: spark-driver-ui-port 4045/TCP
TargetPort: 4045/TCP
Endpoints: 192.169.80.143:4045
Session Affinity: None
Events:

**Comment by liyinan926** [comment]
You can either use `sparkctl forward` (see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/sparkctl#forward), or use `kubectl port-forward` to access the UI.

**Comment by shensonj** [comment]
root@rtanalytics ~]# kubectl port-forward windower-app-driver 4045:4045
Forwarding from 127.0.0.1:4045 -> 4045
Forwarding from [::1]:4045 -> 4045
^C[root@rtanalytics ~]# kubectl port-forward windower-app-driver 4040:4040
Forwarding from 127.0.0.1:4040 -> 4040
Forwarding from [::1]:4040 -> 4040
Handling connection for 4040
E0109 14:30:40.465418   22392 portforward.go:400] an error occurred forwarding 4040 -> 4040: error forwarding port 4040 to pod be746b020c603ecc77f6292f783e3c6030ca1d5c9c4d11d44255e1fb68a8b513, uid : exit status 1: 2020/01/09 14:30:40 socat[24270] E connect(5, AF=2 127.0.0.1:4040, 16): Connection refused
Handling connection for 4040
E0109 14:30:40.475967   22392 portforward.go:400] an error occurred forwarding 4040 -> 4040: error forwarding port 4040 to pod be746b020c603ecc77f6292f783e3c6030ca1d5c9c4d11d44255e1fb68a8b513, uid : exit status 1: 2020/01/09 14:30:40 socat[24272] E connect(5, AF=2 127.0.0.1:4040, 16): Connection refused
Handling connection for 4040
E0109 14:30:40.486216   22392 portforward.go:400] an error occurred forwarding 4040 -> 4040: error forwarding port 4040 to pod be746b020c603ecc77f6292f783e3c6030ca1d5c9c4d11d44255e1fb68a8b513, uid : exit status 1: 2020/01/09 14:30:40 socat[24273] E connect(5, AF=2 127.0.0.1:4040, 16): Connection refused
Handling connection for 4040

**Comment by shensonj** [comment]
kubectl port-forward is giving me following exception

[root@rtanalytics ~]# kubectl port-forward windower-app-driver 4040:4040
Forwarding from 127.0.0.1:4040 -> 4040
Forwarding from [::1]:4040 -> 4040
Handling connection for 4040
E0109 14:30:40.465418   22392 portforward.go:400] an error occurred forwarding 4040 -> 4040: error forwarding port 4040 to pod be746b020c603ecc77f6292f783e3c6030ca1d5c9c4d11d44255e1fb68a8b513, uid : exit status 1: 2020/01/09 14:30:40 socat[24270] E connect(5, AF=2 127.0.0.1:4040, 16): Connection refused
Handling connection for 4040
E0109 14:30:40.475967   22392 portforward.go:400] an error occurred forwarding 4040 -> 4040: error forwarding port 4040 to pod be746b020c603ecc77f6292f783e3c6030ca1d5c9c4d11d44255e1fb68a8b513, uid : exit status 1: 2020/01/09 14:30:40 socat[24272] E connect(5, AF=2 127.0.0.1:4040, 16): Connection refused
Handling connection for 4040

**Comment by liyinan926** [comment]
Were you trying to port forward to 4045 or 4040? Which port did you set for the UI?

**Comment by shensonj** [comment]
sparkConf:
    "spark.ui.port": "4045"

**Comment by liyinan926** [comment]
Then you should just use `kubectl port-forward windower-app-driver 4045:4045`.

**Comment by shensonj** [comment]
Ok.Thanks @liyinan926
