### ISSUE TITLE
Spark executor pods are getting killed with 'OOMKilled' status after running for couple of hours

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#766]
@liyinan926 Spark executor pods are getting killed with 'OOMKilled' status after running for a day.

20/01/10 00:51:07 INFO BlockManagerMaster: Removed 1 successfully in removeExecutor
20/01/10 00:51:07 INFO DAGScheduler: Shuffle files lost for executor: 1 (epoch 5874)
20/01/10 00:51:08 INFO ExecutorPodsAllocator: Going to request 1 executors from Kubernetes.
20/01/10 00:51:08 ERROR TaskSchedulerImpl: Lost executor 1 on 192.169.80.146:
The executor with id 1 exited with exit code 137.
The API gave the following brief reason: null
The API gave the following message: null
The API gave the following container statuses:

ContainerStatus(containerID=docker://15533f4f7a93f78e83736508706f8befc670b36b9593adb9827aa6e727dde0e3, image=orbw-artifactory.ca.alcatel-lucent.com:8081/nokia-nsp-docker-virtual/nspos-spark:19.11.0-rel.107, imageID=docker-pullable://orbw-artifactory.ca.alcatel-lucent.com:8081/nokia-nsp-docker-virtual/nspos-spark@sha256:ff1adec1bd2f7a6ab3780d3e66595e8fa8cf9da5dcf760848ee5309bf2f18e7a, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=executor, ready=false, restartCount=0, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://15533f4f7a93f78e83736508706f8befc670b36b9593adb9827aa6e727dde0e3, exitCode=137, finishedAt=2020-01-10T00:51:07Z, message=null, reason=OOMKilled, signal=null, startedAt=2020-01-09T17:46:39Z, additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={})

20/01/10 00:51:08 WARN TaskSetManager: Lost task 14.0 in stage 34309.0 (TID 3446368, 192.169.80.146, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason:
The executor with id 1 exited with exit code 137.
The API gave the following brief reason: null
The API gave the following message: null
The API gave the following container statuses:

ContainerStatus(containerID=docker://15533f4f7a93f78e83736508706f8befc670b36b9593adb9827aa6e727dde0e3, image=orbw-artifactory.ca.alcatel-lucent.com:8081/nokia-nsp-docker-virtual/nspos-spark:19.11.0-rel.107, imageID=docker-pullable://orbw-artifactory.ca.alcatel-lucent.com:8081/nokia-nsp-docker-virtual/nspos-spark@sha256:ff1adec1bd2f7a6ab3780d3e66595e8fa8cf9da5dcf760848ee5309bf2f18e7a, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=executor, ready=false, restartCount=0, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://15533f4f7a93f78e83736508706f8befc670b36b9593adb9827aa6e727dde0e3, exitCode=137, finishedAt=2020-01-10T00:51:07Z, message=null, reason=OOMKilled, signal=null, startedAt=2020-01-09T17:46:39Z, additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={})

20/01/10 00:51:08 WARN TaskSetManager: Lost task 16.0 in stage 34309.0 (TID 3446370, 192.169.80.146, executor 1): ExecutorLostFailure (executor 1 exited caused by one of the running tasks) Reason:
The executor with id 1 exited with exit code 137.
The API gave the following brief reason: null
The API gave the following message: null
The API gave the following container statuses:

ContainerStatus(containerID=docker://15533f4f7a93f78e83736508706f8befc670b36b9593adb9827aa6e727dde0e3, image=orbw-artifactory.ca.alcatel-lucent.com:8081/nokia-nsp-docker-virtual/nspos-spark:19.11.0-rel.107, imageID=docker-pullable://orbw-artifactory.ca.alcatel-lucent.com:8081/nokia-nsp-docker-virtual/nspos-spark@sha256:ff1adec1bd2f7a6ab3780d3e66595e8fa8cf9da5dcf760848ee5309bf2f18e7a, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=executor, ready=false, restartCount=0, state=ContainerState(running=null, terminated=ContainerStateTerminated(containerID=docker://15533f4f7a93f78e83736508706f8befc670b36b9593adb9827aa6e727dde0e3, exitCode=137, finishedAt=2020-01-10T00:51:07Z, message=null, reason=OOMKilled, signal=null, startedAt=2020-01-09T17:46:39Z, additionalProperties={}), waiting=null, additionalProperties={}), additionalProperties={})

Spark application definition used in spark operator

apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: windower-app
  namespace: nsp
spec:
  type: Scala
  mode: cluster
  sparkVersion: 2.4.4
  image: orbw-artifactory.ca.alcatel-lucent.com:8081/nokia-nsp-docker-virtual/nspos-spark:19.11.0-rel.107
  mainClass: com.nokia.nsp.rtanalytics.baseline.spark.windower.WindowerApp
  mainApplicationFile: local:///opt/nsp/os/spark/spark-app/analytics-rtanalytics-baseline-spark-all.jar
  sparkConf:
    "spark.ui.port": "4045"
    "spark.sql.streaming.checkpointLocation": "/opt/window-data"
    "spark.kubernetes.memoryOverheadFactor": "0.2"
  deps:
    files:
      - local:///opt/nsp/os/spark/spark-app/conf/windower/application.conf 
      - local:///opt/nsp/os/spark/spark-app/log4j.properties  
  volumes:
  - name: test-volume
    hostPath:
      path: "/opt/window-data"
      type: Directory
  driver:
    cores: 1
    memory: 5G
    serviceAccount: spark
    volumeMounts:
      - name: test-volume
        mountPath: "/opt/window-data"
  executor:
    cores: 2
    instances: 1
    memory: 10G
    volumeMounts:
      - name: test-volume
        mountPath: "/opt/window-data"
  restartPolicy:
    type: Always

**Comment by shensonj** [comment]
@mrow4a

**Comment by mrow4a** [comment]
@shensonj do you have some monitoring (prometheus or alike) enabled in your cluster that could allow you to see memory consumption on pod or node level ? You could maybe observe memory consumption and try to conclude something from it. It also depends on the workload you have, maybe it is enough to scale executors a bit. 

Anyways, I hardly doubt this issue has anything to do with spark operator (this repository), and is more related to kubernetes or spark itself. Maybe @liyinan926 also has something more on this to comment.

**Comment by liyinan926** [comment]
Agreed with @mrow4a. Adding monitoring should help. I don't think this has anything to do with the operator.
