### ISSUE TITLE
Spark Operator with webhook: validation failure list: status.terminationTime in body must be of type string: "null"

### ISSUE THREAD

**Issue by shrivardhan92** [GoogleCloudPlatform/spark-on-k8s-operator#768]
crds: latest version from master 
operator version: gcr.io/spark-operator/spark-operator:v2.4.4-v1beta2-latest

`SparkApplication.sparkoperator.k8s.io "pyspark-pi" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"sparkoperator.k8s.io/v1beta2", "kind":"SparkApplication", ******
"configMaps":[]interface {}{map[string]interface {}{"name":"spark-properties", "path":"/etc/spark/conf"}}, "coreLimit":"1200m", "cores":1, ***** "sparkVersion":"2.4.0", "type":"Python"}, "status":map[string]interface {}{"applicationState":map[string]interface {}{"state":"SUBMITTED"}, "driverInfo":map[string]interface {}{"podName":"pyspark-pi-driver", *****"webUIServiceName":"pyspark-pi-ui-svc"}, "executionAttempts":1, "lastSubmissionAttemptTime":"2020-01-13T22:44:43Z", "submissionAttempts":1, "submissionID":"aaff1e8a-4452-47ab-8188-93d9f53e88bd", "terminationTime":interface {}(nil)}}: validation failure list:
status.terminationTime in body must be of type string: "null"`

**Comment by liyinan926** [comment]
Thanks for reporting this! Looks like we are missing the `+nullable` tag for those `metav1.Time` fields. Should be fixed in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/769.

**Comment by liyinan926** [comment]
#769 has been merged. Please give the latest CRD manifests a try.
