### ISSUE TITLE
Disk pressure causes pod eviction 

### ISSUE THREAD

**Issue by sb2nov** [GoogleCloudPlatform/spark-on-k8s-operator#772]
Hi, 

One of my spark jobs keeps getting evicted by some nodes. Is there a way to request storage as well when running the job? In the API one can only request cores and memory.

```
20/01/14 23:50:38 WARN TaskSetManager: Lost task 5.0 in stage 0.0 (TID 5, 192.168.201.25, executor 4): ExecutorLostFailure (executor 4 exited caused by one of the running tasks) Reason:
The executor with id 4 exited with exit code -1.
The API gave the following brief reason: Evicted
The API gave the following message: The node was low on resource: ephemeral-storage. Container executor was using 160Ki, which exceeds its request of 0.
The API gave the following container statuses:
20/01/14 23:50:38 INFO TaskSetManager: Starting task 5.1 in stage 0.0 (TID 8, 192.168.252.135, executor 7, partition 5, PROCESS_LOCAL, 281589 bytes)
```

Are there workaround for this ? I'm using default emptyDir as the volume.

**Comment by sb2nov** [comment]
How do I set limits on `ephemeral-storage` ?

**Comment by liyinan926** [comment]
I assume you run out of your local scrape spaces, which are backed by `emptyDir` volumes by default?

**Comment by sb2nov** [comment]
yes but since one can't request `ephemeral-storage` from the API right now even if there are nodes with enough disk available the pod might get scheduled on some node that has low disk space since the default request size is `0`. It would be nice if the podSpec let you request storage as well.

**Comment by liyinan926** [comment]
Spark 3.0 supports using other types of volumes for scratch spaces. We recently added this in the operator. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#using-volume-for-scratch-space. Note this only works with Spark 3.0 based images.

**Comment by sb2nov** [comment]
Thank you. Is there an operator image for 3.0 ? Or I can just use the 2.4.4 release and install spark in the sparkApplication image?

**Comment by liyinan926** [comment]
You will need to use an operator image based on a Spark 3.0 base image.
