### ISSUE TITLE
Issue with webhook on fresh helm install

### ISSUE THREAD

**Issue by oliv3340** [GoogleCloudPlatform/spark-on-k8s-operator#774]
Hi,

Fresh install off spark-operator seams to not correctly deployed/configure the webhook part.
to be precise, can't mount any volumes/configmap on driver/executors and according to many threat, it's seams to be linked to a non properly working webhook. And off course I've got `OwnerReferences` missing in the driver's specs.

**Env:**
* centos 7.5
* k8s v1.15
* helm v2.12.2
* sparkoperator v1beta2-1.0.1-2.4.4

**Deployment with helm**:
`$ helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=spark-operator,enableWebhook=true`
I run my apps inside the spark-operator namespace directly.

**Running a test app with volume mounts**:
[https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-configmap.yaml](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-configmap.yaml)
with 
`kubectl apply -f my-file.yaml` after setting the good namespace off course.

**Results** :
* diver and executor working
* `OwnerReferences` missing in driver's specs
* Extra volumes and config not mounted
Even without creating the configMap before, I'm able to run the app without any failure, so the spark-operator don't create pods with the good specs at all.

**Expected behaviour** :
* `OwnerReferences` in driver's specs
* Volumes specifies in yaml files mounted

Am I right when I say than volume mounting depends on webhook ?
How can I try to fix it ?

An other thing, when I set `sparkJobNamespace=default`, I've got a permission denied exception when I try to apply an app whtih kubectl. Is that normal ?

Let me know if you need more informations.

Thanks !!

**Comment by liyinan926** [comment]
The webhook is not enabled by default. You need to add the option `--set enableWebhook=true` to your `helm install` command.

**Comment by oliv3340** [comment]
Hi, thanks,
I have enable the webhook, I just forgot to mention it, and forget it in the command I run (edited).
Sorry about that.

**Comment by liyinan926** [comment]
You can check the operator logs to debug. You may want to change the level of logging to `2` to see some of the webhook logs.

**Comment by oliv3340** [comment]
Thanks,
I don't have anything in the logs...
`+ [[ -z root:x:0:0:root:/root:/bin/ash ]]
+ exec /sbin/tini -s -- /usr/bin/spark-operator -v=2 -namespace=spark -ingress-url-format= -controller-threads=10 -resync-interval=30 -logtostderr -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpoint=/metrics -metrics-prefix= -enable-webhook=true -webhook-svc-namespace=spark -webhook-port=8080 -webhook-svc-name=sparkoperator-webhook -webhook-config-name=sparkoperator-webhook-config
I0117 10:39:18.854434       9 main.go:136] Starting the Spark Operator
I0117 10:39:18.854682       9 main.go:168] Enabling metrics collecting and exporting to Prometheus
I0117 10:39:18.854766       9 metrics.go:141] Started Metrics server at localhost:10254/metrics
I0117 10:39:18.855902       9 webhook.go:218] Starting the Spark admission webhook server
I0117 10:39:18.873316       9 webhook.go:424] Updating existing MutatingWebhookConfiguration for the Spark pod admission webhook
I0117 10:39:18.877920       9 main.go:210] Starting application controller goroutines
I0117 10:39:18.877942       9 controller.go:155] Starting the workers of the SparkApplication controller
I0117 10:39:18.978370       9 controller.go:96] Starting the ScheduledSparkApplication controller
I0117 10:39:19.078678       9 controller.go:102] Starting the workers of the ScheduledSparkApplication controller `

I thought the "Updating existing MutatingWebhookConfiguration" step didn't do anything but it seams to be fine actually :
`apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: MutatingWebhookConfiguration
  metadata:
    creationTimestamp: "2020-01-16T15:01:54Z"
    generation: 6
    name: sparkoperator-webhook-config
    resourceVersion: "615163"
    selfLink: /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/sparkoperator-webhook-config
    uid: 982a86f2-e347-4ed3-b66c-936dd5508783
  webhooks:
  - admissionReviewVersions:
    - v1beta1
    clientConfig:
      caBundle: ***encrypted***
      service:
        name: sparkoperator-webhook
        namespace: spark
        path: /webhook
        port: 443
    failurePolicy: Ignore
    matchPolicy: Exact
    name: webhook.sparkoperator.k8s.io
    namespaceSelector: {}
    objectSelector: {}
    reinvocationPolicy: Never
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      resources:
      - pods
      scope: '*'
    sideEffects: Unknown
    timeoutSeconds: 30
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""`

I'm new in k8s, and I simply follow the documentation to deploy my cluster with kubeadm (1 master and 2 nodes) and use calico as network plugin (v3.8.6 - latest).

Thanks

**Comment by liyinan926** [comment]
When you ran your `SparkApplication`, did you see any logs like the following: `Serving admission request`?

**Comment by oliv3340** [comment]
No I don't have anything that looks like `Server admission request`...

**Comment by liyinan926** [comment]
OK, I suggest looking into the API server logs if you have access to it.

**Comment by oliv3340** [comment]
Hi, you were right, I got this error in the API server logs :
```
W0124 13:36:39.748050       1 dispatcher.go:136] Failed calling webhook, failing open webhook.sparkoperator.k8s.io: failed calling webhook "webhook.sparkoperator.k8s.io": Post https://sparkoperator-webhook.spark.svc:443/webhook?timeout=30s: dial tcp 10.104.113.141:443: connect: connection refused
E0124 13:36:39.748129       1 dispatcher.go:137] failed calling webhook "webhook.sparkoperator.k8s.io": Post https://sparkoperator-webhook.spark.svc:443/webhook?timeout=30s: dial tcp 10.104.113.141:443: connect: connection refused
```
I've tried to cURL it with the svc IP but I've got a "connection refused" too. So it's not a DNS issue...

Here is the manifest of the svc :
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-01-17T10:39:12Z"
  labels:
    app.kubernetes.io/instance: sparkoperator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: sparkoperator
    helm.sh/chart: sparkoperator-0.6.1
  name: sparkoperator-webhook
  namespace: spark
  resourceVersion: "615090"
  selfLink: /api/v1/namespaces/spark/services/sparkoperator-webhook
  uid: 4e7dcf80-fe3f-44f3-9162-4f4398566e9e
spec:
  clusterIP: 10.104.113.141
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v1beta2-1.0.1-2.4.4
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by liyinan926** [comment]
This looks like an environment issue. One possibility is your environment doesn't allow exposing a service (with TLS) on port 8080.

**Comment by oliv3340** [comment]
I didn't think about that, but with `webhookPort: 443` I've got the exact same behaviour...
Same with the latest version off spark-operator img (v1beta2-1.0.2-2.4.5-SNAPSHOT).
