### ISSUE TITLE
Adding JVM arguments to spark submit command using operator

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#775]
Is it possible to add JVM arguments to spark submit command using operator ?
Is it possible to configure spark logs directory using spark-operator command

**Comment by shensonj** [comment]
@liyinan926 @mrow4a

**Comment by liyinan926** [comment]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#specifying-extra-java-options
You can put your log4j.properties into a ConfigMap and mount it to the Spark driver/executor pods, and point your config to the mounted file.
