### ISSUE TITLE
Two java process running inside spark executor POD while using spark operator

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#776]
@liyinan926 @mrow4a 

We use our own spark docker image inside spark operator config file.When spark application is submitted through operator,I see two java process running in my executor POD?

ash-4.4$ ps -ef | grep java
    1 nsp       0:00 /sbin/tini -s -- /usr/lib/jvm/java-1.8-openjdk/bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/executorheapdump.hprof -XX:+PrintClassHistogramBeforeFullGC -Dlog4j.configuration=file:/opt/spark/executor/log4j.properties -Xms4G -Xmx4G -cp :/opt/nsp/os/spark/jars/*:/opt/nsp/os/spark/spark-app/libs/extra/*:/opt/nsp/os/spark/spark-app/ignite/libs/*:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-indexing/*:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-log4j/*:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/ignite-spark.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/json4s-core_2.11-3.5.0.jar:/opt/nsp/os/spark/postgresql-0.0.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/hadoop-common-2.6.5.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/scala-library-2.11.12.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/scala-reflect-2.11.12.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spring/*:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-zookeeper/* org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@windower-app-1579217168203-driver-svc.nsp.svc:7078 --executor-id 1 --cores 2 --app-id spark-16663b99bcd64db8a452ffaef36a272f --hostname 192.169.80.150
   13 nsp       0:04 /usr/lib/jvm/java-1.8-openjdk/bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/executorheapdump.hprof -XX:+PrintClassHistogramBeforeFullGC -Dlog4j.configuration=file:/opt/spark/executor/log4j.properties -Xms4G -Xmx4G -cp :/opt/nsp/os/spark/jars/*:/opt/nsp/os/spark/spark-app/libs/extra/*:/opt/nsp/os/spark/spark-app/ignite/libs/*:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-indexing/*:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-log4j/*:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/ignite-spark.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/json4s-core_2.11-3.5.0.jar:/opt/nsp/os/spark/postgresql-0.0.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/hadoop-common-2.6.5.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/scala-library-2.11.12.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spark/scala-reflect-2.11.12.jar:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-spring/*:/opt/nsp/os/spark/spark-app/ignite/libs/ignite-zookeeper/* org.apache.spark.executor.CoarseGrainedExecutorBackend --driver-url spark://CoarseGrainedScheduler@windower-app-1579217168203-driver-svc.nsp.svc:7078 --executor-id 1 --cores 2 --app-id spark-16663b99bcd64db8a452ffaef36a272f --hostname 192.169.80.150

**Comment by jkleckner** [comment]
@shensonj Looks like the first one is the `tini` wrapper and not a `java` process at all.
