### ISSUE TITLE
is there an ubuntu/centos docker image? 

### ISSUE THREAD

**Issue by itamar-otonomo** [GoogleCloudPlatform/spark-on-k8s-operator#778]
I have been trying to prepare a docker image based on gcr.io/spark-operator/spark-py:v2.4.4.

my python code needs specific versions of scipy pandas and numpy. Alas, alpine is a bugger with installing those (using pip). It tries to compile from source and always fail (the web is strewn with horror stories and alleged solutions but none works).

Is there an image based on ubuntu? If there is not, is there a Dockerfile for the alpine image from which I'll be able to reverse engineer an ubuntu version? 

Thanks!

**Comment by liyinan926** [comment]
We don't currently have ubuntu based images. The Dockerfile we used is at https://github.com/apache/spark/tree/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark.

**Comment by jkleckner** [comment]
The image was switched on the v2.4.4 branch to `openjdk:8-jdk-slim` that is [debian based](https://github.com/docker-library/openjdk/blob/master/8/jdk/slim/Dockerfile) with this commit but it has not yet been released as v2.4.5:
* https://github.com/apache/spark/commit/ea8b5df47476fe66b63bd7f7bcd15acfb80bde78

Here is a gitlab.com WIP patch set you can use as a starting point to build spark snapshots on your own:
* https://gitlab.com/jkleckner/spark/tree/add-gitlab-ci-yml

**Comment by itamar-otonomo** [comment]
Thank you very much for your comments.
I'll definitely give it a go.
