### ISSUE TITLE
Spark-pi example fails when docker image starts as non-root user (AccessDeniedException)

### ISSUE THREAD

**Issue by apkerr** [GoogleCloudPlatform/spark-on-k8s-operator#782]
Hello,

I am attempting to run the spark-pi example in a docker container that is started as a non-root user. The user owns the path containing the spark software. 

I think I have the service account set up correctly, as the driver and executor pods are started successfully. I am getting this in the spark-pi-driver log:

`20/01/27 14:48:46 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, 192.168.216.156, executor 1): java.nio.file.AccessDeniedException: ./spark-examples_2.11-2.4.4.jar`

In the executor log, it looks like it's trying to copy the jar to to the root directory on the executor. But it doesn't have permission to access the root directory as a non-root user:

```
20/01/27 14:48:46 INFO Utils: Fetching spark://spark-pi-1580136512257-driver-svc.nsp.svc:7078/jars/spark-examples_2.11-2.4.4.jar to /var/data/spark-ebbc540f-5256-4ef4-8568-9b22233bcc42/spark-a3dadf1e-e21f-4df6-a985-75ff161e6c80/fetchFileTemp1549348282821390884.tmp
20/01/27 14:48:46 INFO Utils: Copying /var/data/spark-ebbc540f-5256-4ef4-8568-9b22233bcc42/spark-a3dadf1e-e21f-4df6-a985-75ff161e6c80/2218273401580136519157_cache to /./spark-examples_2.11-2.4.4.jar
20/01/27 14:48:46 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.nio.file.AccessDeniedException: ./spark-examples_2.11-2.4.4.jar
```

Is there a way to tell the executor where to copy the file? Or not to copy it at all, since it's the same image as the driver and the file is already accessible on the file system?

I have attached the logs from the driver and executor.

[spark-pi-executor.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/4117677/spark-pi-executor.log)

[spark-pi.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/4117654/spark-pi.log)

Thanks

**Comment by abhisrao** [comment]
Could you please share the yaml file that was used for submitting the job? Generally, if local:// is used along with the jar, it would search for the jar file inside the executor pods. Please refer to the example yaml file [here](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml)

**Comment by apkerr** [comment]
My yaml file looks exactly like the example, except that I'm using a different image file. In my docker image, I'm setting the USER to be a non-root user.

**Comment by apkerr** [comment]
I figured out that I needed to add a WORKDIR directive to my Dockerfile.
The docker image was coming up with a working directory of '/', and the non-root user did not have permission to write there.

Once I added a WORKDIR directive pointing to the home directory of the non-root user, the Spark-pi example worked properly.
