### ISSUE TITLE
Is it possible to set memory limit for spark application POD through operator?

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#783]
Is it possible to set memory limit for spark application POD through operator?  I would like to give higher memory for the container than JVM memory. Is there any way I can achieve this? I am having OOM error even though JAVA process looks fine.

@liyinan926 @mrow4a

**Comment by shensonj** [comment]
@jamesthegiantpeach

**Comment by liyinan926** [comment]
The memory limit of the driver/executor container is set to be the same as the memory request, taking in some overhead factor applied to the memory requested through `driver.memory` and `executor.memory`.

**Comment by liyinan926** [comment]
Closing this and please use the other issue (#781) for further questions.
