### ISSUE TITLE
FailedMount warning on spark driver pod

### ISSUE THREAD

**Issue by FloraZhang** [GoogleCloudPlatform/spark-on-k8s-operator#784]
Hi,

I'm trying spark-pi example after installing spark-operator and got FailedMount warning as below:

Events:
  Type     Reason       Age   From               Message
  Normal   Scheduled    38m   default-scheduler  Successfully assigned test/spark-pi-driver to vagrant
  Warning  FailedMount  38m   kubelet, vagrant   MountVolume.SetUp failed for volume "spark-conf-volume" : configmap "spark-pi-1580336050874-driver-conf-map" not found
  Normal   Pulling      38m   kubelet, vagrant   pulling image "gcr.io/spark-operator/spark:v2.4.4"
  Normal   Pulled       38m   kubelet, vagrant   Successfully pulled image "gcr.io/spark-operator/spark:v2.4.4"
  Normal   Created      38m   kubelet, vagrant   Created container
  Normal   Started      38m   kubelet, vagrant   Started container

---
API server log shows below error:

Jan 29 17:14:12 localhost kubelet[2422]: E0129 17:14:12.074851    2422 configmap.go:195] Couldn't get configMap test/spark-pi-1580336050874-driver-conf-map: configmap "spark-pi-1580336050874-driver-conf-map" not found
Jan 29 17:14:12 localhost kubelet[2422]: E0129 17:14:12.074995    2422 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/configmap/ad753d30-42e4-11ea-8a86-0800278ea6a2-spark-conf-volume\" (\"ad753d30-42e4-11ea-8a86-0800278ea6a2\")" failed. No retries permitted until 2020-01-29 17:14:12.574961424 -0500 EST m=+528355.407430497 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"spark-conf-volume\" (UniqueName: \"kubernetes.io/configmap/ad753d30-42e4-11ea-8a86-0800278ea6a2-spark-conf-volume\") pod \"spark-pi-driver\" (UID: \"ad753d30-42e4-11ea-8a86-0800278ea6a2\") : configmap \"spark-pi-1580336050874-driver-conf-map\" not found"

---
Running `kubectl get sparkapplications spark-pi -oyaml` shows executor failed as below:

```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"sparkoperator.k8s.io/v1beta2","kind":"SparkApplication","metadata":{"annotations":{},"name":"spark-pi","namespace":"test"},"spec":{"driver":{"coreLimit":"1200m","cores":1,"labels":{"version":"2.4.4"},"memory":"512m","serviceAccount":"callous-bronco-spark","volumeMounts":[{"mountPath":"/tmp","name":"test-volume"}]},"executor":{"cores":1,"instances":1,"labels":{"version":"2.4.4"},"memory":"512m","volumeMounts":[{"mountPath":"/tmp","name":"test-volume"}]},"image":"gcr.io/spark-operator/spark:v2.4.4","imagePullPolicy":"Always","mainApplicationFile":"local:///opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar","mainClass":"org.apache.spark.examples.SparkPi","mode":"cluster","restartPolicy":{"type":"Never"},"sparkVersion":"2.4.4","type":"Scala","volumes":[{"hostPath":{"path":"/tmp","type":"Directory"},"name":"test-volume"}]}}
  creationTimestamp: "2020-01-29T22:14:09Z"
  generation: 1
  name: spark-pi
  namespace: test
  resourceVersion: "638958"
  selfLink: /apis/sparkoperator.k8s.io/v1beta2/namespaces/test/sparkapplications/spark-pi
  uid: ac3a23d4-42e4-11ea-8a86-0800278ea6a2
spec:
  driver:
    coreLimit: 1200m
    cores: 1
    labels:
      version: 2.4.4
    memory: 512m
    serviceAccount: callous-bronco-spark
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  executor:
    cores: 1
    instances: 1
    labels:
      version: 2.4.4
    memory: 512m
    volumeMounts:
    - mountPath: /tmp
      name: test-volume
  image: gcr.io/spark-operator/spark:v2.4.4
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar
  mainClass: org.apache.spark.examples.SparkPi
  mode: cluster
  restartPolicy:
    type: Never
  sparkVersion: 2.4.4
  type: Scala
  volumes:
  - hostPath:
      path: /tmp
      type: Directory
    name: test-volume
status:
  applicationState:
    state: COMPLETED
  driverInfo:
    podName: spark-pi-driver
    webUIAddress: 10.103.84.38:4040
    webUIPort: 4040
    webUIServiceName: spark-pi-ui-svc
  executionAttempts: 1
  executorState:
    spark-pi-1580336050874-exec-1: FAILED
  lastSubmissionAttemptTime: "2020-01-29T22:14:12Z"
  sparkApplicationId: spark-019efecdf90a4552b87b65ec7bd46b22
  submissionAttempts: 1
  submissionID: 6dc38bcd-b673-497a-adfe-cb5dc212072e
  terminationTime: "2020-01-29T22:14:27Z"
```

I'm not sure if failedmount is the cause of executor failure.

Thanks,
wzhan

**Comment by FloraZhang** [comment]
`kubectl get configmap` shows that spark-pi-1580336050874-driver-conf-map is already created:
```
[tmp]$ kubectl get configmap
NAME                                     DATA   AGE
spark-pi-1580336050874-driver-conf-map   1      44m
[ tmp]$ kubectl describe configmap spark-pi-1580336050874-driver-conf-map
Name:         spark-pi-1580336050874-driver-conf-map
Namespace:    test
Labels:       <none>
Annotations:  <none>

Data
====
spark.properties:
----
#Java properties built from Kubernetes config map with name: spark-pi-1580336050874-driver-conf-map
#Wed Jan 29 22:14:11 GMT 2020
spark.kubernetes.executor.label.version=2.4.4
spark.executor.memory=512m
spark.driver.host=spark-pi-1580336050874-driver-svc.test.svc
spark.driver.blockManager.port=7079
spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=spark-pi
spark.kubernetes.executor.podNamePrefix=spark-pi-1580336050874
spark.kubernetes.container.image=gcr.io/spark-operator/spark\:v2.4.4
spark.jars=/opt/spark/examples/jars/spark-examples_2.11-2.4.4.jar
spark.kubernetes.driver.limit.cores=1200m
spark.kubernetes.submitInDriver=true
spark.driver.memory=512m
spark.kubernetes.container.image.pullPolicy=Always
spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true
spark.submit.deployMode=cluster
spark.kubernetes.executor.label.sparkoperator.k8s.io/submission-id=6dc38bcd-b673-497a-adfe-cb5dc212072e
spark.kubernetes.submission.waitAppCompletion=false
spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true
spark.kubernetes.resource.type=java
spark.kubernetes.python.pyFiles=
spark.master=k8s\://https\://10.96.0.1\:443
spark.executor.cores=1
spark.kubernetes.authenticate.driver.serviceAccountName=callous-bronco-spark
spark.kubernetes.driver.pod.name=spark-pi-driver
spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=spark-pi
spark.executor.instances=1
spark.kubernetes.namespace=test
spark.app.id=spark-019efecdf90a4552b87b65ec7bd46b22
spark.kubernetes.driver.label.sparkoperator.k8s.io/submission-id=6dc38bcd-b673-497a-adfe-cb5dc212072e
spark.app.name=spark-pi
spark.kubernetes.driver.label.version=2.4.4
spark.driver.cores=1
spark.driver.port=7078

Events:  <none>
```

**Comment by liyinan926** [comment]
The error you saw is kind of confusing, but not a real error that would cause the app to fail. What happened here was that Kubernetes backend creates the driver pod first before creating the other Kubernetes resources the driver depends on including the ConfigMap. So if the driver pod starts up running before the ConfigMap gets created and available for mounting/consumption, you will see that error. But the error is typically transient and the driver pod will be able to start running successfully eventually once the ConfigMap is ready. In your job, the driver actually completed successfully, and the failure state reported the executor pod is due to this [bug](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/725). A fix for the bug will be included in the next release. So for now please ignore the reported state of the executors. If the `applicationState` is `COMPLETED`, it means the application has completed successfully.

**Comment by FloraZhang** [comment]
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

helm version
```
Client: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.0", GitCommit:"05811b84a3f93603dd6c2fcfe57944dfa7ab7fd0", GitTreeState:"clean"}
```

**Comment by FloraZhang** [comment]
> The error you saw is kind of confusing, but not a real error that would cause the app to fail. What happened here was that Kubernetes backend creates the driver pod first before creating the other Kubernetes resources the driver depends on including the ConfigMap. So if the driver pod starts up running before the ConfigMap gets created and available for mounting/consumption, you will see that error. But the error is typically transient and the driver pod will be able to start running successfully eventually once the ConfigMap is ready. In your job, the driver actually completed successfully, and the failure state reported the executor pod is due to this [bug](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/725). A fix for the bug will be included in the next release. So for now please ignore the reported state of the executors. If the `applicationState` is `COMPLETED`, it means the application has completed successfully.

Right the driver completed successfully. 
Ok I'll ignore the state of the executor. Thanks for the explanation:)

**Comment by agungsaputro** [comment]
I also experienced the same thing. Can you help me
