### ISSUE TITLE
Applying a hive-site.xml for using AWS Glue

### ISSUE THREAD

**Issue by itamar-otonomo** [GoogleCloudPlatform/spark-on-k8s-operator#786]
I am attempting to make my spark jobs use the AWS Glue metastore.

No matter how I try, it won't click.
I have compiled the FOSS version of the glue client libraries ([link](https://github.com/awslabs/aws-glue-data-catalog-client-for-apache-hive-metastore)) and created my very own docker image.

Whenever I try to access a glue table, the program fails, and by looking at the driver log I see that my hive configurations are being ignored (hive looks for the table in its local metastore and finds it not).

I tried sending the necessary hive configuration and a few ways:
* pass "hive.metastore.client.factory.class": "com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory" to sparkConf
* create a hive-site.xml in /opt/spark/conf in the image (I think it is deleted by the operator)
* use deps.files and give the file location from local:/// and s3a:// locations
* Add a HIVE_CONF_DIR env var with the location of the hive-site.xml
* whole lot of other desperate things

But whatever I try, hive tries to use the local metastore and fails.

What am I missing here?

**Comment by liyinan926** [comment]
The Kubernetes scheduler backend internally creates a ConfigMap that stores Spark configurations and mount in at the path `/opt/spark/conf` in the driver and executor containers and set `SPARK_CONF_DIR` to point to it. So whatever you put under `/opt/spark/conf` in your image gets shadowed. I suggest you use store `hive-site.xml` under a different path.

**Comment by liyinan926** [comment]
See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/216.
