### ISSUE TITLE
setting the Environment variable for containers using spark operator

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#790]
@liyinan926

I would like to set the environment variable for spark executor & driver containers.How can I achieve this ? The following configuration doesn't seem to be working.
 
 executor:
    cores: 1
    instances: 1
    memory: 1G
    memoryOverhead: 1g
    **env:
     - name: NSS_SDB_USE_CACHE
       value: "no"**

**Comment by liyinan926** [comment]
See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md#sparkoperator.k8s.io/v1beta2.SparkPodSpec, and look for `env` and `envVar`. `envVar` is deprecated and will be replaced by `env` in the future, but for now you can still use it if you just want to set simply string env vars.

**Comment by SandishKumarHN** [comment]
@liyinan926  when is the env option is getting released ?? I'm using 2.4.5-v1beta2. env is not working.

**Comment by sakshi-bansal** [comment]
env is not working for me as well. The spark application config shows it:  driver:
    env:
      - name: ENV1
        value: VAL1

But the env variables are not created inside the pods.
