### ISSUE TITLE
New release of the operator since spark 2.4.5 is officially cut 

### ISSUE THREAD

**Issue by sb2nov** [GoogleCloudPlatform/spark-on-k8s-operator#796]
Hi was just wondering when the next release would be.

**Comment by liyinan926** [comment]
Will cut a release today.

**Comment by ahazrat** [comment]
https://console.cloud.google.com/gcr/images/spark-operator/GLOBAL/spark-py@sha256:c1f21b8b6f4f0ad7b25177ad086b7eaf7d96747940b0fe2e8dc6ca688c85db76/details?tab=info

**Comment by liyinan926** [comment]
A new release of the operator has been cut: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/releases/tag/v1beta2-1.1.0-2.4.5. The image has also been published at `gcr.io/spark-operator/spark-operator:v1beta2-1.1.0-2.4.5`.

**Comment by sb2nov** [comment]
Thank you 👍
