### ISSUE TITLE
Deploy spark application from AWS Lambda.

### ISSUE THREAD

**Issue by krisshub** [GoogleCloudPlatform/spark-on-k8s-operator#797]
Hi,
I am trying to deploy spark application from AWS Lambda. Is there a way create spark cluster and submit the application without using helm.

I found an approach using 
https://github.com/radanalyticsio/spark-operator

where the SparkApplication yaml automatically takes care of the cluster creation.

Can we do the same in "spark-on-k8s-operator"

**Comment by liyinan926** [comment]
We don't currently have any plan to handle cluster creation, and we don't currently support Spark scheduler backends other than Kubernetes.

**Comment by krisshub** [comment]
> We don't currently have any plan to handle cluster creation, and we don't currently support Spark scheduler backends other than Kubernetes.

Thank you for the response
