### ISSUE TITLE
sparkConfigMap not picked up

### ISSUE THREAD

**Issue by uprush** [GoogleCloudPlatform/spark-on-k8s-operator#806]
Although spec.sparkConfigMap is mounted at /etc/spark/conf with SPARK_CONF_DIR pointing to it, the configurations (e.g., /etc/spark/conf/spark-defaults.conf) won't be picked up by executors. 

This can be reproduced by:
1. Put hadoop s3a setting in file spark-defaults.conf
2. Create a ConfigMap using spark-defaults.conf
3. Set spec.sparkConfigMap to that ConfigMap.
4. Launch a Spark job accessing S3, job would fail error 'Caused by: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by SimpleAWSCredentialsProvider', indicating s3a setting is not picked up.

This is likely because in /opt/entrypoint.sh, it directly invokes org.apache.spark.executor.CoarseGrainedExecutorBackend, which seems to be not respecting SPARK_CONF_DIR.

**Comment by liyinan926** [comment]
The Kubernetes backend internally creates a ConfigMap storing the Spark configuration, mounts it to `/opt/spark/conf` in the driver pod, and sets `SPARK_CONF_DIR` to point to the path. This is in conflict with the `sparkConfigMap`. See #216 for more details.

**Comment by liyinan926** [comment]
The workaround for now is to use field `sparkConf` or `hadoopConf`.
