### ISSUE TITLE
Support for non-amd64 architectures.

### ISSUE THREAD

**Issue by HindrikStegenga** [GoogleCloudPlatform/spark-on-k8s-operator#809]
Currently the operator does not support architectures besides amd64. This is a request to add builds and docker images which support other architectures. (Arm, Arm64, s390x etc.)

**Comment by ringtail** [comment]
@HindrikStegenga Would like to run spark on AWS A1?

**Comment by HindrikStegenga** [comment]
No, I wanted to run it on a Pi. I don't need to do that anymore though.
