### ISSUE TITLE
how to redirect the log from spark-submit?

### ISSUE THREAD

**Issue by tingweiwu** [GoogleCloudPlatform/spark-on-k8s-operator#813]
when I run other applicaiton use pod. I may set the cmd as the following

```
/bin/bash run.sh 2>&1 | tee ./run.log; test ${PIPESTATUS[0]} -eq 0
```
then I can get the logs from `kubectl logs ...` when the pod is existing
and also get the log from run.log file when the pod is deleted

is there a solution to redirect the console log from spark-submit  when I use SparkApplication?

**Comment by liyinan926** [comment]
We don't currently support redirecting the logs of `spark-submit` as it is executed programmatically by the operator. Also we run `spark-submit` in a fire-and-forget way, i.e., we run `spark-submit` to launch the application (create the driver pod) and exit without waiting for the app to complete.
