### ISSUE TITLE
Support Priority Classes for drivers and executors

### ISSUE THREAD

**Issue by vishwaskumar58** [GoogleCloudPlatform/spark-on-k8s-operator#821]
We want to have a feature so that we are able to define a priority class on driver and executors to enable pod priority and preemption. 

https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

**Comment by ringtail** [comment]
@vishwaskumar58 Would you like to submit a pr or wait for enhancement?

**Comment by ringtail** [comment]
@vishwaskumar58 I would like to make it work. PR is on the air.
