### ISSUE TITLE
Cannot expose driver and executor metrics in pyspark job

### ISSUE THREAD

**Issue by rjonczy** [GoogleCloudPlatform/spark-on-k8s-operator#825]
Hi,

I would like to scrape prometheus metrics from driver and executors, while using this in my pyspark job.

I have seen example in Scala using image: `gcr.io/spark-operator/spark:v2.4.5-gcs-prometheus`, i am using following image to run my pyspark job:

```
FROM gcr.io/spark-operator/spark-py:v2.4.5
```

However, I am not seeing a way how to expose those metrics from pyspark. 
Or is it not supporter?

Thanks,
Robert

**Comment by liyinan926** [comment]
You will need to use a Spark image similar to the one created from https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/spark-docker/Dockerfile. `gcr.io/spark-operator/spark:v2.4.5-gcs-prometheus` doesn't have the Prometheus support built in.

**Comment by alexakr** [comment]
Looking at deployment configuration, the port 8090 is not exposed since it is missing in the "Ports:" line:
    `prometheus.io/port: 8090`
    `Ports:         7078/TCP, 7079/TCP, 4040/TCP`

**Comment by liyinan926** [comment]
Xref: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/476.

**Comment by alexakr** [comment]
Right, so until the port is not exposed, the whole "monitoring" section is useless.

**Comment by liyinan926** [comment]
@rjonczy @alexakr PR #935 will fix this and expose the port.
