### ISSUE TITLE
java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by polyzos** [GoogleCloudPlatform/spark-on-k8s-operator#831]
I'm building my jar file that i need to deploy using the spark-operator. Even though when i run the jar file locally or on databricks everything works as expected, when i try to run it using the spark operator i get a `java.lang.ClassNotFoundException`.
What i do is i copy my jar file to the sparkoperator pod on the path `/opt/spark/examples/jars` along with the other jars and then in the SparkApplication file i add the following:
```
  mainClass: full.path.tomy.MainClass
  mainApplicationFile: "local:///opt/spark/examples/jars/myjarfile-1.0.0.jar"
```
i have also double checked my unzipping the jar to check that everything is in there. 
Also if inside the pod, i try to run the jar using:
```
java -cp myjarfile-1.0.0.jar full.path.tomy.MainClass
```
again everthing works as expected. I find the issue only when trying to deploy on the operator

**Comment by polyzos** [comment]
Ok, so i just noticed that even though i add the jar in the directory it can't find it.
```
20/03/05 12:41:14 WARN DependencyUtils: Local jar /opt/spark/examples/jars/myjarfile-1.0.0.jar does not exist, skipping.
20/03/05 12:41:14 WARN SparkSubmit$$anon$2: Failed to load full.path.tomy.MainClass
java.lang.ClassNotFoundException :full.path.tomy.MainClass
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:806)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/03/05 12:41:14 INFO ShutdownHookManager: Shutdown hook called
20/03/05 12:41:14 INFO ShutdownHookManager: Deleting directory /tmp/spark-ed74d85d-9ee6-4d20-9c5c-d9152669407b
```

**Comment by apkerr** [comment]
I have just noticed the same thing. I'm getting ClassNotFound exceptions when the jars are available in the $SPARK_HOME/jars directory.

**Comment by shensonj** [comment]
@liyinan926 are you aware of any recent changes causing this issue?

**Comment by liyinan926** [comment]
The jar needs to be in the image used by the driver, not the operator.

**Comment by polyzos** [comment]
@liyinan926 can you please elaborate on that? I'm not sure i understand what I should do. If maybe you could break it down in steps, it would be awesome

**Comment by liyinan926** [comment]
You will need to build a custom Spark image for your driver, and add your jar to that image., similar to what is done in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/spark-docker/Dockerfile.

**Comment by apkerr** [comment]
In my case, I was missing a jar that my jar depended on. So it isn't the same issue.

**Comment by liyinan926** [comment]
Closing this and feel free to reopen or discuss further in the Slack channel.

**Comment by polyzos** [comment]
@liyinan926 i tried to use the spark-docker/Dockerfile.
At first it has this line 
```
ENTRYPOINT ["/opt/entrypoint.sh"]
```
but it cant find the script..
So i modified the file to add the following:
```
COPY metis-streams-1.0.0.jar $SPARK_HOME/

COPY entrypoint.sh /opt/
RUN chmod +x /opt/entrypoint.sh
ENTRYPOINT ["/opt/entrypoint.sh"]
```

After that i get an error that no `/usr/bin/spark-operator` is available on the pod logs.

**Comment by apkerr** [comment]
@liyinan926 Could I get an invite to the Slack channel?

**Comment by anandchangediya** [comment]
Any updates on this issue?
I have created a custom image with Spark as base

`FROM spark:latest
COPY my-jar-6.0.0-jar-with-dependencies.jar /opt/spark/jars/`

I am still getting java.lang.ClassNotFoundException. When I create a container of the same image using docker commands I can see the dependencies added
