### ISSUE TITLE
Delta Lake Support

### ISSUE THREAD

**Issue by polyzos** [GoogleCloudPlatform/spark-on-k8s-operator#833]
Is it possible to update the spark-image in order to have hadoop binaries 2.9.2? so that it can be used along with the delta lake since it needs hadoop binaries 2.9.2+

**Comment by polyzos** [comment]
@liyinan926

**Comment by liyinan926** [comment]
You can try building your own custom image based on https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile.
