### ISSUE TITLE
Client mode examples?

### ISSUE THREAD

**Issue by mattdornfeld** [GoogleCloudPlatform/spark-on-k8s-operator#842]
I see that client mode is an option when submitting a SparkApplication, but I can't seem to find an example of client mode being used. When I try to set client mode myself on the spark-pi example I get an error. Any working examples of creating a SparkApplication in client mode? I'm hoping to connect a Jupyter notebook to a created Spark cluster.

**Comment by liyinan926** [comment]
Although `client` mode is an option, we have never figured out what it means for the operator to support the client mode, so it's currently not usable.

**Comment by Bole0331** [comment]
Hi, can you help me understand why even when I set deploy-mode as "cluster" it's still shown as "client" model in my Spark-UI environments?
