### ISSUE TITLE
How does the Spark Operator handle executor failure?

### ISSUE THREAD

**Issue by mattdornfeld** [GoogleCloudPlatform/spark-on-k8s-operator#851]
Let's say the node hosting an executor fails, what happens to the executor? Will the Spark operator reschedule it on another node?

**Comment by pudong7163** [comment]
My understanding is that Spark on k8s relies on k8s for scheduling. In such a case, k8s schedules the failed executors to other nodes if possible. I think the spark operator only checks driver, not executors.

**Comment by liyinan926** [comment]
The operator doesn't manage the executor pods directly. The driver (in k8s mode) is a controller of executor pods, and it is responsible for restarting executors that failed for non-app reasons, e.g., node problems.
