### ISSUE TITLE
Auto-scaling is not working in Spark Jobs using spark-on-k8s-operator

### ISSUE THREAD

**Issue by manojdandy** [GoogleCloudPlatform/spark-on-k8s-operator#854]
Hi,
I have deployed my spark cluster using spark-on-k8s-operator on AWS EKS Ec2 instance.
Its deployed with spark 2.4.5 latest version.
Spark Job Is working on Kubernetes EKS Cluster.
I have submitted the job using a YAML file and now I want to implement auto-scaling for spark jobs.
As it is a deployment for spark-operator but there is no deployment for spark job that is submitted by the YAML file.
As we can scale only the deployments and deployment should be able to scale spark containers/pods. But that is not happening.

Kindly help me with how to autoscale spark jobs. 

Thanks,
Manoj

**Comment by liyinan926** [comment]
Auto scaling for Spark is very different from auto scaling for serving workloads that are typically run using Deployments. Spark executors are created and managed by the driver pod, which serves as a custom k8s controller for executor pods. Spark has what's called dynamic resource allocation, which is a auto scaling mechanism for executors. Spark on Kubernetes, however, doesn't support dynamic resource allocation yet. So for now, there's no way to auto scale Spark jobs.
