### ISSUE TITLE
spark executor head dump not completed when jvm oom

### ISSUE THREAD

**Issue by erictanghu** [GoogleCloudPlatform/spark-on-k8s-operator#861]
I specified executor jvm options
-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
when executor java.lang.OutOfMemoryError happened, a java_pid22.hprof file generate.
i got "Dumping heap to /tmp/java_pid22.hprof ..." message in executor console before container exit.

but the hprof file size only 200M, this is much more smaller than my heap memory.
the hprof file is not completed and MAT gui tool cannot read it.
why?

**Comment by gauravbh1** [comment]
@erictanghu Did you ever resolve this? Is yes then can you please provide some pointers.
