### ISSUE TITLE
Linear search does not account for the case when the container is not found

### ISSUE THREAD

**Issue by zzvara** [GoogleCloudPlatform/spark-on-k8s-operator#868]
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/2e4559eac0f593398d5e19ef85bfc6a5df032033/pkg/webhook/patch.go#L167

When the container not found with the name, hardcoded into the configuration, it should log an error that it was not able to patch the Pod `spec`. Currently, this results in an NPE and panic. In addition, provide a hint to the users that the problem around container naming may be fixed using `spark.kubernetes.executor.podTemplate`.

**Comment by liyinan926** [comment]
Yeah, it needs to be guarded against that. Will definitely fix that. However, the operator will not use the pod template support in Spark 3.0 and has no plan to support that given that it already has an API for most pod configuration needs. So there won't be a way for users to use a custom container name for the driver and container.

**Comment by zzvara** [comment]
I see. `spark.kubernetes.executor.podTemplate` is required to make Spark 3.0.0-rc1 work with the current Spark Operator.

**Comment by liyinan926** [comment]
No, `spark.kubernetes.executor.podTemplate` is not required. It's just an optional way to customize the executor pods using some YAML template. One can still use Spark 3.0.0 with the operator.

**Comment by zzvara** [comment]
Spark 3.0.0-rc1 names the executor pod as "spark-kubernetes-executor". Spark Operator has a configuration constant for that, "executor". Spark Operator searches for "executor" container name, but the container name is "spark-kubernetes-executor".

Thus, the following line of code will result in an NPE:

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/2e4559eac0f593398d5e19ef85bfc6a5df032033/pkg/webhook/patch.go#L177

**Comment by liyinan926** [comment]
I wasn't aware of the renaming of the default executor container name. It was simply `executor` in Spark 2.4.x and 2.3.x. We can use a different default value depending on the value of `spec.sparkVersion`.

**Comment by zzvara** [comment]
Sure, that can work!

Apart from that, we are running Spark 3.0.0-rc1 in production with the Spark Operator as we speak without any issues for 12 Spark streaming jobs.

**Comment by liyinan926** [comment]
Good to know that! Will create a PR with the fix.

**Comment by liyinan926** [comment]
@zzvara FYI: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/876.

**Comment by zzvara** [comment]
Thanks, when it goes live I throw out my podTemplates! :-D
