### ISSUE TITLE
Specifying less than 1 CPU core in operator

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#874]
@liyinan926 

Is it possible to specify less than 1CPU core in spark operator? 
Just want to use only 0.4 core instead of 1CPU core.

driver:
    coreLimit: 1200m
    cores: 1

**Comment by liyinan926** [comment]
`coreRequest` in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md#driverspec accepts Kubernetes cpu core values, e.g., 0.5 or 500m. This is only available in Spark 3.0.
