### ISSUE TITLE
executor stuck in pending status because unable to mount checkpoint directory

### ISSUE THREAD

**Issue by FloraZhang** [GoogleCloudPlatform/spark-on-k8s-operator#877]
Hi,

I'm attempting to bring up a k8s 3 node cluster. 

I'm using pvc for checkpoint volume. Driver and executor share the same pvc. The spark executor pod is stuck in pending status due to a pvc issue described below. Seems that when a spark app driver pod is on one node in the cluster, and the executor is on another node, this happens.

From kubectl describe pod nsp-anomaly-detector-app-1587138762221-exec-1

```
Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Warning FailedMount 13s (x27 over 58m) kubelet, rob-node2 (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[checkpoint-volume], unattached volumes=[nsp-tls-zip application-conf-configs-vol sparklog checkpoint-volume default-token-m56sz ignite-configs-vol log4j-configs-vol spark-local-dir-1 shared-tls-volume]: timed out waiting for the condition
```

In one case, one of the driver & executor pods were on the same node, and I didn't see this issue.

Is there any way to get around this issue?

Thanks,
Flora

**Comment by liyinan926** [comment]
You can use `spec.{driver|executor}.nodeSelector` or `spec.{driver|executor}.affinity` to try make the driver and executor pods scheduled onto the same node. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#using-pod-affinity.

**Comment by FloraZhang** [comment]
@liyinan926 Thank you. PodAffinity works in my case :)
