### ISSUE TITLE
Need to mount EBS per Spark executor Pod

### ISSUE THREAD

**Issue by Bole0331** [GoogleCloudPlatform/spark-on-k8s-operator#882]
Hey @liyinan926, I'm trying to mount EBS (AWSElasticBlockStore) for my spark application, and it seems we can only mount one volume for all executor pods. Does spark-on-k8s-operator support mounting EBS volume per Spark executor pod? And since EBS only allows `ReadWriteOnce` as access mode, containerCreation for executor pods always fail when they are in multiple nodes. Would like to hear your inputs.

**Comment by liyinan926** [comment]
This is expected. The operator mounts the exact volume specified in an `SparkApplication` object to every executor pods. What you want to achieve is similar to what the `StatefulSet` controller does, i.e., creating `PersistentVolumeClaim`s based on a template and add one `PersistentVolumeClaim` to each pod. This is not something the operator currently supports.
