### ISSUE TITLE
Spark-application CRD can be managed using role/rolebinding instead of clusterrole/clusterrolebinding?

### ISSUE THREAD

**Issue by yarrasree** [GoogleCloudPlatform/spark-on-k8s-operator#888]
We want to know if spark-application CRD can be managed using role/rolebinding instead of clusterrole/clusterrolebinding. We were under the impression that if CRD is namespace scoped, then role/rolebinding is sufficient. Here is the reference link.
https://thorsten-hans.com/custom-resource-definitions-with-rbac-for-serviceaccounts#create-the-custom-resource-definition

But we’re facing permission issues when we try to access spark-application CRD using role/rolebinding. Here is the error:
reflector.go:125] github.com/GoogleCloudPlatform/spark-on-k8s-operator/pkg/client/informers/externalversions/factory.go:119: Failed to list *v1beta2.SparkApplication: sparkapplications.sparkoperator.k8s.io is forbidden: User "system:serviceaccount:yarra:yarra-spark-operator" cannot list resource "sparkapplications" in API group "sparkoperator.k8s.io" at the cluster scope

**Comment by liyinan926** [comment]
CRD is non-namespaced, i.e., cluster-scoped.

**Comment by yarrasree** [comment]
Thanks @liyinan926 for your comment. We see that SparkApplication CRD definition mentions the scope as “Namespaced”. Pasting the snippet of the definition below for reference. Wanted to understand what does it mean?

apiVersion: apiextensions.k8s.io/v1beta1
	kind: CustomResourceDefinition
	metadata:
	  creationTimestamp: null
	  name: sparkapplications.sparkoperator.k8s.io
	spec:
	  group: sparkoperator.k8s.io
	  names:
	    kind: SparkApplication
	    listKind: SparkApplicationList
	    plural: sparkapplications
	    shortNames:
	    - sparkapp
	    singular: sparkapplication
	  scope: Namespaced

**Comment by liyinan926** [comment]
The `Namespaced` scope means custom resource instances of the kind `SparkApplication` are namespace scoped. But CRDs that define custom resource kinds are always non-namespaced.
