### ISSUE TITLE
Spark Operator Installation Verification

### ISSUE THREAD

**Issue by marwanfahmi** [GoogleCloudPlatform/spark-on-k8s-operator#894]
Hi,

I'm trying to use the spark operator on a k8s local cluster. I'm running MiniKF, a Kubeflow local deployment that's running k8s 1.14; how can I verify if the spark operator is installed or not?

I tried to go with the Installation in the Quick Start Guide here: (https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md), but I get this error: create: failed to create: namespaces "spark-operator" not found.

Also tried to execute a sample spark job, I get error: unable to recognize "spark_test.yaml": no matches for kind "SparkApplication" in version "sparkoperator.k8s.io/v1beta1"

Can you please guide me here? Thanks a lot.

**Comment by marwanfahmi** [comment]
I was able to install, had to manually create the k8s namespace: "kubectl create namespace spark-operator" before the helm install command.

I was also able to submit a job using "kubectl apply -f ./spark-pi.yaml" getting sparkapplication.sparkoperator.k8s.io/pyspark-pi created.

Could you please advice on how to monitor and get info about the submitted jobs? Thanks.

**Comment by liyinan926** [comment]
You can run `kubectl get sparkapplication <app name> -o=yaml` or `kubectl describe sparkapplication <app name>` to check a submitted job.
