### ISSUE TITLE
How we can set the memory resources limits and the CPU request with spark operators?

### ISSUE THREAD

**Issue by Armelabdelkbir** [GoogleCloudPlatform/spark-on-k8s-operator#901]
i'm new in spark-operator i'm confused how to setup the resources request and limits in YAML file for example in my case i have request 1000m of memory for driver pod, but what about limits, it is unbounded ? and for CPU cores : 1 and coreLimit: 1200m what about the request ?

**Comment by liyinan926** [comment]
Memory limits for the driver and executor pods are set internally by the Kubernetes scheduler backend in Spark, and calculated as the value of `spark.{driver|executor}.memory` + memory overhead.
