### ISSUE TITLE
The labels added into metadata of spark jobs are not added to its driver and executor pods.

### ISSUE THREAD

**Issue by sahil-sawhney** [GoogleCloudPlatform/spark-on-k8s-operator#905]
Hi team, I am using Kustomize to submit my spark jobs for several environments. The labels that I try to patch in are applied to the metadata of my SparkApplication but are not applied to my worker and executor pods. I need these labels to easily filter over the pods on the basis of the environment. Following is an example to demonstrate the scenario:

```apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
  labels:
    environment: APPLIED_BY_KUSTOMIZE
spec:
  driver:
    labels:
      version: DRIVER_VERSION
  executor:
    labels:
      version: EXECUTOR_VERSION
```
Now when I try to do
`kubectl get pods my-spark-driver --show-labels`

The output is
```
NAME                READY   STATUS    RESTARTS   AGE   LABELS
my-spark-driver     1/1     Running   0          29h   version=DRIVER_VERSION, some_auto_generated_labels
```

The driver pod contains "version: DRIVER_VERSION" as the label but not "environment: APPLIED_BY_KUSTOMIZE". And the same behavior for executor as well. This causes a lot of problems to filter the drivers and executors on the basis of the environment and some other use cases.

Please help with this. Thank You

**Comment by gongx** [comment]
I think it's worth fixing(populate applicate labels to driver and executors pods, by default). It will have the consistent behavior as other default operators, such as deployment, replicaset, etc (although there are some differences on yaml file). The only use case which will be potentially broken is that we want application labels totally different from its driver and executors. But I doubt that is a real use case.

For the fix itself:
- We could add label object under spec, and force the two values(from spec.label and metadata.label) are always the same, just like other default operators do. But I think it is un-necessary and breaks the backward-compatibility
- We could simply let driver/executor inherent the application labels from the values of metadata.label which should be enough. 
  - Maybe, we could add separate flag(something like 'labelsInherent') under spec block, by default the value is False and if the user want to populate the application labels, they can set as True. But I really do not think this is necessary.

 @liyinan926 I would like to hear your suggestions on this one. If you are ok with it, i can start a RP on it.

**Comment by liyinan926** [comment]
@gongx Thanks for the detailed write up. I think option 2 sounds good as it would be backward compatible. I don't think it's necessary to have a field that controls label inheritance either. This could be as simple as applying labels in the `SparkApplication` resources and applying the ones defined in driver and executor specs. Labels defined in driver and executor specs will override the ones in `metadata` of the `SparkApplication` resource. Appreciate and looking forward to the PR.

**Comment by gongx** [comment]
@liyinan926 could you take a look at this PR: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/940, please?

**Comment by liyinan926** [comment]
@gongx reviewed and merged your PR. Thanks for fixing this issue!
