### ISSUE TITLE
[Resiliency] Driver pod restart issue

### ISSUE THREAD

**Issue by AliGouta** [GoogleCloudPlatform/spark-on-k8s-operator#907]
We have a bench of spark streaming jobs that we intend to move from mesos/marathon to GKE. We plan to use this spark-k8-operator since it fits most of our requirements. However, we need to understand some strange behaviour regarding the restart policy of the driver after a manual deletion of the driver pod + some cases where the driver simply crashes due to some external issues, i.e. kafka goes down. We expect that the application simply restarts but it seems to be not (spark executors restart fine after a manual deletion).

**Environments:**

spark image 2.4.5
v1beta2-1.1.1-2.4.5
GKE 1.15.9-gke.24

**Steps which I followed:**

1- Create resource via kubectl apply -f apps/xlogs : Application starts fine
2- Delete the driver manually.

**Expected behavior:**
A new driver pod would be restarted as per the restart policy.

**Actual behavior:**
Driver and executor pods got deleted and the application seems to remain in `PENDING_RERUN` state.

**Restart policy configuration :**
A policy I found in another issue which seems to be resolved

 ```
  restartPolicy:
    type: Always
    onFailureRetries: 1000000
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 3
    onSubmissionFailureRetryInterval: 10
```

**Logs from spark-operator:**

```
I0508 21:48:15.300668       9 controller.go:590] Trying to update SparkApplication sparkjob-dev-ali/xlogs-normalizer-k8s, from: [{spark-742418ab5d74460d97680a31d167e353 5b8dc360-5fec-40ca-aea7-c3c1f8bcb7a3 2020-05-08 21:45:17 +0000 UTC 2020-05-08 21:48:02 +0000 UTC {xlogs-normalizer-k8s-ui-svc 4040 172.19.101.187:4040 xlogs-normalizer-k8s-ui-ingress xlogs-normalizer-k8s.internalapis.caas.phenix-noprd.carrefour.com xlogs-normalizer-k8s-driver} {PENDING_RERUN driver pod failed with ExitCode: 143, Reason: Error} map[xlogs-normalizer-k8s-1588974316139-exec-1:FAILED xlogs-normalizer-k8s-1588974316139-exec-10:FAILED xlogs-normalizer-k8s-1588974316139-exec-2:FAILED xlogs-normalizer-k8s-1588974316139-exec-3:FAILED xlogs-normalizer-k8s-1588974316139-exec-4:FAILED xlogs-normalizer-k8s-1588974316139-exec-5:FAILED xlogs-normalizer-k8s-1588974316139-exec-6:FAILED xlogs-normalizer-k8s-1588974316139-exec-7:FAILED xlogs-normalizer-k8s-1588974316139-exec-8:FAILED xlogs-normalizer-k8s-1588974316139-exec-9:FAILED] 1 1}] to [{spark-742418ab5d74460d97680a31d167e353 5b8dc360-5fec-40ca-aea7-c3c1f8bcb7a3 2020-05-08 21:45:17 +0000 UTC 2020-05-08 21:48:02 +0000 UTC {xlogs-normalizer-k8s-ui-svc 4040 172.19.101.187:4040 xlogs-normalizer-k8s-ui-ingress xlogs-normalizer-k8s.internalapis.caas.phenix-noprd.carrefour.com xlogs-normalizer-k8s-driver} {PENDING_RERUN driver pod failed with ExitCode: 143, Reason: Error} map[xlogs-normalizer-k8s-1588974316139-exec-1:FAILED xlogs-normalizer-k8s-1588974316139-exec-10:FAILED xlogs-normalizer-k8s-1588974316139-exec-2:FAILED xlogs-normalizer-k8s-1588974316139-exec-3:FAILED xlogs-normalizer-k8s-1588974316139-exec-4:FAILED xlogs-normalizer-k8s-1588974316139-exec-5:FAILED xlogs-normalizer-k8s-1588974316139-exec-6:FAILED xlogs-normalizer-k8s-1588974316139-exec-7:FAILED xlogs-normalizer-k8s-1588974316139-exec-8:FAILED xlogs-normalizer-k8s-1588974316139-exec-9:FAILED] 1 1}]
I0508 21:48:15.300983       9 controller.go:264] Ending processing key: "sparkjob-dev-ali/xlogs-normalizer-k8s"
I0508 21:48:15.301016       9 controller.go:257] Starting processing key: "sparkjob-dev-ali/xlogs-normalizer-k8s"
I0508 21:48:15.301046       9 controller.go:567] SparkApplication sparkjob-dev-ali/xlogs-normalizer-k8s pending rerun

```
**Application status:**

```
kubectl -n sparkjob-dev-ali get sparkapplication xlogs-normalizer-k8s -o=yaml:

status:
  applicationState:
    errorMessage: 'driver pod failed with ExitCode: 143, Reason: Error'
    state: PENDING_RERUN
driverInfo:
    podName: xlogs-normalizer-k8s-driver
    ...
  executionAttempts: 1
  executorState:
    xlogs-normalizer-k8s-1588974316139-exec-1: FAILED
    xlogs-normalizer-k8s-1588974316139-exec-2: FAILED
    xlogs-normalizer-k8s-1588974316139-exec-3: FAILED
    ....
  submissionAttempts: 1
  submissionID: 5b8dc360-5fec-40ca-aea7-c3c1f8bcb7a3
  terminationTime: "2020-05-08T21:48:02Z"
```

If we update any parameter in the `SparkApplication` specification file, and then resubmit, then this makes it possible to the application to move from `pending` to `submitting` state. However, we need the application (specifically the driver) to restart automatically after a failure which is the purpose of the `restartPolicy`.

Fixing this issue would be so important to using this operator in our production.

**Comment by liyinan926** [comment]
Did the following policy (the one you found in another issue) work for you?

```
restartPolicy:
   type: Always
   onFailureRetries: 1000000
   onFailureRetryInterval: 10
   onSubmissionFailureRetries: 3
   onSubmissionFailureRetryInterval: 10
```

**Comment by AliGouta** [comment]
@liyinan926 Thank you for your replay. Actually, I created this issue after a long investigation. However, I just fixed the issue just by disabling the ingress part in the operator by removing  
  `--ingress-url-format`. Actually, when the application is submited, the ingress object does not succeed to be created (due to some internal company constraints I guess which does not fit how the spark operator creates the ingress object) and keeps on `creating` status. However, it is tricky that such a behaviour has an impact on the driver restart. Well, in my case I can create the ingress separately at the moment. You may close the issue if you want. Now, depends on how you see it. Is it worth investigating why not succeding to create the ingress object (while the app runs fine) prevents the driver from a restart (when the job hits an issue) or we may consider it is a normal behaviour.

**Comment by liyinan926** [comment]
I think the issue is the following: when an app is in the `PENDING_RERUN` state, the operator will validate that all the resources associated with the previous try have been cleaned up before submitting the next run, including the driver pod, the UI service, and the UI service Ingress. I guess the Ingress object might have caused the app to be stuck.

**Comment by AliGouta** [comment]
expected behaviour
