### ISSUE TITLE
Gopkg.toml: no such file or directory.

### ISSUE THREAD

**Issue by venkatakarunakar** [GoogleCloudPlatform/spark-on-k8s-operator#918]
Downloaded the latest version on Mac.

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

➜  spark-on-k8s-operator git:(master) docker build -t soperator:v1 -f Dockerfile .
:
:
Step 7/17 : WORKDIR ${GOPATH}/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator
 ---> Running in 9b8e84f9f8a7
Removing intermediate container 9b8e84f9f8a7
 ---> c305c4385ca3
Step 8/17 : COPY Gopkg.toml Gopkg.lock ./
COPY failed: stat /var/lib/docker/tmp/docker-builder879337802/Gopkg.toml: no such file or directory

**Comment by liyinan926** [comment]
We recently switched to using gomodule instead of dep for dependency management. `Gopkg.toml` and `Gopkg.lock` were removed, but we forgot to update the Dockerfile. Will update it soon.

**Comment by liyinan926** [comment]
Created #919 to fix the Dockerfiles.

**Comment by liyinan926** [comment]
Fixed in #919.
