### ISSUE TITLE
Spark operator fails to mount volume and crashes webhook-init

### ISSUE THREAD

**Issue by abelbarrera15** [GoogleCloudPlatform/spark-on-k8s-operator#926]
I'm installing the spark operator --version 0.7.0 

I continue to get the following error:
![image](https://user-images.githubusercontent.com/25710044/82927529-d94a1d80-9f4e-11ea-8e83-177c8cabd91e.png)

This is because the webhook-init keeps failing (note I deleted the private repo info): 
Controlled By:  Job/spark-sparkoperator-webhook-init
Containers:
  main:
    Host Port:     <none>
    Command:
      /usr/bin/gencerts.sh
      -n
      spark-operator
      -s
      spark-webhook
      -p
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    35
      Started:      Tue, 26 May 2020 14:31:50 +0000
      Finished:     Tue, 26 May 2020 14:31:50 +0000
    Ready:          False
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from spark-sparkoperator-token-cbzzg (ro)

In the logs-- all I see is this: 
Unable to attach or mount volumes: unmounted volumes=[webhook-certs spark-operator-sparkoperator-token-5l59c], unattached volumes=[webhook-certs spark-operator-sparkoperator-token-5l59c]: timed out waiting for the condition

What is happening? I have no issues when I install w/out webhook enabled. The environment I'm installing to is an isolated environment so there is no internet, but I can install this same thing on my local kubernetes w/ no issues when I turn the internet off as well. 

It additionally says this:

TimeGenerated [UTC] | 2020-05-26T14:32:03Z

   Namespace | spark-operator
   LogEntrySource | stdout
   LogEntry | Generating certs for the Spark pod admission webhook in /tmp/spark-pod-webhook-certs.
  ContainerStatusReason | CrashLoopBackOff
  ControllerKind | Job
  ControllerName | spark-sparkoperator-webhook-init
  PodStatus | Running

curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kubernetes.default.svc:443
--

**Comment by abelbarrera15** [comment]
It looks like it can't set an endpoint: 

NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
spark-webhook   ClusterIP   10.10.121.123   <none>        443/TCP   147m


Name:              spark-webhook
Namespace:         spark-operator
Labels:            app.kubernetes.io/instance=spark
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=sparkoperator
                   helm.sh/chart=sparkoperator-0.7.0
Annotations:       meta.helm.sh/release-name: spark
                   meta.helm.sh/release-namespace: spark-operator
Selector:          app.kubernetes.io/name=sparkoperator,app.kubernetes.io/version=v1beta2-1.1.1-2.4.5
Type:              ClusterIP
IP:                10.10.121.123
Port:              webhook  443/TCP
TargetPort:        443/TCP
Endpoints:         <none>
Session Affinity:  None

**Comment by abelbarrera15** [comment]
I believe I found the bug--

In the .sh that generates the self-signed certificate the below is not respected:

https://github.com/istio/istio/issues/12157

Thus, since my server is isolated it won't be able to use the non-FAQN. Could the .sh be changed to be FAQN instead of CN=${SERVICE}.${NAMESPACE}.svc"

**Comment by abelbarrera15** [comment]
Note--- I was able to resolve this by punching a hole in the firewall. I don't think this should be necessary however. Based on what I've come to understand in the process, there should be a code edit that could be made such that it will not fail for pure isolated environments. If I have time, I will try to get back to seeing how I could fix this.

**Comment by czhang120** [comment]
Hi abelbarrera15, 

Could you share details on how you open the firewall to resolve this issue? I think we are having the same issue with an isolated environment. 

Thanks!
