### ISSUE TITLE
Spark operator within Kubeflow

### ISSUE THREAD

**Issue by marwanfahmi** [GoogleCloudPlatform/spark-on-k8s-operator#928]
Hello,

I'm trying to execute a Spark job in a Kubeflow pipeline using a resourceOp, I'm using Kubeflow on GCP instance running a private GKE. I have an issue getting this to work in the KF namespace, I get a java socket closed message, however, when I try to install the operator in another namespace and execute the job manually it works. The KF pipeline runs in the KF namespace.

What could be preventing the Spark operator to create a pod and run it in the KF namespace? Any help would be very much appreciated. Thanks.

**Comment by liyinan926** [comment]
You probably want to create an issue in the kubeflow repo instead. I'm not familiar with Kubeflow and the use of the KF namespace.
