### ISSUE TITLE
Unable to consistently pull metrics in prometheus/grafana

### ISSUE THREAD

**Issue by rakshithvasudev** [GoogleCloudPlatform/spark-on-k8s-operator#936]
Yesterday I was able to see metrics work just fine for [this](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-prometheus.yaml) example. But today the same metrics don't work, when I've made no changes.

Just so you know, I've exposed port 8090 as a service to be scraped by Prometheus by adding extrascrapeconfig. I've installed Prometheus as a [standalone installation](https://github.com/helm/charts/tree/master/stable/prometheus) and not using the prometheus operator.

Also I've exposed the driver and executor metrics in the yaml file. But I'm not able consistently see metrics scraped despite deleting and creating spark jobs multiple times.

I'd like to see if there is something that I could do to pull all the spark metrics consistently or is there something I'm missing.

**Here are some example metrics that aren't working:**
jvm_memory_pool_bytes_used
spark_driver_blockmanager_memory_maxmem_mb  
spark_executor_threadpool_activetasks
spark_executor_threadpool_completetasks
spark_executor_cputime_count
jvm_threads_deadlocked

**Here are some that work fine when the other metrics mentioned above don't work:**
spark_app_executor_running_count
spark_app_executor_success_count
rate(container_network_transmit_bytes_total)[5m]
rate(container_network_receive_bytes_total)[5m]

Any help would be appreciated.

**Comment by AliGouta** [comment]
I think you are mentionning 2 types of metrics. Metrics related to the operator and others related the soark applications. The former works fine, but the latter (when you say you expose the port 8090) I think it is related to this [issue](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/934). I have juste issued a PR about it few hours ago.

**Comment by rakshithvasudev** [comment]
Thanks for the info @AliGouta. You're right, there are some metrics that are not spark related to spark operator. Those are just some examples though. I'm not sure why sometimes those spark operator metrics work. For example if I launch the same job 10 times, I might get metrics out for 3 jobs spread across attempts 1-10. That's where I'm not sure why it's inconsistent and what am I missing.

**Comment by liyinan926** [comment]
This and other issues related to opening up of the port for exposing metrics have been fixed in #935, which is included in the new release: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/releases/tag/v1beta2-1.1.2-2.4.5.

**Comment by AliGouta** [comment]
You are welcome ! Looking forward to further contribute.

**Comment by rakshithvasudev** [comment]
The new release works great! Thanks @AliGouta & @liyinan926
