### ISSUE TITLE
Executor pending

### ISSUE THREAD

**Issue by weimin** [GoogleCloudPlatform/spark-on-k8s-operator#947]
Hi,
I tried to follow your example here on aws eks cluster: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md

I ran kubectl apply -f examples/spark-pi.yaml but it gave an error: 
Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods "spark-pi-driver" is forbidden: error looking up service account default/spark: serviceaccount "spark" not found.

Then I ran kubectl apply -f examples/spark-pi-configmap.yaml to resolve but now the executor seems to be stuck in pending but the driver is running:

`$ kubectl describe sparkapp spark-pi
Name:         spark-pi
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"sparkoperator.k8s.io/v1beta2","kind":"SparkApplication","metadata":{"annotations":{},"name":"spark-pi","namespace":"default...
API Version:  sparkoperator.k8s.io/v1beta2
Kind:         SparkApplication
Metadata:
  Creation Timestamp:  2020-06-16T03:38:16Z
  Generation:          2
  Resource Version:    306307
  Self Link:           /apis/sparkoperator.k8s.io/v1beta2/namespaces/default/sparkapplications/spark-pi
  UID:                 43d560e0-235b-448e-98dd-c1df0dd39f60
Spec:
  Driver:
    Core Limit:  1200m
    Cores:       1
    Labels:
      Version:        2.4.5
    Memory:           512m
    Service Account:  spark
    Volume Mounts:
      Mount Path:  /opt/spark/mycm
      Name:        config-vol
  Executor:
    Cores:      1
    Instances:  1
    Labels:
      Version:  2.4.5
    Memory:     512m
    Volume Mounts:
      Mount Path:         /opt/spark/mycm
      Name:               config-vol
  Image:                  gcr.io/spark-operator/spark:v2.4.5
  Image Pull Policy:      Always
  Main Application File:  local:///opt/spark/examples/jars/spark-examples_2.11-2.4.5.jar
  Main Class:             org.apache.spark.examples.SparkPi
  Mode:                   cluster
  Restart Policy:
    Type:         Never
  Spark Version:  2.4.5
  Type:           Scala
  Volumes:
    Config Map:
      Name:  dummy-cm
    Name:    config-vol
Status:
  Application State:
    State:  RUNNING
  Driver Info:
    Pod Name:             spark-pi-driver
    Web UI Address:       172.20.19.143:4040
    Web UI Port:          4040
    Web UI Service Name:  spark-pi-ui-svc
  Execution Attempts:     1
  Executor State:
    spark-pi-1592297054834-exec-1:  PENDING
  Last Submission Attempt Time:     2020-06-16T08:44:16Z
  Spark Application Id:             spark-9a09e11365f1422ca6fbe8861b5e6cdf
  Submission Attempts:              1
  Submission ID:                    27c338db-f997-4646-9d01-2ac4056fc5ce
  Termination Time:                 <nil>
Events:
  Type     Reason                               Age                From            Message
  ----     ------                               ----               ----            -------
  Normal   SparkApplicationSpecUpdateProcessed  28m                spark-operator  Successfully processed spec update for SparkApplication spark-pi
  Warning  SparkApplicationPendingRerun         28m                spark-operator  SparkApplication spark-pi is pending rerun
  Normal   SparkApplicationSubmitted            28m                spark-operator  SparkApplication spark-pi was submitted successfully
  Normal   SparkDriverRunning                   28m                spark-operator  Driver spark-pi-driver is running
  Normal   SparkExecutorPending                 27m (x2 over 27m)  spark-operator  Executor spark-pi-1592297054834-exec-1 is pending`

**Comment by liyinan926** [comment]
How did you install the operator, through Helm or the yamls in this repo?

**Comment by weimin** [comment]
Hi,
I did it using helm, actually the error went away after I restarted my kubernetes cluster and then ran 

`$ kubectl create serviceaccount tiller --namespace kube-system
$ kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
$ helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator
$ helm install incubator/sparkoperator --namespace spark-operator --set sparkJobNamespace=default
Get the service account using $ kubectl get serviceaccounts and update pi-spark.yaml
$ kubectl apply -f ../Spark/spark-pi.yaml
$ kubectl logs --tail=20 spark-pi-driver -n default | grep 'Pi is'
Pi is roughly 3.1366356831784157
`
I had to enable tiller though to get the install to work.

Thanks!
