### ISSUE TITLE
Please support release Spark 3.0

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#950]
It was released yesterday, can you please update
https://spark.apache.org/docs/latest/

I'm happy to create my own base image if this can already be supported

**Comment by liyinan926** [comment]
Will create a new release based on Spark 3.0 soon. Stay tuned. Thanks.

**Comment by liyinan926** [comment]
I have just built and pushed the following images:

`gcr.io/spark-operator/spark:v3.0.0`
`gcr.io/spark-operator/spark-py:v3.0.0`
`gcr.io/spark-operator/spark-operator:v1beta2-1.1.2-3.0.0`

**Comment by itamar-otonomo** [comment]
Thanks @liyinan926, will there be any changes to the API?

**Comment by liyinan926** [comment]
@itamar-otonomo There won't be major or backward incompatible changes to the API. There's a couple of new options in Spark 3.0.0 missing in the API. I created https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/954 to add them.

**Comment by liyinan926** [comment]
We have pretty much added support for most new options in Spark 3.0.0 that are relevant in the context of the operator. We just added support for [a limited form of dynamic allocation without an external shuffle service](https://issues.apache.org/jira/browse/SPARK-27963) in #976. Closing this and will prepare a new release for 3.0 soon.

**Comment by AceHack** [comment]
Can you create or point to some docs on the dynamic allocation?
