### ISSUE TITLE
High availability and DR support for spark application

### ISSUE THREAD

**Issue by shensonj** [GoogleCloudPlatform/spark-on-k8s-operator#953]
@liyinan926 Can you please let us know if there is any support for High availability and DR support for spark operator?

**Comment by liyinan926** [comment]
You can increase the instances of the operator Deployment to be greater than 1 and turn on leader election to achieve HA within a single cluster. See https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#enabling-leader-election-for-high-availability.
