### ISSUE TITLE
How to run spark 2.5.4, 2.5.5, and 3.0.0 side by side

### ISSUE THREAD

**Issue by AceHack** [GoogleCloudPlatform/spark-on-k8s-operator#961]
Will I need separate operators for each, can one operator do this, that would be preferred.  How can I go about setting this up.  Thanks.

**Comment by liyinan926** [comment]
You don't need separate instances for different versions if all the versions are 2.4.x and above as the Kubernetes submission client is compatible. The latest version of the operator image based on Spark 3.0.0 should be able to handle apps of 2.4.x. With that being said, we do have a prototype of the operator that uses a Kubernetes Job to run `spark-submit` such that a single operator instance can support apps of different Spark version. The prototype is in branch https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/multi-version-support.

**Comment by liyinan926** [comment]
Have you tried running apps of different Spark versions using the 3.0.0 based operator image?

**Comment by AceHack** [comment]
Not yet been running into issues with different versions of 2.4.x at the moment.  I think I got all those figured out and will try 3 soon.

**Comment by AceHack** [comment]
At first, I was not able to run spark 2.4.x jobs with the 3 operators.  The following configuration did not work but it worked fine with the 2 operator.  I got something along the line of spark/app/* jar not found.

```
  deps:
    jars:
      - local:///spark/app/*
```

I changed my configuration to delete the above and use

```
sparkConf:
  "spark.driver.extraClassPath": /spark/app/*
  "spark.executor.extraClassPath": /spark/app/*
```

And that works fine.

**Comment by AceHack** [comment]
I take it back, it's not working, my jobs are failing to read mounted volumes, trying to investigate further.

**Comment by AceHack** [comment]
My code has not changed in weeks, works fine with spark operator 2.4.x but breaks with spark operator 3.x.  The job is running on spark 2.4.6. Somehow I had a bug that spark didn't occur when using the 2.4.x operator but did when using the spark 3.x operator.  I was recursively looking for a file on the file system starting from a directory and going upwards until I reached root.  I accidentally was appending "." to the beginning of the file making absolute paths not work correctly, we'll not work correctly when using the spark 3.x operator.  Anyways, I fixed that bit and now my j2.4.x obs are running with spark 3.x operator.

**Comment by liyinan926** [comment]
That's great to know! Looks like we can make the Spark 3 operator the default. Closing this now.

**Comment by jkleckner** [comment]
@AceHack Just to be clear, your 2.4.x job is running now with spark 3.0 via the spark-operator operator 3.x true?  My belief is that #658 is merged, the operator can't launch 2.4.x spark jobs.

**Comment by liyinan926** [comment]
#658 has not been merged. With or without #658, a 3.0 based operator can launch jobs in both 2.4.x or 3.0 as far as @AceHack verified.

**Comment by AceHack** [comment]
My job is a built against spark 2.4.6 scala 2.12 in a spark 2.4.6 scala 2.12 Docker container.  The operator is using spark 3.0.0 with operator 1.1.2.

**Comment by liyinan926** [comment]
What about jobs in 2.4.5? I believe they should just work like ones in 2.4.6.

**Comment by jkleckner** [comment]
To put it in another way, by specifying the container that the operator uses to be spark 2.4.x-based, the spark-submit with that image works, true?

**Comment by liyinan926** [comment]
@jkleckner The scenario looks like the following:

You can use a 2.4.x driver/executor container image with a 3.0.0 based operator image. 3.0.0 based `spark-submit` run by the operator is able to create a 2.4.x driver pod, which then runs `spark-submit` in client mode and launches 2.4.x executor pods.
