### ISSUE TITLE
Volcano scheduler: minResource configuration support for spark-on-k8s-operator

### ISSUE THREAD

**Issue by Gouthamkreddy1234** [GoogleCloudPlatform/spark-on-k8s-operator#964]
It looks like the minResource configuration is not supported for the spark operator which is crutial for gang scheduling pods in a spark-application. There is default value for minResource that is the total resource of driver and executor which we have to use if we use the spark operator.

(The latest update on this is that it is still being worked on. However, I will be opening this issue to track the progress of this feature)

This feature is currently supported for spark-submit in the Huawei fork of apache/spark (https://github.com/huawei-cloudnative/spark/tree/spark-2.4-volcano-0.1) and since the spark operator automatically runs spark-submit under the hood, we should be able to bring this feature to the spark-on-k8s-operator as well.

**Comment by k82cn** [comment]
@hzxuzhonghu , please help on that when you have time :)

**Comment by Thor-wl** [comment]
@Gouthamkreddy1234 releated PR is https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/966

**Comment by Thor-wl** [comment]
I'm still perfecting e2e case about the feature. New commit is on the  way.

**Comment by liyinan926** [comment]
Thanks @Thor-wl for the PR. @k82cn @hzxuzhonghu could you please take a look at the PR? Thanks.

**Comment by Gouthamkreddy1234** [comment]
Thanks @Thor-wl! :)

**Comment by Thor-wl** [comment]
I have a doubt: whether custom configed request resource is less than the total resource of executors and drivers is permitted. I'm not so familiar with the real scenes of Spark application. Current code logic has no limition to the custom request resource.

**Comment by Thor-wl** [comment]
I have a doubt: whether custom configed request resource less than the total resource of executors and drivers is permitted. I'm not so familiar with the real scenes of Spark application. Current code logic has no limition to the custom request resource.

**Comment by william-wang** [comment]
Usually the custom configed request resource is less than total resource of executors and drivers.

**Comment by Thor-wl** [comment]
> Usually the custom configed request resource is less than total resource of executors and drivers.

ok, thx

**Comment by Gouthamkreddy1234** [comment]
Fixed in GoogleCloudPlatform/spark-on-k8s-operator#966
