### ISSUE TITLE
Does spark-on-k8s-operator support using RAM as local storage?

### ISSUE THREAD

**Issue by william-wang** [GoogleCloudPlatform/spark-on-k8s-operator#973]
Spark support  to use RAM as local storage for diskless nodes case by setting "spark.kubernetes.local.dirs.tmpfs=true" for spilling data.  Does spark operator support this kind of feature? How we can use it if supported.

Here is the instruction of "use RAM as local storage" in spark cloud native  way:
http://spark.apache.org/docs/latest/running-on-kubernetes.html

**Comment by liyinan926** [comment]
Yes, you can achieve it using `sparkConf`, for example:

```
spec
  sparkConf:
    spark.kubernetes.local.dirs.tmpfs: true
```

**Comment by william-wang** [comment]
Great thanks for your response.
