### ISSUE TITLE
Cleanup ui-svc after spark job is completed

### ISSUE THREAD

**Issue by arpit1997** [GoogleCloudPlatform/spark-on-k8s-operator#974]
When spark job is created it creates a k8s service for Spark UI. After the spark job is completed the k8s service is not deleted. 

```
spark-manual-2020-07-14t09-06-27-289746-ui-svc   ClusterIP   172.20.159.23    <none>        4045/TCP            10h
spark-manual-2020-07-14t09-17-39-594006-ui-svc   ClusterIP   172.20.230.95    <none>        4045/TCP            9h
```

Steps to reproduce:
1. Run a spark job
2. Wait for it to complete and see `kubectl get svc -n <namespace>`

**Comment by liyinan926** [comment]
The UI service will be cleaned up once you delete the `SparkApplication` object. There's an ownerReference pointing to the  `SparkApplication` object in the UI service.
