### ISSUE TITLE
spark 3.0.0 operatorVersion: v1beta2-1.1.2-3.0.0 , inconsistent driver and executor pod names

### ISSUE THREAD

**Issue by sujitbiswas** [GoogleCloudPlatform/spark-on-k8s-operator#975]
an earlier version of the spark-operator would have a consistent naming of pods,  example 

drive-pod-name = **metropolis-spark**-driver
executor-pod-name =  **metropolis-spark**-exec... (1 or 2 or 3 etc)

the new version generates the pod name from the mainClass

status:
    applicationState:
      state: RUNNING
    driverInfo:
      podName: **metropolis-spark-driver**
      webUIAddress: 10.233.49.191:4040
      webUIPort: 4040
      webUIServiceName: metropolis-spark-ui-svc
    executionAttempts: 1
    executorState:
      **com-nvidia-metropolis-its-frame-streamprocessor-56ffe0734ef6570c-exec-1**: RUNNING
    lastSubmissionAttemptTime: "2020-07-14T20:13:47Z"
    sparkApplicationId: spark-a6d39e04e1434e70971228339fcdd089
    submissionAttempts: 1
    submissionID: 83fa5468-078f-4c79-8df4-8d6e044c8252
    terminationTime: null

how to fix the pod naming issue?

**Comment by liyinan926** [comment]
See this https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/971.

**Comment by liyinan926** [comment]
BTW: In both 2.4.x and 3.0.0, the *prefix* of the executor pod names is derived from the app name. The operator sets `spark.app.name` to the name of the `SparkApplication` resource when submitting the app to run.

**Comment by sujitbiswas** [comment]
@liyinan926 thank you
