### ISSUE TITLE
hostAliases support in SparkPodSpec

### ISSUE THREAD

**Issue by smndf** [GoogleCloudPlatform/spark-on-k8s-operator#981]
Is there a reason why hostAliases is not supported in the SparkApplication custom resource, while dnsConfig is?

[https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/ )

**Comment by liyinan926** [comment]
No particular reason. Support for such fields are typically added when someone has a use case for a particular field and creates a PR.
