### ISSUE TITLE
Spark 3.0.0 Python image not being able to read using S3AFileSystem

### ISSUE THREAD

**Issue by Coqueiro** [GoogleCloudPlatform/spark-on-k8s-operator#983]
Hi! I'm trying to run a pyspark (spark 3.0.0) job which runs a `spark.read.json("s3a://bucket/path/to/data.json")` in order to retrieve some data for processing, using image `gcr.io/spark-operator/spark-py:v3.0.0` and I'm hitting a `Class org.apache.hadoop.fs.s3a.S3AFileSystem not found` wall:
```
Traceback (most recent call last):                                                                                                                                        │
│   File "/tmp/spark-a6de7139-1901-4d9e-921b-dc5359f227ae/hello_world.py", line 28, in <module>                                                                             │
│     df = spark.read.json("s3a://bucket/path/to/data.json")                                                                                                                  │
│   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 300, in json                                                                                   │
│   File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1305, in __call__                                                                           │
│   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 131, in deco                                                                                        │
│   File "/opt/spark/python/lib/py4j-0.10.9-src.zip/py4j/protocol.py", line 328, in get_return_value                                                                        │
│ py4j.protocol.Py4JJavaError: An error occurred while calling o58.json.                                                                                                    │
│ : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found                                                    │
...
```

I tried creating a custom Spark image as follows:
```
FROM gcr.io/spark-operator/spark-py:v3.0.0

# add s3a connector
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.271/aws-java-sdk-bundle-1.11.271.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.1.2/hadoop-aws-3.1.2.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.11.823/aws-java-sdk-1.11.823.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.11.823/aws-java-sdk-s3-1.11.823.jar $SPARK_HOME/jars
```

But it didn't work either.

Does anyone have a clue how can I start reading/writing files from S3 using Spark 3.0.0? Thanks!

**Comment by Coqueiro** [comment]
Also tried the following docker image:
````
FROM gcr.io/spark-operator/spark-py:v3.0.0

# add s3a connector
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.0.0/hadoop-aws-3.0.0.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/3.0.0/hadoop-client-3.0.0.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.0.0/hadoop-common-3.0.0.jar $SPARK_HOME/jars
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.199/aws-java-sdk-bundle-1.11.199.jar $SPARK_HOME/jars
```
No success either :/

**Comment by be-rock** [comment]
i am seeing this same issue in spark 2.4.5

**Comment by Coqueiro** [comment]
I figured out how to do it:
Here’s a fork with the changes I made to the base docker image (just a few changes):
https://github.com/Coqueiro/spark/tree/branch-3.0-s3
I created a Makefile to aid distribution creation, but I basically just followed the official doc:
http://spark.apache.org/docs/latest/building-spark.html
Also, here’s the image, already built and pushed to Docker Hub:
https://hub.docker.com/repository/docker/coqueirotree/spark-py

It has Spark 3.0.0, Hadoop 3.2.0 and S3A support.

**Comment by kwebster2019** [comment]
> Also tried the following docker image:
> 
> ```
> FROM gcr.io/spark-operator/spark-py:v3.0.0
> 
> # add s3a connector
> ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.0.0/hadoop-aws-3.0.0.jar $SPARK_HOME/jars
> ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/3.0.0/hadoop-client-3.0.0.jar $SPARK_HOME/jars
> ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.0.0/hadoop-common-3.0.0.jar $SPARK_HOME/jars
> ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.199/aws-java-sdk-bundle-1.11.199.jar $SPARK_HOME/jars
> ```
> 
> No success either :/

This actually fixed my issues. i think perhaps for me, maybe the files in the spark 3.0.1 release are corrupt or whenever i download them they are corrupt. (obviously i changed the files to 3.2.0 instead of 3.0.0
