### ISSUE TITLE
Cannot install helm chart on minikube

### ISSUE THREAD

**Issue by songfeil** [GoogleCloudPlatform/spark-on-k8s-operator#985]
Hi, 

I'm trying install the helm chart on minikube following the quick start guides. However it cannot be installed and here's the error log.

`Error: CustomResourceDefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[driver].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[template].properties[executor].properties[sidecars].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]`

Can successfully install with `--set installCrds=false` though. I'm wondering if anyone can help. Thanks!

**Comment by liyinan926** [comment]
You likely ran into this issue: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/921.

**Comment by liyinan926** [comment]
The Helm chart has been fixed, please give the latest version a try.

**Comment by songfeil** [comment]
Fixed! Thanks very much!
