### ISSUE TITLE
ScheduledSparkApplications not being scheduled on the provided cron

### ISSUE THREAD

**Issue by thomaskelm** [GoogleCloudPlatform/spark-on-k8s-operator#998]
We are seeing some interesting behavior with the scheduledsparkapplications where the jobs will be scheduled one-two times successfully and then after that they will no longer be scheduled based on the cron. They will either not be scheduled at all or they will be scheduled several hours/days later at random intervals. There hasn't been anything useful in the logs, it appears to either be overloaded with scheduling tasks or missing cron tabs.

Installation that was used:
```
helm repo add incubator http://storage.googleapis.com/kubernetes-charts-incubator

helm install spark-operator incubator/sparkoperator --namespace spark-operator --set replicas=3 --set controllerThreads=20 --set enableBatchScheduler=true --set enableWebhook=true --set operatorVersion=v1beta2-1.1.2-2.4.5 
```

Versions:
Using AWS EKS
Kubernetes 1.1.15
python3 
pyspark 2.4.5 

Background:
I can't provide too many details around the specific application, but at a high level it is reading from s3, performing operations, and then saving to s3.

We are running daily spark jobs with cron tabs similar to this: `0 7 * * *`, we have roughly 400 scheduledsparkapplications running that are staggered between the following cron schedules `0 5 * * *` and `0 10 * * *`. The first few days that we have the spark operator running all jobs are successfully scheduled, and then something weird happens and the operator will begin missing cron tabs and then it will randomly schedule some of the jobs.

Workaround:
We have figured out that if we restart the spark operator pods, it will begin scheduling pods following the cron again, but the same issue happens again. On restart, it immediately schedules all sparkapplications that it wasn't able to schedule correctly which may cause issues for those who don't have enough resources available.

Please let me know if you need anymore details.

**Comment by liyinan926** [comment]
The number of controller threads is configurable and defaults to 10. You can increase it using the command-line flag `-controller-threads`. If you use the Helm chart, you can set it by adding `--set controllerThreads=<value>`.

**Comment by thomaskelm** [comment]
Yes we have increased it to 20 threads and 3 replicas. Do you have a suggested number of threads to try?

**Comment by liyinan926** [comment]
Increasing the replicas doesn't help since only one of the replicas is active, and the rest are standbys. You might want to try a bigger number like 40 or 50 given that you have 400 resources to handle.

**Comment by thomaskelm** [comment]
okay I will try that and see if helps

**Comment by liyinan926** [comment]
Also if you run into the issue again after bumping up the threads, please take a look at the status section of one of the scheduled job that doesn't seem to get handled properly and let me know what the status says.

**Comment by thomaskelm** [comment]
Here is an example status of a pod that didn't actually schedule on the cron:

![image](https://user-images.githubusercontent.com/10335972/90833008-b55b6580-e30c-11ea-8606-2542a33fb502.png)

![image](https://user-images.githubusercontent.com/10335972/90833652-1a638b00-e30e-11ea-93e1-9034434b475e.png)

The status says scheduled, but there isn't a sparkapplication that was created.

![image](https://user-images.githubusercontent.com/10335972/90833747-4d0d8380-e30e-11ea-9146-0c45d91e8a7a.png)


This Scheduledsparkapplication has a cron schedule of `*/10 * * * *` to run it every 10 minutes.

Prometheus screenshot showing when the pod was actually being scheduled. I restarted the spark operator pod at 21:38 and it was correctly scheduling for the first few iterations, but then the time between runs grew exponentially:
![image](https://user-images.githubusercontent.com/10335972/90833133-feabb500-e30c-11ea-8861-f0fbe30b35e0.png)

I am seeing a large amount of logs in the spark operator that say `Syncing ScheduledSparkApplication ` and then name of the application.

I have the controllerThreads set to 60

**Comment by liyinan926** [comment]
Thanks for adding detailed info. Will look into it.

**Comment by liyinan926** [comment]
Were you seeing line `Next run of ScheduledSparkApplication ... is due` in the operator logs?

**Comment by aolear-ss** [comment]
@liyinan926 @thomaskelm digging up this old issue, what was the resolution? 

Was the timing issue remediated by tuning the resync interval and controller threads to meet the demand of the # of scheduled spark apps or was the final solution to restart the operator on a daily basis?

Thanks!

**Comment by aolear-ss** [comment]
> @liyinan926 @thomaskelm digging up this old issue, what was the resolution?
> 
> Was the timing issue remediated by tuning the resync interval and controller threads to meet the demand of the # of scheduled spark apps or was the final solution to restart the operator on a daily basis?
> 
> Thanks!

After some trial and error, we found that the operator was able to maintain it's configured CRON schedules once changing the `resync-interval` parameter to 300 seconds (instead of the default 30 seconds). The granularity of our CRON's is every ~10-15 minutes and so far after a few days, it is performing much better

The graph below shows occurrences of "Syncing ScheduledSparkApplication". It's pretty clear where we made the configuration change
![image](https://github.com/user-attachments/assets/8a99dc84-222e-4aaa-9660-e095e9de46cb)
